(function(){
'use strict';
if(window.__PN_COLIN_FLOW_V1__)return;
window.__PN_COLIN_FLOW_V1__=true;

var API='https://dkmacktcfhubsumwrydw.supabase.co/functions/v1/navigator-foreman';
var KEY='sb_publishable_VATM2AkVyl-yvxv28S2FXw_CqMpBr6q';
var PROJECT='mundi-pos1';
var FLOW=[
 {id:'T14',n:'01',title:'CONFIRM SLIDE-TO-TRUCK CONNECTION',crew:[],foreman:[],why:'Resolve this early so slide / step steel can proceed.'},
 {id:'T02',n:'02',title:'CHECK NET-SIDE CONNECTION SPACE',crew:['T01'],foreman:[],why:'Confirm the real connection space before setout is locked.'},
 {id:'T03',n:'03',title:'VERIFY SETOUT + REAL HOLES',crew:['T01'],foreman:['T02'],why:'Approve the real setout before drilling becomes irreversible.'},
 {id:'T13',n:'04',title:'CHECK JOIST ARRANGEMENT',crew:['T05'],foreman:['T03'],why:'Confirm joists miss plates / poles before deck build-up.'},
 {id:'T06',n:'05',title:'APPROVE UPRIGHT JOINT PREP TEST',crew:['T05'],foreman:['T03'],why:'Approve one physical 65NB upright / top-rail joint before batch cutting.'},
 {id:'T07',n:'06',title:'APPROVE TOP RAIL FIT + 850 mm',crew:['T06'],foreman:['T06'],why:'Check fit, alignment and finished-height reference before final welding.'},
 {id:'T08',n:'07',title:'CONFIRM REMOVABLE GALVANISING SPLITS',crew:['T07'],foreman:['T07'],why:'Lock the removable split arrangement before pre-galv fabrication is closed out.'},
 {id:'T09',n:'08',title:'RESOLVE BOTTOM SS GUIDE-WIRE ENDS',crew:['T06'],foreman:['T06'],why:'Confirm end fixing details before later mesh / guide-wire work.'},
 {id:'T12',n:'09',title:'CONFIRM GALVANISER VENT / DRAIN + SEND',crew:['T11'],foreman:['T08','T09'],why:'Confirm galvaniser requirements before sections are sent away.'},
 {id:'T16',n:'10',title:'CONFIRM DECK BUILD-UP + MODWOOD METHOD',crew:['T13','T15','T11'],foreman:['T12','T13','T14'],why:'Publish the actual ModWood fixing method before decking starts.'},
 {id:'T17',n:'11',title:'APPROVE MODWOOD INSTALLATION',crew:['T16'],foreman:['T16'],why:'Release decking only after the fixing method and finished level are confirmed.'},
 {id:'T19',n:'12',title:'CONFIRM SS MESH SUPPORT / SYSTEM',crew:['T18'],foreman:['T17'],why:'Confirm the mesh support system before installation.'},
 {id:'T20',n:'13',title:'CONFIRM GUIDE WIRE / LACING / TENSION',crew:['T19','T09'],foreman:['T19','T09'],why:'Confirm the bottom guide-wire and lacing method before final tensioning.'},
 {id:'T23',n:'14',title:'CONFIRM CAB ACCESS LADDER / STEP',crew:['T22'],foreman:[],why:'Approve the cab access detail after decommissioning work exposes the real condition.'},
 {id:'T28',n:'15',title:'PLAY-SAFETY INSPECTION + RECTIFICATIONS',crew:['T20','T21','T23','T24','T27','T15'],foreman:['T20','T23'],why:'Do the final safety inspection only after all relevant systems are physically complete.'},
 {id:'T29',n:'16',title:'FINAL PLAN / REVISION / HANDOVER CHECK',crew:['T28'],foreman:['T28'],why:'Finish with the latest revision and handover check.'}
];
var completed=[];var busy=false;var expanded=false;var poller=null;

function person(){try{return state&&state.currentUser?String(state.currentUser):'';}catch(e){return '';}}
function pin(){try{if(typeof livePin!=='undefined'&&/^\d{6}$/.test(String(livePin)))return String(livePin);}catch(e){}try{return localStorage.getItem('pn_live_pin')||'';}catch(e){return '';}}
function closed(id){try{return !!(state&&(state.done||[]).includes(id)||(state.skipped||[]).includes(id));}catch(e){return false;}}
function taskTitle(id){try{if(typeof TASKS!=='undefined'&&Array.isArray(TASKS)){var t=TASKS.find(function(x){return x&&x.id===id;});if(t&&t.title)return String(t.title);}}catch(e){}var s=FLOW.find(function(x){return x.id===id;});return s?s.title:id;}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function isDone(id){return completed.indexOf(id)>=0;}
function waiting(step){var miss=[];step.foreman.forEach(function(id){if(!isDone(id))miss.push('Colin '+id);});step.crew.forEach(function(id){if(!closed(id))miss.push('crew '+id);});return miss;}
function ready(step){return !isDone(step.id)&&waiting(step).length===0;}
function nextStep(){return FLOW.find(ready)||FLOW.find(function(x){return !isDone(x.id);})||null;}
function doneCount(){return FLOW.filter(function(x){return isDone(x.id);}).length;}

async function req(operation,extra){var p=pin();if(!/^\d{6}$/.test(p))throw new Error('Crew PIN is required');var r=await fetch(API,{method:'POST',headers:{'content-type':'application/json','apikey':KEY},body:JSON.stringify(Object.assign({projectId:PROJECT,pin:p,actor:person(),operation:operation},extra||{}))});var d=await r.json().catch(function(){return {};});if(!r.ok){var e=new Error(d.error||'Foreman workflow request failed');e.status=r.status;throw e;}return d;}

function installStyle(){if(document.getElementById('pnColinFlowStyle'))return;var s=document.createElement('style');s.id='pnColinFlowStyle';s.textContent='\
#pnColinFlow{position:sticky;top:6px;z-index:9000;margin:8px 0 10px;background:#101820;color:#fff;border:2px solid #fff;border-radius:14px;box-shadow:0 5px 18px rgba(0,0,0,.28);font-family:Arial,sans-serif;overflow:hidden}#pnColinFlow .pcfHead{display:flex;align-items:center;gap:8px;padding:8px 9px}.pcfMain{min-width:0;flex:1}.pcfK{font-size:9px;font-weight:900;letter-spacing:.08em;opacity:.72}.pcfNext{font-size:13px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:1px}.pcfProg{font-size:10px;opacity:.78;margin-top:2px}.pcfBtn{border:0;border-radius:9px;padding:9px 10px;font-size:11px;font-weight:900;background:#fff;color:#111;flex:0 0 auto}.pcfBtn.primary{background:#f2c14e}.pcfBody{border-top:1px solid #4b5560;background:#f4f4f0;color:#111;padding:6px;max-height:58vh;overflow:auto}.pcfRow{display:grid;grid-template-columns:30px 1fr auto;gap:7px;align-items:center;border:1px solid #ccc;background:#fff;border-radius:9px;padding:6px 7px;margin:4px 0;min-height:43px}.pcfRow.done{opacity:.58}.pcfRow.ready{border:2px solid #26734d}.pcfNum{font-size:11px;font-weight:900}.pcfTitle{font-size:11px;font-weight:900;line-height:1.2}.pcfState{font-size:9px;font-weight:900;margin-top:2px}.pcfState.ready{color:#26734d}.pcfState.wait{color:#805b00}.pcfState.done{color:#555}.pcfOpen{border:0;background:#e7e7e2;border-radius:7px;padding:7px 8px;font-size:10px;font-weight:900}.pcfFoot{display:flex;gap:6px;padding:6px}.pcfFoot button{flex:1;border:0;border-radius:8px;padding:8px;font-size:10px;font-weight:900}.pcfComplete{background:#26734d;color:#fff}.pcfReset{background:#fee;color:#8d2020}.pcfMsg{font-size:10px;font-weight:900;padding:0 7px 6px;color:#8d2020}\
#pnForemanModal .pnFmTop{padding:5px 8px!important;min-height:38px!important}#pnForemanModal .pnFmTitle{font-size:13px!important}#pnForemanModal .pnFmSub{font-size:9px!important}#pnForemanModal .pnFmClose{padding:7px 9px!important;font-size:10px!important}#pnForemanModal .pnFmNoteBar{padding:4px 6px!important}#pnForemanModal .pnFmTextarea{height:42px!important;min-height:42px!important;font-size:11px!important;padding:5px 7px!important}#pnForemanModal .pnFmTools{padding:4px 5px!important;gap:4px!important;overflow:visible!important;white-space:normal!important;flex-wrap:wrap!important;position:relative!important;z-index:10!important}#pnForemanModal .pnFmTool{padding:7px 8px!important;font-size:10px!important;border-radius:7px!important}#pnForemanModal .pnFmHint{padding:3px 6px!important;font-size:9px!important}#pnForemanModal .pnFmActions{padding:5px!important}#pnForemanModal .pnFmActions button{padding:9px 6px!important;font-size:10px!important}.pnFmPanel{position:relative!important}.pnFmTop,.pnFmNoteBar,.pnFmTools{flex-shrink:0!important}\
';document.head.appendChild(s);}

function clearLegacyColinAssignment(){try{if(person()!=='colin'||!state)return;if(state.startedByPerson&&state.startedByPerson.colin)return;if(state.assignments&&state.assignments.colin)state.assignments.colin=null;}catch(e){}}
function wrapAuto(){try{if(typeof autoFillTeam!=='function'||autoFillTeam.__pnColinFlow)return;var base=autoFillTeam;var w=function(){var out=base.apply(this,arguments);try{if(state&&state.startedByPerson&&!state.startedByPerson.colin&&state.assignments)state.assignments.colin=null;}catch(e){}return out;};w.__pnColinFlow=true;autoFillTeam=w;window.autoFillTeam=w;}catch(e){}}

function openTask(id){try{if(typeof previewTaskId!=='undefined')previewTaskId=id;if(typeof renderTask==='function')renderTask();if(typeof hideAllPrimaryViews==='function')hideAllPrimaryViews();var mv=document.getElementById('mainView');if(mv)mv.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});}catch(e){}}

function ensure(){installStyle();if(person()!=='colin'){var old=document.getElementById('pnColinFlow');if(old)old.remove();return;}clearLegacyColinAssignment();var host=document.querySelector('.app')||document.body;var box=document.getElementById('pnColinFlow');if(!box){box=document.createElement('div');box.id='pnColinFlow';host.insertBefore(box,host.firstChild);}render();}
function render(){var box=document.getElementById('pnColinFlow');if(!box||person()!=='colin')return;var nx=nextStep(),cnt=doneCount(),wait=nx?waiting(nx):[];box.innerHTML='<div class="pcfHead"><div class="pcfMain"><div class="pcfK">COLIN · FOREMAN ORDER OF WORKS</div><div class="pcfNext">'+(nx?esc(nx.n+' · '+nx.title):'ALL FOREMAN STEPS COMPLETE')+'</div><div class="pcfProg">'+cnt+' / '+FLOW.length+' complete'+(nx&&wait.length?' · waiting: '+esc(wait.join(', ')):'')+'</div></div>'+(nx?'<button class="pcfBtn primary" id="pcfNext">OPEN NEXT</button>':'')+'<button class="pcfBtn" id="pcfToggle">'+(expanded?'HIDE':'LIST')+'</button></div>'+(expanded?bodyHtml():'');var t=box.querySelector('#pcfToggle');if(t)t.onclick=function(){expanded=!expanded;render();};var n=box.querySelector('#pcfNext');if(n&&nx)n.onclick=function(){openTask(nx.id);};box.querySelectorAll('[data-open]').forEach(function(b){b.onclick=function(){openTask(b.getAttribute('data-open'));};});var c=box.querySelector('#pcfComplete');if(c&&nx)c.onclick=function(){complete(nx.id);};var r=box.querySelector('#pcfReset');if(r)r.onclick=resetFlow;}
function bodyHtml(){var nx=nextStep();var rows=FLOW.map(function(s){var d=isDone(s.id),r=ready(s),miss=waiting(s);var st=d?'DONE':r?'READY':'WAITING · '+miss.join(', ');return '<div class="pcfRow '+(d?'done':r?'ready':'')+'"><div class="pcfNum">'+esc(s.n)+'</div><div><div class="pcfTitle">'+esc(s.id+' · '+s.title)+'</div><div class="pcfState '+(d?'done':r?'ready':'wait')+'">'+esc(st)+'</div></div><button class="pcfOpen" data-open="'+esc(s.id)+'">OPEN</button></div>';}).join('');return '<div class="pcfBody">'+rows+'<div class="pcfFoot">'+(nx&&ready(nx)?'<button id="pcfComplete" class="pcfComplete">COMPLETE CURRENT FOREMAN STEP</button>':'')+'<button id="pcfReset" class="pcfReset">RESET COLIN TO START</button></div><div id="pcfMsg" class="pcfMsg"></div></div>';}
function msg(v){var e=document.getElementById('pcfMsg');if(e)e.textContent=v||'';}
async function complete(id){if(busy)return;busy=true;msg('');try{var d=await req('flow_complete',{stepId:id});completed=d.flow&&Array.isArray(d.flow.completed)?d.flow.completed:completed;render();}catch(e){msg(e.message||'Could not complete this foreman step.');if(e&&e.status===409){openTask(id);setTimeout(function(){var eb=document.getElementById('pnForemanEdit');if(eb)eb.scrollIntoView({behavior:'smooth',block:'center'});},250);}}finally{busy=false;}}
async function resetFlow(){if(busy||!confirm('Reset Colin\'s FOREMAN checklist to Step 1? This will NOT undo Mitchell / Ronan work and will NOT delete Colin\'s published notes.'))return;busy=true;try{var d=await req('flow_reset');completed=d.flow&&Array.isArray(d.flow.completed)?d.flow.completed:[];expanded=true;render();}catch(e){msg(e.message||'Could not reset Colin.');}finally{busy=false;}}
async function loadFlow(){if(person()!=='colin')return;try{var d=await req('flow_get');completed=d.flow&&Array.isArray(d.flow.completed)?d.flow.completed:[];ensure();}catch(e){ensure();}}

function compactMarkup(){var m=document.getElementById('pnForemanModal');if(!m)return;var pan=m.querySelector('[data-tool="pan"]');if(pan)pan.textContent='SCROLL';var labels={arrow:'↗ ARROW',circle:'○ CIRCLE',pen:'✎ DRAW',text:'T TEXT',eraser:'⌫ ERASE'};Object.keys(labels).forEach(function(k){var b=m.querySelector('[data-tool="'+k+'"]');if(b)b.textContent=labels[k];});var undo=m.querySelector('#pnFmUndo');if(undo)undo.textContent='↶ UNDO';var clear=m.querySelector('#pnFmClear');if(clear)clear.textContent='CLEAR';}

function boot(){installStyle();wrapAuto();clearLegacyColinAssignment();ensure();setTimeout(loadFlow,300);setTimeout(compactMarkup,400);var mo=new MutationObserver(function(){ensure();compactMarkup();});mo.observe(document.body,{childList:true,subtree:true});poller=setInterval(function(){wrapAuto();ensure();if(person()==='colin')loadFlow();},5000);document.addEventListener('visibilitychange',function(){if(!document.hidden){loadFlow();ensure();}});window.addEventListener('pageshow',function(){loadFlow();ensure();});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
