(function(){
'use strict';
if(window.__PN_TASK_GUIDES_5380__)return;window.__PN_TASK_GUIDES_5380__=true;
var PASSES=[0,180,700,1800];
function norm(v){return String(v||'').replace(/\s+/g,' ').trim().toUpperCase();}
function esc(v){return String(v||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function taskRoot(){return document.getElementById('taskCard')||document.body;}
function exactLabel(q,r){var n=norm(q),els=(r||taskRoot()).querySelectorAll('small,span,strong,b,h1,h2,h3,h4,h5,div,p');var best=null,bestLen=1e9;for(var i=0;i<els.length;i++){if(els[i].closest&&els[i].closest('#pnTaskLocationGuide'))continue;var t=norm(els[i].textContent);if(t===n&&t.length<bestLen){best=els[i];bestLen=t.length}}return best;}
function localCard(el,nextMarker){if(!el)return null;var p=el,best=el.parentElement||el;for(var i=0;i<6&&p&&p!==document.body;i++,p=p.parentElement){var t=norm(p.textContent);if(t.indexOf(nextMarker)!==-1)break;if(t.length<3000)best=p;}return best;}
function cleanLines(el){return String(el&&el.innerText||'').split(/\n+/).map(function(x){return x.trim()}).filter(Boolean);}
function parseWhere(card){var a=cleanLines(card),loc='',ori='',src='';for(var i=0;i<a.length;i++){var u=norm(a[i]);if(u==='WHERE')continue;if(/^SOURCE\b/.test(u)){src=a[i];continue}if(u.indexOf('ORIENTATION')!==-1||u.indexOf('CAB / FRONT')!==-1||u.indexOf('DRIVER SIDE')!==-1){ori=a[i];continue}if(!loc)loc=a[i];}return {location:loc,orientation:ori,source:src};}
function titleText(r){var hs=(r||taskRoot()).querySelectorAll('h1,h2,h3');for(var i=0;i<hs.length;i++){if(hs[i].closest&&hs[i].closest('#pnTaskLocationGuide'))continue;var t=String(hs[i].textContent||'').trim(),u=norm(t);if(t&&u!=='ALL WORK'&&u!=='YOUR JOB NOW')return t;}return'';}
function isModwoodDeck(info,title){var t=norm((info.location||'')+' '+title);return t.indexOf('WHOLE TRAY DECK AREA')!==-1||t.indexOf('INSTALL THE MODWOOD DECKING')!==-1||t.indexOf('137×23 MM MODWOOD')!==-1||t.indexOf('137X23 MM MODWOOD')!==-1;}
function addStyle(){if(document.getElementById('pnTaskGuideCss5380'))return;var s=document.createElement('style');s.id='pnTaskGuideCss5380';s.textContent='\
#pnTaskLocationGuide{margin:10px 0 12px;border:1px solid #dce5e1;border-radius:18px;background:#fff;overflow:hidden;box-shadow:0 8px 24px rgba(16,37,52,.055);font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;color:#10202a}\
#pnTaskLocationGuide .tgHead{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:13px 15px;background:#102534;color:#fff;border-top:3px solid #d2a63d}\
#pnTaskLocationGuide .tgEy{font-size:7px;font-weight:950;letter-spacing:.14em;color:#b8c8cf;margin-bottom:3px}#pnTaskLocationGuide h3{margin:0!important;color:#fff!important;font-size:17px!important;line-height:1.08!important;letter-spacing:-.025em!important}#pnTaskLocationGuide .tgBadge{flex:0 0 auto;padding:6px 8px;border-radius:999px;background:#fff;color:#102534;font-size:6.5px;font-weight:950}\
#pnTaskLocationGuide .tgBody{padding:13px 15px 14px}#pnTaskLocationGuide .tgLocation{margin:0 0 10px;font-size:13px;line-height:1.45;font-weight:850;color:#22313a}\
#pnTaskLocationGuide .tgFrame{border:1px solid #dce5e1;border-radius:14px;background:#f7f9f7;padding:12px}#pnTaskLocationGuide svg{display:block;width:100%;height:auto;max-height:270px}\
#pnTaskLocationGuide .tgCompass{display:grid;grid-template-columns:minmax(82px,.8fr) minmax(180px,1.4fr) minmax(82px,.8fr);grid-template-rows:auto minmax(98px,1fr) auto;gap:8px;align-items:center;text-align:center;min-height:180px}\
#pnTaskLocationGuide .tgDir{font-size:8px;line-height:1.3;font-weight:900;color:#5f6e76}.tgDir.top{grid-column:2;grid-row:1}.tgDir.left{grid-column:1;grid-row:2}.tgDir.right{grid-column:3;grid-row:2}.tgDir.bottom{grid-column:2;grid-row:3}.tgWork{grid-column:2;grid-row:2;min-height:92px;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:12px;border:2px solid #102534;border-radius:14px;background:#edf4ef;color:#102534}.tgWork b{font-size:10px;letter-spacing:.08em}.tgWork span{margin-top:5px;font-size:10px;line-height:1.35;font-weight:800}\
#pnTaskLocationGuide .tgNote{margin-top:9px;padding:9px 10px;border-radius:10px;background:#fff8e8;border:1px solid #eadcb4;color:#72591c;font-size:8.5px;line-height:1.45;font-weight:800}#pnTaskLocationGuide .tgSource{margin-top:8px;color:#78858c;font-size:7px;line-height:1.4;font-weight:750}.pnGuideHiddenWhere{display:none!important}\
@media(max-width:700px){#pnTaskLocationGuide{border-radius:15px}#pnTaskLocationGuide .tgHead{padding:12px}#pnTaskLocationGuide h3{font-size:16px!important}#pnTaskLocationGuide .tgBody{padding:12px}#pnTaskLocationGuide .tgLocation{font-size:12px}#pnTaskLocationGuide .tgBadge{display:none}#pnTaskLocationGuide .tgCompass{grid-template-columns:64px 1fr 64px;min-height:160px}.tgWork{min-height:86px;padding:9px}.tgWork span{font-size:9px}}';document.head.appendChild(s);}
function orientationParts(text){var u=norm(text);return {front:u.indexOf('FRONT')!==-1?'CAB / FRONT · RIGHT':'FRONT',rear:u.indexOf('REAR')!==-1?'REAR / SLIDE · LEFT':'REAR',driver:u.indexOf('DRIVER SIDE')!==-1?'DRIVER SIDE · NEAR':'DRIVER SIDE',passenger:u.indexOf('PASSENGER SIDE')!==-1?'PASSENGER SIDE · FAR':'PASSENGER SIDE',has:u.indexOf('FRONT')!==-1||u.indexOf('REAR')!==-1||u.indexOf('DRIVER SIDE')!==-1||u.indexOf('PASSENGER SIDE')!==-1};}
function genericVisual(info){var o=orientationParts(info.orientation);if(!o.has)return '<div class="tgFrame"><div class="tgWork" style="max-width:520px;margin:auto"><b>WORK AREA</b><span>'+esc(info.location||'Use the current task location.')+'</span></div></div>';return '<div class="tgFrame"><div class="tgCompass"><div class="tgDir top">'+esc(o.passenger)+'</div><div class="tgDir left">'+esc(o.rear)+'</div><div class="tgWork"><b>WORK AREA</b><span>'+esc(info.location||'Current task location')+'</span></div><div class="tgDir right">'+esc(o.front)+'</div><div class="tgDir bottom">'+esc(o.driver)+'</div></div></div>';}
function modwoodVisual(){return '<div class="tgFrame"><svg viewBox="0 0 900 390" role="img" aria-label="Top view of truck showing the whole tray deck behind the cab as the ModWood area"><defs><pattern id="tgBoards5380" width="34" height="34" patternUnits="userSpaceOnUse"><rect width="34" height="34" fill="#d7a957"/><path d="M0 0V34M17 0V34" stroke="#b5883e" stroke-width="2"/></pattern></defs><text x="400" y="27" text-anchor="middle" font-size="17" font-weight="900" fill="#5a6972">PASSENGER SIDE · FAR</text><text x="400" y="382" text-anchor="middle" font-size="17" font-weight="900" fill="#5a6972">DRIVER SIDE · NEAR</text><rect x="110" y="60" width="560" height="270" rx="20" fill="url(#tgBoards5380)" stroke="#102534" stroke-width="5"/><rect x="670" y="94" width="145" height="200" rx="26" fill="#102534"/><rect x="692" y="122" width="96" height="54" rx="9" fill="#d9e4e8"/><circle cx="205" cy="339" r="23" fill="#263945"/><circle cx="575" cy="339" r="23" fill="#263945"/><circle cx="205" cy="51" r="23" fill="#263945"/><circle cx="575" cy="51" r="23" fill="#263945"/><text x="390" y="169" text-anchor="middle" font-size="24" font-weight="950" fill="#102534">MODWOOD GOES HERE</text><text x="390" y="201" text-anchor="middle" font-size="16" font-weight="850" fill="#29404e">WHOLE HORIZONTAL TRAY DECK</text><text x="390" y="229" text-anchor="middle" font-size="14" font-weight="800" fill="#4f5d64">behind the cab · across the tray surface</text><text x="742" y="213" text-anchor="middle" font-size="18" font-weight="950" fill="#fff">CAB</text><text x="742" y="237" text-anchor="middle" font-size="11" font-weight="850" fill="#bed0d8">FRONT / RIGHT</text><path d="M100 195H42" stroke="#102534" stroke-width="5"/><path d="M42 195l18-12v24z" fill="#102534"/><text x="40" y="173" font-size="14" font-weight="950" fill="#102534">REAR / SLIDE</text></svg></div>';}
function keyFor(info,title){return norm(title+'|'+info.location+'|'+info.orientation).slice(0,220);}
function clearOld(key){var old=document.getElementById('pnTaskLocationGuide');if(old&&old.getAttribute('data-key')!==key)old.remove();var old17=document.getElementById('pnTaskGuideT17');if(old17)old17.remove();var oldWhere=document.getElementById('pnWhereFirst5379');if(oldWhere)oldWhere.remove();var hidden=document.querySelectorAll('.pnGuideHiddenWhere');for(var i=0;i<hidden.length;i++)hidden[i].classList.remove('pnGuideHiddenWhere');}
function hideOldDrawing(r){var els=(r||taskRoot()).querySelectorAll('div,section,h3,h4');for(var i=0;i<els.length;i++){var t=norm(els[i].textContent);if(t==='1 · SIMPLE DRAWING'||t==='1 - SIMPLE DRAWING'){var p=els[i].parentElement;if(p){p.style.display='none';var nx=p.nextElementSibling;if(nx&&norm(nx.textContent).indexOf('DECK BUILD-UP')!==-1)nx.style.display='none';}}}}
function build(info,title,key){var special=isModwoodDeck(info,title),visual=special?modwoodVisual():genericVisual(info);var note=special?'This is the tray-deck ModWood task. The separate ModWood step / stepping-box is a different task. Do not cover hidden/support work until it is released.':'This only identifies the work area from the wording already in Navigator. It does not create new dimensions, fixing details or structural instructions.';return '<section id="pnTaskLocationGuide" data-key="'+esc(key)+'" aria-label="Where on the real job"><div class="tgHead"><div><div class="tgEy">LOCATION FIRST</div><h3>Where on the real job?</h3></div><div class="tgBadge">INSIDE THIS TASK</div></div><div class="tgBody"><p class="tgLocation">'+esc(info.location||'Use the location shown in the current task.')+'</p>'+visual+'<div class="tgNote">'+esc(note)+'</div>'+(info.source?'<div class="tgSource">'+esc(info.source)+'</div>':'')+'</div></section>';}
function apply(){try{addStyle();var r=taskRoot(),whereLabel=exactLabel('WHERE',r);if(!whereLabel)return;var whereCard=localCard(whereLabel,'3 QUICK STEPS');if(!whereCard)return;var info=parseWhere(whereCard),title=titleText(r),key=keyFor(info,title);clearOld(key);var existing=document.getElementById('pnTaskLocationGuide');if(existing){whereCard.classList.add('pnGuideHiddenWhere');return;}whereCard.insertAdjacentHTML('afterend',build(info,title,key));whereCard.classList.add('pnGuideHiddenWhere');if(isModwoodDeck(info,title))hideOldDrawing(r);}catch(e){try{console.warn('task location guide',e)}catch(_){}}}
for(var i=0;i<PASSES.length;i++)setTimeout(apply,PASSES[i]);document.addEventListener('click',function(){setTimeout(apply,110)},{passive:true});window.addEventListener('pageshow',function(){setTimeout(apply,90)});document.addEventListener('visibilitychange',function(){if(!document.hidden)setTimeout(apply,90)});
})();