(function(){
'use strict';
if(window.__PN_NOVA_5371__)return;window.__PN_NOVA_5371__=true;
var NAV=null,key='my',explicit=false,timer=0,raf=0,detail=false;
function n(v){return String(v==null?'':v).replace(/\s+/g,' ').trim().toUpperCase()}
function e(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function txt(x){return String(x&&x.textContent||'').replace(/\s+/g,' ').trim()}
function who(){try{if(typeof state!=='undefined'&&state&&state.currentUser)return String(state.currentUser)}catch(_){}try{return localStorage.getItem('pn_live_person')||''}catch(_){return''}}
function whoName(){var p=who();return p==='me'?'MITCHELL':p==='ronan'?'RONAN':p==='colin'?'COLIN':'CREW'}
function task(){try{if(typeof previewTaskId!=='undefined'&&previewTaskId&&Array.isArray(TASKS))return TASKS.find(function(x){return x&&x.id===previewTaskId})||null;if(typeof currentPersonTask==='function')return currentPersonTask()||null;var p=who(),id=state&&state.assignments&&state.assignments[p];if(id&&Array.isArray(TASKS))return TASKS.find(function(x){return x&&x.id===id})||null}catch(_){}return null}
function app(){var a=document.querySelector('.app');if(a)return a;var c=document.getElementById('taskCard');if(!c)return null;var p=c,last=c;while(p&&p.parentElement&&p.parentElement!==document.body){p=p.parentElement;last=p}return last}
function kfor(x){var t=n(x&&x.textContent);return t==='MY JOB'?'my':t==='CREW'?'crew':t==='PROGRESS'?'progress':t==='TASKS'?'tasks':''}
function nav(){if(NAV&&NAV.isConnected)return NAV;NAV=document.getElementById('pn536Nav');if(NAV)return NAV;var all=document.querySelectorAll('button,a,[role="button"]'),f={};for(var i=0;i<all.length;i++){var k=kfor(all[i]);if(k&&!f[k])f[k]=all[i]}if(!(f.my&&f.crew&&f.progress&&f.tasks))return null;var p=f.my;while(p&&p!==document.body){if(p.contains(f.crew)&&p.contains(f.progress)&&p.contains(f.tasks)){NAV=p;break}p=p.parentElement}return NAV}
function setNav(k){if(!k)return;key=k;var q=nav();if(!q)return;q.classList.add('pnNovaNav');var b=q.querySelectorAll('button,a,[role="button"]');for(var i=0;i<b.length;i++){var x=kfor(b[i]);if(x)b[i].classList.toggle('pnNovaActive',x===k)}}
function findText(prefix,root){var w=n(prefix),a=(root||document).querySelectorAll('h1,h2,h3,h4,div,span,p,strong,b,small'),best=null,len=1e9;for(var i=0;i<a.length;i++){if(a[i].closest&&a[i].closest('#pnNovaHeader,#pnNovaFocus'))continue;var t=n(a[i].textContent);if(t.indexOf(w)!==0)continue;if(t.length<len){best=a[i];len=t.length}}return best}
function findAction(labels,root){var arr=(Array.isArray(labels)?labels:[labels]).map(n),a=(root||document).querySelectorAll('button,a,[role="button"]');for(var i=0;i<a.length;i++){if(a[i].closest&&a[i].closest('#pnNovaFocus'))continue;var t=n(a[i].textContent);for(var j=0;j<arr.length;j++)if(t===arr[j]||t.indexOf(arr[j]+' ')===0)return a[i]}return null}
function status(){var x=document.getElementById('liveStatus');if(x)return txt(x);var x2=findText('OFFLINE')||findText('LIVE')||findText('MERGING');return x2&&txt(x2).length<100?txt(x2):(navigator.onLine?'LIVE':'OFFLINE')}
function source(){var x=findText('BUILT FROM:');return x?txt(x).replace(/^Built from:\s*/i,'').slice(0,420):''}
function hideOldChrome(){var a=app(),b=findText('PINNACLE NAVIGATOR',a);if(b&&!b.closest('#pnNovaHeader')){var p=b,hit=null;for(var i=0;i<7&&p&&p!==a;i++,p=p.parentElement){var t=n(p.textContent);if(t.indexOf('MUNDI POS 1')!==-1&&t.length<1200)hit=p}if(hit)hit.classList.add('pnNovaOldChrome')}var s=findText('BUILT FROM:',a);if(s&&!s.closest('#pnNovaHeader'))(s.parentElement||s).classList.add('pnNovaOldSource')}
function header(){var a=app();if(!a)return;hideOldChrome();var h=document.getElementById('pnNovaHeader');if(!h){h=document.createElement('header');h.id='pnNovaHeader';a.insertBefore(h,a.firstChild)}var st=status(),warn=/OFFLINE|QUEUED|MERGING|WAIT/i.test(st),src=source();h.innerHTML='<div class="pnNovaBrand"><div class="pnNovaLogo">PN</div><div><b>Pinnacle Navigator</b><small>MUNDI POS 1 · WORKSHOP</small></div></div><div class="pnNovaMeta"><span class="pnNovaStatus '+(warn?'warn':'')+'"><i></i>'+e(st)+'</span><span class="pnNovaUser">'+e(whoName())+'</span></div>'+(src?'<div class="pnNovaSource"><span>SOURCE</span>'+e(src)+'</div>':'')}
function detailRoot(t){var c=document.getElementById('taskCard');if(!c)return null;var x=t&&t.title?findText(t.title,c):null;if(!x)x=findText('3 QUICK STEPS',c);if(!x)return null;var p=x,hit=null;for(var i=0;i<9&&p&&p!==c;i++,p=p.parentElement){var s=n(p.textContent);if(s.indexOf('3 QUICK STEPS')>-1&&s.indexOf('DO THIS')>-1&&s.indexOf('WHY')>-1&&s.indexOf('BIG JOBS RIGHT NOW')<0&&s.length<15000)hit=p}return hit}
function extract(prefix,root){var x=findText(prefix,root);if(!x)return'';var p=x.parentElement||x,s=txt(p),lab=txt(x);if(n(s).indexOf(n(lab))===0)s=s.slice(lab.length).replace(/^\s*[-:|]\s*/,'');return s.slice(0,1300)}
function stateLabel(t){try{var id=String(t&&t.id||'');if(Array.isArray(state.done)&&state.done.indexOf(id)>-1)return'DONE';if(state.holds&&state.holds[id])return'HOLD';var p=who();if(state.startedByPerson&&state.startedByPerson[p]===id)return'IN PROGRESS'}catch(_){}return'READY'}
function proxy(btn,target){if(btn&&target)btn.onclick=function(){try{target.click()}catch(_){}schedule(120)}}
function focus(){var old=document.getElementById('pnNovaFocus');if(old)old.remove();var prev=document.querySelectorAll('.pnNovaLegacy');for(var z=0;z<prev.length;z++)prev[z].classList.remove('pnNovaLegacy','pnNovaLegacyOpen');if(key!=='my')return;var t=task(),d=detailRoot(t);if(!t||!d)return;d.classList.add('pnNovaLegacy');if(detail)d.classList.add('pnNovaLegacyOpen');var action=String(t.action||extract('DO THIS',d)||'').trim(),done=String(t.right||'').trim(),stop=String(t.stop||extract('ASK / CONFIRM THIS',d)||extract('NAVIGATOR CHECK',d)||'').trim(),where=extract('WHERE',d),why=String(t.explain||extract('WHY',d)||'').trim();var primary=document.getElementById('pn5323Primary')||findAction(['OPEN JOB','START JOB','CONTINUE','DONE','MARK DONE'],d),plan=findAction(['PLAN','PLAN · TASK AREA','PLAN - TASK AREA'],d)||document.getElementById('planBtn'),block=findAction('BLOCK / WAIT',d);var f=document.createElement('section');f.id='pnNovaFocus';var st=stateLabel(t);f.innerHTML='<div class="pnNovaHero"><div><div class="pnNovaEyebrow">YOUR JOB NOW · '+e(t.id||'')+'</div><h1>'+e(t.title||'CURRENT JOB')+'</h1><div class="pnNovaPills"><span class="pnNovaPill '+(st==='HOLD'?'hold':'')+'">'+e(st)+'</span>'+(where?'<span class="pnNovaPill ghost">'+e(where.slice(0,105))+'</span>':'')+'</div></div><div class="pnNovaTaskNo">'+e(String(t.id||'T').replace(/^T/i,''))+'</div></div><div class="pnNovaGrid"><article class="pnNovaDo"><span>DO THIS</span><strong>'+e(action||'Follow the current verified instruction.')+'</strong></article>'+(done?'<article class="pnNovaDone"><span>DONE WHEN</span><p>'+e(done)+'</p></article>':'')+'</div>'+(stop?'<div class="pnNovaStop"><b>!</b><div><span>STOP / CONFIRM</span><p>'+e(stop)+'</p></div></div>':'')+'<div class="pnNovaActions">'+(primary?'<button id="pnNovaPrimary">'+e(txt(primary)||'CONTINUE')+' <b>→</b></button>':'')+(plan?'<button id="pnNovaPlan">PLAN</button>':'')+(block?'<button id="pnNovaBlock">BLOCK / WAIT</button>':'')+'</div><div class="pnNovaMore"><button id="pnNovaMore">'+(detail?'HIDE DETAILS':'SHOW FULL JOB DETAIL')+'</button>'+(why?'<p>'+e(why)+'</p>':'')+'</div>';d.parentElement.insertBefore(f,d);proxy(document.getElementById('pnNovaPrimary'),primary);proxy(document.getElementById('pnNovaPlan'),plan);proxy(document.getElementById('pnNovaBlock'),block);document.getElementById('pnNovaMore').onclick=function(){detail=!detail;d.classList.toggle('pnNovaLegacyOpen',detail);this.textContent=detail?'HIDE DETAILS':'SHOW FULL JOB DETAIL'}}
function priorities(){var b=document.getElementById('pnBigJobsHome')||document.getElementById('pnBigJobsToday');if(!b)return;b.classList.add('pnNovaPriorities');var title=b.querySelector('.pnBigTitle');if(title)title.textContent='PROJECT PRIORITIES';var rows=b.querySelectorAll('.pnBigRow');for(var i=0;i<rows.length;i++)rows[i].classList.toggle('pnNovaPriorityHidden',i>2)}
function pageHead(){var o=document.getElementById('pnNovaPageHead');if(o)o.remove();if(key==='my')return;var c=document.getElementById('taskCard');if(!c)return;var m={crew:['CREW','Who is doing what?','Live assignments and the next clear move.'],progress:['PROGRESS','Project progress','Only what matters next.'],tasks:['TASKS','All work','Find a task fast.']}[key];if(!m)return;var h=document.createElement('section');h.id='pnNovaPageHead';h.innerHTML='<small>'+m[0]+'</small><h1>'+m[1]+'</h1><p>'+m[2]+'</p>';c.insertBefore(h,c.firstChild)}
function longLists(){if(key!=='crew')return;var c=document.getElementById('taskCard');if(!c)return;var a=c.querySelectorAll('[id*="history" i],[class*="history" i],[id*="activity" i],[class*="activity" i],[id*="log" i],[class*="log" i]');for(var i=0;i<a.length&&i<3;i++)if(a[i].children&&a[i].children.length>7){a[i].classList.add('pnNovaLong');for(var j=0;j<a[i].children.length;j++)a[i].children[j].classList.add('pnNovaRow')}}
function classes(){document.body.classList.remove('pnNovaMy','pnNovaCrew','pnNovaProgress','pnNovaTasks');document.body.classList.add(key==='crew'?'pnNovaCrew':key==='progress'?'pnNovaProgress':key==='tasks'?'pnNovaTasks':'pnNovaMy')}
function style(){if(document.getElementById('pnNovaCss5371'))return;var l=document.createElement('link');l.id='pnNovaCss5371';l.rel='stylesheet';l.href='./navigator-nova.css?v=5371';document.head.appendChild(l)}
function polish(){try{document.body.classList.add('pnNova');var nk='';var b=nav()&&nav().querySelectorAll('button,a,[role="button"]');if(b)for(var i=0;i<b.length;i++){var k=kfor(b[i]);if(k&&(b[i].classList.contains('active')||b[i].getAttribute('aria-current')==='page')){nk=k;break}}if(!explicit&&nk)key=nk;setNav(key||nk||'my');classes();header();priorities();pageHead();focus();longLists()}catch(err){try{console.warn('Navigator visual layer',err)}catch(_){}}}
function schedule(ms){if(raf)cancelAnimationFrame(raf);if(timer)clearTimeout(timer);raf=requestAnimationFrame(function(){raf=0;polish()});if(ms)timer=setTimeout(function(){timer=0;polish()},ms)}
style();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){schedule(160)},{once:true});else schedule(160);document.addEventListener('click',function(ev){var b=ev.target&&ev.target.closest?ev.target.closest('button,a,[role="button"]'):null;if(!b)return;var q=nav(),k=q&&q.contains(b)?kfor(b):'';if(k){explicit=true;detail=false;setNav(k);schedule(90);return}if(!b.closest('#pnNovaHeader,#pnNovaFocus'))schedule(80)},true);window.addEventListener('pageshow',function(){schedule(100)});document.addEventListener('visibilitychange',function(){if(!document.hidden)schedule(80)});
})();
