(function(){
'use strict';
if(window.__PN_WORKSHOP_UI_V2_5358__)return;
window.__PN_WORKSHOP_UI_V2_5358__=true;

var STYLE_ID='pnWorkshopUiStyleV2';
var OVERVIEW_ID='pnWorkshopOverviewV2';
var VERSION='v53.52';
var refreshTimer=0;

function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function norm(v){return String(v||'').replace(/\s+/g,' ').trim().toUpperCase();}
function stateSafe(){try{return typeof state!=='undefined'&&state?state:null;}catch(e){return null;}}
function personKey(){var s=stateSafe();try{if(s&&s.currentUser)return String(s.currentUser);}catch(e){}try{return localStorage.getItem('pn_live_person')||'';}catch(e){return '';}}
function personName(){var p=personKey();return p==='me'?'MITCHELL':p==='ronan'?'RONAN':p==='colin'?'COLIN':(p?String(p).toUpperCase():'CREW');}
function currentTask(){
  try{
    if(typeof previewTaskId!=='undefined'&&previewTaskId&&typeof TASKS!=='undefined'&&Array.isArray(TASKS))return TASKS.find(function(x){return x&&x.id===previewTaskId;})||null;
    if(typeof currentPersonTask==='function')return currentPersonTask()||null;
    var s=stateSafe(),p=personKey(),id=s&&s.assignments&&s.assignments[p];
    if(id&&typeof TASKS!=='undefined'&&Array.isArray(TASKS))return TASKS.find(function(x){return x&&x.id===id;})||null;
  }catch(e){}
  return null;
}
function counts(){
  var s=stateSafe(),total=29;
  try{if(typeof TASKS!=='undefined'&&Array.isArray(TASKS)&&TASKS.length)total=TASKS.length;}catch(e){}
  var done=s&&Array.isArray(s.done)?s.done.length:0;
  var skipped=s&&Array.isArray(s.skipped)?s.skipped.length:0;
  var holds=s&&s.holds&&typeof s.holds==='object'?Object.keys(s.holds).filter(function(id){return !(s.done||[]).includes(id)&&!(s.skipped||[]).includes(id);}).length:0;
  var closed=done+skipped;
  return {done:done,skipped:skipped,closed:closed,total:total,holds:holds,pct:Math.max(0,Math.min(100,Math.round(closed/Math.max(1,total)*100)))};
}
function pending(){try{var q=JSON.parse(localStorage.getItem('pn_pending_done_stable_v1')||'[]');return Array.isArray(q)?q.length:0;}catch(e){return 0;}}
function exactText(text){var want=norm(text),all=document.querySelectorAll('body *');for(var i=0;i<all.length;i++){var el=all[i];if(el.children.length===0&&norm(el.textContent)===want)return el;}return null;}
function findButton(label){var want=norm(label),bs=document.querySelectorAll('button');for(var i=0;i<bs.length;i++){var b=bs[i];if(b.closest&&b.closest('#'+OVERVIEW_ID))continue;var t=norm(b.textContent);if(t===want||t.indexOf(want+' ')===0)return b;}return null;}
function clickOriginal(label){var b=findButton(label);if(b){b.click();return true;}return false;}
function openMorning(){try{if(typeof window.__pnOpenMorningPack==='function'){window.__pnOpenMorningPack();return true;}}catch(e){}var b=document.querySelector('[data-pn-morning-pack]');if(b){b.click();return true;}return false;}
function openProject(){try{if(typeof window.__pnOpenWorkRegister==='function'){window.__pnOpenWorkRegister();return true;}}catch(e){}return false;}
function openTemplate(){try{if(typeof window.__pnOpenMiter425Template==='function'){window.__pnOpenMiter425Template();return true;}}catch(e){}return false;}
function openToday(){var b=document.getElementById('pn5335TodayBtn')||findButton('TODAY');if(b){b.click();return true;}var m=document.getElementById('pn5335Today');if(m){m.classList.add('open');return true;}return false;}
function common(a,b){if(!a||!b)return null;for(var p=a;p&&p!==document.body;p=p.parentElement)if(p.contains(b))return p;return null;}
function topRoot(el){if(!el)return null;var n=el;while(n.parentElement&&n.parentElement!==document.body)n=n.parentElement;return n===document.body?null:n;}

function style(){
  var old=document.getElementById('pnWorkshopUiStyle');if(old)old.remove();
  if(document.getElementById(STYLE_ID))return;
  var s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
:root{--pn-bg:#eeede8;--pn-panel:#fff;--pn-panel2:#f7f6f2;--pn-ink:#111417;--pn-muted:#6c6e6a;--pn-line:#d6d5cf;--pn-steel:#181d21;--pn-steel2:#252c31;--pn-amber:#f1b82d;--pn-amber2:#ffd766;--pn-green:#23764a;--pn-green-bg:#e8f6ed;--pn-red:#9b3030;--pn-red-bg:#fff0ef;--pn-blue:#315e78;--pn-blue-bg:#edf5fa;--pn-shadow:0 18px 46px rgba(20,26,30,.10);--pn-shadow-sm:0 7px 22px rgba(20,26,30,.07)}
*{box-sizing:border-box}html{background:var(--pn-bg)!important;-webkit-text-size-adjust:100%}body{margin:0!important;min-height:100dvh!important;background:radial-gradient(circle at 50% -160px,#fff 0,#f7f6f2 34%,#eeede8 76%)!important;color:var(--pn-ink)!important;font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif!important;text-rendering:optimizeLegibility!important}button,input,textarea,select{font:inherit}button{touch-action:manipulation;-webkit-tap-highlight-color:transparent}button:focus-visible,input:focus-visible,textarea:focus-visible,summary:focus-visible{outline:3px solid rgba(241,184,45,.45)!important;outline-offset:2px!important}.pnV2Root{width:min(1180px,calc(100% - 28px))!important;max-width:1180px!important;margin:0 auto!important;padding:14px 0 calc(42px + env(safe-area-inset-bottom))!important}.pnV2Root>*{max-width:none!important}
#pnWorkshopOverviewV2{margin:12px 0 16px;border:1px solid #d2d1cb;border-radius:25px;background:#fff;box-shadow:var(--pn-shadow);overflow:hidden}.pnV2Hero{display:grid;grid-template-columns:minmax(0,1fr) 255px;gap:20px;padding:22px 22px 18px;position:relative}.pnV2Hero:before{content:"";position:absolute;left:0;right:0;top:0;height:5px;background:linear-gradient(90deg,var(--pn-amber),var(--pn-amber2))}.pnV2Eyebrow{font-size:10px;font-weight:950;letter-spacing:.13em;color:#767873}.pnV2Task{font-size:clamp(25px,3.1vw,39px);font-weight:950;letter-spacing:-.045em;line-height:1.02;margin-top:6px;max-width:790px}.pnV2Hint{font-size:12px;line-height:1.45;color:#626560;font-weight:700;margin-top:8px;max-width:760px}.pnV2Meta{display:flex;flex-wrap:wrap;gap:6px;margin-top:12px}.pnV2Chip{display:inline-flex;align-items:center;gap:6px;min-height:28px;padding:5px 9px;border-radius:999px;background:#f0efea;color:#383c3e;font-size:8px;font-weight:950;letter-spacing:.06em}.pnV2Chip.live{background:var(--pn-green-bg);color:#175d39}.pnV2Chip.local{background:#fff3d3;color:#6f5008}.pnV2Chip.hold{background:var(--pn-red-bg);color:#822525}.pnV2Status{background:linear-gradient(145deg,var(--pn-steel),var(--pn-steel2));color:#fff;border-radius:18px;padding:15px;display:flex;flex-direction:column;justify-content:space-between;min-height:142px}.pnV2StatusK{font-size:8px;font-weight:950;letter-spacing:.12em;color:#b9bec1}.pnV2Pct{font-size:44px;font-weight:950;letter-spacing:-.065em;line-height:1;margin-top:6px}.pnV2Bar{height:8px;background:rgba(255,255,255,.15);border-radius:99px;overflow:hidden;margin-top:9px}.pnV2Bar i{display:block;height:100%;background:var(--pn-amber);border-radius:99px}.pnV2StatusS{font-size:9px;color:#d3d7d9;font-weight:850;margin-top:6px}.pnV2Quick{display:grid;grid-template-columns:1.2fr repeat(6,minmax(0,1fr));gap:7px;padding:11px 12px 12px;border-top:1px solid #e6e5df;background:#faf9f6}.pnV2Quick button{min-height:50px;border:1px solid #d4d3cc;border-radius:13px;background:#fff;color:#22272a;font-size:9px;font-weight:950;letter-spacing:.035em;cursor:pointer}.pnV2Quick button:hover{transform:translateY(-1px);box-shadow:0 5px 14px rgba(20,25,28,.08);border-color:#bbb}.pnV2Quick .morning{background:var(--pn-amber);border-color:var(--pn-amber);color:#17150d}.pnV2Quick .project{background:var(--pn-steel);border-color:var(--pn-steel);color:#fff}.pnV2Quick .tool{background:#fff4d8;border-color:#e7cf8a;color:#654707}
.pnV2Header{border-bottom:1px solid #d9d8d2!important;padding-bottom:11px!important;margin-bottom:10px!important}.pnV2HeaderBrand{font-size:clamp(23px,2.1vw,31px)!important;letter-spacing:-.035em!important;font-weight:950!important}.pnV2Source{background:#f7f6f2!important;border:1px solid #dbdad4!important;border-radius:10px!important;padding:8px 10px!important;color:#666863!important;font-size:9px!important;line-height:1.35!important;font-weight:750!important}
.pnV2CurrentPanel{background:#fff!important;border:1px solid #d4d3cd!important;border-radius:24px!important;padding:18px!important;box-shadow:var(--pn-shadow)!important;margin:0 0 14px!important}.pnV2SectionK{font-size:10px!important;color:#6f716d!important;font-weight:950!important;letter-spacing:.12em!important}.pnV2SectionTitle{font-size:clamp(28px,3vw,42px)!important;line-height:1!important;letter-spacing:-.05em!important;font-weight:950!important;margin:3px 0 12px!important}.pnV2ActionCard{border:1px solid #afd4bd!important;border-left:6px solid var(--pn-green)!important;background:linear-gradient(135deg,#edf8f1,#f7fbf8)!important;border-radius:18px!important;padding:17px!important;box-shadow:none!important}.pnV2ActionCard h1,.pnV2ActionCard h2,.pnV2ActionCard h3,.pnV2ActionCard b{letter-spacing:-.015em}.pnV2ActionCard button{min-height:54px!important;border-radius:12px!important;font-size:11px!important;font-weight:950!important}.pnV2Open{background:var(--pn-steel)!important;color:#fff!important;border-color:var(--pn-steel)!important;box-shadow:none!important}.pnV2Block{background:#b07900!important;color:#fff!important;border-color:#b07900!important;box-shadow:none!important}.pnV2Info{border:1px solid #dddcd6!important;border-radius:13px!important;background:#fbfaf7!important;box-shadow:none!important;margin-top:9px!important}.pnV2Info summary,.pnV2Info button{min-height:45px!important}.pnV2LegacyNav{border:1px solid #d5d4cd!important;border-radius:15px!important;background:#f8f7f4!important;padding:6px!important;box-shadow:var(--pn-shadow-sm)!important;margin-top:12px!important}.pnV2LegacyNav button{min-height:44px!important;border-radius:10px!important;font-size:9px!important;font-weight:950!important}
#taskCard{max-width:none!important;width:100%!important;background:transparent!important;border:0!important;box-shadow:none!important;padding:0!important}#pn5323OneStep{border:1px solid #d3d2cc!important;border-radius:23px!important;overflow:hidden!important;background:#fff!important;box-shadow:var(--pn-shadow)!important}.pn5323Head{position:relative;background:linear-gradient(135deg,var(--pn-steel),#283036)!important;color:#fff!important;padding:20px!important}.pn5323Head:before{content:"";position:absolute;left:0;top:0;right:0;height:5px;background:var(--pn-amber)}.pn5323K{color:#cbd0d2!important;font-size:9px!important;letter-spacing:.12em!important}.pn5323Title{font-size:clamp(26px,3vw,39px)!important;line-height:1.03!important;letter-spacing:-.04em!important}.pn5323Block{margin:10px 13px 0!important;padding:13px 14px!important;border:1px solid #deddd7!important;border-left-width:5px!important;border-radius:14px!important;background:#faf9f6!important}.pn5323Block .pn5323Label{font-size:8px!important;letter-spacing:.11em!important;color:#747570!important}.pn5323Block .pn5323Text{font-size:15px!important;line-height:1.45!important;color:#16191b!important;font-weight:800!important}.pn5323Block:not(.check):not(.done):not(.stop){border-left-color:var(--pn-blue)!important;background:var(--pn-blue-bg)!important}.pn5323Block.check{border-left-color:var(--pn-amber)!important;background:#fff5db!important}.pn5323Block.check.ok,.pn5323Block.done{border-left-color:var(--pn-green)!important;background:var(--pn-green-bg)!important}.pn5323Block.check.hold,.pn5323Block.stop{border-left-color:var(--pn-red)!important;background:var(--pn-red-bg)!important}.pn5323Actions{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important;padding:13px!important}.pn5323Actions button{min-height:50px!important;border-radius:12px!important;font-size:10px!important;font-weight:950!important}.pn5323Actions .primary,#pn5323Primary{grid-column:1/-1!important;min-height:62px!important;background:var(--pn-steel)!important;color:#fff!important;border:0!important;font-size:13px!important}.pn5323Actions .primary.pnV2Done,#pn5323Primary.pnV2Done{background:var(--pn-green)!important}.pn5323Actions .primary.pnV2Start,#pn5323Primary.pnV2Start{background:var(--pn-amber)!important;color:#17150d!important}.pn5323Actions .primary.pnV2Check,#pn5323Primary.pnV2Check{background:var(--pn-blue)!important}.pn5323Learn{margin:0 13px 13px!important;border:1px solid #ddddd6!important;border-radius:14px!important;background:#faf9f6!important;padding:13px!important}
#pnAnyDoneBox{border:1px solid #b5d7c2!important;border-radius:17px!important;background:var(--pn-green-bg)!important;padding:12px!important}#pnAnyDoneBtn{min-height:56px!important;border-radius:12px!important;background:var(--pn-green)!important;font-size:12px!important}.pnBigHead{align-items:center!important}.pnBigTitle{font-size:22px!important;letter-spacing:-.03em!important}.pnBigRow{padding:10px 0!important}.pnBigNum{background:var(--pn-steel)!important}.pnBigRow.now .pnBigTag{background:var(--pn-green-bg)!important;color:#185d39!important}.pnToolBtn{min-height:58px!important;border-radius:13px!important;background:var(--pn-steel)!important}.pn5345Open{min-height:55px!important;border-radius:13px!important;background:var(--pn-amber)!important;color:#17150d!important}
#pn5335Today,#pn5345Modal,#pnMorningPack{background:var(--pn-bg)!important}.pn5335Top,.pn5345Top,.pnMorningTop{background:rgba(255,255,255,.97)!important;backdrop-filter:blur(14px)!important;border-bottom:1px solid #d6d5cf!important;box-shadow:0 6px 20px rgba(20,25,28,.05)!important}.pn5335Body,.pn5345Body,.pnMorningBody{max-width:1080px!important}.pn5335Hero,.pn5345Hero,.pnMorningHero{background:linear-gradient(135deg,var(--pn-steel),#2b3338)!important;border-radius:20px!important;box-shadow:var(--pn-shadow)!important}.pn5335Open,.pnMorningActions .primary,.pnMorningAddJob{background:var(--pn-amber)!important;color:#17150d!important}.pn5335Why,.pn5335Later,.pn5345Job,.pnMorningCard{border-color:#d7d6d0!important;border-radius:15px!important;box-shadow:var(--pn-shadow-sm)!important}
#pn536Nav{background:rgba(249,249,246,.97)!important;backdrop-filter:blur(16px)!important;border:1px solid #cfcec8!important;border-radius:20px!important;box-shadow:0 12px 35px rgba(20,25,28,.19)!important;padding:6px!important}#pn536Nav button{min-height:56px!important;border-radius:13px!important;background:transparent!important;color:#656661!important;font-size:8px!important;font-weight:950!important}#pn536Nav button.active{background:var(--pn-steel)!important;color:#fff!important}#pn536Nav #pn5335TodayBtn{background:#fff2cc!important;color:#614508!important}#pnPlanOverlay{background:#111416!important}.pnPlanTop,.pnPlanHint{background:#161b1f!important}.pnPlanBody{background:#c9c9c3!important}.pnPlanControls button{border-radius:10px!important}#pnStablePending{background:var(--pn-amber)!important;color:#17150d!important;border:1px solid #cf9818!important;box-shadow:0 7px 20px rgba(0,0,0,.16)!important}
#pn522Version,#pnUpdateBanner{display:none!important}details>summary{cursor:pointer}
@media(min-width:901px){.pnV2LegacyNav{display:none!important}.pnV2Root{padding-top:18px!important}.pnV2CurrentPanel{padding:22px!important}.pnV2ActionCard{padding:20px!important}}
@media(max-width:900px){.pnV2Root{width:min(100% - 14px,780px)!important;padding-top:8px!important}.pnV2Hero{grid-template-columns:1fr;padding:17px 15px 14px;gap:12px}.pnV2Status{min-height:auto}.pnV2Pct{font-size:36px}.pnV2Quick{grid-template-columns:repeat(4,minmax(0,1fr));padding:8px;gap:6px}.pnV2Quick button{min-height:46px;font-size:8px}.pnV2Quick .morning{grid-column:span 2}.pnV2CurrentPanel{padding:13px!important;border-radius:19px!important}.pnV2SectionTitle{font-size:30px!important}.pnV2ActionCard{padding:13px!important}.pnV2HeaderBrand{font-size:22px!important}}
@media(max-width:560px){.pnV2Root{width:100%!important;padding:6px 7px calc(110px + env(safe-area-inset-bottom))!important}.pnV2Hero{padding:15px 12px 12px}.pnV2Task{font-size:24px}.pnV2Hint{font-size:11px}.pnV2Status{padding:11px;border-radius:14px}.pnV2Quick{grid-template-columns:repeat(3,minmax(0,1fr))}.pnV2Quick .morning{grid-column:span 3}.pnV2Quick .project{grid-column:span 2}.pnV2CurrentPanel{padding:11px!important}.pnV2SectionTitle{font-size:27px!important}.pnV2ActionCard button{min-height:52px!important}.pn5323Head{padding:16px 14px!important}.pn5323Title{font-size:25px!important}.pn5323Block .pn5323Text{font-size:14px!important}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important;animation-duration:.01ms!important}}
`;
  document.head.appendChild(s);
}

function markRoot(){var host=document.getElementById('taskCard')||exactText('YOUR JOB NOW');if(!host)return null;var r=topRoot(host);if(r)r.classList.add('pnV2Root');return r;}
function polishHeader(){
  var brand=exactText('Pinnacle Navigator');if(brand){brand.classList.add('pnV2HeaderBrand');var p=brand.parentElement;if(p&&p.parentElement)p.parentElement.classList.add('pnV2Header');}
  var all=document.querySelectorAll('body *');for(var i=0;i<all.length;i++){var t=String(all[i].textContent||'').trim();if(t.indexOf('Built from:')===0&&all[i].children.length===0)all[i].classList.add('pnV2Source');}
}
function polishCurrent(){
  var open=findButton('OPEN JOB'),block=findButton('BLOCK / WAIT'),title=exactText('YOUR JOB NOW');
  if(open)open.classList.add('pnV2Open');if(block)block.classList.add('pnV2Block');if(title){title.classList.add('pnV2SectionTitle');var prev=title.previousElementSibling;if(prev)prev.classList.add('pnV2SectionK');}
  var c=common(open,block);if(c){var action=c.parentElement&&c.parentElement.textContent&&norm(c.parentElement.textContent).indexOf('OPEN JOB')>=0?c.parentElement:c;action.classList.add('pnV2ActionCard');var panel=action;for(var i=0;i<5&&panel;i++,panel=panel.parentElement){var txt=norm(panel.textContent);if(txt.indexOf('YOUR JOB NOW')>=0&&txt.indexOf('CREW RIGHT NOW')>=0){panel.classList.add('pnV2CurrentPanel');break;}}}
  ['WHY DID NAVIGATOR GIVE ME THIS JOB?','CREW RIGHT NOW'].forEach(function(x){var e=exactText(x);if(e){var p=e.parentElement;if(p)p.classList.add('pnV2Info');}});
}
function polishLegacyNav(){var a=findButton('MY JOB'),b=findButton('CREW'),c=findButton('PROGRESS'),d=findButton('TASKS');var p=common(a,b);if(p&&c&&p.contains(c)&&d&&p.contains(d))p.classList.add('pnV2LegacyNav');}
function paintPrimary(){var b=document.getElementById('pn5323Primary');if(!b)return;var t=norm(b.textContent);b.classList.remove('pnV2Done','pnV2Start','pnV2Check');if(t.indexOf('DONE')>=0||t.indexOf('FINISH')>=0)b.classList.add('pnV2Done');else if(t.indexOf('START')>=0)b.classList.add('pnV2Start');else if(t.indexOf('CHECK')>=0)b.classList.add('pnV2Check');}
function overviewHtml(){
  var t=currentTask(),c=counts(),p=pending(),online=navigator.onLine;
  var title=t?(String(t.id||'')+' · '+String(t.title||'CURRENT TASK')):'Open My Job';
  var hint=t?'This is the task Navigator currently has in front of you. Open it for the exact work, checks, plans and DONE action.':'Open your job to see the next live piece of work.';
  return '<div class="pnV2Hero"><div><div class="pnV2Eyebrow">PINNACLE BUILDERS · MUNDI POS 1 · WORKDAY CONTROL</div><div class="pnV2Task">'+esc(title)+'</div><div class="pnV2Hint">'+esc(hint)+'</div><div class="pnV2Meta"><span class="pnV2Chip '+(online?'live':'local')+'">'+(online?'● LIVE + SYNC READY':'LOCAL COPY READY')+'</span><span class="pnV2Chip">'+esc(personName())+'</span><span class="pnV2Chip">'+esc(VERSION)+'</span>'+(c.holds?'<span class="pnV2Chip hold">'+c.holds+' ACTIVE HOLD'+(c.holds===1?'':'S')+'</span>':'')+(p?'<span class="pnV2Chip local">'+p+' CHANGE'+(p===1?'':'S')+' WAITING TO SYNC</span>':'')+'</div></div><div class="pnV2Status"><div><div class="pnV2StatusK">PROJECT TASK PROGRESS</div><div class="pnV2Pct">'+c.pct+'%</div><div class="pnV2Bar"><i style="width:'+c.pct+'%"></i></div></div><div class="pnV2StatusS">'+c.closed+' of '+c.total+' tasks closed · '+c.holds+' hold'+(c.holds===1?'':'s')+'</div></div></div><div class="pnV2Quick"><button class="morning" data-pnv2="morning">MORNING PACK</button><button data-pnv2="my">MY JOB</button><button data-pnv2="today">TODAY</button><button data-pnv2="tasks">TASKS</button><button data-pnv2="crew">CREW</button><button class="project" data-pnv2="project">FULL PROJECT</button><button class="tool" data-pnv2="tool">42.5 TEMPLATE</button></div>';
}
function bindOverview(box){if(!box||box.__pnV2Bound)return;box.__pnV2Bound=true;box.addEventListener('click',function(e){var b=e.target&&e.target.closest?e.target.closest('[data-pnv2]'):null;if(!b)return;var k=b.getAttribute('data-pnv2');if(k==='morning')openMorning();else if(k==='my')clickOriginal('MY JOB');else if(k==='today')openToday();else if(k==='tasks')clickOriginal('TASKS');else if(k==='crew')clickOriginal('CREW');else if(k==='project')openProject();else if(k==='tool')openTemplate();setTimeout(schedule,100);});}
function ensureOverview(){
  var host=document.getElementById('taskCard');if(!host){var t=exactText('YOUR JOB NOW');if(t){host=t;for(var i=0;i<6&&host.parentElement;i++){if(norm(host.parentElement.textContent).indexOf('OPEN JOB')>=0){host=host.parentElement;break;}host=host.parentElement;}}}
  if(!host||!host.parentNode)return;
  var old=document.getElementById('pnWorkshopOverview');if(old)old.remove();
  var box=document.getElementById(OVERVIEW_ID);if(!box){box=document.createElement('section');box.id=OVERVIEW_ID;host.parentNode.insertBefore(box,host);}
  var html=overviewHtml();if(box.__pnV2Html!==html){box.__pnV2Html=html;box.innerHTML=html;box.__pnV2Bound=false;}bindOverview(box);
}
function sync(){style();markRoot();polishHeader();ensureOverview();polishCurrent();polishLegacyNav();paintPrimary();document.documentElement.classList.toggle('pnV2Offline',!navigator.onLine);}
function schedule(){if(refreshTimer)clearTimeout(refreshTimer);refreshTimer=setTimeout(function(){refreshTimer=0;sync();},100);}
function boot(){
  sync();[180,550,1200,2600,5000].forEach(function(ms){setTimeout(sync,ms);});
  window.addEventListener('pageshow',sync);window.addEventListener('focus',schedule);window.addEventListener('resize',schedule);window.addEventListener('online',sync);window.addEventListener('offline',sync);
  window.addEventListener('pn-state-changed',sync);window.addEventListener('pn-preflight-changed',sync);window.addEventListener('pn-one-step-rendered',sync);window.addEventListener('pn-stability-status',sync);
  document.addEventListener('visibilitychange',function(){if(!document.hidden)sync();});
  document.addEventListener('click',function(){setTimeout(schedule,80);},true);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
