(function(){
'use strict';
if(window.__PN_WORKSHOP_UI_MINIMAL_5367__)return;
window.__PN_WORKSHOP_UI_MINIMAL_5367__=true;

var STYLE_ID='pnMinimalWorkshopStyle5367';
var VERSION='v53.60';

function norm(v){return String(v||'').replace(/\s+/g,' ').trim().toUpperCase();}
function leafExact(text){var want=norm(text),all=document.querySelectorAll('body *');for(var i=0;i<all.length;i++){var el=all[i];if(el.children.length===0&&norm(el.textContent)===want)return el;}return null;}
function leafStarts(text){var want=norm(text),all=document.querySelectorAll('body *');for(var i=0;i<all.length;i++){var el=all[i],t=norm(el.textContent);if(el.children.length===0&&t.indexOf(want)===0)return el;}return null;}
function findButton(text){var want=norm(text),all=document.querySelectorAll('button,a,[role="button"]');for(var i=0;i<all.length;i++){var t=norm(all[i].textContent);if(t===want||t.indexOf(want+' ')===0)return all[i];}return null;}
function common(a,b){if(!a||!b)return null;for(var p=a;p&&p!==document.body;p=p.parentElement)if(p.contains(b))return p;return null;}
function topRoot(el){if(!el)return null;var n=el;while(n.parentElement&&n.parentElement!==document.body)n=n.parentElement;return n===document.body?null:n;}
function add(el,cls){if(el)el.classList.add(cls);}
function currentPanel(){var h=leafExact('YOUR JOB NOW');if(!h)return null;var p=h;for(var i=0;i<9&&p&&p!==document.body;i++,p=p.parentElement){var buttons=p.querySelectorAll?Array.from(p.querySelectorAll('button,a,[role="button"]')):[];if(buttons.some(function(b){return norm(b.textContent).indexOf('OPEN JOB')===0;}))return p;}return h.parentElement;}
function tag(){try{var task=document.getElementById('taskCard')||leafExact('YOUR JOB NOW');var root=topRoot(task);add(root,'pnMinimalRoot');var brand=leafExact('Pinnacle Navigator');add(brand,'pnMinimalBrand');if(brand&&brand.parentElement)add(brand.parentElement,'pnMinimalBrandWrap');var source=leafStarts('Built from:');add(source,'pnMinimalSource');if(source&&source.parentElement)add(source.parentElement,'pnMinimalSourceWrap');var panel=currentPanel();add(panel,'pnMinimalCurrent');var open=findButton('OPEN JOB'),block=findButton('BLOCK / WAIT');add(open,'pnMinimalOpen');add(block,'pnMinimalBlock');var action=common(open,block);if(action){var p=action;for(var j=0;j<3&&p&&p!==panel;j++,p=p.parentElement){if(norm(p.textContent).indexOf('RECOMMENDED')!==-1||norm(p.textContent).indexOf('NOT STARTED')!==-1){action=p;break;}}add(action,'pnMinimalAction');}var why=leafStarts('WHY DID NAVIGATOR GIVE ME THIS JOB');if(why)add(why.parentElement||why,'pnMinimalDisclosure');var crew=leafStarts('CREW RIGHT NOW');if(crew)add(crew.parentElement||crew,'pnMinimalDisclosure');var my=findButton('MY JOB'),cr=findButton('CREW'),pr=findButton('PROGRESS'),ts=findButton('TASKS');var nav=common(my,cr);nav=common(nav,pr);nav=common(nav,ts);add(nav,'pnMinimalNav');add(findButton('OPEN FULL PROJECT WORK REGISTER'),'pnMinimalUtility');add(findButton('MORNING PACK'),'pnMinimalUtility');add(findButton('42.5 TEMPLATE'),'pnMinimalUtility');add(findButton('42.5 MM DEFAULT MITER TEMPLATE'),'pnMinimalUtility');document.documentElement.classList.add('pnMinimalReady');}catch(e){}}

function style(){if(document.getElementById(STYLE_ID))return;var s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
:root{--pn-bg:#f4f2ed;--pn-surface:#fff;--pn-surface-soft:#faf9f6;--pn-ink:#12181f;--pn-muted:#687078;--pn-line:#e2ded6;--pn-navy:#172431;--pn-navy-2:#223343;--pn-gold:#d7a62b;--pn-gold-soft:#fff7df;--pn-green:#247c4b;--pn-green-soft:#edf8f1;--pn-red:#a53b35;--pn-red-soft:#fff3f1;--pn-shadow:0 18px 48px rgba(27,34,40,.09);--pn-shadow-soft:0 8px 26px rgba(27,34,40,.055)}
*{box-sizing:border-box}html{background:var(--pn-bg)!important;scrollbar-gutter:stable;-webkit-text-size-adjust:100%}body{margin:0!important;min-height:100dvh!important;background:linear-gradient(180deg,#fbfaf7 0,#f4f2ed 42%,#f4f2ed 100%)!important;color:var(--pn-ink)!important;font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif!important;text-rendering:optimizeLegibility!important}body:before{content:"";position:fixed;left:0;right:0;top:0;height:6px;background:linear-gradient(90deg,var(--pn-navy) 0 76%,var(--pn-gold) 76% 100%);z-index:99999;pointer-events:none}button,input,textarea,select{font:inherit}button{touch-action:manipulation;-webkit-tap-highlight-color:transparent}button:focus-visible,a:focus-visible,input:focus-visible,textarea:focus-visible,summary:focus-visible{outline:3px solid rgba(215,166,43,.28)!important;outline-offset:2px!important}
.pnMinimalRoot{width:min(1180px,calc(100% - 44px))!important;max-width:1180px!important;margin:0 auto!important;padding:26px 0 110px!important}.pnMinimalRoot>*{max-width:none!important}.pnMinimalBrand{font-size:clamp(24px,2.2vw,34px)!important;font-weight:900!important;letter-spacing:-.045em!important;line-height:1!important;color:var(--pn-ink)!important}.pnMinimalBrandWrap{padding:2px 0 13px!important}.pnMinimalSourceWrap{margin:2px 0 16px!important}.pnMinimalSource{display:block!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;background:transparent!important;border:0!important;border-top:1px solid var(--pn-line)!important;border-bottom:1px solid var(--pn-line)!important;border-radius:0!important;padding:8px 2px!important;color:#7a7f83!important;font-size:9px!important;line-height:1.25!important;font-weight:650!important;letter-spacing:.01em!important}
.pnMinimalCurrent{background:var(--pn-surface)!important;border:1px solid var(--pn-line)!important;border-radius:26px!important;padding:24px!important;box-shadow:var(--pn-shadow)!important;margin:0 0 18px!important;overflow:hidden!important}.pnMinimalCurrent h1,.pnMinimalCurrent h2,.pnMinimalCurrent h3{color:var(--pn-ink)!important;letter-spacing:-.035em!important;margin-top:0!important}.pnMinimalCurrent button{border-radius:14px!important;font-weight:850!important;letter-spacing:.01em!important;box-shadow:none!important}.pnMinimalAction{background:linear-gradient(135deg,#f0f9f3 0,#f8fbf9 100%)!important;border:1px solid #c8e4d2!important;border-left:5px solid var(--pn-green)!important;border-radius:20px!important;padding:20px!important;box-shadow:none!important;margin-top:12px!important}.pnMinimalOpen,.pnMinimalBlock{min-height:58px!important;border-radius:14px!important;font-size:14px!important;font-weight:900!important;transition:transform .12s ease,box-shadow .12s ease!important}.pnMinimalOpen{background:var(--pn-navy)!important;border-color:var(--pn-navy)!important;color:#fff!important}.pnMinimalOpen:hover{background:var(--pn-navy-2)!important;transform:translateY(-1px)!important;box-shadow:0 8px 20px rgba(23,36,49,.14)!important}.pnMinimalBlock{background:#fffaf0!important;border:1px solid #dfbd63!important;color:#8c6500!important}.pnMinimalBlock:hover{background:var(--pn-gold-soft)!important;transform:translateY(-1px)!important}.pnMinimalDisclosure{background:var(--pn-surface-soft)!important;border:1px solid var(--pn-line)!important;border-radius:14px!important;box-shadow:none!important;margin-top:9px!important;color:#2f373e!important}.pnMinimalDisclosure button,.pnMinimalDisclosure summary{min-height:46px!important;padding:0 14px!important;font-size:10px!important;font-weight:850!important;letter-spacing:.01em!important}
#taskCard{width:100%!important;max-width:none!important;margin:0!important;background:transparent!important;border:0!important;box-shadow:none!important;padding:0!important}#pn5323OneStep{background:var(--pn-surface)!important;border:1px solid var(--pn-line)!important;border-radius:24px!important;overflow:hidden!important;box-shadow:var(--pn-shadow-soft)!important;margin:18px 0!important}.pn5323Head{background:var(--pn-navy)!important;color:#fff!important;padding:22px 24px!important;border:0!important;position:relative!important}.pn5323Head:before{content:"";position:absolute;left:0;top:0;right:0;height:4px;background:var(--pn-gold)}.pn5323K{color:#bfc9d2!important;font-size:9px!important;font-weight:800!important;letter-spacing:.1em!important}.pn5323Title{font-size:clamp(26px,3vw,40px)!important;line-height:1.03!important;letter-spacing:-.045em!important;font-weight:900!important}.pn5323Block{margin:12px 16px 0!important;padding:14px 16px!important;border:1px solid var(--pn-line)!important;border-left:4px solid #aeb8c1!important;border-radius:14px!important;background:#fff!important;box-shadow:none!important}.pn5323Block .pn5323Label{font-size:8px!important;font-weight:850!important;letter-spacing:.09em!important;color:#7a8086!important}.pn5323Block .pn5323Text{font-size:15px!important;line-height:1.45!important;color:#20272d!important;font-weight:700!important}.pn5323Block.check{border-left-color:var(--pn-gold)!important;background:#fffaf0!important}.pn5323Block.check.ok,.pn5323Block.done{border-left-color:var(--pn-green)!important;background:var(--pn-green-soft)!important}.pn5323Block.check.hold,.pn5323Block.stop{border-left-color:var(--pn-red)!important;background:var(--pn-red-soft)!important}.pn5323Actions{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:10px!important;padding:16px!important}.pn5323Actions button{min-height:52px!important;border-radius:13px!important;font-weight:900!important}.pn5323Actions .primary,#pn5323Primary{grid-column:1/-1!important;min-height:60px!important;background:var(--pn-navy)!important;color:#fff!important;border:0!important;font-size:13px!important}.pn5323Learn{margin:0 16px 16px!important;border:1px solid var(--pn-line)!important;border-radius:14px!important;background:var(--pn-surface-soft)!important;padding:14px!important}
#pnBigJobsHome,#pnBigJobsToday{background:var(--pn-surface)!important;border:1px solid var(--pn-line)!important;border-radius:24px!important;padding:20px!important;box-shadow:var(--pn-shadow-soft)!important;color:var(--pn-ink)!important;margin:18px 0!important}.pnBigHead{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:16px!important;margin-bottom:8px!important}.pnBigTitle{font-size:23px!important;font-weight:900!important;letter-spacing:-.03em!important}.pnBigSub{font-size:8px!important;font-weight:750!important;color:#8a8e91!important;line-height:1.35!important}.pnBigRow{display:grid!important;grid-template-columns:34px 1fr auto!important;gap:12px!important;align-items:center!important;min-height:54px!important;padding:8px 2px!important;border-top:1px solid #ebe8e2!important}.pnBigRow.first{border-top:0!important}.pnBigNum{width:31px!important;height:31px!important;border-radius:10px!important;background:var(--pn-navy)!important;color:#fff!important;display:grid!important;place-items:center!important;font-size:11px!important;font-weight:900!important}.pnBigName{font-size:13px!important;font-weight:800!important;letter-spacing:-.01em!important}.pnBigTag{padding:6px 9px!important;border-radius:999px!important;background:#f0f1f1!important;color:#636b70!important;font-size:8px!important;font-weight:850!important}.pnBigRow.now .pnBigTag{background:#e8f6ed!important;color:#1d6a40!important}.pnBigRow.galv .pnBigTag{background:#fff4d8!important;color:#805a00!important}.pnBigMore,.pnBigHolds,.pnWorkshopTools{border-top:1px solid #ebe8e2!important;padding-top:10px!important;margin-top:6px!important}.pnBigMore summary,.pnBigHolds summary{font-size:9px!important;font-weight:800!important;color:#626970!important;cursor:pointer!important}.pnBigHolds{background:transparent!important;border:0!important;border-radius:0!important;padding-left:0!important;padding-right:0!important}.pnBigNote{display:none!important}.pnToolsLabel{font-size:8px!important;font-weight:800!important;color:#8b8f92!important;letter-spacing:.08em!important}.pnToolBtn{min-height:48px!important;border-radius:12px!important;background:var(--pn-navy)!important;border:0!important;color:#fff!important;padding:10px 13px!important}.pnToolMain{font-size:10px!important}.pnToolSub{font-size:7px!important;color:#cbd3da!important}.pnMinimalUtility{min-height:46px!important;border-radius:12px!important;font-size:9px!important;font-weight:850!important;box-shadow:none!important}
#pnAnyDoneBox{background:var(--pn-green-soft)!important;border:1px solid #c7e2d1!important;border-radius:16px!important;padding:12px!important;box-shadow:none!important}#pnAnyDoneBtn{min-height:52px!important;border:0!important;border-radius:12px!important;background:var(--pn-green)!important;color:#fff!important;font-size:11px!important;font-weight:900!important}
.pnMinimalNav{position:sticky!important;bottom:18px!important;z-index:500!important;width:min(680px,calc(100% - 24px))!important;margin:20px auto 0!important;padding:7px!important;background:rgba(255,255,255,.92)!important;border:1px solid rgba(214,211,203,.95)!important;border-radius:18px!important;box-shadow:0 16px 40px rgba(22,29,35,.12)!important;backdrop-filter:blur(16px)!important;-webkit-backdrop-filter:blur(16px)!important}.pnMinimalNav button{min-height:46px!important;border:0!important;border-radius:12px!important;background:transparent!important;color:#5f676d!important;font-size:9px!important;font-weight:850!important;box-shadow:none!important}.pnMinimalNav button[aria-selected="true"],.pnMinimalNav button.active,.pnMinimalNav button:first-child{background:var(--pn-navy)!important;color:#fff!important}
#pnMorningPack,#pnMorningPackModal,.pnMorningPanel,.pnMorningModal{font-family:inherit!important}#pnMorningPack button,#pnMorningPackModal button,.pnMorningPanel button,.pnMorningModal button{border-radius:12px!important;box-shadow:none!important}#pnPlanOverlay{font-family:inherit!important}.pnPlanTop{background:var(--pn-navy)!important}.pnPlanLoading{border-radius:16px!important}.pnPlanControls button{border-radius:10px!important}
@media(max-width:760px){html{scrollbar-gutter:auto}.pnMinimalRoot{width:calc(100% - 14px)!important;padding:14px 0 90px!important}.pnMinimalCurrent{border-radius:20px!important;padding:15px!important}.pnMinimalAction{padding:14px!important;border-radius:16px!important}.pnMinimalOpen,.pnMinimalBlock{min-height:54px!important;font-size:12px!important}.pnBigTitle{font-size:19px!important}.pnBigRow{grid-template-columns:30px 1fr!important;gap:9px!important}.pnBigTag{grid-column:2!important;justify-self:start!important;margin-top:-5px!important}.pnMinimalNav{position:fixed!important;left:7px!important;right:7px!important;bottom:max(7px,env(safe-area-inset-bottom))!important;width:auto!important;margin:0!important;border-radius:16px!important}.pnMinimalSource{font-size:8px!important}.pn5323Actions{grid-template-columns:1fr!important}.pn5323Actions .primary,#pn5323Primary{grid-column:1!important}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important;animation-duration:.01ms!important}}
`;document.head.appendChild(s);}

style();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',tag,{once:true});else tag();setTimeout(tag,180);setTimeout(tag,700);setTimeout(tag,1600);
})();
