(function(){
'use strict';
if(window.__PN_NOVA_5373__)return;window.__PN_NOVA_5373__=true;
var NAV=null,key='my',explicit=false,detail=false,timers=[];
function n(v){return String(v==null?'':v).replace(/\s+/g,' ').trim().toUpperCase()}
function e(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function txt(x){return String(x&&x.textContent||'').replace(/\s+/g,' ').trim()}
function who(){try{if(typeof state!=='undefined'&&state&&state.currentUser)return String(state.currentUser)}catch(_){}try{return localStorage.getItem('pn_live_person')||''}catch(_){return''}}
function whoName(){var p=who();return p==='me'?'MITCHELL':p==='ronan'?'RONAN':p==='colin'?'COLIN':'CREW'}
function task(){try{if(typeof previewTaskId!=='undefined'&&previewTaskId&&Array.isArray(TASKS))return TASKS.find(function(x){return x&&x.id===previewTaskId})||null;if(typeof currentPersonTask==='function')return currentPersonTask()||null;var p=who(),id=state&&state.assignments&&state.assignments[p];if(id&&Array.isArray(TASKS))return TASKS.find(function(x){return x&&x.id===id})||null}catch(_){}return null}
function app(){return document.querySelector('.app')||document.getElementById('taskCard')&&document.getElementById('taskCard').parentElement||document.body}
function kfor(x){var t=n(x&&x.textContent);if(t==='MY JOB')return'my';if(t==='CREW')return'crew';if(t==='PROGRESS')return'progress';if(t==='TASKS')return'tasks';if(t==='UPDATES')return'updates';return''}
function nav(){if(NAV&&NAV.isConnected)return NAV;NAV=document.getElementById('pn536Nav');if(NAV)return NAV;var all=document.querySelectorAll('button,a,[role="button"]'),hits=[];for(var i=0;i<all.length;i++)if(kfor(all[i]))hits.push(all[i]);if(hits.length<3)return null;var p=hits[0];while(p&&p!==document.body){var count=0;for(var j=0;j<hits.length;j++)if(p.contains(hits[j]))count++;if(count>=3){NAV=p;break}p=p.parentElement}return NAV}
function setNav(k){if(!k)return;key=k;var q=nav();if(!q)return;q.classList.add('pnNovaNav');var b=q.querySelectorAll('button,a,[role="button"]');for(var i=0;i<b.length;i++){var x=kfor(b[i]);if(x)b[i].classList.toggle('pnNovaActive',x===k)}}
function findText(prefix,root){var w=n(prefix),a=(root||document).querySelectorAll('h1,h2,h3,h4,div,span,p,strong,b,small'),best=null,len=1e9;for(var i=0;i<a.length;i++){if(a[i].closest&&a[i].closest('#pnNovaHeader,#pnNovaFocus'))continue;var t=n(a[i].textContent);if(t.indexOf(w)!==0)continue;if(t.length<len){best=a[i];len=t.length}}return best}
function findAction(labels,root){var arr=(Array.isArray(labels)?labels:[labels]).map(n),a=(root||document).querySelectorAll('button,a,[role="button"]');for(var i=0;i<a.length;i++){if(a[i].closest&&a[i].closest('#pnNovaFocus'))continue;var t=n(a[i].textContent);for(var j=0;j<arr.length;j++)if(t===arr[j]||t.indexOf(arr[j]+' ')===0)return a[i]}return null}
function status(){var x=document.getElementById('liveStatus');if(x)return txt(x);return navigator.onLine?'LIVE':'OFFLINE'}
function source(){var x=findText('BUILT FROM:');return x?txt(x).replace(/^Built from:\s*/i,'').slice(0,420):''}
function hideOldChrome(){var a=app(),b=findText('PINNACLE NAVIGATOR',a);if(b&&!b.closest('#pnNovaHeader')){var p=b,hit=null;for(var i=0;i<6&&p&&p!==a;i++,p=p.parentElement){var t=n(p.textContent);if(t.indexOf('MUNDI POS 1')!==-1&&t.length<1200)hit=p}if(hit)hit.classList.add('pnNovaOldChrome')}var s=findText('BUILT FROM:',a);if(s&&!s.closest('#pnNovaHeader'))(s.parentElement||s).classList.add('pnNovaOldSource')}
function header(){var a=app();if(!a)return;hideOldChrome();var h=document.getElementById('pnNovaHeader');if(!h){h=document.createElement('header');h.id='pnNovaHeader';a.insertBefore(h,a.firstChild)}var st=status(),warn=/OFFLINE|QUEUED|MERGING|WAIT/i.test(st),src=source();h.innerHTML='<div class="pnNovaBrand"><div class="pnNovaLogo">PN</div><div><b>Pinnacle Navigator</b><small>MUNDI POS 1 · WORKSHOP</small></div></div><div class="pnNovaMeta"><span class="pnNovaStatus '+(warn?'warn':'')+'"><i></i>'+e(st)+'</span><span class="pnNovaUser">'+e(whoName())+'</span></div>'+(src?'<div class="pnNovaSource"><span>SOURCE</span>'+e(src)+'</div>':'')}
function detailRoot(t){var c=document.getElementById('taskCard');if(!c)return null;var x=t&&t.title?findText(t.title,c):null;if(!x)x=findText('3 QUICK STEPS',c);if(!x)return null;var p=x,hit=null;for(var i=0;i<9&&p&&p!==c;i++,p=p.parentElement){var s=n(p.textContent);if(s.indexOf('3 QUICK STEPS')>-1&&s.indexOf('DO THIS')>-1&&s.indexOf('WHY')>-1&&s.indexOf('BIG JOBS RIGHT NOW')<0&&s.length<16000)hit=p}return hit}
function summaryRoot(t){var c=document.getElementById('taskCard')||document;var open=findAction(['OPEN JOB','START JOB','CONTINUE'],c),block=findAction('BLOCK / WAIT',c);if(!open)return null;var p=open,hit=null;for(var i=0;i<8&&p&&p!==c.parentElement;i++,p=p.parentElement){var s=n(p.textContent);if(s.indexOf(n(t&&t.title||'YOUR JOB NOW'))>-1&&(!block||p.contains(block))&&s.length<7000){hit=p;break}}return hit||open.parentElement}
function extract(prefix,root){var x=findText(prefix,root);if(!x)return'';var p=x.parentElement||x,s=txt(p),lab=txt(x);if(n(s).indexOf(n(lab))===0)s=s.slice(lab.length).replace(/^\s*[-:|]\s*/,'');return s.slice(0,1300)}
function stateLabel(t){try{var id=String(t&&t.id||'');if(Array.isArray(state.done)&&state.done.indexOf(id)>-1)return'DONE';if(state.holds&&state.holds[id])return'HOLD';var p=who();if(state.startedByPerson&&state.startedByPerson[p]===id)return'IN PROGRESS'}catch(_){}return'READY'}
function proxy(btn,target){if(btn&&target)btn.onclick=function(){try{target.click()}catch(_){ }later(120)}}
function fallbackAction(root,title){var parts=root?root.querySelectorAll('p,div,strong'):[],best='';for(var i=0;i<parts.length;i++){var s=txt(parts[i]);if(s.length>45&&s.length<380&&n(s).indexOf(n(title||''))<0&&!/RECOMMENDED|SIGNED IN|YOUR JOB NOW|OPEN JOB|BLOCK \/ WAIT/.test(n(s))){if(!best||s.length<best.length)best=s}}return best}
function focus(){var old=document.getElementById('pnNovaFocus');if(old)old.remove();var prev=document.querySelectorAll('.pnNovaLegacy');for(var z=0;z<prev.length;z++)prev[z].classList.remove('pnNovaLegacy','pnNovaLegacyOpen');if(key!=='my')return;var t=task(),d=detailRoot(t),summary=false;if(!d){d=summaryRoot(t);summary=!!d}if(!d)return;var title=String(t&&t.title||'').trim();if(!title){var h=d.querySelector('h1,h2,h3,strong');title=h?txt(h):'CURRENT JOB'}d.classList.add('pnNovaLegacy');if(detail&&!summary)d.classList.add('pnNovaLegacyOpen');var action=String(t&&t.action||extract('DO THIS',d)||fallbackAction(d,title)||'Follow the current verified instruction.').trim(),done=String(t&&t.right||'').trim(),stop=String(t&&t.stop||extract('ASK / CONFIRM THIS',d)||extract('NAVIGATOR CHECK',d)||'').trim(),where=extract('WHERE',d),why=String(t&&t.explain||extract('WHY',d)||'').trim();var primary=findAction(['OPEN JOB','START JOB','CONTINUE','DONE','MARK DONE'],d)||document.getElementById('pn5323Primary'),plan=findAction(['PLAN','PLAN · TASK AREA','PLAN - TASK AREA'],d)||document.getElementById('planBtn'),block=findAction('BLOCK / WAIT',d);var f=document.createElement('section');f.id='pnNovaFocus';var st=stateLabel(t),id=String(t&&t.id||'').replace(/^T/i,'');f.innerHTML='<div class="pnNovaHero"><div><div class="pnNovaEyebrow">YOUR JOB NOW'+(t&&t.id?' · '+e(t.id):'')+'</div><h1>'+e(title)+'</h1><div class="pnNovaPills"><span class="pnNovaPill '+(st==='HOLD'?'hold':'')+'">'+e(st)+'</span>'+(where?'<span class="pnNovaPill ghost">'+e(where.slice(0,105))+'</span>':'')+'</div></div>'+(id?'<div class="pnNovaTaskNo">'+e(id)+'</div>':'')+'</div><div class="pnNovaGrid"><article class="pnNovaDo"><span>DO THIS</span><strong>'+e(action)+'</strong></article>'+(done?'<article class="pnNovaDone"><span>DONE WHEN</span><p>'+e(done)+'</p></article>':'')+'</div>'+(stop?'<div class="pnNovaStop"><b>!</b><div><span>STOP / CONFIRM</span><p>'+e(stop)+'</p></div></div>':'')+'<div class="pnNovaActions">'+(primary?'<button id="pnNovaPrimary">'+e(txt(primary)||'CONTINUE')+' <b>→</b></button>':'')+(plan?'<button id="pnNovaPlan">PLAN</button>':'')+(block?'<button id="pnNovaBlock">BLOCK / WAIT</button>':'')+'</div>'+(!summary?'<div class="pnNovaMore"><button id="pnNovaMore">'+(detail?'HIDE DETAILS':'SHOW FULL JOB DETAIL')+'</button>'+(why?'<p>'+e(why)+'</p>':'')+'</div>':'');d.parentElement.insertBefore(f,d);proxy(document.getElementById('pnNovaPrimary'),primary);proxy(document.getElementById('pnNovaPlan'),plan);proxy(document.getElementById('pnNovaBlock'),block);var more=document.getElementById('pnNovaMore');if(more)more.onclick=function(){detail=!detail;d.classList.toggle('pnNovaLegacyOpen',detail);this.textContent=detail?'HIDE DETAILS':'SHOW FULL JOB DETAIL'}}
function priorities(){var b=document.getElementById('pnBigJobsHome')||document.getElementById('pnBigJobsToday');if(!b)return;b.classList.add('pnNovaPriorities');var title=b.querySelector('.pnBigTitle');if(title)title.textContent='PROJECT PRIORITIES';var rows=b.querySelectorAll('.pnBigRow');for(var i=0;i<rows.length;i++)rows[i].classList.toggle('pnNovaPriorityHidden',i>2)}
function pageHead(){var o=document.getElementById('pnNovaPageHead');if(o)o.remove();if(key==='my')return;var c=document.getElementById('taskCard');if(!c)return;var m={crew:['CREW','Who is doing what?','Live assignments and the next clear move.'],progress:['PROGRESS','Project progress','Only what matters next.'],tasks:['TASKS','All work','Find a task fast.'],updates:['UPDATES','Latest changes','What changed recently.']}[key];if(!m)return;var h=document.createElement('section');h.id='pnNovaPageHead';h.innerHTML='<small>'+m[0]+'</small><h1>'+m[1]+'</h1><p>'+m[2]+'</p>';c.insertBefore(h,c.firstChild)}
function longLists(){if(key!=='crew'&&key!=='updates')return;var c=document.getElementById('taskCard');if(!c)return;var a=c.querySelectorAll('[id*="history" i],[class*="history" i],[id*="activity" i],[class*="activity" i],[id*="log" i],[class*="log" i]');for(var i=0;i<a.length&&i<3;i++)if(a[i].children&&a[i].children.length>7){a[i].classList.add('pnNovaLong');for(var j=0;j<a[i].children.length;j++)a[i].children[j].classList.add('pnNovaRow')}}
function classes(){document.body.classList.remove('pnNovaMy','pnNovaCrew','pnNovaProgress','pnNovaTasks','pnNovaUpdates');document.body.classList.add(key==='crew'?'pnNovaCrew':key==='progress'?'pnNovaProgress':key==='tasks'?'pnNovaTasks':key==='updates'?'pnNovaUpdates':'pnNovaMy')}
function style(){if(document.getElementById('pnNovaCss5373'))return;var l=document.createElement('link');l.id='pnNovaCss5373';l.rel='stylesheet';l.href='./navigator-nova.css?v=5373';document.head.appendChild(l)}
function polish(){try{document.body.classList.add('pnNova');var q=nav(),nk='';if(q){var b=q.querySelectorAll('button,a,[role="button"]');for(var i=0;i<b.length;i++){var k=kfor(b[i]);if(k&&(b[i].classList.contains('active')||b[i].getAttribute('aria-current')==='page')){nk=k;break}}}if(!explicit&&nk)key=nk;setNav(key||nk||'my');classes();header();priorities();pageHead();focus();longLists()}catch(err){try{console.warn('Navigator visual layer',err)}catch(_){}}}
function later(ms){timers.push(setTimeout(polish,ms||0))}
style();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){[80,300,800,1800].forEach(later)},{once:true});else[0,250,700,1600].forEach(later);document.addEventListener('click',function(ev){var b=ev.target&&ev.target.closest?ev.target.closest('button,a,[role="button"]'):null;if(!b)return;var q=nav(),k=q&&q.contains(b)?kfor(b):'';if(k){explicit=true;detail=false;setNav(k);later(60);return}if(!b.closest('#pnNovaHeader,#pnNovaFocus'))later(70)},true);window.addEventListener('pageshow',function(){later(80)});document.addEventListener('visibilitychange',function(){if(!document.hidden)later(80)});
})();
