(()=>{'use strict';
const TZ='Australia/Perth',STORE='ytintel-progress-hq-v1',REPO='MitchLoxton/pinnacle-navigator',API='https://api.github.com/repos/'+REPO,LEVEL_SIZE=250;
const WEEK={start:'2026-09-14',end:'2026-09-20'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const uid=()=>Math.random().toString(36).slice(2,9);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isoDate=(d=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
const shortDay=s=>new Intl.DateTimeFormat('en-AU',{timeZone:TZ,weekday:'short'}).format(new Date(s+'T12:00:00+08:00'));
const perthStamp=()=>{const p=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(new Date()).reduce((a,x)=>(a[x.type]=x.value,a),{});return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}:${p.second}+08:00`};
const defaultState=()=>({version:1,week:WEEK,outcomes:[
{id:'release',title:'Release truth',why:'The same production release must have green checks, green deploy and real browser proof.',tasks:[
{id:uid(),title:'Benchmark contract shipped: v0.39 resilient benchmark mode',priority:'P0',done:true,evidence:'Release commit ff1098beb8e0aa185ffa0cecacaafa1b0315877c',blocker:''},
{id:uid(),title:'Core CI green on the release commit',priority:'P0',done:true,evidence:'YTIntel Core CI succeeded on ff1098b',blocker:''},
{id:uid(),title:'GitHub Pages deploy green on the release commit',priority:'P0',done:true,evidence:'Pages deploy succeeded on ff1098b',blocker:''},
{id:uid(),title:'Blake Ryan production smoke proves 16/16 benchmark sections',priority:'P0',done:true,evidence:'Production smoke 34757645134 succeeded; 16 benchmark sections, 17 appendix sections, 223.5 WPM, zero browser errors',blocker:''},
{id:uid(),title:'Make cloud research reliable again or formally choose the fallback-first contract',priority:'P0',done:false,evidence:'',blocker:'Current premium research path returns CREDIT_BALANCE_EXHAUSTED.'},
{id:uid(),title:'Keep release notes and verified Discord release receipt green',priority:'P1',done:true,evidence:'Verified production workflow completed the Discord release step.',blocker:''}]},
{id:'proof',title:'Real-user proof',why:'A technically correct product only counts if a clean user can enter, analyse and leave with a useful next action.',tasks:[
{id:uid(),title:'Fresh account: signup → email confirm → production return → persistent session',priority:'P0',done:false,evidence:'',blocker:'Needs true browser proof, not database inference.'},
{id:uid(),title:'Verify YTIntel profile + username persist for the fresh account',priority:'P0',done:false,evidence:'',blocker:''},
{id:uid(),title:'Verify intended signed-out and signed-in Analyse behaviour',priority:'P1',done:false,evidence:'',blocker:''},
{id:uid(),title:'Real creator case 1: complete benchmark analysis + record usable next-video decision',priority:'P0',done:false,evidence:'',blocker:''},
{id:uid(),title:'Real creator case 2: complete benchmark analysis + record usable next-video decision',priority:'P0',done:false,evidence:'',blocker:''},
{id:uid(),title:'Real creator case 3: complete benchmark analysis + record usable next-video decision',priority:'P0',done:false,evidence:'',blocker:''},
{id:uid(),title:'Document the canonical creator journey as a repeatable acceptance flow',priority:'P1',done:false,evidence:'',blocker:''}]},
{id:'trust',title:'Trust debt',why:'Security debt and known P0/P1 problems must be visible, owned and evidence-backed.',tasks:[
{id:uid(),title:'Resolve or explicitly disposition public.ytintel_ai_setup RLS debt',priority:'P0',done:false,evidence:'',blocker:'RLS was previously observed disabled.'},
{id:uid(),title:'Resolve or explicitly disposition public.ytintel_ai_usage RLS debt',priority:'P0',done:false,evidence:'',blocker:'RLS was previously observed disabled.'},
{id:uid(),title:'Review YTIntel-relevant Supabase advisor findings and label each fixed / intentional / deferred',priority:'P0',done:false,evidence:'',blocker:''},
{id:uid(),title:'Create GitHub P0/P1 issues for every unresolved product or trust problem',priority:'P1',done:false,evidence:'',blocker:'Open issue count previously did not reflect known debt.'},
{id:uid(),title:'Verify the Sunday review reaches Discord and leaves its .posted receipt',priority:'P1',done:false,evidence:'',blocker:''},
{id:uid(),title:'Run Sunday checkpoint and write next weekly review',priority:'P0',done:false,evidence:'',blocker:''}]}],sessions:[
{id:uid(),date:'2026-09-14',time:'19:00',minutes:60,title:'Cloud research decision + provider/fallback contract',done:false},
{id:uid(),date:'2026-09-15',time:'19:00',minutes:75,title:'Fresh-account browser proof',done:false},
{id:uid(),date:'2026-09-16',time:'19:00',minutes:75,title:'Real creator case 1 + case 2',done:false},
{id:uid(),date:'2026-09-17',time:'19:00',minutes:60,title:'Real creator case 3 + canonical journey',done:false},
{id:uid(),date:'2026-09-18',time:'19:00',minutes:60,title:'Supabase trust/security dispositions',done:false},
{id:uid(),date:'2026-09-19',time:'10:00',minutes:90,title:'GitHub P0/P1 register + regression proof',done:false},
{id:uid(),date:'2026-09-20',time:'18:30',minutes:60,title:'Sunday checkpoint + weekly review + Discord receipt',done:false}],checkpoints:[
{id:uid(),text:'Current Core CI is green for the architecture that actually ships.',done:true},
{id:uid(),text:'Latest production release also passed Pages deployment and live browser smoke.',done:true},
{id:uid(),text:'A fresh signup confirms, returns to production, persists profile/username and survives refresh/sign-in/sign-out.',done:false},
{id:uid(),text:'At least three real creator cases complete the canonical journey and produce usable next actions.',done:false},
{id:uid(),text:'The two AI-table security items are fixed or explicitly dispositioned with a safe next action.',done:false},
{id:uid(),text:'Current YTIntel Supabase advisor findings are reviewed and dispositioned.',done:false},
{id:uid(),text:'GitHub contains an active YTIntel P0/P1 problem register.',done:false},
{id:uid(),text:'The weekly review reaches Discord and leaves a .posted receipt.',done:false},
{id:uid(),text:'We avoided uncontrolled feature expansion before the stable base earned it.',done:false}],logs:[{id:uid(),at:'2026-09-14T12:20:00+08:00',type:'ship',title:'Benchmark mode production proof passed',body:'16/16 benchmark sections, 17-section appendix, 223.5 WPM and zero browser errors.'}],timer:{seconds:2700,running:false,lastStarted:null,label:''},github:{checkedAt:'',items:[]}});
function load(){try{const x=JSON.parse(localStorage.getItem(STORE)||'null');return x&&x.version===1?x:defaultState()}catch{return defaultState()}}
let state=load(),activeFilter='all',tick=null;
function allTasks(){return state.outcomes.flatMap(o=>o.tasks.map(t=>({...t,outcomeId:o.id,outcomeTitle:o.title})))}
function baselineXP(){const done=allTasks().filter(t=>t.done),evidenced=done.filter(t=>String(t.evidence||'').trim()).length,sessions=state.sessions.filter(s=>s.done).length,checks=state.checkpoints.filter(c=>c.done).length;return done.length*90+evidenced*25+sessions*60+checks*25}
function normalize(){state.week=state.week||WEEK;state.logs=Array.isArray(state.logs)?state.logs:[];state.timer=state.timer||{seconds:2700,running:false,lastStarted:null,label:''};state.github=state.github||{checkedAt:'',items:[]};if(!Array.isArray(state.github.items))state.github.items=[];state.game=state.game||{xp:baselineXP(),awardKeys:[],sprints:[],activeTab:'today'};state.game.awardKeys=Array.isArray(state.game.awardKeys)?state.game.awardKeys:[];state.game.sprints=Array.isArray(state.game.sprints)?state.game.sprints:[];state.game.activeTab=state.game.activeTab||'today';}
normalize();
function persist(render=true){localStorage.setItem(STORE,JSON.stringify(state));if(render)renderAll()}
function log(type,title,body=''){state.logs.unshift({id:uid(),at:perthStamp(),type,title,body});state.logs=state.logs.slice(0,120)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),1700)}
function celebrate(amount,text){$('#celebrateXP').textContent=`+${amount} XP`;$('#celebrateText').textContent=text;const c=$('#celebrate');c.classList.remove('show');void c.offsetWidth;c.classList.add('show');setTimeout(()=>c.classList.remove('show'),1450)}
function award(key,amount,reason){if(key&&state.game.awardKeys.includes(key))return false;if(key)state.game.awardKeys.push(key);state.game.xp=Math.max(0,(Number(state.game.xp)||0)+amount);log('xp',`+${amount} XP`,reason);persist(false);celebrate(amount,reason);return true}
function priorityRank(p){return p==='P0'?0:p==='P1'?1:2}
function nextTask(){return allTasks().filter(t=>!t.done).sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority)||Number(Boolean(a.blocker))-Number(Boolean(b.blocker)))[0]||null}
function outcomeRate(o){return o.tasks.length?o.tasks.filter(t=>t.done).length/o.tasks.length:0}
function checkinDates(){return new Set(state.logs.filter(x=>x.type==='checkin').map(x=>x.at.slice(0,10)))}
function streak(){const days=checkinDates();let n=0,d=new Date();for(let i=0;i<30;i++){const key=isoDate(d);if(days.has(key)){n++;d.setDate(d.getDate()-1);continue}if(i===0){d.setDate(d.getDate()-1);continue}break}return n}
function proofToday(){const d=isoDate();return state.logs.some(x=>x.type==='task_done'&&x.at.slice(0,10)===d)}
function sprintToday(){const d=isoDate();return state.logs.some(x=>x.type==='sprint'&&x.at.slice(0,10)===d)}
function checkedInToday(){return checkinDates().has(isoDate())}
function todaySessions(){return state.sessions.filter(s=>s.date===isoDate()).sort((a,b)=>a.time.localeCompare(b.time))}
function todayScore(){const sessions=todaySessions(),sr=sessions.length?sessions.filter(s=>s.done).length/sessions.length:0;return Math.round(sr*40+(checkedInToday()?20:0)+(proofToday()?25:0)+(sprintToday()?15:0))}
function levelInfo(){const xp=Math.max(0,Number(state.game.xp)||0),level=Math.floor(xp/LEVEL_SIZE)+1,inLevel=xp%LEVEL_SIZE;return{xp,level,inLevel,pct:Math.round(inLevel/LEVEL_SIZE*100),next:LEVEL_SIZE-inLevel}}
function renderHeader(){const s=streak();$('#streakTop').textContent=`${s} day streak`;$('#streakSub').textContent=checkedInToday()?'Banked today ✓':'Tap to check in'}
function renderGame(){const g=levelInfo();$('#levelText').textContent=`Level ${g.level}`;$('#levelCaption').textContent=g.next===LEVEL_SIZE?'Fresh level. Keep moving.':`${g.next} XP to Level ${g.level+1}`;$('#xpText').textContent=`${g.inLevel} / ${LEVEL_SIZE} XP`;$('#xpBar').style.width=g.pct+'%';$('#todayScore').innerHTML=`${todayScore()}<span>/100</span>`}
function renderToday(){const t=nextTask();$('#nextTitle').textContent=t?t.title:'Week cleared. Run the review.';$('#nextWhy').textContent=t?(state.outcomes.find(o=>o.id===t.outcomeId)?.why||''):'You cleared every open outcome task.';const chips=[];if(t)chips.push(`<span class="chip">${esc(t.priority)}</span>`);const sess=todaySessions().find(s=>!s.done);if(sess)chips.push(`<span class="chip">◷ ${esc(sess.minutes)} min scheduled</span>`);if(t?.blocker)chips.push('<span class="chip">⚠ Blocker recorded</span>');chips.push('<span class="chip">+120 XP with proof</span>');$('#nextChips').innerHTML=chips.join('');const list=todaySessions();$('#todaySchedule').innerHTML=list.length?list.map(s=>{const now=new Date(),dt=new Date(`${s.date}T${s.time}:00+08:00`),current=!s.done&&Math.abs(now-dt)<90*60000;return `<div class="session ${s.done?'done':''} ${current?'current':''}"><div class="time">${esc(s.time)}</div><div><div class="name">${esc(s.title)}</div><div class="meta">${esc(s.minutes)} min focus block</div></div><button class="status ${s.done?'good':current?'current':''}" data-session="${s.id}">${s.done?'✓ Done':current?'Current':'Mark done'}</button></div>`}).join(''):'<div class="sub">No work blocks scheduled today. Add one so the day has a clear finish line.</div>';$$('[data-session]').forEach(b=>b.onclick=()=>toggleSession(b.dataset.session))}
function renderWeek(){const rates=state.outcomes.map(outcomeRate),colors=['var(--green)','var(--blue)','var(--red)'];$('#outcomeRings').innerHTML=state.outcomes.map((o,i)=>`<article class="card ring-card"><div class="ring" style="--pct:${Math.round(rates[i]*100)};--ring:${colors[i]}"><div class="ring-inner">${Math.round(rates[i]*100)}%</div></div><h3>${esc(o.title)}</h3><p>${o.tasks.filter(t=>t.done).length} / ${o.tasks.length} tasks</p></article>`).join('');const tasks=allTasks(),done=tasks.filter(t=>t.done).length,pct=tasks.length?Math.round(done/tasks.length*100):0;$('#weekTaskCount').textContent=`${done} / ${tasks.length} tasks`;$('#weekProgress').style.width=pct+'%';const days=[];for(let i=0;i<7;i++){const d=new Date(`${state.week.start}T12:00:00+08:00`);d.setDate(d.getDate()+i);const key=isoDate(d),sessions=state.sessions.filter(s=>s.date===key),complete=sessions.length&&sessions.every(s=>s.done);days.push(`<div class="day ${complete?'done':''} ${key===isoDate()?'today':''}"><div class="day-dot">${complete?'✓':key===isoDate()?'•':''}</div><span>${shortDay(key)}</span></div>`)}$('#weekDays').innerHTML=days.join('');const blockers=tasks.filter(t=>!t.done&&t.blocker);$('#blockerCount').textContent=`${blockers.length} open`;$('#blockerList').innerHTML=blockers.length?blockers.slice(0,4).map(t=>`<div class="block"><i class="dot"></i><div><b>${esc(t.title)}</b><small>${esc(t.blocker)}</small></div><em>${esc(t.priority)}</em></div>`).join(''):'<div class="sub">No blockers. Keep moving.</div>';$('#taskList').innerHTML=state.outcomes.map(o=>`<div class="kicker" style="margin-top:8px">${esc(o.title)}</div>${o.tasks.map(t=>`<div class="task ${t.done?'done':''}"><button class="check" data-task-toggle="${t.id}">${t.done?'✓':''}</button><div><div class="task-name">${esc(t.title)}</div><div class="task-note">${esc(t.priority)}${t.blocker&&!t.done?' · '+esc(t.blocker):''}</div>${t.evidence?`<div class="proofline">Proof: ${esc(t.evidence)}</div>`:''}</div><button class="mini-btn" data-proof-task="${t.id}">${t.evidence?'Edit':'Proof'}</button></div>`).join('')}`).join('');$$('[data-task-toggle]').forEach(b=>b.onclick=()=>toggleTask(b.dataset.taskToggle));$$('[data-proof-task]').forEach(b=>b.onclick=()=>openProof(b.dataset.proofTask));$('#checkpointList').innerHTML=state.checkpoints.map(c=>`<div class="check-row ${c.done?'done':''}"><button data-checkpoint="${c.id}">${c.done?'✓':''}</button><span>${esc(c.text)}</span></div>`).join('');$$('[data-checkpoint]').forEach(b=>b.onclick=()=>toggleCheckpoint(b.dataset.checkpoint))}
function proofCategory(text=''){const x=text.toLowerCase();if(/github|commit|sha|issue/.test(x))return'github';if(/pages|deploy|production/.test(x))return'deployments';if(/test|smoke|benchmark|browser|ci/.test(x))return'tests';return'other'}
function renderProof(){const local=allTasks().filter(t=>String(t.evidence||'').trim()).map(t=>({category:proofCategory(t.evidence),title:t.title,body:t.evidence,status:t.done?'Verified':'Evidence',good:t.done}));const live=(state.github.items||[]).map(x=>({...x,good:x.status==='Verified'}));const items=[...live,...local].filter((x,i,a)=>a.findIndex(y=>y.title===x.title&&y.body===x.body)===i).filter(x=>activeFilter==='all'||x.category===activeFilter);$('#proofFeed').innerHTML=items.length?items.map(x=>`<article class="proof-item ${x.good?'good':x.status==='Blocked'?'bad':''}"><div class="proof-icon">${x.category==='github'?'◉':x.category==='deployments'?'▲':x.category==='tests'?'⚗':'▧'}</div><div><b>${esc(x.title)}</b><p>${esc(x.body)}</p></div><span class="proof-pill">${esc(x.status||'Verified')}</span></article>`).join(''):'<div class="card flat sub">No proof in this filter yet.</div>'}
function renderSprint(){const t=nextTask();$('#sprintTask').textContent=state.timer.label||t?.title||'Weekly review';$('#timerBig').textContent=formatTime(remainingSeconds());$('#pauseSprint').textContent=state.timer.running?'Pause':'Start';$('#sprintReward').textContent='✦ +60 XP + proof bonus'}
function renderAll(){renderHeader();renderGame();renderToday();renderWeek();renderProof();renderSprint();setTab(state.game.activeTab||'today',false)}
function setTab(tab,persistTab=true){$$('.view').forEach(v=>v.classList.toggle('on',v.id===`view-${tab}`));$$('.bottomnav button').forEach(b=>b.classList.toggle('on',b.dataset.tab===tab));state.game.activeTab=tab;if(persistTab)persist(false);window.scrollTo({top:0,behavior:'smooth'})}
function findTask(id){for(const o of state.outcomes){const t=o.tasks.find(x=>x.id===id);if(t)return{t,o}}return null}
function openProof(id){const select=$('#proofTask');const tasks=allTasks();select.innerHTML=tasks.map(t=>`<option value="${t.id}">${esc(t.outcomeTitle)} · ${esc(t.title)}</option>`).join('');const target=findTask(id||nextTask()?.id);if(target){select.value=target.t.id;$('#proofText').value=target.t.evidence||''}else $('#proofText').value='';$('#proofDialog').showModal()}
function saveProof(){const f=findTask($('#proofTask').value),text=$('#proofText').value.trim();if(!f||!text){toast('Add evidence first');return}const wasDone=f.t.done;f.t.evidence=text;f.t.done=true;log('task_done',f.t.title,text);if(!wasDone)award(`task:${f.t.id}`,120,'Task proven');else persist(false);$('#proofDialog').close();renderAll();toast(wasDone?'Proof updated':'Task proven ✓')}
function toggleTask(id){const f=findTask(id);if(!f)return;if(f.t.done){f.t.done=false;log('reopen','Task reopened',f.t.title);persist();toast('Task reopened');return}openProof(id)}
function toggleSession(id){const s=state.sessions.find(x=>x.id===id);if(!s)return;s.done=!s.done;if(s.done){log('session','Work block complete',s.title);award(`session:${s.id}`,80,'Focus block completed')}else persist(false);renderAll();toast(s.done?'Work block banked +80 XP':'Work block reopened')}
function toggleCheckpoint(id){const c=state.checkpoints.find(x=>x.id===id);if(!c)return;c.done=!c.done;if(c.done)award(`checkpoint:${c.id}`,50,'Sunday checkpoint proven');else persist(false);renderAll()}
function openCheckin(){$('#checkinDialog').showModal()}
function saveCheckin(){const ship=$('#checkShip').value.trim(),block=$('#checkBlock').value.trim(),next=$('#checkNext').value.trim();log('checkin','Daily check-in',`Shipped: ${ship||'—'} | Blocked: ${block||'—'} | Next: ${next||'—'}`);award(`checkin:${isoDate()}`,40,'Daily accountability streak');$('#checkinDialog').close();$('#checkShip').value=$('#checkBlock').value=$('#checkNext').value='';renderAll();toast('Check-in banked')}
function remainingSeconds(){if(!state.timer.running||!state.timer.lastStarted)return Math.max(0,Number(state.timer.seconds)||0);return Math.max(0,Math.round((Number(state.timer.seconds)||0)-(Date.now()-state.timer.lastStarted)/1000))}
function formatTime(sec){sec=Math.max(0,Math.floor(sec));return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function startSprint(){if(state.timer.running)return;const t=nextTask();if(!state.timer.label)state.timer.label=t?.title||'Focus sprint';if(remainingSeconds()<=0)state.timer.seconds=2700;state.timer.running=true;state.timer.lastStarted=Date.now();persist(false);renderSprint();startTicker();toast('Sprint started')}
function pauseSprint(){if(!state.timer.running){startSprint();return}state.timer.seconds=remainingSeconds();state.timer.running=false;state.timer.lastStarted=null;persist(false);renderSprint();toast('Sprint paused')}
function finishSprint(){const label=state.timer.label||nextTask()?.title||'Focus sprint';state.timer.seconds=remainingSeconds();state.timer.running=false;state.timer.lastStarted=null;const id=uid();state.game.sprints.push({id,at:perthStamp(),label});log('sprint','Focus sprint complete',label);award(`sprint:${id}`,60,'Focus sprint completed');state.timer.seconds=2700;state.timer.label='';persist(false);renderAll();toast('Sprint complete. Now prove it.');setTimeout(()=>{setTab('proof');openProof(nextTask()?.id)},900)}
function startTicker(){if(tick)return;tick=setInterval(()=>{if(!state.timer.running){clearInterval(tick);tick=null;return}const r=remainingSeconds();$('#timerBig').textContent=formatTime(r);if(r<=0){clearInterval(tick);tick=null;finishSprint()}},1000)}
async function refreshGithub(){toast('Refreshing GitHub…');try{const [commits,runs,issues]=await Promise.all([fetch(`${API}/commits?per_page=1`).then(r=>r.json()),fetch(`${API}/actions/runs?per_page=20`).then(r=>r.json()),fetch(`${API}/issues?state=open&per_page=100`).then(r=>r.json())]);const items=[];if(Array.isArray(commits)&&commits[0])items.push({category:'github',title:'Latest commit',body:`${commits[0].sha.slice(0,7)} · ${commits[0].commit?.message?.split('\n')[0]||'Commit'}`,status:'Verified'});const wr=runs?.workflow_runs||[];const page=wr.find(x=>/pages|deploy pinnacle/i.test(x.name||''));if(page)items.push({category:'deployments',title:'Pages deployment',body:`${page.conclusion||page.status} · run ${page.run_number}`,status:page.conclusion==='success'?'Verified':'In Progress'});const smoke=wr.find(x=>/production.*smoke|browser smoke/i.test(x.name||''));if(smoke)items.push({category:'tests',title:'Production browser smoke',body:`${smoke.conclusion||smoke.status} · run ${smoke.run_number}`,status:smoke.conclusion==='success'?'Verified':'In Progress'});const core=wr.find(x=>/core ci/i.test(x.name||''));if(core)items.push({category:'tests',title:'Core CI',body:`${core.conclusion||core.status} · run ${core.run_number}`,status:core.conclusion==='success'?'Verified':'In Progress'});const open=Array.isArray(issues)?issues.filter(x=>!x.pull_request).length:0;items.push({category:'github',title:'Open issue register',body:`${open} open issue${open===1?'':'s'} currently visible`,status:'Live'});state.github={checkedAt:perthStamp(),items};persist(false);renderProof();toast('GitHub evidence refreshed')}catch(e){console.warn(e);toast('GitHub refresh unavailable')}}
function buildStatus(){const g=levelInfo(),tasks=allTasks(),done=tasks.filter(t=>t.done),open=tasks.filter(t=>!t.done),blockers=open.filter(t=>t.blocker);return `YTIntel Progress HQ status — ${isoDate()} Perth\nLevel ${g.level} · ${g.xp} total XP · ${streak()} day streak · today ${todayScore()}/100\nWeek: ${done.length}/${tasks.length} outcome tasks proven\n\nTop outcomes:\n${state.outcomes.map(o=>`- ${o.title}: ${o.tasks.filter(t=>t.done).length}/${o.tasks.length} (${Math.round(outcomeRate(o)*100)}%)`).join('\n')}\n\nNext move: ${nextTask()?.title||'Weekly review'}\nOpen blockers: ${blockers.length}${blockers.length?'\n'+blockers.map(t=>`- ${t.title}: ${t.blocker}`).join('\n'):''}\n\nRecent proof:\n${tasks.filter(t=>t.evidence).slice(0,6).map(t=>`- ${t.title}: ${t.evidence}`).join('\n')||'- None yet'}\n\nSunday checkpoint: ${state.checkpoints.filter(c=>c.done).length}/${state.checkpoints.length} passed.`}
async function copyStatus(){const text=buildStatus();try{await navigator.clipboard.writeText(text);toast('Status copied for ChatGPT')}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('Status copied')}}
function addTask(){const o=state.outcomes.find(x=>x.id===$('#taskOutcome').value),title=$('#taskTitle').value.trim();if(!o||!title)return;o.tasks.push({id:uid(),title,priority:$('#taskPriority').value,done:false,evidence:'',blocker:$('#taskBlocker').value.trim()});log('task','Task added',title);persist();$('#taskDialog').close();$('#taskTitle').value=$('#taskBlocker').value='';toast('Task added')}
function addSession(){const title=$('#sessionTitle').value.trim();if(!title)return;state.sessions.push({id:uid(),date:$('#sessionDate').value||isoDate(),time:$('#sessionTime').value||'19:00',minutes:Number($('#sessionMinutes').value)||45,title,done:false});log('schedule','Work block added',title);persist();$('#sessionDialog').close();$('#sessionTitle').value='';toast('Work block scheduled')}
function wire(){$$('.bottomnav button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('#checkInQuick').onclick=openCheckin;$('#startSprintFromToday').onclick=()=>{setTab('sprint');startSprint()};$('#attachProofFromToday').onclick=()=>openProof(nextTask()?.id);$('#addProofBtn').onclick=()=>openProof(nextTask()?.id);$('#saveProof').onclick=e=>{e.preventDefault();saveProof()};$('#saveCheckin').onclick=e=>{e.preventDefault();saveCheckin()};$('#addTaskBtn').onclick=()=>{$('#taskOutcome').innerHTML=state.outcomes.map(o=>`<option value="${o.id}">${esc(o.title)}</option>`).join('');$('#taskDialog').showModal()};$('#saveTask').onclick=e=>{e.preventDefault();addTask()};$('#addSessionBtn').onclick=()=>{$('#sessionDate').value=isoDate();$('#sessionTime').value='19:00';$('#sessionDialog').showModal()};$('#saveSession').onclick=e=>{e.preventDefault();addSession()};$('#pauseSprint').onclick=pauseSprint;$('#completeSprint').onclick=finishSprint;$('#copyStatus').onclick=copyStatus;$('#refreshGithub').onclick=refreshGithub;$$('#proofFilters .filter').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;$$('#proofFilters .filter').forEach(x=>x.classList.toggle('on',x===b));renderProof()});window.addEventListener('keydown',e=>{if(e.key==='Escape')$$('dialog[open]').forEach(d=>d.close())})}
wire();renderAll();if(state.timer.running)startTicker();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});setTimeout(()=>{if(!(state.github.items||[]).length)refreshGithub()},700);
})();