(()=>{'use strict';
const TZ='Australia/Perth';
const STORE='ytintel-progress-hq-v1';
const WEEK={start:'2026-09-14',end:'2026-09-20'};
const REPO='MitchLoxton/pinnacle-navigator';
const API='https://api.github.com/repos/'+REPO;
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>Math.random().toString(36).slice(2,9);
const isoDate=(d=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
const shortDate=s=>new Intl.DateTimeFormat('en-AU',{timeZone:TZ,weekday:'short',day:'numeric',month:'short'}).format(new Date(s+'T12:00:00+08:00'));
const fullDate=s=>new Intl.DateTimeFormat('en-AU',{timeZone:TZ,weekday:'long',day:'numeric',month:'short'}).format(new Date(s+'T12:00:00+08:00'));
const nowPerth=()=>new Date(new Date().toLocaleString('en-US',{timeZone:TZ}));

const defaultState=()=>({
  version:1,
  week:WEEK,
  outcomes:[
    {id:'release',title:'Release truth',why:'The same production release must have green code checks, green deploy and a real browser proof.',tasks:[
      {id:uid(),title:'Benchmark contract shipped: v0.39 resilient benchmark mode',priority:'P0',done:true,evidence:'Release commit ff1098beb8e0aa185ffa0cecacaafa1b0315877c',blocker:''},
      {id:uid(),title:'Core CI green on the release commit',priority:'P0',done:true,evidence:'YTIntel Core CI run 201 succeeded on ff1098b',blocker:''},
      {id:uid(),title:'GitHub Pages deploy green on the release commit',priority:'P0',done:true,evidence:'Pages run 1188 succeeded on ff1098b',blocker:''},
      {id:uid(),title:'Blake Ryan production smoke proves 16/16 benchmark sections',priority:'P0',done:true,evidence:'Production smoke run 34757645134 succeeded; prior proof receipt recorded 16 premium sections, 17 appendix sections, 223.5 WPM, no browser errors',blocker:''},
      {id:uid(),title:'Make the cloud research path reliable again or formally choose the fallback-first contract',priority:'P0',done:false,evidence:'',blocker:'Current premium research path returns CREDIT_BALANCE_EXHAUSTED.'},
      {id:uid(),title:'Keep release notes and verified Discord release receipt green',priority:'P1',done:true,evidence:'Verified production workflow completed the Discord release step successfully.',blocker:''}
    ]},
    {id:'proof',title:'Real-user proof',why:'A technically correct product only counts if a clean user can enter, analyse and leave with a useful next action.',tasks:[
      {id:uid(),title:'Fresh account: signup → email confirm → production return → persistent session',priority:'P0',done:false,evidence:'',blocker:'Needs true browser proof, not database inference.'},
      {id:uid(),title:'Verify YTIntel profile + username persist for the fresh account',priority:'P0',done:false,evidence:'',blocker:''},
      {id:uid(),title:'Verify intended signed-out and signed-in Analyse behaviour',priority:'P1',done:false,evidence:'',blocker:''},
      {id:uid(),title:'Real creator case 1: complete benchmark analysis + record usable next-video decision',priority:'P0',done:false,evidence:'',blocker:''},
      {id:uid(),title:'Real creator case 2: complete benchmark analysis + record usable next-video decision',priority:'P0',done:false,evidence:'',blocker:''},
      {id:uid(),title:'Real creator case 3: complete benchmark analysis + record usable next-video decision',priority:'P0',done:false,evidence:'',blocker:''},
      {id:uid(),title:'Document the canonical creator journey as a repeatable acceptance flow',priority:'P1',done:false,evidence:'',blocker:''}
    ]},
    {id:'trust',title:'Trust + problem register',why:'Security debt and known P0/P1 problems must be visible, owned and evidence-backed.',tasks:[
      {id:uid(),title:'Resolve or explicitly disposition public.ytintel_ai_setup RLS debt',priority:'P0',done:false,evidence:'',blocker:'RLS was previously observed disabled.'},
      {id:uid(),title:'Resolve or explicitly disposition public.ytintel_ai_usage RLS debt',priority:'P0',done:false,evidence:'',blocker:'RLS was previously observed disabled.'},
      {id:uid(),title:'Review YTIntel-relevant Supabase advisor findings and label each fixed / intentional / deferred',priority:'P0',done:false,evidence:'',blocker:''},
      {id:uid(),title:'Create GitHub P0/P1 issues for every unresolved product or trust problem',priority:'P1',done:false,evidence:'',blocker:'Open issue count previously did not reflect known debt.'},
      {id:uid(),title:'Verify the Sunday review reaches Discord and leaves its .posted receipt',priority:'P1',done:false,evidence:'',blocker:''},
      {id:uid(),title:'Run Sunday checkpoint and write next weekly review',priority:'P0',done:false,evidence:'',blocker:''}
    ]}
  ],
  sessions:[
    {id:uid(),date:'2026-09-14',time:'19:00',minutes:60,title:'Cloud research decision + provider/fallback contract',done:false},
    {id:uid(),date:'2026-09-15',time:'19:00',minutes:75,title:'Fresh-account browser proof',done:false},
    {id:uid(),date:'2026-09-16',time:'19:00',minutes:75,title:'Real creator case 1 + case 2',done:false},
    {id:uid(),date:'2026-09-17',time:'19:00',minutes:60,title:'Real creator case 3 + canonical journey',done:false},
    {id:uid(),date:'2026-09-18',time:'19:00',minutes:60,title:'Supabase trust/security dispositions',done:false},
    {id:uid(),date:'2026-09-19',time:'10:00',minutes:90,title:'GitHub P0/P1 register + regression proof',done:false},
    {id:uid(),date:'2026-09-20',time:'18:30',minutes:60,title:'Sunday checkpoint + weekly review + Discord receipt',done:false}
  ],
  checkpoints:[
    {id:uid(),text:'Current Core CI is green for the architecture that actually ships.',done:true},
    {id:uid(),text:'Latest production release also passed Pages deployment and live browser smoke.',done:true},
    {id:uid(),text:'A fresh signup confirms, returns to production, persists profile/username and survives refresh/sign-in/sign-out.',done:false},
    {id:uid(),text:'At least three real creator cases complete the canonical journey and produce usable next actions.',done:false},
    {id:uid(),text:'The two AI-table security items are fixed or explicitly dispositioned with a safe next action.',done:false},
    {id:uid(),text:'Current YTIntel Supabase advisor findings are reviewed and dispositioned.',done:false},
    {id:uid(),text:'GitHub contains an active YTIntel P0/P1 problem register.',done:false},
    {id:uid(),text:'The weekly review reaches Discord and leaves a .posted receipt.',done:false},
    {id:uid(),text:'We avoided uncontrolled feature expansion before the stable base earned it.',done:false}
  ],
  logs:[
    {id:uid(),at:'2026-09-14T12:20:00+08:00',type:'ship',title:'Benchmark mode production proof passed',body:'16/16 benchmark sections, 17-section evidence appendix, 223.5 WPM, zero browser errors and successful mobile proof on the Blake Ryan production smoke.'}
  ],
  timer:{seconds:2700,running:false,lastStarted:null,label:''},
  github:{checkedAt:'',release:'-',commit:'-',workflows:'-',issues:'-'}
});
function clean(s){return String(s??'').trim()}
function load(){try{const x=JSON.parse(localStorage.getItem(STORE)||'null');return x&&x.version===1?x:defaultState()}catch{return defaultState()}}
let state=load();
function save(){localStorage.setItem(STORE,JSON.stringify(state));render();}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500)}
function allTasks(){return state.outcomes.flatMap(o=>o.tasks.map(t=>({...t,outcomeId:o.id,outcomeTitle:o.title}))) }
function priorityRank(p){return p==='P0'?0:p==='P1'?1:2}
function nextTask(){const xs=allTasks().filter(t=>!t.done).sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority));return xs[0]||null}
function completedTasks(){return allTasks().filter(t=>t.done)}
function checkInDays(){return [...new Set(state.logs.filter(x=>x.type==='checkin').map(x=>x.at.slice(0,10)))].sort()}
function streak(){const days=new Set(checkInDays());let d=nowPerth(),n=0;for(let i=0;i<14;i++){const k=isoDate(d);if(days.has(k)){n++;d.setDate(d.getDate()-1);continue}if(i===0){d.setDate(d.getDate()-1);continue}break}return n}
function evidenceRate(){const done=completedTasks();return done.length?done.filter(t=>clean(t.evidence)).length/done.length:0}
function taskRate(){const all=allTasks();return all.length?all.filter(t=>t.done).length/all.length:0}
function sessionRate(){const today=isoDate();const eligible=state.sessions.filter(s=>s.date<=today);return eligible.length?eligible.filter(s=>s.done).length/eligible.length:0}
function accountabilityScore(){const tr=taskRate(),er=evidenceRate(),sr=sessionRate(),cr=Math.min(1,streak()/5);return Math.round((tr*.65+er*.15+sr*.1+cr*.1)*100)}
function render(){renderHeader();renderFocus();renderScore();renderOutcomes();renderSchedule();renderCheckpoint();renderLogs();renderGithub();}
function renderHeader(){$('#weekLabel').textContent=`${fullDate(state.week.start)} → ${fullDate(state.week.end)} · Perth time · ${allTasks().filter(t=>t.done).length}/${allTasks().length} outcome tasks proven`;}
function nextSession(){const now=Date.now();return state.sessions.filter(s=>!s.done).map(s=>({...s,dt:new Date(`${s.date}T${s.time}:00+08:00`)})).filter(s=>s.dt.getTime()>=now-3*3600000).sort((a,b)=>a.dt-b.dt)[0]||state.sessions.find(s=>!s.done)||null}
function renderFocus(){const t=nextTask(),s=nextSession();$('#focusTitle').textContent=t?t.title:'All weekly outcome tasks are complete.';$('#focusWhy').textContent=t?`${t.outcomeTitle}: ${state.outcomes.find(o=>o.id===t.outcomeId)?.why||''}`:'Run the Sunday checkpoint and prepare the next three outcomes.';const meta=[];if(t)meta.push(`<span class="pill ${t.priority==='P0'?'bad':'warn'}">${esc(t.priority)}</span>`);if(t?.blocker)meta.push(`<span class="pill warn">Blocker recorded</span>`);if(s)meta.push(`<span class="pill">Next block: ${esc(shortDate(s.date))} ${esc(s.time)} · ${esc(s.minutes)}m</span>`);$('#focusMeta').innerHTML=meta.join('');if(!state.timer.running&&!state.timer.label&&t)state.timer.label=t.title;$('#timerLabel').textContent=state.timer.label||'Use the next action above.';}
function renderScore(){const score=accountabilityScore();$('#scoreValue').textContent=score+'%';$('#taskValue').textContent=Math.round(taskRate()*100)+'%';$('#evidenceValue').textContent=Math.round(evidenceRate()*100)+'%';$('#streakValue').textContent=streak();$('#scoreBar').style.width=score+'%';}
function outcomeRate(o){return o.tasks.length?o.tasks.filter(t=>t.done).length/o.tasks.length:0}
function renderOutcomes(){const p0=allTasks().filter(t=>!t.done&&t.priority==='P0');$('#scopeGuard').innerHTML=p0.length?`<b>Scope guard:</b> ${p0.length} P0 item${p0.length===1?'':'s'} remain. New feature work should not outrank these unless it directly removes a P0 blocker.`:'<b>Scope guard:</b> no open P0 items. The stable base has earned controlled expansion.';$('#outcomeList').innerHTML=state.outcomes.map(o=>`<section class="outcome"><div class="outcome-head"><div><div class="outcome-title">${esc(o.title)}</div><div class="outcome-meta">${o.tasks.filter(t=>t.done).length}/${o.tasks.length} complete · ${Math.round(outcomeRate(o)*100)}%</div></div><span class="pill ${outcomeRate(o)===1?'good':''}">${Math.round(outcomeRate(o)*100)}%</span></div><div class="bar" style="margin-top:8px"><span style="width:${Math.round(outcomeRate(o)*100)}%"></span></div><div class="task-list">${o.tasks.map(t=>`<div class="task ${t.done?'done':''} ${!t.done&&t.blocker?'blocked':''}" data-task="${t.id}"><button class="check ${t.done?'done':''}" data-toggle-task="${t.id}" aria-label="${t.done?'Reopen':'Complete'} task">${t.done?'✓':''}</button><div><div class="task-title">${esc(t.title)}</div><div class="task-note">${esc(t.priority)}${t.blocker?` · ${esc(t.blocker)}`:''}</div>${t.evidence?`<div class="task-evidence">Evidence: ${esc(t.evidence)}</div>`:''}</div><div class="task-actions"><button class="icon-btn" data-edit-evidence="${t.id}">Proof</button><button class="icon-btn" data-delete-task="${t.id}">×</button></div></div>`).join('')}</div></section>`).join('');$$('[data-toggle-task]').forEach(b=>b.onclick=()=>toggleTask(b.dataset.toggleTask));$$('[data-edit-evidence]').forEach(b=>b.onclick=()=>openEvidence(b.dataset.editEvidence,true));$$('[data-delete-task]').forEach(b=>b.onclick=()=>deleteTask(b.dataset.deleteTask));}
function findTask(id){for(const o of state.outcomes){const t=o.tasks.find(x=>x.id===id);if(t)return{t,o}}return null}
let pendingTask=null;
function toggleTask(id){const f=findTask(id);if(!f)return;if(f.t.done){f.t.done=false;log('reopen','Task reopened',f.t.title);save();toast('Task reopened');return}openEvidence(id,false)}
function openEvidence(id,editing){const f=findTask(id);if(!f)return;pendingTask=id;$('#evidenceTask').textContent=f.t.title;$('#evidenceText').value=f.t.evidence||'';$('#confirmDone').textContent=editing?'Save proof + done':'Mark done';$('#evidenceDialog').showModal()}
function deleteTask(id){const f=findTask(id);if(!f)return;if(!confirm('Delete this task?'))return;f.o.tasks=f.o.tasks.filter(x=>x.id!==id);save();toast('Task deleted')}
function renderSchedule(){const days=[];for(let i=0;i<7;i++){const d=new Date(`${state.week.start}T12:00:00+08:00`);d.setDate(d.getDate()+i);days.push(isoDate(d))}const today=isoDate();$('#scheduleList').innerHTML=days.map(d=>{const sessions=state.sessions.filter(s=>s.date===d).sort((a,b)=>a.time.localeCompare(b.time));return`<section class="day ${d===today?'today':''}"><div class="day-head"><div><div class="day-name">${esc(fullDate(d))}</div><div class="day-date">${d===today?'TODAY · ':''}${sessions.length} work block${sessions.length===1?'':'s'}</div></div><button class="icon-btn" data-add-day="${d}">+</button></div>${sessions.length?sessions.map(s=>`<div class="session ${s.done?'done':''}"><div class="session-time">${esc(s.time)}</div><div><div class="session-title">${esc(s.title)}</div><div class="session-meta">${esc(s.minutes)} minutes</div></div><div class="task-actions"><button class="icon-btn" data-session-done="${s.id}">${s.done?'↺':'✓'}</button><button class="icon-btn" data-session-delete="${s.id}">×</button></div></div>`).join(''):'<div class="empty">No session scheduled.</div>'}</section>`}).join('');$$('[data-add-day]').forEach(b=>b.onclick=()=>openSession(b.dataset.addDay));$$('[data-session-done]').forEach(b=>b.onclick=()=>toggleSession(b.dataset.sessionDone));$$('[data-session-delete]').forEach(b=>b.onclick=()=>deleteSession(b.dataset.sessionDelete));}
function toggleSession(id){const s=state.sessions.find(x=>x.id===id);if(!s)return;s.done=!s.done;log(s.done?'session_done':'session_reopen',s.done?'Work block completed':'Work block reopened',`${s.date} ${s.time} · ${s.title}`);save();}
function deleteSession(id){if(!confirm('Delete this work block?'))return;state.sessions=state.sessions.filter(x=>x.id!==id);save()}
function renderCheckpoint(){$('#checkpointList').innerHTML=state.checkpoints.map(c=>`<div class="checkpoint-row ${c.done?'done':''}"><button data-checkpoint="${c.id}">${c.done?'✓':''}</button><span>${esc(c.text)}</span></div>`).join('');$$('[data-checkpoint]').forEach(b=>b.onclick=()=>{const c=state.checkpoints.find(x=>x.id===b.dataset.checkpoint);c.done=!c.done;save()})}
function renderLogs(){const xs=[...state.logs].sort((a,b)=>b.at.localeCompare(a.at)).slice(0,12);$('#activityList').innerHTML=xs.length?xs.map(x=>`<div class="log"><b>${esc(x.title)}</b><p>${esc(x.body)}</p><div class="outcome-meta">${esc(new Intl.DateTimeFormat('en-AU',{timeZone:TZ,weekday:'short',day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}).format(new Date(x.at)))}</div></div>`).join(''):'<div class="empty">No activity yet.</div>'}
function log(type,title,body){state.logs.push({id:uid(),at:new Date().toISOString(),type,title,body})}
function renderGithub(){const g=state.github;const row=(title,value,sub)=>`<div class="gh"><b>${esc(value||'-')}</b><span>${esc(title)}${sub?` · ${esc(sub)}`:''}</span></div>`;$('#githubGrid').innerHTML=row('Current release',g.release,g.checkedAt?`checked ${g.checkedAt}`:'not checked yet')+row('Latest YTIntel commit',g.commit,'main')+row('Recent workflows',g.workflows,'Core / Pages / smoke')+row('Open issues',g.issues,'repository tracker');}
async function refreshGithub(){const b=$('#refreshGithub');b.disabled=true;b.textContent='Checking…';try{const [release,commits,runs,issues]=await Promise.all([fetch('../latest/release.json?progress='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():{}),fetch(`${API}/commits?path=ytintel&per_page=1`,{headers:{accept:'application/vnd.github+json'}}).then(r=>r.ok?r.json():[]),fetch(`${API}/actions/runs?per_page=12`,{headers:{accept:'application/vnd.github+json'}}).then(r=>r.ok?r.json():{}),fetch(`${API}/issues?state=open&per_page=100`,{headers:{accept:'application/vnd.github+json'}}).then(r=>r.ok?r.json():[])]);const rs=(runs.workflow_runs||[]).filter(x=>/YTIntel Core CI|Deploy Pinnacle Navigator|YTIntel Production Browser Smoke/.test(x.name)).slice(0,6);const compactRuns=rs.map(x=>`${x.name.replace('Deploy Pinnacle Navigator to GitHub Pages','Pages').replace('YTIntel Production Browser Smoke','Smoke').replace('YTIntel Core CI','Core')}:${x.conclusion||x.status}`).join(' · ');state.github={checkedAt:new Intl.DateTimeFormat('en-AU',{timeZone:TZ,hour:'numeric',minute:'2-digit'}).format(new Date()),release:release.version||'-',commit:commits[0]?.sha?.slice(0,7)||'-',workflows:compactRuns||'-',issues:String((issues||[]).filter(x=>!x.pull_request).length)};save();toast('GitHub evidence refreshed')}catch(e){toast('GitHub refresh failed');console.warn(e)}finally{b.disabled=false;b.textContent='Refresh'}}
function openSession(date=isoDate()){$('#sessionDate').value=date;$('#sessionTime').value='19:00';$('#sessionMinutes').value='60';$('#sessionTitle').value=nextTask()?.title||'YTIntel work block';$('#sessionDialog').showModal()}
function addTask(){$('#taskOutcome').innerHTML=state.outcomes.map(o=>`<option value="${o.id}">${esc(o.title)}</option>`).join('');$('#taskTitle').value='';$('#taskPriority').value='P1';$('#taskBlocker').value='';$('#taskDialog').showModal()}
function addSessionFromForm(){const s={id:uid(),date:$('#sessionDate').value,time:$('#sessionTime').value,minutes:Number($('#sessionMinutes').value)||60,title:clean($('#sessionTitle').value),done:false};if(!s.date||!s.time||!s.title)return false;state.sessions.push(s);log('schedule','Work block scheduled',`${s.date} ${s.time} · ${s.title}`);save();return true}
function addTaskFromForm(){const o=state.outcomes.find(x=>x.id===$('#taskOutcome').value),title=clean($('#taskTitle').value);if(!o||!title)return false;o.tasks.push({id:uid(),title,priority:$('#taskPriority').value,done:false,evidence:'',blocker:clean($('#taskBlocker').value)});save();return true}
function saveCheckIn(){const shipped=clean($('#checkInShipped').value),blocked=clean($('#checkInBlocked').value)||'None',next=clean($('#checkInNext').value),score=Math.min(10,Math.max(1,Number($('#checkInScore').value)||8));if(!shipped||!next)return false;log('checkin',`Daily check-in · ${score}/10`,`Shipped: ${shipped} | Blocked: ${blocked} | Next: ${next}`);save();return true}
function saveFinish(){const changed=clean($('#finishChanged').value),evidence=clean($('#finishEvidence').value),next=clean($('#finishNext').value);if(!changed||!next)return false;log('work','Work block closed',`Changed: ${changed}${evidence?` | Evidence: ${evidence}`:''} | Next: ${next}`);state.timer.running=false;state.timer.seconds=2700;state.timer.lastStarted=null;state.timer.label=next;save();return true}
function copyStatus(){const open=state.outcomes.map(o=>`${o.title}: ${o.tasks.filter(t=>t.done).length}/${o.tasks.length}`).join(' | ');const next=nextTask();const blocks=allTasks().filter(t=>!t.done&&t.blocker).map(t=>t.title+': '+t.blocker).slice(0,5);const cp=state.checkpoints.filter(c=>c.done).length;const text=`YTIntel Progress HQ status — ${isoDate()} Perth\nAccountability: ${accountabilityScore()}%\nOutcomes: ${open}\nSunday checkpoint: ${cp}/${state.checkpoints.length}\nNext action: ${next?.title||'None'}\nCurrent blockers: ${blocks.length?blocks.join(' || '):'None'}\nLatest activity: ${[...state.logs].sort((a,b)=>b.at.localeCompare(a.at)).slice(0,4).map(x=>x.title+': '+x.body).join(' || ')}`;navigator.clipboard?.writeText(text).then(()=>toast('Status copied for ChatGPT')).catch(()=>prompt('Copy this status:',text))}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ytintel-progress-${isoDate()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function calendarExport(){const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//YTIntel//Progress HQ//EN','CALSCALE:GREGORIAN'];for(const s of state.sessions){const start=s.date.replaceAll('-','')+'T'+s.time.replace(':','')+'00';const endDate=new Date(`${s.date}T${s.time}:00+08:00`);endDate.setMinutes(endDate.getMinutes()+s.minutes);const ed=`${endDate.getFullYear()}${String(endDate.getMonth()+1).padStart(2,'0')}${String(endDate.getDate()).padStart(2,'0')}T${String(endDate.getHours()).padStart(2,'0')}${String(endDate.getMinutes()).padStart(2,'0')}00`;lines.push('BEGIN:VEVENT',`UID:${s.id}@ytintel-progress`,`DTSTART;TZID=Australia/Perth:${start}`,`DTEND;TZID=Australia/Perth:${ed}`,`SUMMARY:${s.title.replace(/[\n,;]/g,' ')}`,'DESCRIPTION:YTIntel Progress HQ work block','END:VEVENT')}lines.push('END:VCALENDAR');const blob=new Blob([lines.join('\r\n')],{type:'text/calendar'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ytintel-work-week.ics';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Calendar exported')}
let timerInterval=null;
function tick(){if(!state.timer.running||!state.timer.lastStarted)return;const elapsed=Math.floor((Date.now()-state.timer.lastStarted)/1000),left=Math.max(0,state.timer.seconds-elapsed);showTimer(left);if(left<=0){state.timer.running=false;state.timer.seconds=0;state.timer.lastStarted=null;localStorage.setItem(STORE,JSON.stringify(state));clearInterval(timerInterval);notifyTimer();toast('Focus block complete')}}
function showTimer(sec=state.timer.seconds){const m=Math.floor(sec/60),s=sec%60;$('#timerTime').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function startTimer(){if(state.timer.running)return;if(state.timer.seconds<=0)state.timer.seconds=2700;state.timer.running=true;state.timer.lastStarted=Date.now();state.timer.label=state.timer.label||nextTask()?.title||'YTIntel focus';localStorage.setItem(STORE,JSON.stringify(state));timerInterval=setInterval(tick,1000);renderFocus();tick();if('Notification'in window&&Notification.permission==='default')Notification.requestPermission().catch(()=>{})}
function pauseTimer(){if(!state.timer.running)return;const elapsed=Math.floor((Date.now()-state.timer.lastStarted)/1000);state.timer.seconds=Math.max(0,state.timer.seconds-elapsed);state.timer.running=false;state.timer.lastStarted=null;localStorage.setItem(STORE,JSON.stringify(state));clearInterval(timerInterval);showTimer();toast('Timer paused')}
function notifyTimer(){if('Notification'in window&&Notification.permission==='granted')new Notification('YTIntel focus block complete',{body:'Log what changed, evidence, and the exact next action.'})}
function initTimer(){if(state.timer.running&&state.timer.lastStarted){timerInterval=setInterval(tick,1000);tick()}else showTimer()}
let deferredPrompt=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});
async function install(){if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else toast('On iPhone: Share → Add to Home Screen')}
function bind(){$('#openYTIntel').onclick=()=>location.href='../latest/';$('#copyStatus').onclick=copyStatus;$('#installBtn').onclick=install;$('#refreshGithub').onclick=refreshGithub;$('#addTaskBtn').onclick=addTask;$('#addSessionBtn').onclick=()=>openSession();$('#calendarBtn').onclick=calendarExport;$('#exportBtn').onclick=exportData;$('#checkInBtn').onclick=()=>{$('#checkInShipped').value='';$('#checkInBlocked').value='';$('#checkInNext').value=nextTask()?.title||'';$('#checkInScore').value='8';$('#checkInDialog').showModal()};$('#startTimer').onclick=startTimer;$('#pauseTimer').onclick=pauseTimer;$('#finishTimer').onclick=()=>{$('#finishChanged').value='';$('#finishEvidence').value='';$('#finishNext').value=nextTask()?.title||'';$('#finishDialog').showModal()};$('#saveTask').onclick=e=>{e.preventDefault();if(addTaskFromForm())$('#taskDialog').close()};$('#saveSession').onclick=e=>{e.preventDefault();if(addSessionFromForm())$('#sessionDialog').close()};$('#saveCheckIn').onclick=e=>{e.preventDefault();if(saveCheckIn())$('#checkInDialog').close()};$('#saveFinish').onclick=e=>{e.preventDefault();if(saveFinish())$('#finishDialog').close()};$('#confirmDone').onclick=e=>{e.preventDefault();const f=findTask(pendingTask),ev=clean($('#evidenceText').value);if(!f||!ev)return;f.t.evidence=ev;f.t.done=true;log('done','Task proven complete',`${f.t.title} | ${ev}`);save();$('#evidenceDialog').close();toast('Done with evidence')};$$('[data-jump]').forEach(b=>b.onclick=()=>{document.getElementById(b.dataset.jump)?.scrollIntoView({behavior:'smooth',block:'start'});$$('[data-jump]').forEach(x=>x.classList.toggle('on',x===b))});}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=1').catch(()=>{});
bind();render();initTimer();setTimeout(()=>{if(!state.github.checkedAt)refreshGithub()},800);
})();