(()=>{'use strict';
const SB='https://dkmacktcfhubsumwrydw.supabase.co';
const KEY='sb_publishable_VATM2AkVyl-yvxv28S2FXw_CqMpBr6q';
const AUTH_KEY='ytintel-ops-auth-v1';
const INTRO_KEY='ytintel-shared-hq-intro-v1';
const LOCAL_KEY='ytintel-progress-hq-v1';
const POLL_MS=15000;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate=v=>v?new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Perth',day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}).format(new Date(v)):'—';
let session=null,workspace=null,membership=null,objectives=[],tasks=[],events=[],team=[],metrics={},poll=null,busy=false;
function saveSession(s){session=s||null;if(s)localStorage.setItem(AUTH_KEY,JSON.stringify(s));else localStorage.removeItem(AUTH_KEY)}
function loadSession(){try{return JSON.parse(localStorage.getItem(AUTH_KEY)||'null')}catch{return null}}
function toast(msg){const t=$('#toast');if(!t)return; t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),1800)}
function primeHQ(){try{if(localStorage.getItem(INTRO_KEY))return;const x=JSON.parse(localStorage.getItem(LOCAL_KEY)||'null');if(x?.game){x.game.activeTab='hq';localStorage.setItem(LOCAL_KEY,JSON.stringify(x))}localStorage.setItem(INTRO_KEY,'1')}catch{}}
primeHQ();
function authHeaders(token=session?.access_token){const h={apikey:KEY,'Content-Type':'application/json'};if(token)h.Authorization=`Bearer ${token}`;return h}
async function parse(r){const text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!r.ok){const msg=body?.message||body?.msg||body?.error_description||body?.hint||body?.error||`${r.status} ${r.statusText}`;throw new Error(msg)}return body}
async function refreshSession(){if(!session?.refresh_token)throw new Error('Sign in again');const r=await fetch(`${SB}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:authHeaders(null),body:JSON.stringify({refresh_token:session.refresh_token})});const data=await parse(r);data.expires_at=Math.floor(Date.now()/1000)+(Number(data.expires_in)||3600);saveSession(data);return data}
async function ensureSession(){if(!session)session=loadSession();if(!session)return null;if(session.expires_at&&session.expires_at<Math.floor(Date.now()/1000)+90)await refreshSession();try{const r=await fetch(`${SB}/auth/v1/user`,{headers:authHeaders()});const user=await parse(r);session.user=user;saveSession(session);return session}catch(e){try{return await refreshSession()}catch{saveSession(null);session=null;return null}}}
async function rest(path,opts={}){await ensureSession();if(!session)throw new Error('AUTH_REQUIRED');const headers={...authHeaders(),...(opts.headers||{})};if(opts.body!==undefined&&typeof opts.body!=='string')opts.body=JSON.stringify(opts.body);const r=await fetch(`${SB}/rest/v1/${path}`,{...opts,headers});return parse(r)}
async function rpc(name,args={}){return rest(`rpc/${name}`,{method:'POST',headers:{Prefer:'return=representation'},body:args})}
function installStyles(){const s=document.createElement('style');s.textContent=`
.bottomnav{grid-template-columns:repeat(5,1fr)!important}.bottomnav button.on[data-tab=hq]{color:var(--gold)}
.shared-stack{display:grid;gap:12px}.shared-hero{border-color:#5e4821;background:radial-gradient(circle at 88% 22%,rgba(255,192,80,.17),transparent 30%),linear-gradient(145deg,#17130d,#0b131e 64%)}
.shared-live{display:inline-flex;align-items:center;gap:6px;border:1px solid #20543c;background:#0d251a;color:var(--green);border-radius:999px;padding:6px 9px;font-size:8px;font-weight:950}.shared-live i{width:6px;height:6px;border-radius:50%;background:var(--green);box-shadow:0 0 10px var(--green)}
.shared-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.shared-head h1{font-size:24px;line-height:1.04;margin:8px 0 5px;letter-spacing:-.04em}.shared-actions{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}
.shared-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.shared-metric{border:1px solid #1d2c3e;background:#0a1420;border-radius:14px;padding:11px}.shared-metric b{display:block;font-size:22px;letter-spacing:-.04em}.shared-metric span{display:block;color:var(--muted);font-size:8px;margin-top:3px}
.shared-next{border-color:#724817;background:radial-gradient(circle at 100% 30%,rgba(255,155,45,.18),transparent 34%),#11120f}.shared-next h2{font-size:20px;margin:8px 0 6px}.shared-next-meta{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}
.shared-objectives{display:grid;gap:9px}.shared-objective{border:1px solid #202f42;background:#0a1420;border-radius:16px;padding:12px}.shared-objective-head{display:flex;justify-content:space-between;gap:8px}.shared-objective h3{font-size:12px;margin:0}.shared-objective p{font-size:8px;line-height:1.4;color:var(--muted);margin:4px 0 9px}.shared-progress{height:7px;background:#151f2c;border-radius:999px;overflow:hidden}.shared-progress span{height:100%;display:block;background:linear-gradient(90deg,var(--orange),var(--purple));border-radius:999px}
.shared-task{border-top:1px solid #192535;padding:9px 0}.shared-task:first-of-type{margin-top:9px}.shared-task-top{display:grid;grid-template-columns:1fr auto;gap:8px}.shared-task-title{font-size:10px;font-weight:900;line-height:1.35}.shared-task-note{font-size:8px;color:var(--muted);margin-top:3px}.shared-task-controls{display:grid;grid-template-columns:1.05fr 1fr .9fr auto;gap:5px;margin-top:7px}.shared-task-controls select,.shared-task-controls input{min-width:0;width:100%;border:1px solid #27384d;background:#08111b;color:#dce6f0;border-radius:9px;padding:7px;font-size:8px}.shared-task-controls button{border:1px solid #37445a;background:#101927;color:#d8e3ef;border-radius:9px;padding:7px 8px;font-size:8px;font-weight:900}.shared-task.done{opacity:.62}.shared-task.done .shared-task-title{text-decoration:line-through}.shared-proof{font-size:8px;color:var(--green);margin-top:5px;overflow-wrap:anywhere}
.shared-team{display:flex;gap:7px;overflow:auto}.shared-person{min-width:130px;border:1px solid #233249;background:#0a1420;border-radius:13px;padding:10px}.shared-person b{font-size:10px;display:block}.shared-person span{font-size:8px;color:var(--muted)}
.shared-feed{display:grid;gap:7px}.shared-event{display:grid;grid-template-columns:9px 1fr auto;gap:8px;align-items:start;border-left:1px solid #28384d;padding:5px 0 5px 10px}.shared-event-dot{width:7px;height:7px;border-radius:50%;background:var(--blue);margin-top:4px;box-shadow:0 0 9px rgba(49,140,255,.35)}.shared-event.product .shared-event-dot{background:var(--green)}.shared-event.team .shared-event-dot{background:var(--orange)}.shared-event b{display:block;font-size:9px}.shared-event p{font-size:8px;color:var(--muted);margin:2px 0 0;line-height:1.35}.shared-event time{font-size:7px;color:#66778c;white-space:nowrap}
.shared-auth{max-width:520px;margin:22px auto}.shared-auth h2{font-size:21px;margin:5px 0}.shared-auth .field{margin:10px 0}.shared-auth-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px}.shared-auth-actions button{border:1px solid #344359;background:#101a27;color:white;border-radius:11px;padding:11px;font-weight:900}.shared-auth-actions .main{background:linear-gradient(90deg,#ff9e32,#ffc45d);color:#201204;border:0}.shared-message{font-size:9px;line-height:1.45;color:var(--muted);margin-top:9px}.shared-error{color:#ff93a1}.shared-connected{font-size:8px;color:var(--muted);text-align:right;margin-top:5px}
@media(min-width:720px){.shared-grid{grid-template-columns:repeat(6,minmax(0,1fr))}.shared-two{display:grid;grid-template-columns:1.25fr .75fr;gap:12px}.shared-task-controls{grid-template-columns:1fr 1fr .8fr auto}}
@media(max-width:540px){.shared-task-controls{grid-template-columns:1fr 1fr}.shared-head{display:block}.shared-actions{justify-content:flex-start;margin-top:9px}.shared-connected{text-align:left}}
`;document.head.append(s)}
function labelMember(m){return m?.display_name||m?.email?.split('@')[0]||m?.user_id?.slice(0,8)||'Unassigned'}
function taskRank(t){const p={P0:0,P1:1,P2:2}[t.priority]??3,s={in_progress:0,next:1,backlog:2,blocked:3,done:9}[t.status]??5;return p*10+s}
function nextSharedTask(){return tasks.filter(t=>t.status!=='done'&&t.status!=='blocked').sort((a,b)=>taskRank(a)-taskRank(b)||a.sort_order-b.sort_order)[0]||tasks.filter(t=>t.status!=='done').sort((a,b)=>taskRank(a)-taskRank(b))[0]||null}
function objectiveRate(o){const xs=tasks.filter(t=>t.objective_id===o.id),done=xs.filter(t=>t.status==='done').length;return xs.length?Math.round(done/xs.length*100):0}
function ownerOptions(current){return `<option value="">Unassigned</option>`+team.map(m=>`<option value="${m.user_id}" ${m.user_id===current?'selected':''}>${esc(labelMember(m))}</option>`).join('')}
function statusOptions(current){return ['backlog','next','in_progress','blocked','done'].map(x=>`<option value="${x}" ${x===current?'selected':''}>${x.replace('_',' ')}</option>`).join('')}
function eventBody(e){const d=e.detail||{};if(e.event_type==='vault_saved')return [d.title,d.channel].filter(Boolean).join(' · ')||'A winning-video analysis was saved.';if(e.event_type==='competitor_added')return d.label||d.seed||'Competitor tracking updated.';if(e.event_type==='analysis_started')return d.video_id?`Video ${d.video_id}`:'Premium research started.';if(e.title?.includes('Research stage'))return [d.stage,d.status,d.model,d.error_code].filter(Boolean).join(' · ');if(e.event_type==='creator_dna_updated')return [d.niche,d.subniche,d.target_audience].filter(Boolean).join(' · ');if(d.title&&d.status)return `${d.title} · ${d.status}`;return Object.entries(d).slice(0,3).map(([k,v])=>`${k}: ${typeof v==='object'?'…':v}`).join(' · ')}
function renderAuth(message='',error=false){const root=$('#sharedHQ');if(!root)return;root.innerHTML=`<article class="card shared-auth shared-hero"><div class="kicker">SHARED YTINTEL OPERATIONS</div><h2>One business. One source of truth.</h2><div class="sub">Sign in with your YTIntel account. Progress HQ will then show the same live roadmap, ownership and product activity to both founders.</div><div class="field"><label>Email</label><input id="opsEmail" type="email" autocomplete="email" placeholder="you@example.com"></div><div class="field"><label>Password</label><input id="opsPassword" type="password" autocomplete="current-password" placeholder="••••••••"></div><div class="shared-auth-actions"><button class="main" id="opsSignIn">Sign in</button><button id="opsSignUp">Create account</button></div>${message?`<div class="shared-message ${error?'shared-error':''}">${esc(message)}</div>`:''}<div class="shared-message">Your shared roadmap is protected by YTIntel authentication and workspace membership. Product activity is synced from the real YTIntel database.</div></article>`;$('#opsSignIn').onclick=signIn;$('#opsSignUp').onclick=signUp}
function renderJoin(message='',error=false){const root=$('#sharedHQ');if(!root)return;root.innerHTML=`<article class="card shared-auth shared-hero"><div class="shared-live"><i></i> YTINTEL ACCOUNT CONNECTED</div><h2>Join the founder workspace</h2><div class="sub">Signed in as ${esc(session?.user?.email||'YTIntel user')}. Enter the private founder invite code once. After that, both founders share the same live dashboard.</div><div class="field"><label>Founder workspace code</label><input id="opsInvite" autocomplete="off" placeholder="YTINTEL-…"></div><div class="shared-auth-actions"><button class="main" id="opsJoin">Join workspace</button><button id="opsSignOut">Sign out</button></div>${message?`<div class="shared-message ${error?'shared-error':''}">${esc(message)}</div>`:''}</article>`;$('#opsJoin').onclick=joinWorkspace;$('#opsSignOut').onclick=signOut}
function renderHQ(){const root=$('#sharedHQ');if(!root||!workspace)return;const next=nextSharedTask(),owner=team.find(m=>m.user_id===next?.owner_id);const useful=metrics.feedback_total?Math.round((Number(metrics.feedback_useful||0)/Number(metrics.feedback_total))*100):0;const xp=Number(metrics.workspace_xp||0);root.innerHTML=`<div class="shared-stack">
<article class="card shared-hero"><div class="shared-head"><div><span class="shared-live"><i></i> LIVE TOOL SYNC</span><h1>${esc(workspace.name)}</h1><div class="sub">The roadmap is shared. Product activity comes from YTIntel itself. Team ownership, blockers and proof are shared between both founders.</div></div><div class="shared-actions"><a class="mini-btn" href="../latest/">Open YTIntel ↗</a><button class="mini-btn" id="opsRefresh">Refresh</button><button class="mini-btn" id="opsName">My name</button><button class="mini-btn" id="opsSignOut">Sign out</button></div></div><div class="shared-connected">${esc(session?.user?.email||'')} · ${esc(membership?.role||'member')} · auto-refresh 15s</div></article>
${next?`<article class="card shared-next"><div class="kicker">NEXT TEAM MOVE</div><h2>${esc(next.title)}</h2><div class="sub">${esc(objectives.find(o=>o.id===next.objective_id)?.description||'')}</div><div class="shared-next-meta"><span class="chip">${esc(next.priority)}</span><span class="chip">${esc(next.status.replace('_',' '))}</span><span class="chip">Owner: ${esc(labelMember(owner))}</span>${next.due_date?`<span class="chip">Due ${esc(next.due_date)}</span>`:''}<span class="chip">+${esc(next.xp)} XP when proven</span></div></article>`:''}
<div class="shared-grid"><div class="shared-metric"><b>${esc(metrics.research_7d??0)}</b><span>research runs · 7d</span></div><div class="shared-metric"><b>${esc(metrics.vault_entries??0)}</b><span>Vault winners saved</span></div><div class="shared-metric"><b>${esc(metrics.competitors??0)}</b><span>active competitors</span></div><div class="shared-metric"><b>${esc(metrics.watchtower_alerts_7d??0)}</b><span>Watchtower alerts · 7d</span></div><div class="shared-metric"><b>${esc(useful)}%</b><span>feedback marked useful</span></div><div class="shared-metric"><b>${esc(xp)}</b><span>shared business XP</span></div></div>
<div class="shared-two"><article class="card flat"><div class="section-head"><div><div class="kicker">ENDGAME ROADMAP</div><h2>What we are actually building</h2></div></div><div class="shared-objectives">${objectives.map(o=>renderObjective(o)).join('')}</div></article><div class="shared-stack"><article class="card flat"><div class="section-head"><div><div class="kicker">FOUNDERS</div><h2>Who owns what</h2></div></div><div class="shared-team">${team.map(m=>`<div class="shared-person"><b>${esc(labelMember(m))}</b><span>${esc(m.role)}</span></div>`).join('')}</div></article><article class="card flat"><div class="section-head"><div><div class="kicker">LIVE PRODUCT ACTIVITY</div><h2>What YTIntel is doing</h2></div><span class="sub">automatic</span></div><div class="shared-feed">${events.slice(0,18).map(renderEvent).join('')||'<div class="sub">Activity will appear here as the tool is used.</div>'}</div></article></div></div>
</div>`;
$('#opsRefresh').onclick=()=>loadWorkspace(true);$('#opsSignOut').onclick=signOut;$('#opsName').onclick=editName;root.querySelectorAll('[data-task-status]').forEach(el=>el.onchange=()=>updateTask(el.dataset.taskStatus,{status:el.value}));root.querySelectorAll('[data-task-owner]').forEach(el=>el.onchange=()=>updateTask(el.dataset.taskOwner,{owner_id:el.value||null}));root.querySelectorAll('[data-task-due]').forEach(el=>el.onchange=()=>updateTask(el.dataset.taskDue,{due_date:el.value||null}));root.querySelectorAll('[data-task-proof]').forEach(el=>el.onclick=()=>editProof(el.dataset.taskProof));root.querySelectorAll('[data-add-shared]').forEach(el=>el.onclick=()=>addSharedTask(el.dataset.addShared));}
function renderObjective(o){const xs=tasks.filter(t=>t.objective_id===o.id).sort((a,b)=>a.sort_order-b.sort_order),pct=objectiveRate(o);return `<section class="shared-objective"><div class="shared-objective-head"><div><h3>${esc(o.title)}</h3><p>${esc(o.description)}</p></div><span class="chip">${pct}%</span></div><div class="shared-progress"><span style="width:${pct}%"></span></div>${xs.map(renderTask).join('')}<button class="mini-btn" data-add-shared="${o.id}" style="margin-top:7px">+ Shared task</button></section>`}
function renderTask(t){const owner=team.find(m=>m.user_id===t.owner_id);return `<div class="shared-task ${t.status==='done'?'done':''}"><div class="shared-task-top"><div><div class="shared-task-title">${esc(t.title)}</div><div class="shared-task-note">${esc(t.priority)} · owner ${esc(labelMember(owner))} · +${esc(t.xp)} XP</div>${t.proof?`<div class="shared-proof">Proof: ${esc(t.proof)}</div>`:''}</div><span class="status ${t.status==='done'?'good':t.status==='in_progress'?'current':''}">${esc(t.status.replace('_',' '))}</span></div><div class="shared-task-controls"><select data-task-status="${t.id}" aria-label="Task status">${statusOptions(t.status)}</select><select data-task-owner="${t.id}" aria-label="Task owner">${ownerOptions(t.owner_id)}</select><input data-task-due="${t.id}" type="date" value="${esc(t.due_date||'')}" aria-label="Due date"><button data-task-proof="${t.id}">${t.proof?'Edit proof':'Add proof'}</button></div></div>`}
function renderEvent(e){return `<div class="shared-event ${esc(e.source||'')}"><i class="shared-event-dot"></i><div><b>${esc(e.title)}</b><p>${esc(eventBody(e)||e.event_type)}</p></div><time>${esc(fmtDate(e.occurred_at))}</time></div>`}
async function signIn(){const email=$('#opsEmail')?.value.trim(),password=$('#opsPassword')?.value;if(!email||!password)return renderAuth('Enter your email and password.',true);try{const r=await fetch(`${SB}/auth/v1/token?grant_type=password`,{method:'POST',headers:authHeaders(null),body:JSON.stringify({email,password})});const data=await parse(r);data.expires_at=Math.floor(Date.now()/1000)+(Number(data.expires_in)||3600);saveSession(data);session=data;toast('YTIntel account connected');await bootMember()}catch(e){renderAuth(e.message,true)}}
async function signUp(){const email=$('#opsEmail')?.value.trim(),password=$('#opsPassword')?.value;if(!email||!password||password.length<6)return renderAuth('Use a valid email and a password of at least 6 characters.',true);try{const redirect=`${location.origin}${location.pathname}`;const r=await fetch(`${SB}/auth/v1/signup?redirect_to=${encodeURIComponent(redirect)}`,{method:'POST',headers:authHeaders(null),body:JSON.stringify({email,password})});const data=await parse(r);if(data?.access_token){data.expires_at=Math.floor(Date.now()/1000)+(Number(data.expires_in)||3600);saveSession(data);session=data;await bootMember()}else renderAuth('Account created. Check your email to confirm it, then come back and sign in.',false)}catch(e){renderAuth(e.message,true)}}
async function signOut(){saveSession(null);session=null;workspace=membership=null;objectives=[];tasks=[];events=[];team=[];metrics={};clearInterval(poll);poll=null;renderAuth('Signed out.',false)}
async function joinWorkspace(){const code=$('#opsInvite')?.value.trim();if(!code)return renderJoin('Enter the founder workspace code.',true);try{await rpc('ytintel_ops_join_workspace',{p_code:code});toast('Founder workspace joined');await bootMember()}catch(e){renderJoin(e.message,true)}}
async function bootMember(){await ensureSession();if(!session){renderAuth();return}const user=session.user||await parse(await fetch(`${SB}/auth/v1/user`,{headers:authHeaders()}));session.user=user;saveSession(session);let rows=[];try{rows=await rest(`ytintel_ops_members?select=workspace_id,role,display_name,joined_at&user_id=eq.${encodeURIComponent(user.id)}`)}catch{}if(!rows?.length){renderJoin();return}membership=rows[0];const ws=await rest(`ytintel_ops_workspaces?select=id,name,slug& id=eq.${membership.workspace_id}`.replace('& ', '&'));workspace=ws?.[0]||{id:membership.workspace_id,name:'YTIntel Founders',slug:'ytintel-founders'};await loadWorkspace(false);startPoll()}
async function loadWorkspace(showToast=false){if(busy||!workspace)return;busy=true;try{const id=workspace.id;const [os,ts,es,ms,ds]=await Promise.all([rest(`ytintel_ops_objectives?select=*&workspace_id=eq.${id}&order=sort_order.asc`),rest(`ytintel_ops_tasks?select=*&workspace_id=eq.${id}&order=sort_order.asc`),rest(`ytintel_ops_events?select=*&workspace_id=eq.${id}&order=occurred_at.desc&limit=60`),rpc('ytintel_ops_team',{p_workspace:id}),rpc('ytintel_ops_dashboard',{p_workspace:id})]);objectives=os||[];tasks=ts||[];events=es||[];team=ms||[];metrics=ds||{};renderHQ();if(showToast)toast('Shared HQ refreshed')}catch(e){console.warn('[Progress HQ shared]',e);toast('Shared sync unavailable')}finally{busy=false}}
function startPoll(){clearInterval(poll);poll=setInterval(()=>{if(!document.hidden)loadWorkspace(false)},POLL_MS)}
async function updateTask(id,patch){try{await rest(`ytintel_ops_tasks?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:{...patch,updated_at:new Date().toISOString()}});await loadWorkspace(false);toast('Shared task updated')}catch(e){toast(e.message)}}
async function editProof(id){const t=tasks.find(x=>x.id===id);if(!t)return;const proof=prompt('Proof / receipt / decision',t.proof||'');if(proof===null)return;const patch={proof:proof.trim()};if(proof.trim()&&t.status!=='done'&&confirm('Mark this shared task done as well?'))patch.status='done';await updateTask(id,patch)}
async function addSharedTask(objectiveId){const title=prompt('Shared task');if(!title?.trim())return;const owner=team.find(m=>m.user_id===session?.user?.id);try{await rest('ytintel_ops_tasks',{method:'POST',headers:{Prefer:'return=minimal'},body:{workspace_id:workspace.id,objective_id:objectiveId,title:title.trim(),status:'next',priority:'P1',owner_id:owner?.user_id||null,xp:30,sort_order:tasks.filter(t=>t.objective_id===objectiveId).length+1}});await loadWorkspace(false);toast('Shared task added')}catch(e){toast(e.message)}}
async function editName(){const me=team.find(m=>m.user_id===session?.user?.id);const name=prompt('Your display name',me?.display_name||'');if(name===null)return;try{await rest(`ytintel_ops_members?workspace_id=eq.${workspace.id}&user_id=eq.${session.user.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:{display_name:name.trim()||null}});await loadWorkspace(false)}catch(e){toast(e.message)}}
async function sendEvent(type,title,detail={},xp=0){if(!workspace||!session)return;try{await rpc('ytintel_ops_event',{p_workspace:workspace.id,p_type:type,p_title:title,p_detail:detail,p_source:'progress-hq',p_source_ref:null,p_dedupe_key:null,p_xp:xp});await loadWorkspace(false)}catch(e){console.warn('[Progress HQ event]',e)}}
function wireLocalEvents(){document.addEventListener('click',e=>{const id=e.target?.id;if(id==='completeSprint')setTimeout(()=>sendEvent('focus_completed','Founder focus sprint completed',{focus:$('#sprintTask')?.textContent||'Focus sprint'},60),150);if(id==='saveCheckin')setTimeout(()=>sendEvent('checkin','Founder daily check-in',{source:'Progress HQ'},20),150)},true);window.addEventListener('focus',()=>{if(workspace)loadWorkspace(false)});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&workspace)loadWorkspace(false)})}
function consumeAuthHash(){const p=new URLSearchParams(location.hash.replace(/^#/,''));const access=p.get('access_token'),refresh=p.get('refresh_token');if(!access||!refresh)return false;const s={access_token:access,refresh_token:refresh,expires_in:Number(p.get('expires_in')||3600),expires_at:Math.floor(Date.now()/1000)+Number(p.get('expires_in')||3600),token_type:'bearer'};saveSession(s);session=s;history.replaceState({},'',location.pathname+location.search);return true}
async function init(){installStyles();wireLocalEvents();consumeAuthHash();session=loadSession();if(!session){renderAuth();return}try{await bootMember()}catch(e){console.warn(e);saveSession(null);session=null;renderAuth('Your saved session expired. Sign in again.',true)}}
window.YTIntelSharedHQ={refresh:()=>loadWorkspace(true),get workspace(){return workspace},get session(){return session}};
init();
})();