const API='https://dkmacktcfhubsumwrydw.supabase.co/functions/v1/ytintel-v08';
const HEADERS={'content-type':'application/json','x-ytintel-client':'web-v08'};
const STORE='ytintel-v08-history';
let lastReport=null, selectedNiche=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const num=x=>x==null||x===''?'-':Number(x).toLocaleString(undefined,{maximumFractionDigits:2});
const compact=x=>!Number.isFinite(Number(x))?'-':new Intl.NumberFormat(undefined,{notation:'compact',maximumFractionDigits:1}).format(Number(x));
const time=x=>{x=Math.max(0,Math.round(Number(x)||0));const h=Math.floor(x/3600),m=Math.floor((x%3600)/60),s=x%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`};
const date=x=>{if(!x)return'-';const d=new Date(x);return Number.isNaN(d.valueOf())?String(x):d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})};
const med=xs=>{const a=xs.map(Number).filter(Number.isFinite).sort((a,b)=>a-b);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
const metric=(label,value,cls='')=>`<div class="metric"><span>${esc(label)}</span><b class="${cls}">${esc(value)}</b></div>`;
const list=(xs,empty='No strong evidence detected.')=>xs?.length?`<ul class="list">${xs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:`<p class="muted">${esc(empty)}</p>`;
async function api(action,body={}){const r=await fetch(`${API}?action=${encodeURIComponent(action)}`,{method:'POST',headers:HEADERS,body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw Error(d.error||`HTTP ${r.status}`);return d}
function tab(name){$$('[data-tab]').forEach(b=>b.classList.toggle('on',b.dataset.tab===name));$$('.view').forEach(v=>v.classList.toggle('active',v.id===name));if(name==='history'&&typeof renderHistory==='function')renderHistory();if(name==='visuals'&&typeof renderVisuals==='function')renderVisuals()}
$$('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
fetch(`${API}?action=health`).then(r=>r.json()).then(d=>$('#status').textContent=`v${d.version} ready`).catch(()=>$('#status').textContent='engine online');
function showErr(id,e){const x=$(id);x.textContent=e?.message||String(e);x.classList.add('show')}function clearErr(id){const x=$(id);x.classList.remove('show');x.textContent=''}

$('#analyseForm').onsubmit=async e=>{e.preventDefault();clearErr('#error');$('#report').innerHTML='';$('#loading').classList.add('show');try{const d=await api('analyze',{url:$('#videoUrl').value.trim()});lastReport=d.report;renderReport(lastReport);if(typeof saveHistory==='function')saveHistory(lastReport);if(typeof prefillSimilar==='function')prefillSimilar(lastReport);if(typeof renderVisuals==='function')renderVisuals();setTimeout(()=>$('#report').scrollIntoView({behavior:'smooth',block:'start'}),50)}catch(x){showErr('#error',x)}finally{$('#loading').classList.remove('show')}};
function heatSvg(points){if(!points?.length)return'';const W=1000,H=180,pad=10;const vals=points.map(x=>Number(x.value)||0),max=Math.max(...vals,1),coords=points.map((x,i)=>`${pad+(W-pad*2)*i/(points.length-1)},${H-pad-(H-pad*2)*(Number(x.value)||0)/max}`).join(' ');const area=`${pad},${H-pad} ${coords} ${W-pad},${H-pad}`;return `<div class="heat-wrap"><svg class="heat-svg" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><polyline points="${area}" fill="rgba(141,169,255,.13)" stroke="none"></polyline><polyline points="${coords}" fill="none" stroke="#8da9ff" stroke-width="4" vector-effect="non-scaling-stroke"></polyline></svg><div class="heat-labels"><span>Start</span><span>25%</span><span>50%</span><span>75%</span><span>End</span></div></div>`}
function outlierText(out){const m=Number(out?.multiple);if(!Number.isFinite(m))return'Channel-relative baseline unavailable for this video.';if(m>=10)return'Monster outlier — this video is performing at least 10× the recent channel norm.';if(m>=5)return'Strong outlier — this is far above the creator’s recent baseline.';if(m>=3)return'Clear outlier — materially stronger than the creator’s recent uploads.';if(m>=1.5)return'Above normal — stronger than the recent channel median.';return'Near channel norm — useful as a control, not an obvious breakout.'}
function methodSummaryHtml(r){const s=r.summary_intelligence||{},methods=s.methods||[];return `<article class="card c12 summary-card"><div class="eyebrow">CONCISE VIDEO SUMMARY</div><h2 style="margin:5px 0">What the video actually teaches / discusses</h2>${methods.length?`<div class="method-grid">${methods.map(x=>`<div class="method"><div class="split"><b>${esc(x.label)}</b><span class="pill">${esc(x.timestamp)}</span></div><p>${esc(x.explanation)}</p></div>`).join('')}</div>`:'<p class="muted">This transcript is more descriptive than instructional, so YTIntel did not invent a fake method list.</p>'}<div class="takeaway"><div class="eyebrow">TAKEAWAY</div>${esc(s.takeaway||'No concise takeaway available.')}</div><div class="warn">${esc(s.guardrail||'Summary is transcript-derived.')}</div></article>`}
function renderReport(r){const v=r.video||{},q=r.research_intelligence||{},m=q.retention_mechanics||{},f=q.format_engine||{},a=q.actionable_summary||{},p=r.pacing||{},pkg=q.packaging||{},prod=q.production_load||{},tl=q.timeline||[],risk=m.script_attention_risk_zones||[],peaks=r.heatmap?.top_peaks||[],norm=r.heatmap?.normalized_100||[],segs=r.transcript?.segments||[],top=[...tl].sort((x,y)=>(y.signal_score||0)-(x.signal_score||0)).slice(0,8),mx=Math.max(1,...top.map(x=>Number(x.signal_score||0))),out=v.outlier||{},hs=r.hook_story||{};
const outTxt=out.multiple==null?'-':`${num(out.multiple)}×`;const quality=`${r.transcript?.available?'<span class="pill good">Transcript ✓</span>':'<span class="pill hot">Transcript missing</span>'}${r.heatmap?.available?'<span class="pill good">100-point Most Replayed ✓</span>':'<span class="pill hot">Most Replayed unavailable</span>'}`;
$('#report').innerHTML=`<div class="grid">
<article class="card c12"><div class="split"><div style="flex:1;min-width:260px"><div class="eyebrow">FACTS LAYER</div><h2 style="margin:5px 0">${esc(v.title||'Untitled')}</h2><div class="muted">${esc(v.channel||'Unknown channel')}</div><div class="pillrow" style="margin-top:9px">${quality}</div></div><div style="text-align:right"><div class="eyebrow">CHANNEL-RELATIVE</div><div class="outlier ${Number(out.multiple)>=3?'good':''}">${esc(outTxt)}</div><div class="source-note">outlier multiple</div></div></div>
<div class="metrics">${metric('Views',compact(v.view_count))}${metric('Upload',date(v.upload_date))}${metric('Subscribers',compact(v.channel_follower_count))}${metric('Comments',compact(v.comment_count))}${metric('Length',time(v.duration))}${metric('Clean words',num(p.total_words))}${metric('WPM',num(p.video_words_per_minute))}${metric('Proof loops/min',num(m.loops_per_minute))}${metric('Payoffs/min',num(m.payoffs_per_minute))}${metric('First payoff',m.first_payoff_timestamp||'-')}${metric('Re-hook spacing',m.median_rehook_interval_seconds==null?'-':`${num(m.median_rehook_interval_seconds)}s`)}${metric('Channel median',compact(out.channel_median_views))}</div></article>
<article class="card c12 outlier-card"><div class="outlier-layout"><div><div class="eyebrow">OUTLIER MULTIPLIER</div><div class="outlier jumbo ${Number(out.multiple)>=3?'good':''}">${esc(outTxt)}</div></div><div class="grow"><h2>How unusual is this video for this creator?</h2><p>${esc(outlierText(out))}</p><div class="metrics mini">${metric('This video',compact(v.view_count))}${metric('Recent channel median',compact(out.channel_median_views))}${metric('Baseline sample',out.sample_size??'-')}${metric('Tier',out.tier||'-')}</div>${out.basis?`<div class="source-note">${esc(out.basis)}</div>`:''}</div></div></article>
<article class="card c12"><div class="section-head"><div><div class="eyebrow">MOST REPLAYED — 100 POINTS</div><h2>Where viewers came back</h2></div><span class="pill">Replay / seek interest, not Studio retention</span></div>${r.heatmap?.available?heatSvg(norm):'<p class="amber">No Most Replayed curve is exposed for this video/session. YTIntel will not fabricate one.</p>'}${peaks.length?`<div class="peaks">${peaks.slice(0,8).map((x,i)=>`<div class="peak"><span>#${i+1}</span><b>${time(x.time)}</b><span>intensity ${num(x.value)}</span></div>`).join('')}</div>`:''}</article>
<article class="card c8"><div class="eyebrow">THE ENGINE</div><div class="engine"><strong>${esc(f.primary||'Not enough evidence')}</strong><p>${esc(f.one_sentence_engine||'')}</p></div><h3>Why this likely worked</h3>${list(a.why_it_works_evidence||[])}</article>
<article class="card c4 winner-box"><div class="eyebrow">STEAL THESE MECHANICS</div><h2 style="margin-top:5px">Transferable without copying</h2>${list(a.transferable_mechanics||[])}</article>
<article class="card c12"><div class="eyebrow">HOOK → RE-HOOK → FULFILLMENT</div><h2 style="margin:5px 0 12px">How the promise is created, reset and paid off</h2><div class="hook-grid"><div class="evidence-card"><div class="stepnum">1</div><div class="eyebrow">HOOK · ${esc(hs.hook?.timestamp||'0:00')}</div><h3>${esc(hs.hook?.type||'Opening')}</h3><p class="evidence-text">${esc(hs.hook?.excerpt||q.opening?.first_15_seconds||'-')}</p><div class="source-note">${esc(hs.hook?.mechanism||'Opening mechanism not classified.')}</div></div><div class="evidence-card"><div class="stepnum">2</div><div class="eyebrow">RE-HOOK EXAMPLE · ${esc(hs.rehook?.timestamp||'-')}</div><h3>Where attention is reset later</h3><p class="evidence-text">${esc(hs.rehook?.excerpt||'No explicit re-hook example was detected.')}</p><div class="source-note">${esc(hs.rehook?.reason||'No strong explicit re-hook found.')}</div></div><div class="evidence-card"><div class="stepnum">3</div><div class="eyebrow">PROMISE FULFILLMENT · ${esc(hs.fulfillment?.timestamp||'-')}</div><h3>Where the hook/title gets paid off</h3><p class="evidence-text">${esc(hs.fulfillment?.excerpt||'No strong transcript-level fulfillment example detected.')}</p><div class="source-note">${esc(hs.fulfillment?.reason||hs.guardrail||'Best-effort transcript evidence.')}</div></div></div><div class="warn">${esc(hs.guardrail||'Hook fulfillment is transcript evidence, not measured retention.')}</div></article>
<article class="card c6"><div class="eyebrow">PACKAGING → DELIVERY</div><h3>Does the script actually cover the title promise?</h3><div class="metrics" style="grid-template-columns:repeat(2,1fr)">${metric('Title type',pkg.title_type||'-')}${metric('Title words',num(pkg.title_words))}${metric('Promise first 60s',pkg.first_60s_promise_coverage_percent==null?'-':`${num(pkg.first_60s_promise_coverage_percent)}%`)}${metric('Promise full video',pkg.full_video_promise_coverage_percent==null?'-':`${num(pkg.full_video_promise_coverage_percent)}%`)}</div></article>
<article class="card c6"><div class="eyebrow">PRODUCTION LOAD</div><h3>How hard is the format to execute?</h3><div class="pillrow"><span class="pill">${esc(prod.research_load||'-')} research load</span><span class="pill">${esc(prod.editing_demand_proxy||'-')} edit-demand proxy</span><span class="pill">${num(prod.estimated_proof_or_test_moments)} proof/test moments</span><span class="pill">${num(prod.estimated_distinct_payoff_beats)} payoff beats</span></div><div class="warn">Edit demand is still a transcript/content proxy until frame-level cut analysis is live.</div></article>
<article class="card c8"><div class="eyebrow">ATTENTION TIMELINE</div><h3>Strongest 30-second script windows</h3><div class="timeline">${top.map(x=>`<div class="tl"><span>${time(x.start)}</span><div><div class="bar"><i style="width:${Math.max(4,(Number(x.signal_score||0)/mx)*100)}%"></i></div><div class="source-note" style="margin-top:4px">${esc(x.text_preview||'')}</div></div><b>${num(x.signal_score)}</b></div>`).join('')||'<p class="muted">No timeline available.</p>'}</div></article>
<article class="card c4"><div class="eyebrow">RISK FLAGS</div><h3>Where the script may drag</h3>${risk.length?risk.map(x=>`<div class="risk"><b>${esc(x.start_timestamp)}–${esc(x.end_timestamp)}</b><div class="muted">${esc(x.reason)}</div></div>`).join(''):'<p class="muted">No long low-signal zones flagged.</p>'}<div class="warn">Hypotheses only — not measured audience-retention drops.</div></article>
<article class="card c12"><div class="split"><div><div class="eyebrow">REMAKE BLUEPRINT</div><h2 style="margin:4px 0">Turn evidence into the next video</h2></div><div class="spacer"></div><button class="btn small no-print" id="copyMd">Copy report as Markdown</button><button class="btn small no-print" id="printPdf">Print / Save PDF</button></div>${(a.remake_blueprint||[]).map(x=>`<div class="beat"><small>${esc(x.zone)}</small><div><b>${esc(x.instruction)}</b><p>Source evidence: ${esc(x.observed)}</p></div></div>`).join('')||'<p class="muted">No blueprint available.</p>'}</article>
<article class="card c6"><div class="eyebrow">DATA QUALITY</div><p><b>Heatmap source:</b> ${esc(r.extraction?.replay_source||'not available')}</p><p><b>Transcript:</b> ${esc(q.data_quality?.transcript||r.transcript?.source||'-')}</p><p><b>Visual edit pace:</b> hotzone targeting is live; true cut/motion-graphic classification is still beta.</p></article>
<article class="card c6"><div class="eyebrow">VISUAL / AUDIO HANDOFF</div><h3>Use replay evidence to inspect the right moments</h3><p>${(r.visual_intelligence?.hotzone_targets||[]).length?`${r.visual_intelligence.hotzone_targets.length} replay hotzones are queued as visual-analysis targets.`:'No replay hotzones are available to target.'}</p><button class="btn small no-print" id="openVisuals">Open Visuals + Edit tab</button></article>
<article class="card c12"><div class="split"><div><div class="eyebrow">CLEAN TRANSCRIPT</div><h2 style="margin:4px 0">Full timestamped transcript</h2></div><div class="spacer"></div><button class="btn small no-print" id="copyTranscript">Copy transcript as Markdown</button></div><div class="transcript">${segs.slice(0,900).map(s=>`<div class="tr"><time>${time(s.start)}</time><p>${esc(s.text||'')}</p></div>`).join('')||'<p class="muted">Transcript unavailable.</p>'}</div></article>
${methodSummaryHtml(r)}
</div>`;
$('#copyMd').onclick=()=>copyReportMarkdown(r);$('#printPdf').onclick=()=>window.print();$('#copyTranscript').onclick=()=>copyTranscriptMarkdown(r);$('#openVisuals').onclick=()=>tab('visuals');}
function reportMarkdown(r){const v=r.video||{},q=r.research_intelligence||{},m=q.retention_mechanics||{},a=q.actionable_summary||{},f=q.format_engine||{},peaks=r.heatmap?.top_peaks||[],hs=r.hook_story||{},s=r.summary_intelligence||{};return `# ${v.title||'YouTube video'}\n\n## Facts\n- Channel: ${v.channel||'-'}\n- Views: ${v.view_count??'-'}\n- Outlier multiple: ${v.outlier?.multiple??'-'}x\n- Channel median views: ${v.outlier?.channel_median_views??'-'}\n- Upload date: ${v.upload_date||'-'}\n- Subscribers: ${v.channel_follower_count??'-'}\n- Comments: ${v.comment_count??'-'}\n- Duration: ${time(v.duration)}\n- WPM: ${r.pacing?.video_words_per_minute??'-'}\n- Format engine: ${f.primary||'-'}\n- First payoff: ${m.first_payoff_timestamp||'-'}\n- Re-hook spacing: ${m.median_rehook_interval_seconds??'-'}s\n\n## Most Replayed peaks\n${peaks.map((x,i)=>`${i+1}. ${time(x.time)} — ${x.value}`).join('\n')||'No replay data.'}\n\n## Hook\n${hs.hook?.excerpt||'-'}\n\n## Re-hook example (${hs.rehook?.timestamp||'-'})\n${hs.rehook?.excerpt||'-'}\n\n## Promise fulfillment (${hs.fulfillment?.timestamp||'-'})\n${hs.fulfillment?.excerpt||'-'}\n\n## Why it worked\n${(a.why_it_works_evidence||[]).map(x=>`- ${x}`).join('\n')}\n\n## Steal these mechanics\n${(a.transferable_mechanics||[]).map(x=>`- ${x}`).join('\n')}\n\n## Remake blueprint\n${(a.remake_blueprint||[]).map(x=>`- **${x.zone}** — ${x.instruction} Source evidence: ${x.observed}`).join('\n')}\n\n## Methods / key points\n${(s.methods||[]).map(x=>`- **${x.timestamp} — ${x.label}**: ${x.explanation}`).join('\n')||'- No strong instructional methods extracted.'}\n\n## Takeaway\n${s.takeaway||'-'}`}
function transcriptMarkdown(r){const v=r.video||{},segs=r.transcript?.segments||[];return `# Transcript — ${v.title||'YouTube video'}\n\nChannel: ${v.channel||'-'}\nURL: ${v.webpage_url||v.original_url||''}\n\n${segs.map(s=>`[${time(s.start)}] ${s.text||''}`).join('\n')}`}
async function copyText(text,button,label,filename){try{await navigator.clipboard.writeText(text);button.textContent='Copied ✓';setTimeout(()=>button.textContent=label,1400)}catch{const blob=new Blob([text],{type:'text/markdown'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();URL.revokeObjectURL(a.href)}}
function copyReportMarkdown(r){copyText(reportMarkdown(r),$('#copyMd'),'Copy report as Markdown','ytintel-report.md')}
function copyTranscriptMarkdown(r){copyText(transcriptMarkdown(r),$('#copyTranscript'),'Copy transcript as Markdown','ytintel-transcript.md')}
