// Synthetic test data, never a production or benchmark analysis.
export const report={video:{id:'QAfixture01',title:'Testing an irrigation schedule',channel:'Synthetic QA',duration:600,upload_date:'2026-08-01',view_count:100,outlier:{multiple:1,channel_median_views:100}},content_niche:'Testing',transcript:{available:true,segments:Array.from({length:12},(_,i)=>({start:i*50,end:(i+1)*50,text:`Trial ${i+1} recorded soil moisture at dawn before watering. We measured the same planting bed and logged rainfall for the comparison. The observed change is a case study, not a guarantee.`}))},heatmap:{available:false,normalized_100:[],top_peaks:[]},research_intelligence:{timeline:[]},content_extraction:{target_count:7,items:[{statement:'BAD RAW OVERRIDE',start:0,exact_line:'BAD RAW OVERRIDE'}]}};
const ref=i=>({segment_id:i,quote:`Trial ${i+1} recorded soil moisture at dawn before watering.`});
export const plan={video_kind:'instruction',declared_count:null,summary_goal:'Explain the matched irrigation comparison.',summary_questions:['What changed in each planting bed?','Were rainy periods separated?'],takeaway_questions:['What was controlled?','Which limits matter?'],review_questions:['Are observations distinct from causation?','Do instructions preserve the measurement controls?']};
export const summary={summary:'The demonstration follows a controlled garden experiment rather than offering a universal watering recipe. It explains how matching the measurement hour, documenting weather and keeping the comparison bed consistent makes the resulting observations easier to interpret. The useful output is a repeatable measurement procedure; the limited sample does not establish a reliable improvement for every garden.',beats:Array.from({length:12},(_,i)=>({start_segment:i,meaning:`Stage ${i+1} advances the comparison by explaining the measurement choice and its implications for interpreting the trial.`})),verdict:'The supplied upload is at its channel median; these observations do not establish a breakout mechanism.',verdict_basis:'inference',limitations:['Synthetic fixture; not a real video analysis.']};
export const takeaways={kind:'actions',declared_count:null,items:Array.from({length:5},(_,i)=>({title:['Control observation timing','Separate rain from irrigation','Keep comparison plots stable','Record uncertainty explicitly','Repeat before generalising'][i],explanation:`Lesson ${i+1} concerns experimental discipline rather than the speaker's personal motivation. Consistent observations make comparisons interpretable, while uncontrolled conditions can make a change look useful even when its cause remains unclear.`,application:'Create a dated measurement log and record the changing conditions before interpreting the next result.',evidence:[ref(i*2)]}))};
export const mechanics={hook:{primary_type:'Experiment',why:'It introduces an observable comparison.',opening:ref(0),first_promise:{segment_id:null,quote:''}},hook_lines:[{evidence:ref(0),job:'Introduces the comparison and limits its scope.'},{evidence:ref(1),job:'Establishes the repeated measurement.'}],rehooks:[{evidence:ref(4),why:'Reintroduces the comparison condition.',type:'Method reset'}],payoffs:[{evidence:ref(8),why:'Explains what the observed comparison can support.',promise:'A repeatable measurement method'}],title_promise_verdict:'The source describes its trial rather than proving a universal benefit.',transferable_mechanics:[{mechanic:'Anchor the test in measurements',how_to_reuse:'Show the recorded values before asserting an interpretation.',evidence:ref(0)}],funnel:{selling_sections:[],cta_evidence:[],interpretation:'No sales interval is established by the supplied test captions.'},uncertainties:['Caption timing is not word-accurate.']};
export const claims={claims:[{claim:'The trial is a case study, not a guarantee.',evidence:ref(0),assessment:'creator_claim',reason:'The caption describes a single demonstration.',sources:[]}],limits:['No external sources in this synthetic fixture.']};
export const review={pass:true,summary_score:4,takeaways_score:4,source_fidelity_score:5,issues:[],summary:'Test fixture passes the configured checks.'};
export const remake={directions:[0,1].map(i=>({title:i?'A rainfall-control trial':'A dawn-measurement diary',alternate_titles:['Controlled garden measurements','A repeatable observation routine'],opening_hook:'This test is about what the measurements can support, not a promised result.',beat_sheet:Array.from({length:4},(_,j)=>({beat:`Original direction ${i+1}, beat ${j+1}`,purpose:'Explain one controlled condition and its consequence.',evidence_to_show:'An original measurement log with dates and limitations.'})),thumbnail:{focal_subject:'A labelled measurement log',composition:'One legible comparison with the conditions noted.',text:'TEST LOG',avoid:'Do not imply guaranteed growth.'},evidence:[ref(i),ref(i+4)],steal:'Show the evidence before interpreting the comparison.',avoid:'Do not reuse another creator\'s results as your own.',measurement_plan:['Record comparable public outcomes.','Evaluate the test against your own observations.']}))};
export const outputs={plan,summary,takeaways,mechanics,claims,review,remake,final_review:review};
