import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
await mkdir('ytintel-live-proof',{recursive:true});
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1280,height:900},serviceWorkers:'block'});
const page=await context.newPage();
const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/ytintel-v0|api\.openai\.com/i.test(r.url()))requests.push(r.url())});
try{
  const url=`https://mitchloxton.github.io/pinnacle-navigator/ytintel/latest/?qa=benchmark-live-${Date.now()}`;
  await page.goto(url,{waitUntil:'domcontentloaded',timeout:45000});
  await page.waitForFunction(()=>window.YTIntelStableShell?.coreReady===true&&window.YTIntelStableShell?.intelligenceReady===true&&window.YTIntelStableShell?.premiumLayerReady===true,null,{timeout:45000});
  await page.waitForTimeout(500);
  const start=await page.evaluate(()=>({version:document.querySelector('#version')?.textContent,scripts:document.scripts.length,core:document.documentElement.dataset.ytintelCore,shell:document.documentElement.dataset.ytintelShell,premiumLayer:document.documentElement.dataset.ytintelPremiumLayer,wpmGuard:!!window.YTIntelWpmGuard,premium:!!window.YTIntelPremium}));
  assert.equal(start.version,'v0.39.0');assert.equal(start.scripts,1);assert.equal(start.core,'ready');assert.equal(start.shell,'stable');assert.equal(start.premiumLayer,'ready');assert.equal(start.wpmGuard,true);assert.equal(start.premium,true);
  const select=async name=>{await page.locator(`[data-tab="${name}"]`).click();await page.waitForFunction(n=>{const x=document.getElementById(n);return x&&x.classList.contains('active')&&!x.hidden&&getComputedStyle(x).display!=='none'},name)};
  await select('competitors');await page.locator('#competitorInput').fill('@YTIntelLiveSmoke');await page.locator('#addCompetitor').click();assert((await page.locator('#competitorList').innerText()).includes('@YTIntelLiveSmoke'));
  await select('vault');await page.locator('#creator_niche').fill('GTA 6');await page.locator('#creator_subniche').fill('GTA 6 news and analysis');await page.locator('#creator_audience').fill('GTA 6 players who want evidence-first creator analysis');await page.locator('#creator_brand').fill('Evidence first. No guru claims. Do not copy source wording or unsupported revenue numbers.');await page.locator('#saveCreator').click();await page.waitForFunction(()=>/Saved locally/i.test(document.querySelector('#creatorSaved')?.textContent||''));
  await select('analyse');await page.setViewportSize({width:390,height:844});for(const name of ['competitors','vault','analyse']){await page.locator(`[data-dock="${name}"]`).click();await page.waitForFunction(n=>document.getElementById(n)?.classList.contains('active'),name)}
  const mobile=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth}));assert(mobile.scroll<=mobile.viewport+1,`mobile overflow ${mobile.scroll}>${mobile.viewport}`);
  await page.locator('#videoUrl').fill('https://www.youtube.com/watch?v=GzhT10i4vag');await page.locator('#analyseBtn').click();await page.waitForFunction(()=>!document.querySelector('#progressCard')?.classList.contains('hidden'),null,{timeout:10000});
  await page.locator('[data-dock="vault"]').click();await page.waitForFunction(()=>document.querySelector('#vault')?.classList.contains('active'));await page.locator('[data-dock="analyse"]').click();
  await page.waitForFunction(()=>window.__YTINTEL_SOURCE_REPORT?.video?.id==='GzhT10i4vag'||(document.querySelector('#analyseError')?.textContent||'').trim().length>0,null,{timeout:210000});
  await page.waitForFunction(()=>['ready','fallback'].includes(document.documentElement.dataset.ytintelPremium)||(document.querySelector('#analyseError')?.textContent||'').trim().length>0,null,{timeout:390000});
  const result=await page.evaluate(()=>({premiumState:document.documentElement.dataset.ytintelPremium,premiumSections:document.querySelectorAll('#v400-premium-report [data-premium-section]').length,appendixSections:document.querySelectorAll('#v400-appendix .section').length,error:(document.querySelector('#analyseError')?.textContent||'').trim(),premiumStatus:document.querySelector('#v400-progress')?.innerText||'',claims:document.querySelector('[data-premium-section="6"]')?.innerText||'',pattern:document.querySelector('[data-premium-section="11"]')?.innerText||'',business:document.querySelector('[data-premium-section="12"]')?.innerText||'',remake:document.querySelector('[data-premium-section="14"]')?.innerText||'',creatorLoop:document.querySelector('[data-premium-section="15"]')?.innerText||'',audit:document.querySelector('[data-premium-section="16"]')?.innerText||'',version:document.querySelector('#version')?.textContent,active:document.querySelector('.view.active')?.id,wpm:window.__YTINTEL_SOURCE_REPORT?.pacing?.video_words_per_minute??null,totalWords:window.__YTINTEL_SOURCE_REPORT?.pacing?.total_words??null}));
  assert.equal(result.error,'',result.error);assert.equal(result.premiumState,'ready',result.premiumStatus);assert.equal(result.premiumSections,16);assert(result.appendixSections>=17,`expected stable appendix, got ${result.appendixSections}`);assert.equal(result.version,'v0.39.0');assert.equal(result.active,'analyse');
  assert.match(result.claims,/Claims ledger|verified|creator_claim|uncertain|contradicted|arithmetic_issue/i);assert.match(result.pattern,/cross-channel validation|Public YouTube validation sample/i);assert.match(result.business,/selling|commercial|CTA|runtime/i);assert.match(result.remake,/Remake blueprint|DIRECTION 1|Opening:/i);assert.match(result.creatorLoop,/measure|Creator Loop/i);assert.match(result.audit,/PASS|Fidelity|benchmark/i);
  assert(Number.isFinite(Number(result.wpm))&&Number(result.wpm)>=80&&Number(result.wpm)<=330,`implausible corrected WPM ${result.wpm}`);assert(Number(result.totalWords)>500,`deduped words too low: ${result.totalWords}`);assert.deepEqual(errors,[],errors.join(' | '));assert(requests.some(x=>/ytintel-v093\?action=research-begin/i.test(x)),`premium research endpoint not called: ${requests.join(', ')}`);
  await page.screenshot({path:'ytintel-live-proof/v390-premium-benchmark-mobile.png',fullPage:true});const receipt={pass:true,url,start,result:{...result,claims:result.claims.slice(0,1200),pattern:result.pattern.slice(0,1000),business:result.business.slice(0,1000),remake:result.remake.slice(0,1400),audit:result.audit.slice(0,1000)},mobile,errors,requests:requests.map(x=>x.replace(/&?token=[^&]+/g,'')),checked_at:new Date().toISOString()};await writeFile('ytintel-live-proof/v390-premium-benchmark-receipt.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt,null,2));
}finally{await browser.close()}
