import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
await mkdir('ytintel-live-proof',{recursive:true});
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});
await context.addInitScript(()=>{try{localStorage.setItem('ytintel-v350-profile',JSON.stringify({niche:'gta6',subniche:'how to make money with gta6',channel:'@badprofile',audience:'Gamers',brand:'test',complete:true}));localStorage.setItem('ytintel-v340-creator',JSON.stringify({niche:'gta6',subniche:'how to make money with gta6',audience:'Gamers',brand:'test'}))}catch{}});
const page=await context.newPage(),errors=[],requests=[];page.setDefaultTimeout(60000);
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{try{const u=new URL(r.url());if(u.hostname.endsWith('supabase.co'))requests.push({path:u.pathname,action:u.searchParams.get('action'),status:r.status()})}catch{}});
const url='https://mitchloxton.github.io/pinnacle-navigator/ytintel/latest/?qa=v361-live-'+Date.now();
try{
 await page.goto(url,{waitUntil:'domcontentloaded',timeout:60000});
 await page.waitForFunction(()=>window.YTINTEL_VERSION==='0.36.1'&&!document.querySelector('#boot')&&!document.querySelector('#app')?.hidden,null,{timeout:120000});
 const boot=await page.evaluate(()=>({version:window.YTINTEL_VERSION,visible:document.querySelector('#version')?.textContent,scripts:[...document.scripts].filter(x=>x.src).map(x=>new URL(x.src).pathname.split('/').pop()),nav:[...document.querySelectorAll('[data-tab]')].filter(x=>getComputedStyle(x).display!=='none').map(x=>x.dataset.tab),creator:getComputedStyle(document.querySelector('#creatorCard')).display,dna:!!document.querySelector('#v350-profile-overlay,#v361-dna-overlay'),signin:!!document.querySelector('#v361-signin-dna'),text:document.body.innerText}));
 assert.equal(boot.version,'0.36.1');assert.equal(boot.visible,'v0.36.1');assert.deepEqual(boot.scripts,['v360-entry.js']);assert.deepEqual(boot.nav,['analyse','compare','vault','competitors']);assert.equal(boot.creator,'none');assert.equal(boot.dna,false);assert.equal(boot.signin,true);assert(!boot.text.includes('07/09/26 MONDAY BRIEF'));
 await page.locator('#videoUrl').fill('https://www.youtube.com/watch?v=GzhT10i4vag');await page.locator('#analyseBtn').click();
 await page.waitForFunction(()=>document.querySelector('#progressPct')?.textContent==='100%'||document.querySelector('#progressState')?.textContent==='STOPPED',null,{timeout:300000});await page.waitForTimeout(750);
 const result=await page.evaluate(()=>{const sec=n=>document.querySelector(`#report [data-section="${n}"]`);const mv=label=>[...sec(1).querySelectorAll('.metric')].find(x=>(x.querySelector('span')?.textContent||'').trim().toLowerCase()===label.toLowerCase())?.querySelector('b')?.textContent||'';const sources=[...sec(2).querySelectorAll('.v361-source')].map(x=>x.textContent.trim()),payoffs=[...sec(6).querySelectorAll('.note .time')].map(x=>x.textContent.trim());return{pct:document.querySelector('#progressPct')?.textContent,state:document.querySelector('#progressState')?.textContent,error:document.querySelector('#analyseError')?.textContent||'',sections:[...document.querySelectorAll('#report [data-section]')].map(x=>Number(x.dataset.section)),niche:mv('Niche'),subniche:mv('Subniche'),summary:sec(2)?.innerText||'',takeaways:sec(3)?.innerText||'',payoffText:sec(6)?.innerText||'',payoffs,sources,labels:[...document.querySelectorAll('#report .section-head .eyebrow')].map(x=>x.textContent),visual:sec(9)?.innerText||'',motion:sec(10)?.innerText||'',audio:sec(11)?.innerText||'',package:sec(12)?.innerText||'',remake:sec(14)?.innerText||'',review:sec(16)?.innerText||''}});
 assert.equal(result.pct,'100%');assert.notEqual(result.state,'STOPPED',result.error);assert.deepEqual(result.sections,Array.from({length:17},(_,i)=>i+1));assert.match(result.niche,/YouTube|Creator Economy/i);assert(!/gta6/i.test(result.niche+' '+result.subniche));assert(result.summary.includes('SOURCE-SYNTHESIZED WATCH REPLACEMENT')||result.summary.includes('ON-DEVICE MODEL SYNTHESIS'));assert(!result.summary.includes('Content · Now · Understand'));assert(result.sources.length>=7||result.summary.includes('ON-DEVICE MODEL SYNTHESIS'));assert.equal(new Set(result.sources).size,result.sources.length);assert(result.takeaways.length>250);assert(!result.payoffs.includes('0:00'));assert.equal(new Set(result.payoffs).size,result.payoffs.length);assert(result.labels.every(x=>!x.includes('MONDAY BRIEF')));assert(/STORYBOARD|visual frame source|frames measured|unavailable/i.test(result.visual));assert(/SAMPLED|VISION|not measured|unavailable/i.test(result.motion));assert(/WPM/i.test(result.audio));assert(result.package.length>250&&/title|thumbnail|packag|promise/i.test(result.package));assert(result.remake.length>80);assert(/cross-check|integrity|review/i.test(result.review));
 assert(requests.some(x=>x.action==='analyze'&&x.status===200));assert(requests.some(x=>x.action==='media'&&[200,502].includes(x.status)));assert(!requests.some(x=>String(x.action||'').includes('research-stage')));assert(!requests.some(x=>String(x.path||'').includes('ytintel-v093')));
 await page.screenshot({path:'ytintel-live-proof/desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(350);const mobile=await page.evaluate(()=>({viewport:innerWidth,width:document.documentElement.scrollWidth,dock:[...document.querySelectorAll('[data-dock]')].filter(x=>getComputedStyle(x).display!=='none').map(x=>x.dataset.dock)}));assert(mobile.width<=mobile.viewport+2,`mobile overflow ${mobile.width}`);assert.deepEqual(mobile.dock,['analyse','compare','vault','competitors']);await page.screenshot({path:'ytintel-live-proof/mobile.png',fullPage:true});assert.equal(errors.length,0,errors.join('\n'));
 const receipt={pass:true,version:boot.version,scripts:boot.scripts,signed_out_creator_dna_hidden:boot.creator==='none'&&!boot.dna,sections:result.sections.length,niche:result.niche,subniche:result.subniche,summary_source_receipts:result.sources.length,payoff_times:result.payoffs,monday_brief_visible:result.labels.some(x=>x.includes('MONDAY BRIEF')),packaging_chars:result.package.length,mobile,requests,errors};await writeFile('ytintel-live-proof/receipt.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt,null,2));
}finally{await browser.close()}
