import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';

await mkdir('ytintel-live-proof',{recursive:true});
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});
await context.addInitScript(()=>{try{localStorage.setItem('ytintel-v350-profile',JSON.stringify({niche:'GTA 6',subniche:'GTA 6 money/news',channel:'@ytinteltest',audience:'GTA 6 players',competitors:'Blake Ryan',brand:'Proof over hype. No guru language. Use only provable claims.',complete:true}))}catch{}});
const page=await context.newPage();page.setDefaultTimeout(60000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
const url='https://mitchloxton.github.io/pinnacle-navigator/ytintel/latest/?qa=v0375-analyse-'+Date.now();
try{
 await page.goto(url,{waitUntil:'domcontentloaded',timeout:60000});
 await page.waitForFunction(()=>window.YTINTEL_VERSION==='0.37.5'&&window.YTIntelSingleAnalyse?.version==='0.37.3'&&window.YTIntelCreatorAssets?.version==='0.37.4'&&window.YTIntelCreatorAssetsCloud?.version==='0.37.5'&&!document.querySelector('#boot')&&!document.querySelector('#app')?.hidden,null,{timeout:120000});
 const shell=await page.evaluate(()=>({version:window.YTINTEL_VERSION,nav:[...document.querySelectorAll('[data-tab]')].filter(x=>getComputedStyle(x).display!=='none').map(x=>x.dataset.tab),dock:[...document.querySelectorAll('[data-dock]')].filter(x=>getComputedStyle(x).display!=='none').map(x=>x.dataset.dock),compare:!!document.querySelector('#compare,[data-tab="compare"],[data-dock="compare"]'),creatorInAnalyse:!!document.querySelector('#analyse #creatorCard'),creatorInVault:!!document.querySelector('#vault #creatorCard'),progressClass:document.querySelector('#progressCard')?.className||'',activity:!!document.querySelector('#v373-activity'),activityOpen:document.querySelector('#v373-activity')?.open||false,activityInsideProgress:!!document.querySelector('#progressCard #v373-activity'),assetsInVault:!!document.querySelector('#vault #v374-assets-root'),cloudAssetsLoaded:window.YTIntelCreatorAssetsCloud?.version==='0.37.5'}));
 assert.equal(shell.version,'0.37.5');assert.equal(shell.compare,false,'Compare must remain removed for the single-video focus');assert.deepEqual(shell.nav,['analyse','vault','competitors']);assert.deepEqual(shell.dock,['analyse','vault','competitors']);assert.equal(shell.creatorInAnalyse,false,'Creator DNA must not live in Analyse');assert.equal(shell.creatorInVault,true,'Creator DNA should live outside Analyse');assert.match(shell.progressClass,/v373-popup/);assert(shell.activity&&!shell.activityOpen&&!shell.activityInsideProgress,'Activity must be folded outside the one-bar popup');assert(shell.assetsInVault,'Creator Assets must live in Vault, not Analyse');assert(shell.cloudAssetsLoaded,'Creator Assets cloud module must load');
 await page.locator('#videoUrl').fill('https://www.youtube.com/watch?v=GzhT10i4vag');await page.locator('#analyseBtn').click();
 await page.waitForFunction(()=>document.querySelector('#report')?.dataset.v363Premium==='1',null,{timeout:360000});
 await page.waitForFunction(()=>window.__YTINTEL_SINGLE_ANALYSE?.version==='0.37.3',null,{timeout:60000});
 await page.waitForFunction(()=>document.querySelector('#progressPct')?.textContent==='100%'||document.querySelector('#progressState')?.textContent==='STOPPED',null,{timeout:180000});
 await page.waitForTimeout(900);
 const result=await page.evaluate(()=>{const sec=n=>document.querySelector(`#report [data-section="${n}"]`),txt=n=>sec(n)?.innerText||'',sections=[...document.querySelectorAll('#report [data-section]')];return{count:sections.length,strip:txt(1),summary:txt(2),takeaways:txt(3),rehooks:txt(5),payoffs:txt(6),replay:txt(7),visual:txt(9),motion:txt(10),audio:txt(11),packaging:txt(12),channel:txt(15),make:txt(16),vaultHidden:getComputedStyle(sec(17)).display==='none',exportText:txt(18),takeawayRows:sec(3)?.querySelectorAll('.v373-takeaway').length||0,packageBank:!!document.querySelector('#v373-package'),blueprintNote:!!document.querySelector('#v373-blueprint'),assetBridge:!!document.querySelector('#v374-asset-bridge'),assetBridgeText:document.querySelector('#v374-asset-bridge')?.innerText||'',exportButtons:[...sec(18)?.querySelectorAll('button')||[]].map(x=>x.textContent.trim()),markdown:window.__YTINTEL_FULL_MARKDOWN||'',pct:document.querySelector('#progressPct')?.textContent||'',state:document.querySelector('#progressState')?.textContent||'',compare:!!document.querySelector('#compare,[data-tab="compare"],[data-dock="compare"]')};});
 assert.equal(result.count,18);assert.equal(result.compare,false);assert.notEqual(result.state,'STOPPED');assert.equal(result.pct,'100%');assert(result.vaultHidden,'Vault entry must be hidden from Analyse');assert(/Niche\s+YouTube \/ Creator Business/i.test(result.strip),`source niche not repaired: ${result.strip}`);assert(!/Niche\s+GTA 6/i.test(result.strip),'Creator DNA leaked into source niche');assert(/1\. The short version/i.test(result.summary));for(const x of ['What the video is','How it is built','What it actually shows/proves','How it is doing','What is worth taking'])assert(result.summary.includes(x),`summary missing ${x}`);assert(!/The video develops the promise/i.test(result.summary),'generic summary slop survived');assert(result.takeawayRows>=5,`expected >=5 takeaways, got ${result.takeawayRows}`);assert(!/No strong deterministic takeaways/i.test(result.takeaways));assert(/attention resets detected|No defensible attention resets/i.test(result.rehooks));assert(/First payoff|No source-backed payoff/i.test(result.payoffs));assert(/Replay curve available|No public Most Replayed curve|REAL PUBLIC MOST REPLAYED/i.test(result.replay));assert(/storyboard|frame|visual/i.test(result.visual));assert(/motion|frame-pair|visual-change|change/i.test(result.motion));assert(/audio|waveform|WPM/i.test(result.audio));assert(result.packageBank&&/PACKAGE BANK/i.test(result.packaging)&&/Pattern-mine filing/i.test(result.packaging));assert(!/\bSubscribers\s+0\b/i.test(result.channel),'channel context still displays subscriber zero');assert(result.blueprintNote&&/build sheet/i.test(result.make)&&/Direction 1/i.test(result.make)&&/Title variants/i.test(result.make)&&/Exact hook direction/i.test(result.make)&&/Beat sheet/i.test(result.make)&&/Thumbnail composition/i.test(result.make));assert(result.assetBridge&&/Creator footage supply/i.test(result.assetBridgeText),'Make It Yours must bridge into the creator footage workspace');assert(result.exportButtons.includes('Copy full analysis Markdown')&&result.exportButtons.includes('Download Markdown'));assert(result.markdown.startsWith('# YTIntel Analysis —'));assert(!/The vault entry/i.test(result.markdown));assert.equal(errors.length,0,errors.join('\n'));
 await page.screenshot({path:'ytintel-live-proof/v375-analyse-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);const mobile=await page.evaluate(()=>({viewport:innerWidth,width:document.documentElement.scrollWidth,dock:[...document.querySelectorAll('[data-dock]')].filter(x=>getComputedStyle(x).display!=='none').map(x=>x.dataset.dock)}));assert(mobile.width<=mobile.viewport+2,`mobile overflow ${mobile.width}`);assert.deepEqual(mobile.dock,['analyse','vault','competitors']);await writeFile('ytintel-live-proof/v375-analyse-receipt.json',JSON.stringify({pass:true,url,result,mobile,errors},null,2));console.log('V375_ANALYSE_PASS',JSON.stringify({pass:true,pct:result.pct,takeaways:result.takeawayRows,packageBank:result.packageBank,creatorAssetsBridge:result.assetBridge,cloudAssets:shell.cloudAssetsLoaded,compareRemoved:!result.compare,mobile,errors},null,2));
}finally{await browser.close()}
