import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
await mkdir('ytintel-live-proof',{recursive:true});
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1280,height:900},serviceWorkers:'block'});
const page=await context.newPage();
const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/ytintel-v0|api\.openai\.com/i.test(r.url()))requests.push(r.url())});
try{
  const url=`https://mitchloxton.github.io/pinnacle-navigator/ytintel/latest/?qa=v390-live-${Date.now()}`;
  await page.goto(url,{waitUntil:'domcontentloaded',timeout:45000});
  await page.waitForFunction(()=>window.YTIntelStableShell?.coreReady===true&&window.YTIntelStableShell?.intelligenceReady===true,null,{timeout:45000});
  await page.waitForTimeout(500);
  const start=await page.evaluate(()=>({version:document.querySelector('#version')?.textContent,scripts:document.scripts.length,core:document.documentElement.dataset.ytintelCore,shell:document.documentElement.dataset.ytintelShell,wpmGuard:!!window.YTIntelWpmGuard}));
  assert.equal(start.version,'v0.39.0');assert.equal(start.scripts,1);assert.equal(start.core,'ready');assert.equal(start.shell,'stable');assert.equal(start.wpmGuard,true);
  const select=async name=>{await page.locator(`[data-tab="${name}"]`).click();await page.waitForFunction(n=>{const x=document.getElementById(n);return x&&x.classList.contains('active')&&!x.hidden&&getComputedStyle(x).display!=='none'},name)};
  await select('competitors');await page.locator('#competitorInput').fill('@YTIntelLiveSmoke');await page.locator('#addCompetitor').click();assert((await page.locator('#competitorList').innerText()).includes('@YTIntelLiveSmoke'));
  await select('vault');await page.locator('#creator_niche').fill('YouTube creator education');await page.locator('#creator_subniche').fill('AI content systems');await page.locator('#creator_audience').fill('YouTube creators');await page.locator('#creator_brand').fill('Evidence first. Never copy source wording.');await page.locator('#saveCreator').click();await page.waitForFunction(()=>/Saved locally/i.test(document.querySelector('#creatorSaved')?.textContent||''));
  await select('analyse');await page.setViewportSize({width:390,height:844});for(const name of ['competitors','vault','analyse']){await page.locator(`[data-dock="${name}"]`).click();await page.waitForFunction(n=>document.getElementById(n)?.classList.contains('active'),name)}
  const mobile=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth}));assert(mobile.scroll<=mobile.viewport+1,`mobile overflow ${mobile.scroll}>${mobile.viewport}`);
  await page.locator('#videoUrl').fill('https://www.youtube.com/watch?v=GzhT10i4vag');await page.locator('#analyseBtn').click();await page.waitForFunction(()=>!document.querySelector('#progressCard')?.classList.contains('hidden'),null,{timeout:10000});
  await page.locator('[data-dock="vault"]').click();await page.waitForFunction(()=>document.querySelector('#vault')?.classList.contains('active'));await page.locator('[data-dock="analyse"]').click();
  await page.waitForFunction(()=>document.querySelectorAll('#report > .section').length>=17||(document.querySelector('#analyseError')?.textContent||'').trim().length>0,null,{timeout:210000});
  await page.waitForFunction(()=>document.documentElement.dataset.ytintelIntelligence==='v390'||(document.querySelector('#analyseError')?.textContent||'').trim().length>0,null,{timeout:15000});
  const result=await page.evaluate(()=>({sections:document.querySelectorAll('#report > .section').length,error:(document.querySelector('#analyseError')?.textContent||'').trim(),pct:document.querySelector('#progressPct')?.textContent||'',buttonDisabled:document.querySelector('#analyseBtn')?.disabled,version:document.querySelector('#version')?.textContent,active:document.querySelector('.view.active')?.id,intelligence:document.documentElement.dataset.ytintelIntelligence,summary:document.querySelector('#report > .section[data-section="2"]')?.innerText||'',takeaways:document.querySelector('#report > .section[data-section="3"]')?.innerText||'',audio:document.querySelector('#report > .section[data-section="11"]')?.innerText||'',remake:document.querySelector('#report > .section[data-section="14"]')?.innerText||'',review:document.querySelector('#report > .section[data-section="16"]')?.innerText||'',wpm:window.__YTINTEL_SOURCE_REPORT?.pacing?.video_words_per_minute??null,totalWords:window.__YTINTEL_SOURCE_REPORT?.pacing?.total_words??null,rawWpm:window.__YTINTEL_SOURCE_REPORT?.pacing?.raw_reported_words_per_minute??null}));
  assert.equal(result.error,'',result.error);assert(result.sections>=17,`expected 17 sections, got ${result.sections}`);assert.equal(result.pct,'100%');assert.equal(result.buttonDisabled,false);assert.equal(result.version,'v0.39.0');assert.equal(result.active,'analyse');assert.equal(result.intelligence,'v390');assert.match(result.summary,/INTELLIGENCE PASS/i);assert.match(result.summary,/Receipt:/i);assert.match(result.takeaways,/(ACTIONABLE TAKEAWAYS|FACT \/ LIST VIDEO MODE)/i);assert.match(result.takeaways,/Receipt:/i);
  assert(Number.isFinite(Number(result.wpm))&&Number(result.wpm)>=80&&Number(result.wpm)<=330,`implausible corrected WPM ${result.wpm}; raw ${result.rawWpm}`);assert(Number(result.totalWords)>500,`deduped words too low: ${result.totalWords}`);assert.match(result.audio,new RegExp(String(result.wpm).replace('.','\\.')));
  assert.match(result.remake,/CREATOR-DNA BLUEPRINT/i);assert.match(result.remake,/AI content systems/i);assert.match(result.review,/INDEPENDENT DETERMINISTIC CROSS-CHECK/i);assert(!/692\.7 WPM/.test(result.review),'broken historical WPM leaked into review');assert.deepEqual(errors,[],errors.join(' | '));assert(!requests.some(x=>/ytintel-v093|api\.openai\.com/i.test(x)),`paid/model route called: ${requests.join(', ')}`);
  await page.screenshot({path:'ytintel-live-proof/v390-mobile.png',fullPage:true});const receipt={pass:true,url,start,result:{...result,summary:result.summary.slice(0,900),takeaways:result.takeaways.slice(0,900),remake:result.remake.slice(0,900),review:result.review.slice(0,900)},mobile,errors,requests:requests.map(x=>x.replace(/\?.*$/,'')),checked_at:new Date().toISOString()};await writeFile('ytintel-live-proof/v390-receipt.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt,null,2));
}finally{await browser.close()}
