import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
await mkdir('ytintel-live-proof',{recursive:true});
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});
await context.addInitScript(()=>{try{localStorage.setItem('ytintel-v350-profile',JSON.stringify({niche:'GTA 6',subniche:'GTA 6 news + proof-led build in public',channel:'@ytinteltest',audience:'GTA 6 players',competitors:'@BlakeRyanUnscripted',brand:'Proof over hype. No guru promises. Never copy source wording.',complete:true}));localStorage.setItem('ytintel-v340-creator',JSON.stringify({niche:'GTA 6',subniche:'GTA 6 news + proof-led build in public',audience:'GTA 6 players',brand:'Proof over hype. No guru promises. Never copy source wording.'}))}catch{}});
const page=await context.newPage(),errors=[],requests=[];page.setDefaultTimeout(60000);
page.on('pageerror',e=>errors.push(e.message));
page.on('response',r=>{try{const u=new URL(r.url());if(u.hostname.endsWith('supabase.co'))requests.push({path:u.pathname,action:u.searchParams.get('action'),status:r.status()})}catch{}});
const url='https://mitchloxton.github.io/pinnacle-navigator/ytintel/latest/?qa=v037-live-'+Date.now();
let heartbeat=null;
try{
 await page.goto(url,{waitUntil:'domcontentloaded',timeout:60000});
 await page.waitForFunction(()=>window.YTINTEL_VERSION==='0.37.0'&&!document.querySelector('#boot')&&!document.querySelector('#app')?.hidden,null,{timeout:120000});
 const boot=await page.evaluate(()=>({version:window.YTINTEL_VERSION,visible:document.querySelector('#version')?.textContent,scripts:[...document.scripts].filter(x=>x.src).map(x=>new URL(x.src).pathname.split('/').pop()),nav:[...document.querySelectorAll('[data-tab]')].filter(x=>getComputedStyle(x).display!=='none').map(x=>x.dataset.tab),creator:getComputedStyle(document.querySelector('#creatorCard')).display,dna:!!document.querySelector('#v350-profile-overlay,#v361-dna-overlay'),signin:!!document.querySelector('#v361-signin-dna'),hero:document.querySelector('#analyse .hero')?.innerText||''}));
 assert.equal(boot.version,'0.37.0');assert.equal(boot.visible,'v0.37.0');assert.deepEqual(boot.scripts,['v360-entry.js']);assert.deepEqual(boot.nav,['analyse','compare','vault','competitors']);assert.equal(boot.creator,'none');assert.equal(boot.dna,false);assert.equal(boot.signin,true);assert.match(boot.hero,/PREMIUM VIDEO ANALYSIS/);
 await page.locator('#videoUrl').fill('https://www.youtube.com/watch?v=GzhT10i4vag');await page.locator('#analyseBtn').click();
 heartbeat=setInterval(async()=>{try{console.log('LIVE_HEARTBEAT',JSON.stringify(await page.evaluate(()=>({pct:document.querySelector('#progressPct')?.textContent||'',state:document.querySelector('#progressState')?.textContent||'',msg:document.querySelector('#progressMsg')?.textContent||'',sections:document.querySelectorAll('#report [data-section]').length,premium:document.querySelector('#report')?.dataset.v363Premium||'',error:document.querySelector('#analyseError')?.textContent||''}))))}catch{}},20000);
 await page.waitForFunction(()=>document.querySelector('#progressPct')?.textContent==='100%'||document.querySelector('#progressState')?.textContent==='STOPPED',null,{timeout:360000});
 await page.waitForFunction(()=>document.querySelector('#report')?.dataset.v363Premium==='1',null,{timeout:45000});
 await page.waitForFunction(()=>document.querySelectorAll('#v363-transcript .v363-transcript-line').length>0||window.__YTINTEL_TRANSCRIPT_RECEIPT?.source==='unavailable',null,{timeout:45000});
 await page.waitForFunction(()=>!!document.querySelector('#v364-title-surfaces'),null,{timeout:30000});
 await page.waitForFunction(()=>!!document.querySelector('#v364-channel-stats'),null,{timeout:45000});
 await page.waitForTimeout(250);if(heartbeat){clearInterval(heartbeat);heartbeat=null}
 const result=await page.evaluate(()=>{const secs=[...document.querySelectorAll('#report [data-section]')],sec=n=>document.querySelector(`#report [data-section="${n}"]`),w=t=>(String(t||'').match(/[A-Za-z0-9$%’'_-]+/g)||[]).length,mv=label=>[...sec(1).querySelectorAll('.metric')].find(x=>(x.querySelector('span')?.textContent||'').trim().toLowerCase()===label.toLowerCase())?.querySelector('b')?.textContent||'';return{pct:document.querySelector('#progressPct')?.textContent,state:document.querySelector('#progressState')?.textContent,error:document.querySelector('#analyseError')?.textContent||'',sections:secs.map(x=>Number(x.dataset.section)),titles:secs.map(x=>x.querySelector('h2')?.textContent.trim()),words:Object.fromEntries(secs.map(x=>[x.dataset.section,w(x.innerText)])),niche:mv('Niche'),subniche:mv('Subniche'),subs:mv('Subscribers'),summary:sec(2)?.innerText||'',hook:sec(4)?.innerText||'',replay:sec(7)?.innerText||'',visual:sec(9)?.innerText||'',motion:sec(10)?.innerText||'',audio:sec(11)?.innerText||'',packaging:sec(12)?.innerText||'',numbers:sec(13)?.innerText||'',claims:sec(14)?.innerText||'',claimRows:sec(14)?.querySelectorAll('tbody tr').length||0,channel:sec(15)?.innerText||'',make:sec(16)?.innerText||'',vault:sec(17)?.innerText||'',export:sec(18)?.innerText||'',transcriptRows:document.querySelectorAll('#v363-transcript .v363-transcript-line').length||0,transcriptReceipt:window.__YTINTEL_TRANSCRIPT_RECEIPT||null,titleSurface:document.querySelector('#v364-title-surfaces')?.innerText||'',channelStats:document.querySelector('#v364-channel-stats')?.innerText||'',premium:window.__YTINTEL_PREMIUM_BRIEF||null,bodyText:document.body.innerText||''}});
 const expected=['The strip','The summary — so you never watch it','Key takeaways','The hook','The re-hooks','The payoffs','Most Replayed','The structure map','Visuals — key frame by key frame','Motion graphics','Audio','Packaging','The numbers table','The claims ledger','Channel context','Make it yours','The vault entry','Export'];
 assert.equal(result.pct,'100%');assert.notEqual(result.state,'STOPPED',result.error);assert.deepEqual(result.sections,Array.from({length:18},(_,i)=>i+1));assert.deepEqual(result.titles,expected);assert.equal(result.premium?.section_count,18);for(const s of ['What the video is','How it is built','How it is doing','What appears to matter','What is worth taking'])assert(result.summary.includes(s));assert(result.words['2']>=260);assert(result.words['4']>=220);assert(result.words['8']>=260);assert(result.claimRows>=4);assert(/VERIFIED|THEIR CLAIM|WRONG/.test(result.claims));assert(/The channel's real recent hits/.test(result.channel));assert(/Cross-channel validation sample/.test(result.channel));assert(/The business under the video/.test(result.channel));assert(/Steal this/.test(result.make)&&/Do not copy that/.test(result.make)&&/Measure after publishing/.test(result.make));assert(/WPM/.test(result.numbers));assert(/title|thumbnail|promise/i.test(result.packaging));assert(/Most Replayed|replay/i.test(result.replay));assert(/storyboard|frame|visual|unavailable/i.test(result.visual));assert(/motion|transition|sampled|unavailable/i.test(result.motion));assert(/WPM|music|audio|unavailable/i.test(result.audio));assert(/Hook keywords/.test(result.vault)&&/Title keywords/.test(result.vault));assert(/Download Markdown/.test(result.export)&&/PDF/.test(result.export));assert(result.transcriptRows>0,`transcript appendix unavailable: ${JSON.stringify(result.transcriptReceipt)}`);assert(/TITLE SURFACE CHECK/.test(result.titleSurface));assert(/[1-9]/.test(result.subs)&&result.subs!=='0',`subscriber count unresolved: ${result.subs}; ${result.channelStats}`);assert(/subscribers/i.test(result.channelStats));assert(!/NaN%|undefined undefined/.test(result.bodyText));
 assert(requests.some(x=>x.action==='analyze'&&x.status===200));assert(requests.some(x=>x.action==='media'&&[200,502].includes(x.status)));assert(requests.some(x=>x.action==='discover'&&x.status===200));assert(requests.some(x=>x.action==='channel-stats'&&x.status===200));assert(requests.some(x=>x.action==='channel-public'&&x.status===200));assert(!requests.some(x=>String(x.action||'').includes('research-stage')));assert(!requests.some(x=>String(x.path||'').includes('ytintel-v093')&&x.action!=='channel-public'));
 await page.screenshot({path:'ytintel-live-proof/desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(500);const mobile=await page.evaluate(()=>({viewport:innerWidth,width:document.documentElement.scrollWidth,dock:[...document.querySelectorAll('[data-dock]')].filter(x=>getComputedStyle(x).display!=='none').map(x=>x.dataset.dock)}));assert(mobile.width<=mobile.viewport+2,`mobile overflow ${mobile.width}`);assert.deepEqual(mobile.dock,['analyse','compare','vault','competitors']);await page.screenshot({path:'ytintel-live-proof/mobile.png',fullPage:true});assert.equal(errors.length,0,errors.join('\n'));
 const receipt={pass:true,release:'0.37.0',deployed_url:url,sections:result.sections.length,section_titles:result.titles,word_counts:result.words,niche:result.niche,subniche:result.subniche,subscribers:result.subs,claims_rows:result.claimRows,title_surface_check:true,transcript_rows:result.transcriptRows,mobile,requests,errors,limitations:['Public web factual verification beyond the source engine is not fabricated.','Most Replayed is real only when YouTube exposes it.','Storyboard imagery is sampled seek-bar evidence, not every encoded frame.','On-device multimodal AI is optional and was not assumed by this headless production proof.']};await writeFile('ytintel-live-proof/receipt.json',JSON.stringify(receipt,null,2));console.log('V370_LIVE_PASS',JSON.stringify(receipt,null,2));
}finally{if(heartbeat)clearInterval(heartbeat);await browser.close()}
