import {createServer} from 'node:http';import {readFile,mkdir,writeFile} from 'node:fs/promises';import {resolve,extname} from 'node:path';import {chromium} from 'playwright';import assert from 'node:assert/strict';
const root=process.cwd(),proof='ytintel-brief-proof';await mkdir(proof,{recursive:true});
const server=createServer(async(req,res)=>{try{let p=resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!p.startsWith(root+'/'))throw Error();if(p.endsWith('/latest/'))p+='index.html';res.setHeader('Content-Type',({'.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.html':'text/html','.json':'application/json','.svg':'image/svg+xml'})[extname(p)]||'text/plain');res.end(await readFile(p));}catch{res.statusCode=404;res.end('not found');}});await new Promise(r=>server.listen(8767,'127.0.0.1',r));
const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname==='127.0.0.1'||u.hostname.includes('jsdelivr'))return route.continue();if(u.hostname.endsWith('supabase.co'))return route.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,configured:true,version:'0.33.0',discovery:{videos:[]}})});return route.fulfill({status:404,body:'Fixture has no external media'});});
 await page.goto('http://127.0.0.1:8767/ytintel/latest/index.html',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.YTIntelBriefWorkspace&&window.YTIntelBrief&&document.documentElement.dataset.yt300CoreAnalysis==='1');
 await page.locator('#yt330Profile summary').click();await page.locator('[data-profile="niche"]').fill('Gaming');await page.locator('[data-profile="subniche"]').fill('Fixture only');await page.locator('[data-profile="channel_name"]').fill('Test channel');await page.locator('[data-profile="brand_rules"]').fill('No invented numbers. Evidence before hype.');await page.locator('#yt330ProfileSave').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('ytintel-v300-profile')||'{}').niche==='Gaming');
 await page.evaluate(()=>localStorage.setItem('ytintel-v300-analysis-vault',JSON.stringify([1,2,3].map(i=>({id:'fixture'+i,video_id:'QAfixture0'+i,title:'Synthetic saved analysis '+i,channel:'Fixture channel',niche:'Gaming',subniche:'Fixture only',pulled_at:'2026-09-08T00:00:00Z',report:{video:{view_count:100*i,channel_follower_count:10,like_count:5,comment_count:1,outlier:{multiple:i,channel_median_views:100}}},synthesis:{hook:{exact_quote:'Fixture hook '+i,why:'An observable comparison'},benchmark_mechanics:{title_promise_verdict:'Fixture promise delivered'}},vault_entry:{script_style:'Test style',title_keywords:['shared','keyword'+i],hook_keywords:['test'],motion_graphics:[]}})))));
 await page.locator('#mobileDock [data-dock="history"]').click();await page.waitForSelector('.yt330-folder');await page.locator('#yt330GroupButton').click();await page.waitForSelector('[data-compare="0"]');await page.locator('[data-compare="0"]').check();await page.locator('[data-compare="1"]').check();await page.locator('#yt330CompareRun').click();await page.waitForSelector('.yt330-matrix table');const text=await page.locator('.yt330-matrix').innerText();assert(text.includes('Fixture hook 1'));assert(text.includes('Fixture hook 2'));assert.equal(await page.locator('.yt330-matrix img').count(),2);assert.deepEqual(errors,[]);const dims=await page.evaluate(()=>({viewport:innerWidth,width:document.documentElement.scrollWidth}));assert(dims.width<=dims.viewport+2);await page.screenshot({path:proof+'/group-mobile.png'});await writeFile(proof+'/workspace.json',JSON.stringify({pass:true,provider:'Synthetic saved rows; no model claim',profile_saved:true,group_compared:2,thumbnails:2,errors,dims},null,2));
}catch(e){await page.screenshot({path:proof+'/failure.png'}).catch(()=>{});await writeFile(proof+'/failure.json',JSON.stringify({error:e.message,errors}));throw e;}finally{await browser.close();server.close();}
