(()=>{
if(window.__goalOsGroceryV30)return;window.__goalOsGroceryV30=true;
try{
const css=`.shopgroups{display:grid;gap:10px}.shopgroup{border:1px solid var(--line);border-radius:16px;padding:11px;background:#0b100d}.shopgroup h3{font-size:12px;margin:0 0 7px;color:var(--lime)}.shopitem{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px 0;border-top:1px solid #1e2821}.shopitem:first-of-type{border-top:0}.shopitem button{width:28px;height:28px;border-radius:50%;border:1px solid #455248;background:#080d09;color:transparent;flex:0 0 auto}.shopitem.bought{opacity:.5}.shopitem.bought button{background:var(--lime);color:#11170d;border-color:var(--lime)}.shopname{font-size:11px;line-height:1.35}.shopqty{font-size:11px;font-weight:900;white-space:nowrap}.shopdays{font-size:11px;color:#d6dfd3;line-height:1.45;margin-top:5px}.foodactions{display:flex;gap:7px;flex-wrap:wrap}.foodactions .btn{flex:1}`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
const brand=document.querySelector('.brand');if(brand)brand.textContent='GOAL OS · V30 GYM + GROCERY';
const foodCard=[...document.querySelectorAll('.card')].find(x=>x.querySelector('.kick')?.textContent.includes('FOOD & MACROS'));
if(foodCard){const top=foodCard.querySelector('.foodTop');const open=[...top.querySelectorAll('button')].find(b=>b.textContent.trim()==='Open');if(open&&!document.getElementById('shop3Top')){const b=document.createElement('button');b.id='shop3Top';b.className='btn do';b.textContent='3-day shop';b.onclick=e=>{e.stopPropagation();openGrocery()};open.before(b)}}
const foodModal=document.getElementById('foodModal');if(foodModal&&!document.getElementById('shop3Food')){const rem=document.getElementById('remaining');const b=document.createElement('button');b.id='shop3Food';b.className='btn primary foodbtn';b.textContent='🛒 3-day grocery shopping list';b.onclick=openGrocery;rem.after(b)}
if(!document.getElementById('groceryModal'))document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="groceryModal" onclick="if(event.target===this)closeGrocery()"><div class="sheet"><div class="sheethead"><div><div class="kick">3-DAY GROCERY SHOP</div><h2 style="margin:3px 0">Buy this. Done.</h2><div class="shopdays" id="shopDays"></div></div><button class="btn" onclick="closeGrocery()">×</button></div><div class="notice"><b>Default choices:</b> chicken for mains, salmon on training-day dinners, lean beef on recovery dinner, potatoes for dinner carbs. This keeps the list exact and simple.</div><div class="shopgroups" id="shopGroups"></div><button class="btn foodbtn" onclick="clearShopChecks()">Clear shopping ticks</button></div></div>`);
if(!st.shopChecks)st.shopChecks={};
const SHOP={train:[['Protein','Eggs',3,'count'],['Protein','Chicken breast',200,'g'],['Protein','Salmon fillet',200,'g'],['Protein','Plant protein powder',30,'g'],['Carbs','Oats',100,'g'],['Carbs','Dry rice',110,'g'],['Carbs','Potatoes',400,'g'],['Carbs','Rice cakes',3,'count'],['Produce','Bananas',2,'count'],['Produce','Berries',150,'g'],['Produce','Other fruit (apple/orange)',1,'count'],['Produce','Mixed vegetables / salad',500,'g'],['Fats + extras','Fortified soy milk',300,'ml'],['Fats + extras','Olive oil',10,'g'],['Fats + extras','Peanut butter',20,'g']],recover:[['Protein','Eggs',3,'count'],['Protein','Chicken breast',200,'g'],['Protein','Lean beef',200,'g'],['Protein','Plant protein powder',30,'g'],['Protein','High-protein soy yogurt',250,'g'],['Carbs','Oats',90,'g'],['Carbs','Dry rice',90,'g'],['Carbs','Potatoes',400,'g'],['Produce','Berries',250,'g'],['Produce','Other fruit (apple/orange)',1,'count'],['Produce','Mixed vegetables / salad',500,'g'],['Fats + extras','Fortified soy milk',300,'ml'],['Fats + extras','Olive oil',10,'g'],['Fats + extras','Almonds',30,'g']],active:[['Protein','Eggs',4,'count'],['Protein','Chicken breast',200,'g'],['Protein','Lean protein for dinner',200,'g'],['Protein','Plant protein powder',30,'g'],['Protein','High-protein soy yogurt',250,'g'],['Carbs','Wholegrain bread',3,'slices'],['Carbs','Dry rice',110,'g'],['Carbs','Potatoes',400,'g'],['Produce','Avocado',0.5,'count'],['Produce','Other fruit',2,'count'],['Produce','Mixed vegetables / salad',500,'g'],['Fats + extras','Olive oil',10,'g'],['Fats + extras','Nuts',30,'g']]};
function typeFor(d){const n=days[d.getDay()];return ['Monday','Tuesday','Thursday','Friday'].includes(n)?'train':n==='Saturday'?'active':'recover'}
function data(){const out={},labels=[];for(let n=0;n<3;n++){const d=new Date();d.setDate(d.getDate()+n);const ty=typeFor(d);labels.push(d.toLocaleDateString(undefined,{weekday:'short',day:'numeric',month:'short'})+' · '+(ty==='train'?'Training':ty==='active'?'Active':'Recovery'));SHOP[ty].forEach(([cat,name,q,u])=>{const k=cat+'|'+name+'|'+u;(out[k]||(out[k]={cat,name,q:0,u})).q+=q})}return{items:Object.values(out),labels}}
function fmt(q,u){if(u==='g'&&q>=1000)return (q/1000).toFixed(q%1000?1:0)+' kg';if(u==='ml'&&q>=1000)return (q/1000).toFixed(q%1000?1:0)+' L';if(u==='count')return q===0.5?'½':Number.isInteger(q)?String(q):q.toFixed(1);return q+' '+u}
function id(x){return key()+'|'+x.cat+'|'+x.name}
window.openGrocery=()=>{document.getElementById('groceryModal').classList.add('open');renderGrocery()};
window.closeGrocery=()=>document.getElementById('groceryModal').classList.remove('open');
window.toggleShop=i=>{st.shopChecks[i]=!st.shopChecks[i];save();renderGrocery()};
window.clearShopChecks=()=>{const p=key()+'|';Object.keys(st.shopChecks).filter(k=>k.startsWith(p)).forEach(k=>delete st.shopChecks[k]);save();renderGrocery()};
window.renderGrocery=()=>{const g=data();document.getElementById('shopDays').innerHTML=g.labels.join('<br>');const cats=['Protein','Carbs','Produce','Fats + extras'];document.getElementById('shopGroups').innerHTML=cats.map(cat=>`<div class="shopgroup"><h3>${cat}</h3>${g.items.filter(x=>x.cat===cat).map(x=>{const i=id(x),b=!!st.shopChecks[i];return `<div class="shopitem ${b?'bought':''}"><button onclick="toggleShop('${i.replace(/'/g,"\\'")}')">✓</button><div class="shopname" style="flex:1">${x.name}</div><div class="shopqty">${fmt(x.q,x.u)}</div></div>`}).join('')}</div>`).join('')};
save();
}catch(e){console.error('Grocery patch failed',e)}
})();