(()=>{
'use strict';
if(window.__FOUNDER_WEEKLY_AI__)return;window.__FOUNDER_WEEKLY_AI__=true;
const SUPA='https://dkmacktcfhubsumwrydw.supabase.co';
const KEY='sb_publishable_VATM2AkVyl-yvxv28S2FXw_CqMpBr6q';
const PLAN_URL=`${SUPA}/functions/v1/navigator-v523-patch?action=plan`;
const db=window.supabase.createClient(SUPA,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
function toast(msg,tone=''){if(typeof window.FounderWeeklyToast==='function')return window.FounderWeeklyToast(msg,tone);let t=$('#fwAiToast');if(!t){t=document.createElement('div');t.id='fwAiToast';t.style.cssText='position:fixed;right:18px;bottom:18px;z-index:400;max-width:380px;padding:12px 14px;border-radius:13px;border:1px solid #344054;background:#10151d;color:#fff;font:850 11px Inter,system-ui;box-shadow:0 20px 60px rgba(0,0,0,.45);transition:.2s';document.body.appendChild(t)}t.textContent=msg;t.style.borderColor=tone==='bad'?'rgba(255,98,111,.5)':tone==='good'?'rgba(86,227,159,.45)':'#344054';t.style.opacity='1';clearTimeout(t._x);t._x=setTimeout(()=>t.style.opacity='0',3200)}
function setValue(el,val,event='input'){if(!el)return;el.value=String(val??'');el.dispatchEvent(new Event(event,{bubbles:true}))}
function rows(key){return $$(`[data-cp-title^="${key}:"]`)}
function resize(key,n){let guard=0;while(rows(key).length<n&&guard++<12)$(`[data-add="${key}"]`)?.click();guard=0;while(rows(key).length>n&&guard++<12){const rm=$$(`[data-cp-remove^="${key}:"]`).at(-1);if(!rm)break;rm.click()}}
function applyRows(key,xs){resize(key,xs.length);xs.forEach((x,i)=>{setValue($(`[data-cp-title="${key}:${i}"]`),x.title);setValue($(`[data-cp-weight="${key}:${i}"]`),x.weight);setValue($(`[data-cp-type="${key}:${i}"]`),x.checkpoint_type,'change');setValue($(`[data-cp-done="${key}:${i}"]`),x.definition_of_done);setValue($(`[data-cp-evidence="${key}:${i}"]`),x.evidence_required)})}
function injectStyles(){if($('#fwAiStyle'))return;const s=document.createElement('style');s.id='fwAiStyle';s.textContent=`.fw-ai-btn{position:relative;overflow:hidden;background:linear-gradient(135deg,#7d61ff,#ff4f78)!important;border-color:transparent!important;color:#fff!important;box-shadow:0 12px 34px rgba(125,97,255,.2)!important}.fw-ai-btn:before{content:'';position:absolute;inset:-2px auto -2px -50%;width:32%;transform:skewX(-22deg);background:linear-gradient(90deg,transparent,rgba(255,255,255,.18),transparent);animation:fwAiSweep 2.8s ease-in-out infinite}@keyframes fwAiSweep{0%,55%{left:-50%}100%{left:125%}}.fw-ai-note{margin-top:14px;padding:13px 14px;border:1px solid rgba(127,156,255,.2);border-radius:14px;background:linear-gradient(120deg,rgba(127,156,255,.06),rgba(255,79,120,.035));font-size:10px;line-height:1.55;color:#98a5b6}.fw-ai-note b{color:#e5eaff}.fw-ai-note ul{margin:8px 0 0;padding-left:18px}.fw-ai-thinking{opacity:.72;pointer-events:none}`;document.head.appendChild(s)}
async function requestPlan(){const btn=$('#aiPlanBtn');if(!btn)return;const goal=$('#teamGoal')?.value.trim()||'',result=$('#externalResult')?.value.trim()||'',mh=Number($('#mitchellHours')?.value||0),nh=Number($('#nookyHours')?.value||0);if(!mh||!nh)return toast('Add realistic hours for both founders first so the AI does not make a fantasy week.','bad');btn.disabled=true;btn.classList.add('fw-ai-thinking');const old=btn.textContent;btn.textContent='AI is building the week…';try{const g=await db.auth.getSession(),token=g.data?.session?.access_token;if(!token)throw Error('Sign in first.');const r=await fetch(PLAN_URL,{method:'POST',headers:{authorization:`Bearer ${token}`,apikey:KEY,'content-type':'application/json'},body:JSON.stringify({team_goal:goal,external_result_definition:result,mitchell_hours:mh,nooky_hours:nh,mitchell_notes:$('#mitchellQuest')?.value||'',nooky_notes:$('#nookyQuest')?.value||'',project_context:'Founder Weekly. Current product-development principle: perfect one core loop at a time, keep the weekly ship externally observable, and avoid feature sprawl.'})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw Error(d.error||`AI planner ${r.status}`);const p=d.plan;setValue($('#teamGoal'),p.team_goal);setValue($('#externalResult'),p.external_result_definition);setValue($('#mitchellQuest'),p.mitchell_main_quest);setValue($('#nookyQuest'),p.nooky_main_quest);applyRows('mitchell',p.mitchell_checkpoints||[]);applyRows('nooky',p.nooky_checkpoints||[]);renderNote(p,d.model);toast('AI proposal ready. Review it together, edit anything you disagree with, then Save → both Approve → LOCK WEEK.','good')}catch(e){toast(e?.message||String(e),'bad')}finally{btn.disabled=false;btn.classList.remove('fw-ai-thinking');btn.textContent=old}}
function renderNote(p,model){let n=$('#fwAiNote');if(!n){n=document.createElement('div');n.id='fwAiNote';n.className='fw-ai-note';const target=$('.approval-box');target?.insertAdjacentElement('beforebegin',n)}if(!n)return;n.innerHTML=`<b>AI PROPOSAL · ${String(model||'GPT-5.6 Sol')}</b><div>${esc(p.reasoning_summary||'')}</div>${Array.isArray(p.review_plan)&&p.review_plan.length?`<ul>${p.review_plan.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}${p.scope_guardrail?`<div style="margin-top:8px"><b>Scope guardrail:</b> ${esc(p.scope_guardrail)}</div>`:''}<div style="margin-top:8px;color:#728096">This is only a proposal. Nothing counts until you both approve the saved plan and lock the week.</div>`}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function inject(){injectStyles();const actions=$('.setup-actions');if(!actions||$('#aiPlanBtn'))return;const b=document.createElement('button');b.id='aiPlanBtn';b.type='button';b.className='btn fw-ai-btn';b.textContent='✦ AI propose the week';b.onclick=requestPlan;actions.insertBefore(b,actions.firstChild);const hint=document.createElement('div');hint.className='fw-ai-note';hint.id='fwAiHint';hint.innerHTML='<b>Fast setup:</b> enter realistic hours + the result you want, then let AI propose 5–8 auditable checkpoints and weights for each founder. You still review and approve every percentage before LOCK WEEK.';actions.insertAdjacentElement('beforebegin',hint)}
let queued=false;const obs=new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;inject()})});obs.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject,{once:true});else inject();
})();
