const API='https://dkmacktcfhubsumwrydw.supabase.co/functions/v1/ytintel-v09';
const HEADERS={'content-type':'application/json','x-ytintel-client':'web-v09'};
const STORE='ytintel-v09-history';
let lastReport=null,selectedNiche=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=x=>x==null||x===''?'-':Number(x).toLocaleString(undefined,{maximumFractionDigits:2});
const compact=x=>!Number.isFinite(Number(x))?'-':new Intl.NumberFormat(undefined,{notation:'compact',maximumFractionDigits:1}).format(Number(x));
const time=x=>{x=Math.max(0,Math.round(Number(x)||0));const h=Math.floor(x/3600),m=Math.floor((x%3600)/60),s=x%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`};
const date=x=>{if(!x)return'-';const d=new Date(x);return Number.isNaN(d.valueOf())?String(x):d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})};
const med=xs=>{const a=xs.map(Number).filter(Number.isFinite).sort((a,b)=>a-b);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
const metric=(label,value,cls='')=>`<div class="metric"><span>${esc(label)}</span><b class="${cls}">${esc(value)}</b></div>`;
const list=(xs,empty='No strong evidence detected.')=>xs?.length?`<ul class="list">${xs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:`<p class="muted">${esc(empty)}</p>`;
async function api(action,body={}){const r=await fetch(`${API}?action=${encodeURIComponent(action)}`,{method:'POST',headers:HEADERS,body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw Error(d.error||`HTTP ${r.status}`);return d}
function tab(name){$$('[data-tab]').forEach(b=>b.classList.toggle('on',b.dataset.tab===name));$$('.view').forEach(v=>v.classList.toggle('active',v.id===name));if(name==='history'&&typeof renderHistory==='function')renderHistory();if(name==='visuals'&&typeof renderVisuals==='function')renderVisuals()}
$$('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
fetch(`${API}?action=health`).then(r=>r.json()).then(d=>$('#status').textContent=`v${d.version} ready`).catch(()=>$('#status').textContent='engine online');
function showErr(id,e){const x=$(id);if(!x)return;x.textContent=e?.message||String(e);x.classList.add('show')}function clearErr(id){const x=$(id);if(!x)return;x.classList.remove('show');x.textContent=''}

$('#analyseForm').onsubmit=async e=>{e.preventDefault();clearErr('#error');$('#report').innerHTML='';$('#loading').classList.add('show');try{const d=await api('analyze',{url:$('#videoUrl').value.trim()});lastReport=d.report;renderReport(lastReport);if(typeof saveHistory==='function')saveHistory(lastReport);if(typeof prefillSimilar==='function')prefillSimilar(lastReport);if(typeof renderVisuals==='function')renderVisuals();setTimeout(()=>$('#report').scrollIntoView({behavior:'smooth',block:'start'}),60)}catch(x){showErr('#error',x)}finally{$('#loading').classList.remove('show')}};
function heatSvg(points){if(!points?.length)return'';const W=1000,H=180,pad=10,max=Math.max(...points.map(x=>Number(x.value)||0),1),coords=points.map((x,i)=>`${pad+(W-pad*2)*i/(points.length-1)},${H-pad-(H-pad*2)*(Number(x.value)||0)/max}`).join(' '),area=`${pad},${H-pad} ${coords} ${W-pad},${H-pad}`;return `<div class="heat-wrap"><svg class="heat-svg" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><polyline points="${area}" fill="rgba(141,169,255,.13)" stroke="none"></polyline><polyline points="${coords}" fill="none" stroke="#8da9ff" stroke-width="4" vector-effect="non-scaling-stroke"></polyline></svg><div class="heat-labels"><span>Start</span><span>25%</span><span>50%</span><span>75%</span><span>End</span></div></div>`}
function outlierText(o){const m=Number(o?.multiple);if(!Number.isFinite(m))return'Channel-relative baseline unavailable.';if(m>=10)return'Monster outlier — at least 10× the creator’s recent long-form norm.';if(m>=5)return'Strong outlier — far above the creator’s recent baseline.';if(m>=3)return'Clear outlier — materially stronger than recent uploads.';if(m>=1.5)return'Above normal — stronger than the recent channel median.';return'Near channel norm — useful as a control rather than a breakout.'}
function detailListHtml(r){const ce=r.content_extraction||{},items=ce.items||[];if(!items.length)return'';const target=ce.target_count&&ce.target_count<=60?ce.target_count:null,shown=items.slice(0,target||Math.min(25,items.length)),label=target?`${target} CLEAN POINTS`:'KEY DETAILS / POINTS';return `<article class="card c12 clean-list-card"><div class="section-head"><div><div class="eyebrow">${label}</div><h2>${target?`The ${target} points, stripped of the clutter`:'What is actually said in the video'}</h2></div><span class="pill">transcript-derived</span></div><div class="clean-points">${shown.map((x,i)=>`<div class="clean-point"><span class="point-no">${i+1}</span><div class="grow"><b>${esc(x.statement)}</b><span class="point-time">${esc(x.timestamp)}</span></div></div>`).join('')}</div>${items.length>shown.length?`<details class="more-details"><summary>Show ${items.length-shown.length} more extracted points</summary><div class="clean-points">${items.slice(shown.length).map((x,i)=>`<div class="clean-point"><span class="point-no">${shown.length+i+1}</span><div class="grow"><b>${esc(x.statement)}</b><span class="point-time">${esc(x.timestamp)}</span></div></div>`).join('')}</div></details>`:''}</article>`}
function whySpecificHtml(r){const xs=r.why_it_worked_specific||[];if(!xs.length)return'';return `<article class="card c12"><div class="eyebrow">WHY IT WORKED — WITH RECEIPTS</div><h2 style="margin:5px 0 12px">Every claim has the exact example beside it</h2><div class="evidence-stack">${xs.map(x=>`<div class="specific-evidence"><div class="specific-head"><b>${esc(x.label)}</b><span class="pill">${esc(x.timestamp||'-')}</span></div><div class="specific-claim">${esc(x.claim)}</div><blockquote>“${esc(x.example||'-')}”</blockquote></div>`).join('')}</div></article>`}
function hookHtml(r){const hf=r.hook_framework||{},hs=r.hook_story||{},seq=hf.sequence||[];return `<article class="card c12 hook-focus"><div class="eyebrow">HOOK ANALYSIS</div><h2 style="margin:5px 0">${esc(hf.primary_type||hs.hook?.type||'Opening hook')}</h2><blockquote class="hook-quote">“${esc(hf.exact_line||hs.hook?.micro_excerpt||hs.hook?.excerpt||'-')}”</blockquote><p class="hook-why">${esc(hf.why||hs.hook?.mechanism||'')}</p>${seq.length?`<div class="hook-sequence">${seq.map((x,i)=>`<div class="hook-move"><span>${i+1}</span><div><b>${esc(x.type)}</b><p>“${esc(x.line)}”</p><small>${esc(x.why)}</small></div></div>`).join('')}</div>`:''}<div class="hook-grid compact-hook"><div class="evidence-card"><div class="eyebrow">RE-HOOK · ${esc(hs.rehook?.timestamp||'-')}</div><p class="evidence-text">${esc(hs.rehook?.excerpt||'No strong explicit re-hook found.')}</p><div class="source-note">${esc(hs.rehook?.reason||'')}</div></div><div class="evidence-card"><div class="eyebrow">PROMISE FULFILLMENT · ${esc(hs.fulfillment?.timestamp||'-')}</div><p class="evidence-text">${esc(hs.fulfillment?.excerpt||'No strong transcript-level fulfillment example detected.')}</p><div class="source-note">${esc(hs.fulfillment?.reason||hs.guardrail||'')}</div></div></div><div class="warn">Promise fulfillment is transcript matching, not a private YouTube retention metric.</div></article>`}
function methodSummaryHtml(r){const s=r.summary_intelligence||{},methods=s.methods||[];return `<article class="card c12 summary-card"><div class="eyebrow">CONCISE VIDEO SUMMARY</div><h2 style="margin:5px 0">Key methods / things discussed</h2>${methods.length?`<div class="method-grid">${methods.map(x=>`<div class="method"><div class="split"><b>${esc(x.label)}</b><span class="pill">${esc(x.timestamp)}</span></div><p>${esc(x.explanation)}</p></div>`).join('')}</div>`:'<p class="muted">This reads as entertainment/narrative rather than a how-to, so YTIntel did not invent a fake method list.</p>'}<div class="takeaway"><div class="eyebrow">TAKEAWAY</div>${esc(s.takeaway||'No concise takeaway available.')}</div></article>`}
function renderReport(r){const v=r.video||{},q=r.research_intelligence||{},m=q.retention_mechanics||{},f=q.format_engine||{},a=q.actionable_summary||{},p=r.pacing||{},prod=q.production_load||{},tl=q.timeline||[],risk=m.script_attention_risk_zones||[],peaks=r.heatmap?.top_peaks||[],norm=r.heatmap?.normalized_100||[],segs=r.transcript?.segments||[],top=[...tl].sort((x,y)=>(y.signal_score||0)-(x.signal_score||0)).slice(0,6),mx=Math.max(1,...top.map(x=>Number(x.signal_score||0))),o=v.outlier||{},outTxt=o.multiple==null?'-':`${num(o.multiple)}×`;
const quality=`${r.transcript?.available?'<span class="pill good">Transcript ✓</span>':'<span class="pill hot">Transcript missing</span>'}${r.heatmap?.available?'<span class="pill good">100-point Most Replayed ✓</span>':'<span class="pill hot">Most Replayed unavailable</span>'}`;
$('#report').innerHTML=`<div class="grid">
<article class="card c12 facts-card"><div class="split"><div class="grow"><div class="eyebrow">FACTS</div><h2 style="margin:5px 0">${esc(v.title||'Untitled')}</h2><div class="muted">${esc(v.channel||'Unknown channel')}</div><div class="pillrow" style="margin-top:9px">${quality}</div></div><div class="outlier-hero ${Number(o.multiple)>=3?'hot-outlier':''}"><span>OUTLIER</span><strong>${esc(outTxt)}</strong></div></div><div class="metrics lean-metrics">${metric('Views',compact(v.view_count))}${metric('Channel median',compact(o.channel_median_views))}${metric('Subscribers',compact(v.channel_follower_count))}${metric('Upload',date(v.upload_date))}${metric('Length',time(v.duration))}${metric('WPM',num(p.video_words_per_minute))}</div></article>
<article class="card c12 outlier-card"><div class="outlier-layout"><div><div class="eyebrow">OUTLIER MULTIPLIER</div><div class="outlier jumbo ${Number(o.multiple)>=3?'good':''}">${esc(outTxt)}</div></div><div class="grow"><h2>How unusual is this upload for this creator?</h2><p>${esc(outlierText(o))}</p><div class="metrics mini">${metric('This video',compact(v.view_count))}${metric('Recent median',compact(o.channel_median_views))}${metric('Sample',o.sample_size??'-')}${metric('Tier',o.tier||'-')}</div><div class="source-note">${esc(o.basis||'')}</div></div></div></article>
<article class="card c12"><div class="section-head"><div><div class="eyebrow">MOST REPLAYED — 100 POINTS</div><h2>What viewers came back to</h2></div><span class="pill">public replay / seek interest</span></div>${r.heatmap?.available?heatSvg(norm):'<p class="amber">No public Most Replayed curve was exposed for this video/session. YTIntel will not invent one.</p>'}${peaks.length?`<div class="peaks">${peaks.slice(0,8).map((x,i)=>`<div class="peak"><span>#${i+1}</span><b>${time(x.time)}</b><span>intensity ${num(x.value)}</span></div>`).join('')}</div>`:''}<div class="warn">This is Most Replayed, not private YouTube Studio audience-retention %.</div></article>
${detailListHtml(r)}
${hookHtml(r)}
${whySpecificHtml(r)}
<article class="card c8"><div class="eyebrow">THE ENGINE</div><div class="engine"><strong>${esc(f.primary||'Not enough evidence')}</strong><p>${esc(f.one_sentence_engine||'')}</p></div></article>
<article class="card c4 winner-box"><div class="eyebrow">STEAL THESE MECHANICS</div><h2 style="margin-top:5px">What to actually reuse</h2>${list(a.transferable_mechanics||[])}</article>
<article class="card c6"><div class="eyebrow">PRODUCTION LOAD</div><h3>What the format demands</h3><div class="pillrow"><span class="pill">${esc(prod.research_load||'-')} research</span><span class="pill">${num(prod.estimated_proof_or_test_moments)} proof/test beats</span><span class="pill">${num(prod.estimated_distinct_payoff_beats)} payoff beats</span></div><div class="warn">True cuts/min and motion-graphic density require video-file scene/frame analysis; transcript proxies are not presented as real edit pace.</div></article>
<article class="card c6"><div class="eyebrow">VISUAL / AUDIO HANDOFF</div><h3>Analyse the moments with evidence first</h3><p>${(r.visual_intelligence?.hotzone_targets||[]).length?`${r.visual_intelligence.hotzone_targets.length} replay hotzones are queued as visual-analysis targets.`:'No replay hotzones are available to target.'}</p><button class="btn small no-print" id="openVisuals">Open Visuals + Edit vault</button></article>
<article class="card c8"><div class="eyebrow">ATTENTION TIMELINE</div><h3>Strong transcript windows</h3><div class="timeline">${top.map(x=>`<div class="tl"><span>${time(x.start)}</span><div><div class="bar"><i style="width:${Math.max(4,Number(x.signal_score||0)/mx*100)}%"></i></div><div class="source-note">${esc(x.text_preview||'')}</div></div><b>${num(x.signal_score)}</b></div>`).join('')||'<p class="muted">No timeline available.</p>'}</div></article>
<article class="card c4"><div class="eyebrow">RISK FLAGS</div><h3>Possible low-signal zones</h3>${risk.length?risk.slice(0,5).map(x=>`<div class="risk"><b>${esc(x.start_timestamp)}–${esc(x.end_timestamp)}</b><div class="muted">${esc(x.reason)}</div></div>`).join(''):'<p class="muted">No long low-signal zones flagged.</p>'}<div class="warn">Hypotheses only — never labelled as measured retention drops.</div></article>
<article class="card c12"><div class="split"><div><div class="eyebrow">REMAKE BLUEPRINT</div><h2 style="margin:4px 0">Turn the evidence into the next video</h2></div><div class="spacer"></div><button class="btn small no-print" id="copyMd">Copy report as Markdown</button><button class="btn small no-print" id="printPdf">Print / Save PDF</button></div>${(a.remake_blueprint||[]).map(x=>`<div class="beat"><small>${esc(x.zone)}</small><div><b>${esc(x.instruction)}</b><p>Evidence: ${esc(x.observed)}</p></div></div>`).join('')||'<p class="muted">No blueprint available.</p>'}</article>
<article class="card c12"><div class="split"><div><div class="eyebrow">CLEAN TRANSCRIPT</div><h2 style="margin:4px 0">Full timestamped transcript</h2></div><div class="spacer"></div><button class="btn small no-print" id="copyTranscript">Copy transcript as Markdown</button></div><div class="transcript">${segs.slice(0,900).map(s=>`<div class="tr"><time>${time(s.start)}</time><p>${esc(s.text||'')}</p></div>`).join('')||'<p class="muted">Transcript unavailable.</p>'}</div></article>
${methodSummaryHtml(r)}
</div>`;
$('#copyMd').onclick=()=>copyReportMarkdown(r);$('#printPdf').onclick=()=>window.print();$('#copyTranscript').onclick=()=>copyTranscriptMarkdown(r);$('#openVisuals').onclick=()=>tab('visuals')}
function reportMarkdown(r){const v=r.video||{},a=r.research_intelligence?.actionable_summary||{},hf=r.hook_framework||{},hs=r.hook_story||{},peaks=r.heatmap?.top_peaks||[],pts=r.content_extraction?.items||[],why=r.why_it_worked_specific||[];return `# ${v.title||'YouTube video'}\n\n## Facts\n- Channel: ${v.channel||'-'}\n- Views: ${v.view_count??'-'}\n- Outlier: ${v.outlier?.multiple??'-'}x\n- Channel median: ${v.outlier?.channel_median_views??'-'}\n- Subscribers: ${v.channel_follower_count??'-'}\n- Upload: ${v.upload_date||'-'}\n- WPM: ${r.pacing?.video_words_per_minute??'-'}\n\n## Most Replayed\n${peaks.map((x,i)=>`${i+1}. ${time(x.time)} — ${x.value}`).join('\n')||'No public replay data.'}\n\n## Clean points\n${pts.map((x,i)=>`${i+1}. ${x.statement} (${x.timestamp})`).join('\n')||'No clean point list extracted.'}\n\n## Hook\nType: ${hf.primary_type||'-'}\nExact line: "${hf.exact_line||'-'}"\nWhy: ${hf.why||'-'}\n\n## Re-hook\n${hs.rehook?.timestamp||'-'} — ${hs.rehook?.excerpt||'-'}\n\n## Promise fulfillment\n${hs.fulfillment?.timestamp||'-'} — ${hs.fulfillment?.excerpt||'-'}\n\n## Why it worked — evidence\n${why.map(x=>`- **${x.label} (${x.timestamp})** ${x.claim}\n  - Example: "${x.example}"`).join('\n')}\n\n## Steal these mechanics\n${(a.transferable_mechanics||[]).map(x=>`- ${x}`).join('\n')}\n\n## Remake blueprint\n${(a.remake_blueprint||[]).map(x=>`- **${x.zone}** — ${x.instruction} Evidence: ${x.observed}`).join('\n')}`}
function transcriptMarkdown(r){const v=r.video||{},segs=r.transcript?.segments||[];return `# Transcript — ${v.title||'YouTube video'}\n\nChannel: ${v.channel||'-'}\nURL: ${v.webpage_url||v.original_url||''}\n\n${segs.map(s=>`[${time(s.start)}] ${s.text||''}`).join('\n')}`}
async function copyText(text,button,label,filename){try{await navigator.clipboard.writeText(text);button.textContent='Copied ✓';setTimeout(()=>button.textContent=label,1400)}catch{const blob=new Blob([text],{type:'text/markdown'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();URL.revokeObjectURL(a.href)}}
function copyReportMarkdown(r){copyText(reportMarkdown(r),$('#copyMd'),'Copy report as Markdown','ytintel-report.md')}
function copyTranscriptMarkdown(r){copyText(transcriptMarkdown(r),$('#copyTranscript'),'Copy transcript as Markdown','ytintel-transcript.md')}
