api=async function(action,body={}){const r=await fetch(`https://dkmacktcfhubsumwrydw.supabase.co/functions/v1/ytintel-v093?action=${encodeURIComponent(action)}`,{method:'POST',headers:{'content-type':'application/json','x-ytintel-client':'web-v093'},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw Error(d.error||`HTTP ${r.status}`);return d};
fetch('https://dkmacktcfhubsumwrydw.supabase.co/functions/v1/ytintel-v093?action=health').then(r=>r.json()).then(d=>{const x=document.querySelector('#status');if(x)x.textContent=`v${d.version} ready`}).catch(()=>{});
window.addEventListener('load',()=>{
  const releases=[...document.querySelectorAll('#updates .release')];
  const byText=(needle)=>releases.find(x=>(x.querySelector('.eyebrow')?.textContent||'').toLowerCase().includes(needle.toLowerCase()));
  const setEyebrow=(card,text)=>{const e=card?.querySelector('.eyebrow');if(e)e.textContent=text;};
  setEyebrow(byText('v0.9.1'),'V0.9.1 · 4 SEP 2026');
  const combined=byText('v0.8 / 0.8.1');
  if(combined){setEyebrow(combined,'V0.8.1 · 4 SEP 2026');const h=combined.querySelector('h3');if(h)h.textContent='Visible update system';const ul=combined.querySelector('ul');if(ul)ul.innerHTML='<li><b>What’s New popup</b> after each release.</li><li>Permanent <b>What’s New</b> button and Updates tab.</li><li>Cache-safe latest build to stop stale front-end versions.</li><li>v0.8 research history preserved through the update.</li>';if(!document.querySelector('[data-release="v080"]')){const card=document.createElement('article');card.className='card c6 release';card.dataset.release='v080';card.innerHTML='<div class="eyebrow">V0.8 · 4 SEP 2026</div><h3>Evidence-first analyser UI</h3><ul class="list"><li>Hook → Re-hook → Promise Fulfillment with transcript evidence.</li><li>Dedicated Outlier Multiplier section.</li><li>Copy full transcript as Markdown.</li><li>Concise transcript-derived summary at the end of Analyse.</li><li>Visuals + Edit beta introduced.</li><li>Removed repetitive generic Do Not Copy output.</li></ul>';combined.insertAdjacentElement('afterend',card)}}
  setEyebrow(byText('v0.7'),'V0.7 · 4 SEP 2026');setEyebrow(byText('v0.6'),'V0.6 · 4 SEP 2026');const foundation=byText('v0.5');if(foundation)setEyebrow(foundation,'V0.5 → V0.2 · 3–4 SEP 2026');
  const s=document.createElement('script');s.src='v10-ui.js?v=0105-accuracy-reset';s.defer=false;s.onload=()=>{const h=document.createElement('script');h.src='v102-hotfix.js?v=0105';h.defer=false;h.onload=()=>{const p=document.createElement('script');p.src='v102-pattern.js?v=0105';p.defer=false;p.onload=()=>{const q=document.createElement('script');q.src='v103-history.js?v=0105-clickable-history';q.defer=false;q.onload=()=>{const m=document.createElement('script');m.src='v104-media.js?v=0105-live-media';m.defer=false;m.onload=()=>{const z=document.createElement('script');z.src='v104-media-proxy.js?v=0105-proxy';z.defer=false;z.onload=()=>{const ai=document.createElement('script');ai.src='v105-ai.js?v=0105-sol-max';ai.defer=false;document.body.appendChild(ai)};document.body.appendChild(z)};document.body.appendChild(m)};document.body.appendChild(q)};document.body.appendChild(p)};document.body.appendChild(h)};document.body.appendChild(s);
});
