(function(){
const RELEASE='ytintel-whats-new-0.10.2';
const css=`.structured-list{display:grid;gap:7px}.structured-item{display:grid;grid-template-columns:34px 1fr auto;gap:10px;align-items:start;padding:12px;background:#0a0d12;border:1px solid #28303b;border-radius:12px}.structured-item .si-num{width:28px;height:28px;display:grid;place-items:center;border-radius:8px;background:#181d27;color:#9fb4ff;font-weight:900}.structured-item h4{margin:2px 0 4px;font-size:14px}.structured-item p{margin:0;color:#9daabd;font-size:12px;line-height:1.45}.structured-item time{font-size:10px;color:#8996aa;white-space:nowrap}.evidence-toggle{margin-top:5px}.evidence-toggle summary{cursor:pointer;color:#8fa7d6;font-size:11px}.release-102{border-left:3px solid #55e29d!important}@media(max-width:650px){.structured-item{grid-template-columns:30px 1fr}.structured-item time{grid-column:2}}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
function goodEvidence(x){const e=String(x?.explanation||x?.exact_line||'').trim(),l=String(x?.label||'').toLowerCase();if(!e||e.length<18)return'';if(/\b(?:tip|step|method)\s*(?:number\s*)?(?:one|two|three|four|five|six|seven|eight|nine|ten|\d+)\b/i.test(e)&&e.length<75)return'';if(/^and that(?:'s| is) tip/i.test(e))return'';const terms=l.match(/[a-z0-9]+/g)||[];const hit=terms.some(t=>t.length>3&&e.toLowerCase().includes(t));if(!hit&&/^(just|look|and i'll|>>|i'll be honest)/i.test(e))return'';return e}
function structuredHtml(r,summary=false){const c=r.content_extraction||{},xs=c.items||[];if(!xs.length)return'';const isStructured=c.kind==='structured-sections';if(!isStructured)return `<div class="takeaway-list">${xs.slice(0,summary?8:15).map((x,i)=>`<div class="takeaway-row"><span class="n">${i+1}</span><b>${esc(x.statement)}</b><span class="approx">${esc(x.timestamp||'')}</span></div>`).join('')}</div>`;return `<div class="structured-list">${xs.slice(0,summary?12:Math.max(12,c.target_count||12)).map((x,i)=>{const ev=goodEvidence(x);return `<div class="structured-item"><span class="si-num">${esc(x.index??i+1)}</span><div><h4>${esc(x.label||x.statement||`Item ${i+1}`)}</h4>${ev?`<details class="evidence-toggle"><summary>Transcript evidence</summary><p>“${esc(ev)}”</p></details>`:''}</div><time>${esc(x.timestamp||'')}</time></div>`}).join('')}</div>`}
if(typeof detailListHtml==='function')detailListHtml=function(r){const c=r.content_extraction||{},xs=c.items||[];if(!xs.length)return'';return `<article class="card c12"><div class="section-head"><div><div class="eyebrow">${c.target_count?`${c.target_count} KEY TAKEAWAYS`:'KEY TAKEAWAYS'}</div><h2>${c.kind==='structured-sections'?'The actual sections/methods — no numbered transcript dump':'The useful points from the transcript'}</h2></div><span class="pill">transcript-grounded</span></div>${structuredHtml(r,false)}<div class="v10-note v10-warn"><strong>Timing:</strong> ≈ means estimated inside a coarse caption window. Exact deep links remain disabled until cue-level captions are solved.</div></article>`};
if(typeof methodSummaryHtml==='function')methodSummaryHtml=function(r){const c=r.content_extraction||{},xs=c.items||[];return `<article class="card c12 summary-card"><div class="eyebrow">QUICK SUMMARY</div><h2 style="margin:5px 0">${c.kind==='structured-sections'&&c.target_count?`${c.target_count} methods / sections covered`:'Key takeaways'}</h2>${xs.length?structuredHtml(r,true):'<p class="muted">No clean takeaway passed the evidence threshold.</p>'}<div class="v10-note"><strong>Current ceiling:</strong> these labels are structure/transcript-grounded. Editorial one-sentence explanations will move to the reasoning-model layer rather than being faked with n-grams.</div></article>`};
if(typeof renderReport==='function'){
 const old=renderReport;renderReport=function(r){old(r);const w=r.pacing?.wpm_verification;if(w){document.querySelectorAll('#report .v10-good').forEach(n=>{if((n.textContent||'').includes('WPM verified'))n.innerHTML=`<strong>Video WPM recalculated:</strong> ${esc(w.word_count)} cleaned transcript words ÷ ${esc((Number(w.duration_seconds||0)/60).toFixed(2))} video minutes = <b>${esc(w.calculated_wpm)}</b> WPM.${w.delta!=null&&Number(w.delta)>.15?` Previous pipeline differed by ${esc(w.delta)} WPM; the current cleaned calculation is the displayed figure.`:' Independent calculation agrees with the previous pipeline.'} This is Video WPM, not speaking-only WPM.`})}
  const bad=/re-?hook.{0,30}(?:30\s*s|30\s*sec|every\s+30)|every\s+30\s*(?:s|sec)|30\s*(?:s|sec)(?:onds?)?\s*(?:apart|spacing)|payoffs?\s*\/?\s*min|payoff.{0,25}per minute|first payoff.{0,12}0:00/i;
  [...document.querySelectorAll('#report li,#report .beat')].forEach(el=>{if(bad.test(el.textContent||''))el.remove()});
 };
}
const grid=document.querySelector('#updates .grid');if(grid&&!grid.querySelector('.release-102')){grid.querySelectorAll('.release.current').forEach(x=>x.classList.remove('current'));const a=document.createElement('article');a.className='card c12 release current release-102';a.innerHTML=`<div class="split"><div><div class="eyebrow">V0.10.2 · CURRENT</div><h2 style="margin:4px 0">Structured takeaways + accuracy hotfix</h2><div class="source-note">4 Sep 2026</div></div><span class="pill good">LIVE</span></div><ul class="list"><li>Educational/list videos now detect their declared structure — e.g. the Claude test resolves all <b>10/10 tips</b> instead of ranking random transcript sentences.</li><li>Structured takeaway UI now leads with the actual method/section label and hides weak filler explanations behind evidence.</li><li>Stale 30-second cadence claims are stripped from Steal/Remake output.</li><li>Video WPM display now explains the cleaned recalculation instead of calling a cleaning delta a failed check.</li><li>Pattern Mine retries failed source videos once and still refuses to output if fewer than 5 complete analyses survive.</li></ul>`;grid.prepend(a)}
const modal=document.querySelector('#updateModal');if(modal){const panel=modal.querySelector('.update-panel');if(panel)panel.innerHTML=`<div class="update-top"><div class="grow"><span class="update-version">YTIntel v0.10.2 · 4 SEP 2026</span><h2>Less water, cleaner takeaways.</h2><p>Structured videos now resolve their real sections instead of turning transcript paragraphs into fake “key points.”</p></div><button class="update-close" id="v102Close">×</button></div><div class="update-items"><div class="update-item"><div class="tick">✓</div><div><b>10-tip / 20-detail structure detection</b><span class="muted">Find section markers first, then show the actual method/detail labels.</span></div></div><div class="update-item"><div class="tick">✓</div><div><b>WPM calculation clarified</b><span class="muted">Cleaned words ÷ full runtime; no speaking-WPM claim.</span></div></div><div class="update-item"><div class="tick">✓</div><div><b>Old 30-second artefacts stripped</b><span class="muted">They no longer leak into Steal These Mechanics or Remake Blueprint.</span></div></div></div><div class="update-actions"><button class="primary" id="v102Continue">Continue</button><button id="v102Log">Full update log</button></div>`;const close=()=>{modal.classList.remove('show');try{localStorage.setItem(RELEASE,'seen')}catch{}};document.querySelector('#v102Close')?.addEventListener('click',close);document.querySelector('#v102Continue')?.addEventListener('click',close);document.querySelector('#v102Log')?.addEventListener('click',()=>{close();if(typeof tab==='function')tab('updates')});try{if(localStorage.getItem(RELEASE)!=='seen')setTimeout(()=>modal.classList.add('show'),320)}catch{}}
})();