(function(){
const VERSION='0.10.3';
const css=`
.folder{cursor:pointer}.folder:hover{border-color:#445068;transform:translateY(-1px)}
.video-row.history-clickable{cursor:pointer;transition:border-color .15s ease,background .15s ease,transform .15s ease}.video-row.history-clickable:hover{border-color:#40506a;background:#0e1219;transform:translateY(-1px)}
.history-row-hint{font-size:10px;color:#8493a8;margin-top:5px}.history-row-actions{display:flex;gap:7px;flex-wrap:wrap;align-items:center}.history-open-btn{border-color:rgba(141,169,255,.4)!important;background:rgba(141,169,255,.09)!important}
.saved-history-modal{position:fixed;inset:0;z-index:100050;display:none;align-items:center;justify-content:center;padding:18px;background:rgba(2,4,8,.88);backdrop-filter:blur(10px)}.saved-history-modal.show{display:flex}.saved-history-panel{width:min(860px,100%);max-height:88vh;overflow:auto;border:1px solid #333c4b;border-radius:20px;background:linear-gradient(180deg,#151922,#0b0f15);box-shadow:0 30px 100px rgba(0,0,0,.7);padding:22px}.saved-history-top{display:flex;gap:14px;align-items:flex-start}.saved-history-top .grow{flex:1}.saved-history-top h2{margin:4px 0 5px;font-size:25px;line-height:1.1}.saved-history-close{width:36px;height:36px;border:1px solid #343c49;border-radius:10px;background:#191e27;color:#fff;font-size:20px;cursor:pointer}.saved-history-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:14px 0}.saved-history-stat{padding:11px;border:1px solid #29313e;border-radius:11px;background:#090c11}.saved-history-stat span{display:block;font-size:9px;letter-spacing:.08em;color:#8190a7;font-weight:900;text-transform:uppercase;margin-bottom:4px}.saved-history-stat b{font-size:15px}.saved-history-section{margin-top:16px}.saved-history-section h3{margin:0 0 8px}.saved-history-point{padding:9px 10px;margin:6px 0;border:1px solid #27303c;border-radius:10px;background:#080b10;font-size:12px;line-height:1.4}.saved-history-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.pattern-saved.history-clickable{cursor:pointer}.pattern-saved.history-clickable:hover{border-color:#40506a;background:#0e1219}
@media(max-width:700px){.saved-history-grid{grid-template-columns:repeat(2,1fr)}.video-row.history-clickable{align-items:flex-start}.history-row-actions{width:100%;margin-top:8px}.saved-history-panel{padding:16px}}
`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
document.title='YTIntel v0.10.3 — Clickable History';
const status=document.querySelector('#status');if(status)status.textContent='v0.10.3 ready';

function hEsc(x){return typeof esc==='function'?esc(x):String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function getModal(){let m=document.querySelector('#savedHistoryModal');if(m)return m;m=document.createElement('div');m.id='savedHistoryModal';m.className='saved-history-modal';m.innerHTML='<div class="saved-history-panel"><div id="savedHistoryBody"></div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('show')});document.addEventListener('keydown',e=>{if(e.key==='Escape')m.classList.remove('show')});return m}
function closeModal(){document.querySelector('#savedHistoryModal')?.classList.remove('show')}
function startReanalyse(item){closeModal();if(typeof tab==='function')tab('analyse');const input=document.querySelector('#videoUrl');if(input)input.value=item?.url||'';setTimeout(()=>{const form=document.querySelector('#analyseForm');if(form&&item?.url){if(typeof form.requestSubmit==='function')form.requestSubmit();else form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))}},40)}
function openSource(item){if(item?.url)window.open(item.url,'_blank','noopener,noreferrer')}
function stat(label,value){return `<div class="saved-history-stat"><span>${hEsc(label)}</span><b>${hEsc(value??'-')}</b></div>`}
function openSavedVideo(item){if(!item)return;const m=getModal(),body=m.querySelector('#savedHistoryBody');const points=(item.contentPoints||[]).filter(Boolean),mechs=(item.mechanics||[]).filter(Boolean);body.innerHTML=`<div class="saved-history-top"><div class="grow"><div class="eyebrow">SAVED ANALYSIS · ${hEsc(item.niche||'History')}</div><h2>${hEsc(item.title||'Untitled')}</h2><div class="muted">${hEsc(item.channel||'')} · saved ${item.saved?new Date(item.saved).toLocaleString():'previously'}</div></div><button class="saved-history-close" id="savedHistoryClose">×</button></div><div class="saved-history-grid">${stat('Views',typeof compact==='function'?compact(item.views):item.views)}${stat('Outlier',item.outlier?.multiple!=null?(typeof num==='function'?num(item.outlier.multiple):item.outlier.multiple)+'×':'n/a')}${stat('Video WPM',item.wpm!=null?Math.round(item.wpm):'n/a')}${stat('Top replay',item.topPeak!=null?(typeof time==='function'?time(item.topPeak):item.topPeak):'n/a')}</div><div class="saved-history-section"><div class="eyebrow">HOOK</div><h3>${hEsc(item.hook||'Not classified')}</h3></div>${points.length?`<div class="saved-history-section"><div class="eyebrow">SAVED KEY TAKEAWAYS</div><h3>What was banked from this analysis</h3>${points.slice(0,18).map((x,i)=>`<div class="saved-history-point"><b>${i+1}.</b> ${hEsc(x)}</div>`).join('')}</div>`:''}${mechs.length?`<div class="saved-history-section"><div class="eyebrow">SAVED MECHANICS</div>${mechs.slice(0,10).map(x=>`<div class="saved-history-point">${hEsc(x)}</div>`).join('')}</div>`:''}<div class="saved-history-actions"><button class="btn primary" id="savedReanalyse">Re-analyse now</button><button class="btn history-open-btn" id="savedOpenSource">Open YouTube</button><button class="btn" id="savedClose2">Close</button></div><div class="v10-note"><strong>Saved view:</strong> this opens the compact history snapshot without spending another analysis request. Re-analyse runs the current engine against the source again.</div>`;body.querySelector('#savedHistoryClose').onclick=closeModal;body.querySelector('#savedClose2').onclick=closeModal;body.querySelector('#savedReanalyse').onclick=()=>startReanalyse(item);body.querySelector('#savedOpenSource').onclick=()=>openSource(item);m.classList.add('show')}

function decorateVideoRows(xs){const root=document.querySelector('#folderDetail');if(!root||!xs?.length)return;const shown=xs.length<3?[...xs]:[...xs].sort((a,b)=>(Number(b.outlier?.multiple)||0)-(Number(a.outlier?.multiple)||0)||(Number(b.views)||0)-(Number(a.views)||0));const rows=[...root.querySelectorAll('.video-row')];rows.forEach((row,i)=>{const item=shown[i];if(!item)return;row.classList.add('history-clickable');row.dataset.historyId=item.id||'';row.title='Open saved analysis';const grow=row.querySelector('.grow');if(grow&&!grow.querySelector('.history-row-hint')){const hint=document.createElement('div');hint.className='history-row-hint';hint.textContent='Tap anywhere to open the saved analysis';grow.appendChild(hint)}let actions=row.querySelector('.actions');if(!actions){actions=document.createElement('div');actions.className='actions history-row-actions';row.appendChild(actions)}else actions.classList.add('history-row-actions');if(!actions.querySelector('[data-open-saved]')){const open=document.createElement('button');open.className='btn small history-open-btn';open.dataset.openSaved=item.id||String(i);open.textContent='Open saved';actions.prepend(open);open.onclick=e=>{e.stopPropagation();openSavedVideo(item)}}let re=actions.querySelector('[data-reanalyse]');if(re){re.textContent='Re-analyse';re.onclick=e=>{e.stopPropagation();startReanalyse(item)}}else{re=document.createElement('button');re.className='btn small';re.textContent='Re-analyse';actions.appendChild(re);re.onclick=e=>{e.stopPropagation();startReanalyse(item)}}if(!actions.querySelector('[data-open-youtube]')){const src=document.createElement('button');src.className='btn small';src.dataset.openYoutube=item.id||String(i);src.textContent='YouTube';actions.appendChild(src);src.onclick=e=>{e.stopPropagation();openSource(item)}}row.onclick=e=>{if(e.target.closest('button'))return;openSavedVideo(item)}})}

if(typeof renderFolder==='function'){
 const previousRenderFolder=renderFolder;
 renderFolder=function(xs){const out=previousRenderFolder(xs);setTimeout(()=>decorateVideoRows(xs),0);return out};
}

function patternHistoryRows(){try{return JSON.parse(localStorage.getItem('ytintel-v10-pattern-history')||'[]')}catch{return[]}}
function openSavedPattern(item){if(!item)return;const m=getModal(),body=m.querySelector('#savedHistoryBody'),w=item.winner||{};body.innerHTML=`<div class="saved-history-top"><div class="grow"><div class="eyebrow">SAVED PATTERN MINE</div><h2>${hEsc(item.name||'Pattern Mine')}</h2><div class="muted">${item.created?new Date(item.created).toLocaleString():''} · ${item.video_count||0} videos</div></div><button class="saved-history-close" id="savedHistoryClose">×</button></div><div class="saved-history-grid">${stat('Videos',item.video_count||0)}${stat('Repeated',(item.repeated||[]).length)}${stat('Unique',(item.unique||[]).length)}${stat('Winner outlier',w.outlier_multiple!=null?(typeof num==='function'?num(w.outlier_multiple):w.outlier_multiple)+'×':'n/a')}</div><div class="saved-history-section"><div class="eyebrow">WINNER VS PACK</div><h3>${hEsc(w.title||'No winner saved')}</h3><div class="saved-history-point"><b>Hook:</b> ${hEsc(w.hook_type||'-')} — “${hEsc(w.hook_exact||'-')}”</div></div>${(item.repeated||[]).length?`<div class="saved-history-section"><div class="eyebrow">MOST REPEATED</div>${item.repeated.slice(0,12).map(x=>`<div class="saved-history-point"><b>${hEsc(x.video_count||'')} videos:</b> ${hEsc(x.statement||'')}</div>`).join('')}</div>`:''}${(item.unique||[]).length?`<div class="saved-history-section"><div class="eyebrow">UNIQUE / UNCOMMON</div>${item.unique.slice(0,12).map(x=>`<div class="saved-history-point">${hEsc(x.statement||'')}</div>`).join('')}</div>`:''}<div class="saved-history-actions"><button class="btn primary" id="savedPatternCopy">Copy Markdown</button><button class="btn" id="savedClose2">Close</button></div>`;body.querySelector('#savedHistoryClose').onclick=closeModal;body.querySelector('#savedClose2').onclick=closeModal;body.querySelector('#savedPatternCopy').onclick=async()=>{try{await navigator.clipboard.writeText(item.markdown||'');body.querySelector('#savedPatternCopy').textContent='Copied ✓'}catch{}};m.classList.add('show')}
function decoratePatternHistory(){const items=patternHistoryRows();document.querySelectorAll('.pattern-saved').forEach((row,i)=>{const item=items[i];if(!item)return;row.classList.add('history-clickable');row.title='Open saved Pattern Mine';row.onclick=e=>{if(e.target.closest('button'))return;openSavedPattern(item)};if(!row.querySelector('[data-pm-open]')){const actions=row.querySelector('.actions');if(actions){const b=document.createElement('button');b.className='btn small history-open-btn';b.dataset.pmOpen=item.id;b.textContent='Open';actions.prepend(b);b.onclick=e=>{e.stopPropagation();openSavedPattern(item)}}}})}
if(typeof renderHistory==='function'){
 const previousRenderHistory=renderHistory;
 renderHistory=function(){const out=previousRenderHistory();setTimeout(()=>{const xs=typeof history==='function'?history():[];const groups={};for(const x of xs)(groups[x.niche]??=[]).push(x);if(selectedNiche&&groups[selectedNiche])decorateVideoRows(groups[selectedNiche]);decoratePatternHistory()},0);return out};
}

const grid=document.querySelector('#updates .grid');if(grid&&!grid.querySelector('.release-103')){grid.querySelectorAll('.release.current').forEach(x=>x.classList.remove('current'));const a=document.createElement('article');a.className='card c12 release current release-103';a.innerHTML=`<div class="split"><div><div class="eyebrow">V0.10.3 · CURRENT</div><h2 style="margin:4px 0">Clickable research history</h2><div class="source-note">5 Sep 2026</div></div><span class="pill good">LIVE</span></div><ul class="list"><li><b>Every video inside a History folder is now clickable.</b> Tap the row to reopen its saved snapshot without spending another analysis request.</li><li><b>One-tap Re-analyse</b> now reruns the current engine immediately instead of only pre-filling the URL.</li><li><b>Open YouTube</b> is available beside every saved video.</li><li><b>Pattern Mine history is clickable too</b>, so saved cross-video research can be reopened instead of only copied/deleted.</li><li>The same controls work even when a niche has fewer than 3 videos and YTIntel is withholding “winning pattern” claims.</li></ul>`;grid.prepend(a)}

try{if(typeof renderHistory==='function'&&document.querySelector('#history')?.classList.contains('active'))renderHistory()}catch{}
})();
