(function(){
const VERSION='0.10.4';
const RELEASE='ytintel-whats-new-0.10.4';
const IV=['https://invidious.tiekoetter.com','https://inv.nadeko.net','https://invidious.nerdvpn.de','https://yt.chocolatemoo53.com'];
const cache=new Map();
const css=`
.media-live{border-left:3px solid #55e29d!important}.media-status{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.frame-targets{display:grid;gap:12px}.frame-target{border:1px solid #29313d;border-radius:15px;background:#090c11;padding:13px}.frame-target-head{display:flex;gap:9px;align-items:center;margin-bottom:10px}.frame-target-head .rank{width:34px;height:34px;border-radius:10px;background:#182031;color:#9fb4ff;display:grid;place-items:center;font-weight:950}.frame-strip{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.frame-sample{min-width:0}.frame-crop{width:100%;aspect-ratio:16/9;border-radius:10px;border:1px solid #2a3340;background-color:#06080c;background-repeat:no-repeat;overflow:hidden;box-shadow:inset 0 0 0 1px rgba(255,255,255,.015)}.frame-label{display:flex;justify-content:space-between;gap:8px;margin-top:5px;font-size:10px;color:#8d9ab0}.frame-transcript{margin-top:10px;padding:9px 10px;border-left:2px solid #34415a;background:#0b0f15;border-radius:0 9px 9px 0;color:#b7c2d3;font-size:12px;line-height:1.45}.audio-live-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.audio-live-card{border:1px solid #29313d;border-radius:14px;background:#0a0d12;padding:15px}.audio-event{display:grid;grid-template-columns:62px 1fr;gap:9px;padding:8px 0;border-bottom:1px solid #232a34}.audio-event:last-child{border-bottom:0}.audio-event time{font-size:11px;color:#8ea7ff;font-weight:850}.audio-event b{font-size:12px}.audio-event small{display:block;color:#8f9bad;margin-top:2px}.media-empty{padding:13px;border:1px dashed #303846;border-radius:12px;color:#94a1b5;background:#090c11}.media-source{font-size:10px;color:#77869c;margin-top:8px}.media-loading{padding:18px;border:1px solid #29313d;border-radius:14px;background:#0b0e14;color:#b7c2d2}.release-104{border-left:3px solid #55e29d!important}
@media(max-width:800px){.frame-strip{grid-template-columns:1fr}.audio-live-grid{grid-template-columns:1fr}.frame-crop{aspect-ratio:16/9}}
`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
function e(x){return typeof esc==='function'?esc(x):String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function t(sec){return typeof time==='function'?time(sec):(()=>{sec=Math.max(0,Math.round(Number(sec)||0));const m=Math.floor(sec/60),s=sec%60;return m+':'+String(s).padStart(2,'0')})()}
function timeoutFetch(url,ms=9000){const c=new AbortController(),x=setTimeout(()=>c.abort(),ms);return fetch(url,{signal:c.signal,headers:{accept:'application/json'}}).finally(()=>clearTimeout(x))}
async function ivVideo(id){if(cache.has('iv:'+id))return cache.get('iv:'+id);let err='';for(const base of IV){try{const r=await timeoutFetch(`${base}/api/v1/videos/${encodeURIComponent(id)}?local=true`,10000);if(!r.ok){err=`${base} HTTP ${r.status}`;continue}const d=await r.json();if(d?.videoId||d?.storyboards?.length){const out={base,data:d};cache.set('iv:'+id,out);return out}}catch(x){err=String(x?.message||x)}}throw new Error(err||'No public storyboard source answered.')}
function pickStoryboard(xs){return (xs||[]).filter(x=>Number(x.interval)>0&&x.templateUrl&&Number(x.width)>0&&Number(x.height)>0&&Number(x.storyboardWidth)>0&&Number(x.storyboardHeight)>0).sort((a,b)=>Number(b.width)*Number(b.height)-Number(a.width)*Number(a.height))[0]||null}
function absoluteUrl(u,base){if(!u)return'';if(/^https?:\/\//i.test(u))return u;return base+u}
function frameAt(sb,sec,base){const interval=Math.max(1,Number(sb.interval)||10000),count=Math.max(1,Number(sb.count)||1),cols=Math.max(1,Number(sb.storyboardWidth)||1),rows=Math.max(1,Number(sb.storyboardHeight)||1),idx=Math.min(count-1,Math.max(0,Math.floor((Math.max(0,Number(sec)||0)*1000)/interval))),per=cols*rows,sheet=Math.floor(idx/per),cell=idx%per,col=cell%cols,row=Math.floor(cell/cols);let url=String(sb.templateUrl||'').replace(/\$M/g,String(sheet));url=absoluteUrl(url,base);const px=cols<=1?0:(col/(cols-1))*100,py=rows<=1?0:(row/(rows-1))*100;return{sec:idx*interval/1000,index:idx,url,col,row,cols,rows,interval,style:`background-image:url(&quot;${e(url)}&quot;);background-size:${cols*100}% ${rows*100}%;background-position:${px}% ${py}%`}}
function nearestTranscript(r,sec){const segs=r?.transcript?.segments||[];let best=null,dist=Infinity;for(const s of segs){const st=Number(s.start)||0,en=Number(s.end??st+30),mid=(st+en)/2,d=Math.abs(mid-sec);if(d<dist){dist=d;best=s}}return best?.text?String(best.text).replace(/\s+/g,' ').trim():''}
function frameStrip(sb,peak,base){const step=Math.max(1,Number(sb.interval||10000)/1000),secs=[Math.max(0,peak.time-step),peak.time,peak.time+step],labs=['before','peak','after'];return secs.map((s,i)=>{const f=frameAt(sb,s,base);return `<div class="frame-sample"><div class="frame-crop" style="${f.style}"></div><div class="frame-label"><span>${labs[i]}</span><b>${e(t(f.sec))}</b></div></div>`}).join('')}
function vttSeconds(s){const p=String(s||'').split(':').map(Number);if(p.some(Number.isNaN))return null;return p.length===3?p[0]*3600+p[1]*60+p[2]:p[0]*60+p[1]}
function parseAudioEvents(vtt){const out=[];const blocks=String(vtt||'').split(/\r?\n\r?\n+/);for(const b of blocks){const m=b.match(/(\d{1,2}:\d{2}:\d{2}[.,]\d+|\d{1,2}:\d{2}[.,]\d+)\s+-->\s+(\d{1,2}:\d{2}:\d{2}[.,]\d+|\d{1,2}:\d{2}[.,]\d+)/);if(!m)continue;const start=vttSeconds(m[1].replace(',','.'));if(start==null)continue;const text=b.split(/\r?\n/).slice(1).join(' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim();if(!text)continue;const cues=[...text.matchAll(/\[([^\]]{2,60})\]/g)].map(x=>x[1].trim());if(/[♪♫]/.test(text))cues.push('music / sung audio');for(const cue of cues){const low=cue.toLowerCase();if(!/(music|applause|laugh|cheer|sigh|gasps?|door|click|ring|buzz|beep|whoosh|boom|bang|gunshot|engine|horn|typing|knock|alarm|footsteps?|clap|crowd|sound|sfx|transition)/i.test(low))continue;out.push({start,type:/music|song|sung/i.test(low)?'music':'sfx',label:cue,source:'caption cue'})}}return out}
async function captionAudio(base,video){const caps=video?.captions||[];const cap=caps.find(x=>/^en(?:-|$)/i.test(x.languageCode||''))||caps.find(x=>/english/i.test(x.label||''))||caps[0];if(!cap?.url)return[];const url=absoluteUrl(cap.url,base);try{const r=await timeoutFetch(url,10000);if(!r.ok)return[];return parseAudioEvents(await r.text())}catch{return[]}}
function recognizedTracks(r){return (r?.visual_intelligence?.recognized_audio?.tracks||[]).map(x=>({name:x?.title||x?.name||x?.song||x?.track||x?.videoTitle||'',artist:x?.artist||x?.by||''})).filter(x=>x.name)}
function audioHtml(events,tracks){const sfx=events.filter(x=>x.type==='sfx'),music=events.filter(x=>x.type==='music');return `<div class="audio-live-grid"><div class="audio-live-card"><div class="eyebrow">SOUND EFFECTS · MEASURED FROM PUBLIC CAPTION CUES</div><h3>Detected SFX moments</h3>${sfx.length?sfx.slice(0,30).map(x=>`<div class="audio-event"><time>${e(t(x.start))}</time><div><b>${e(x.label)}</b><small>${e(x.source)}</small></div></div>`).join(''):'<div class="media-empty">No caption-coded SFX cue was detected in the public caption track. YTIntel is not inventing one.</div>'}</div><div class="audio-live-card"><div class="eyebrow">B-ROLL / BACKGROUND MUSIC · MEASURED</div><h3>Music evidence</h3>${tracks.length?tracks.map(x=>`<div class="audio-event"><time>track</time><div><b>${e(x.name)}</b><small>${e(x.artist||'YouTube-attributed track')}</small></div></div>`).join(''):''}${music.length?music.slice(0,30).map(x=>`<div class="audio-event"><time>${e(t(x.start))}</time><div><b>${e(x.label)}</b><small>caption-coded music cue</small></div></div>`).join(''):tracks.length?'':'<div class="media-empty">No public track credit or caption-coded music cue was detected. No fake track name is shown.</div>'}</div></div>`}
async function buildMedia(r,root){const id=r?.video?.id,peaks=r?.heatmap?.top_peaks||[];if(!id){root.innerHTML='<div class="card empty">Analyse a video first.</div>';return}root.innerHTML='<div class="media-loading">Pulling real storyboard frames and public audio cues…</div>';try{const iv=await ivVideo(id),sb=pickStoryboard(iv.data.storyboards||[]),events=await captionAudio(iv.base,iv.data),tracks=recognizedTracks(r);const samples=[];if(sb&&peaks.length){for(const p of peaks.slice(0,8)){samples.push({time:Number(p.time)||0,value:Number(p.value)||0,transcript:nearestTranscript(r,Number(p.time)||0)})}}r.media_intelligence={storyboard:sb?{source:iv.base,width:sb.width,height:sb.height,interval_ms:sb.interval}:null,frame_samples:samples,audio_events:events,tracks};try{if(typeof saveHistory==='function')saveHistory(r)}catch{}
root.innerHTML=`<div class="card media-live"><div class="split"><div><div class="eyebrow">FRAME SAMPLING · LIVE</div><h2 style="margin:5px 0">Actual video storyboard frames at the replay peaks</h2><p class="muted">Each hotzone shows a real before / peak / after frame sample from YouTube's public storyboard sprites.</p></div><span class="pill good">${sb?'FRAMES LIVE':'NO STORYBOARD'}</span></div>${sb&&samples.length?`<div class="frame-targets">${samples.map((x,i)=>`<div class="frame-target"><div class="frame-target-head"><span class="rank">#${i+1}</span><b>${e(t(x.time))}</b><span class="pill">replay ${e(Number(x.value).toFixed(2))}</span></div><div class="frame-strip">${frameStrip(sb,x,iv.base)}</div>${x.transcript?`<div class="frame-transcript"><b>Nearest transcript:</b> ${e(x.transcript)}</div>`:''}</div>`).join('')}</div>`:`<div class="media-empty">A public storyboard was not returned for this video. The old fake “visual cause” placeholder has been removed.</div>`}<div class="media-source">Frame source: ${e(sb?iv.base:'unavailable')} ${sb?`· ${e(sb.width)}×${e(sb.height)} frame · ${e(Number(sb.interval)/1000)}s storyboard interval`:''}</div></div><div class="card media-live"><div class="eyebrow">AUDIO EVIDENCE · LIVE WHERE PUBLIC DATA EXISTS</div><h2 style="margin:5px 0 12px">Sound effects + background music</h2>${audioHtml(events,tracks)}<div class="media-source">This section only prints detected public caption cues or actual YouTube-attributed tracks. It does not call transcript density “audio analysis.”</div></div>`;
}catch(err){root.innerHTML=`<div class="card"><div class="eyebrow">MEDIA ANALYSIS</div><h2>Frame source unavailable on this pass</h2><div class="media-empty">${e(err?.message||err)}</div><p class="muted">The old roadmap instructions have been removed. Retry the Visuals tab later; YTIntel will not fabricate frames or audio.</p></div>`}}

if(typeof renderVisuals==='function'){
 renderVisuals=function(){const root=document.querySelector('#visualRoot');if(!root)return;if(!lastReport){root.innerHTML='<div class="card empty">Analyse a video first. Visuals + Audio will then sample the actual replay hotzones.</div>';return}buildMedia(lastReport,root)};
}else{
 window.renderVisuals=function(){const root=document.querySelector('#visualRoot');if(!root)return;if(!lastReport){root.innerHTML='<div class="card empty">Analyse a video first.</div>';return}buildMedia(lastReport,root)};
}

if(typeof record==='function'){
 const prevRecord=record;record=function(r){const x=prevRecord(r),mi=r.media_intelligence||{};x.sfxTypes=(mi.audio_events||[]).filter(a=>a.type==='sfx').map(a=>a.label);x.musicCues=(mi.audio_events||[]).filter(a=>a.type==='music').map(a=>a.label);x.mediaFrameSampled=!!mi.storyboard;x.audioTracks=[...(x.audioTracks||[]),...(mi.tracks||[]).map(a=>a.name)].filter(Boolean);return x};
}

const status=document.querySelector('#status');if(status)status.textContent='v0.10.4 ready';document.title='YTIntel v0.10.4 — Media Sampling';
const grid=document.querySelector('#updates .grid');if(grid&&!grid.querySelector('.release-104')){grid.querySelectorAll('.release.current').forEach(x=>x.classList.remove('current'));const a=document.createElement('article');a.className='card c12 release current release-104';a.innerHTML=`<div class="split"><div><div class="eyebrow">V0.10.4 · CURRENT</div><h2 style="margin:4px 0">Visuals stopped being a roadmap</h2><div class="source-note">5 Sep 2026</div></div><span class="pill good">LIVE</span></div><ul class="list"><li><b>Actual storyboard frame sampling is live:</b> before / peak / after frames are pulled at the strongest Most Replayed hotzones.</li><li><b>Fake “visual cause” placeholders removed.</b> If no frame source is available, the app says so.</li><li><b>Sound Effects section now prints real public caption-coded SFX cues</b> with timestamps when the source exposes them.</li><li><b>B-roll / Background Music now prints actual music cues and attributed tracks</b> when public evidence exists.</li><li>The app no longer tells the user to “separate speech/music/SFX.” That is YTIntel's job.</li></ul>`;grid.prepend(a)}
const modal=document.querySelector('#updateModal');if(modal){const panel=modal.querySelector('.update-panel');if(panel)panel.innerHTML=`<div class="update-top"><div class="grow"><span class="update-version">YTIntel v0.10.4 · 5 SEP 2026</span><h2>Visuals now show actual frames.</h2><p>The previous Visuals screen was a roadmap. This release samples real storyboard frames around replay peaks and only prints audio evidence that was actually detected.</p></div><button class="update-close" id="v104Close">×</button></div><div class="update-items"><div class="update-item"><div class="tick">✓</div><div><b>Before / peak / after frames</b><span class="muted">Real storyboard samples at Most Replayed hotzones.</span></div></div><div class="update-item"><div class="tick">✓</div><div><b>Sound Effects evidence</b><span class="muted">Caption-coded SFX cues with timestamps, when public captions expose them.</span></div></div><div class="update-item"><div class="tick">✓</div><div><b>Background music evidence</b><span class="muted">Music cues and attributed tracks only when actually detected.</span></div></div></div><div class="update-actions"><button class="primary" id="v104Continue">Continue</button><button id="v104Log">Full update log</button></div>`;const close=()=>{modal.classList.remove('show');try{localStorage.setItem(RELEASE,'seen')}catch{}};document.querySelector('#v104Close')?.addEventListener('click',close);document.querySelector('#v104Continue')?.addEventListener('click',close);document.querySelector('#v104Log')?.addEventListener('click',()=>{close();if(typeof tab==='function')tab('updates')});try{if(localStorage.getItem(RELEASE)!=='seen')setTimeout(()=>modal.classList.add('show'),380)}catch{}}
})();
