(function(){
const E=x=>typeof esc==='function'?esc(x):String(x??'');
const classifySaved=x=>{const s=`${x?.title||''} ${x?.channel||''}`.toLowerCase();if(/\b(gta|grand theft auto|rockstar)\b/.test(s))return'GTA';if(/\b(roblox|blox fruits|brookhaven)\b/.test(s))return'ROBLOX';if(/youtube automation|faceless youtube|faceless channel|cash cow/.test(s))return'YouTube Automation';if(/\b(chatgpt|openai|claude|anthropic|gemini|artificial intelligence|ai agent|prompt engineering|\bai\b)\b/.test(s))return'AI';if(/tutorial|how to|explained|guide|education|course|learn/.test(s))return'Info / Education';if(/minecraft|fortnite|gaming|gameplay/.test(s))return'Gaming';if(/trading|futures|forex|crypto|stock/.test(s))return'Trading / Finance';if(/fitness|gym|workout|bodybuilding/.test(s))return'Fitness';if(/dropship|shopify|ecommerce|e-commerce/.test(s))return'E-commerce';return x?.niche||'Other'};
function applyNicheFix(){
 if(typeof nicheFor==='function')nicheFor=function(r){return r?.content_niche||classifySaved({title:r?.video?.title,channel:r?.video?.channel,niche:'Other'})};
 try{const k='ytintel-v09-history',xs=JSON.parse(localStorage.getItem(k)||'[]');let changed=false;for(const x of xs){const n=classifySaved(x);if(n&&n!==x.niche){x.niche=n;changed=true}}if(changed){localStorage.setItem(k,JSON.stringify(xs));if(typeof renderHistory==='function'&&document.querySelector('#history')?.classList.contains('active'))renderHistory()}}catch{}
}
applyNicheFix();window.addEventListener('load',()=>{setTimeout(applyNicheFix,1800);setTimeout(applyNicheFix,3500)},{once:true});
function takeawayHtml(r){const c=r?.content_extraction||{},xs=c.items||[];if(!xs.length)return'';return `<article class="card c12"><div class="section-head"><div><div class="eyebrow">KEY TAKEAWAYS</div><h2>${c.target_count?`The ${c.target_count} actual ways / methods — with how to do them`:'What the video actually teaches'}</h2></div><span class="pill">content-grounded</span></div><div class="takeaway-list">${xs.map((x,i)=>`<div class="takeaway-row"><span class="n">${x.index||i+1}</span><div><b>${E(x.label||x.statement)}</b>${x.how_to_do||x.explanation?`<p class="muted" style="margin:5px 0 0">${E(x.how_to_do||x.explanation)}</p>`:''}${x.exact_line?`<small style="display:block;margin-top:5px;color:#8793a7">Evidence: “${E(x.exact_line)}”</small>`:''}</div><span class="approx">${E(x.timestamp||'')}</span></div>`).join('')}</div><div class="v10-note v10-good"><strong>Rule:</strong> if the video promises “5 ways”, this section must try to contain the five actual ways plus a concise explanation of how to do each one. Random transcript sentences are no longer treated as the list.</div></article>`}
function rehookHtml(r){const xs=r?.rehook_examples||[];return `<article class="card c12"><div class="eyebrow">RE-HOOK EXAMPLES</div><h2 style="margin:5px 0">Real attention resets from the video</h2>${xs.length?`<div class="takeaway-list">${xs.map((x,i)=>`<div class="takeaway-row"><span class="n">${i+1}</span><div><b>${E(x.excerpt)}</b><small style="display:block;margin-top:5px;color:#8793a7">${E(x.reason)}</small></div><span class="approx">${E(x.timestamp)}</span></div>`).join('')}</div>`:'<p class="muted">No explicit re-hook/section transition passed the evidence rule. YTIntel will not invent one.</p>'}</article>`}
function inject(r){const report=document.querySelector('#report');if(!report)return;report.querySelectorAll('[data-v107]').forEach(x=>x.remove());for(const e of [...report.querySelectorAll('.card .eyebrow')]){const t=(e.textContent||'').trim().toUpperCase();if(!e.closest('[data-v107]')&&(t.includes('KEY TAKEAWAYS')||t.includes('CLEAN POINTS')))e.closest('.card')?.remove()}
 const niche=document.createElement('article');niche.className='card c12';niche.dataset.v107='1';niche.innerHTML=`<div class="eyebrow">CONTENT NICHE</div><h2 style="margin:5px 0">${E(r.content_niche||'Other')}</h2><p class="muted">This is based on what the video is actually about — e.g. GTA, Info / Education, AI, ROBLOX or YouTube Automation — not the hook style.</p>`;const temp=document.createElement('div');temp.innerHTML=takeawayHtml(r)+rehookHtml(r);[...temp.children].forEach(x=>x.dataset.v107='1');const facts=report.querySelector('.facts-card');if(facts)facts.after(niche,...temp.children);else report.prepend(niche,...temp.children)}
if(typeof renderReport==='function'){const old=renderReport;renderReport=function(r){old(r);inject(r)}}
const updates=document.querySelector('#updates .grid');if(updates&&!updates.querySelector('[data-v107-release]')){const a=document.createElement('article');a.className='card c12 release current';a.dataset.v107Release='1';a.innerHTML=`<div class="eyebrow">V0.10.7 · 5 SEP 2026</div><h3>Actual analyser fixes — not just UI claims</h3><ul class="list"><li><b>Structured takeaways:</b> list videos now reconstruct the actual ways/methods and attach a concise how-to.</li><li><b>Re-hooks:</b> examples now come from explicit transcript section transitions / attention resets.</li><li><b>Niches:</b> History folders now use actual subject matter such as GTA, Info / Education, AI, ROBLOX and YouTube Automation rather than hook categories.</li><li><b>Visuals:</b> the media backend now reads YouTube's signed storyboard specification directly first, with multiple public mirror fallbacks after that.</li><li><b>AI Intelligence v0.10.6 is preserved below in the update log.</b></li></ul>`;updates.querySelectorAll('.release.current').forEach(x=>x.classList.remove('current'));updates.prepend(a)}
function settleStatus(){const s=document.querySelector('#status');if(!s)return;const cur=s.textContent||'';s.textContent=cur.toLowerCase().includes('key needed')?'v0.10.7 · fixes live · Sol AI key needed':'v0.10.7 · analyser fixes live'}
setTimeout(settleStatus,2800);
})();