(function(){
const VERSION='0.10.8', RELEASE='ytintel-whats-new-0.10.8';
const $=s=>document.querySelector(s);
function saveDraft(id,key){const el=$(id);if(!el)return;try{const old=localStorage.getItem(key);if(old&&!el.value)el.value=old}catch{};el.addEventListener('input',()=>{try{localStorage.setItem(key,el.value)}catch{}})}
function drafts(){saveDraft('#videoUrl','ytintel-draft-video');saveDraft('#similarQuery','ytintel-draft-similar');saveDraft('#channelQuery','ytintel-draft-channel');saveDraft('#batchUrls','ytintel-draft-batch')}
function networkPill(){let el=$('#networkState');if(!el){el=document.createElement('span');el.id='networkState';el.className='status';const s=$('#status');s?.insertAdjacentElement('afterend',el)}const draw=()=>{const on=navigator.onLine;el.textContent=on?'online':'offline';el.style.opacity=on?'.65':'1';el.style.borderColor=on?'':'rgba(255,196,92,.5)';el.title=on?'YTIntel can reach live analysis services.':'You are offline. Saved shell/history remain available; new analysis needs internet.'};window.addEventListener('online',draw);window.addEventListener('offline',draw);draw()}
function registerSW(){if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=0108').catch(()=>{}),{once:true})}
function release(){const g=$('#updates .grid');if(!g)return;g.querySelector('[data-v108-release]')?.remove();g.querySelectorAll('.release.current').forEach(x=>x.classList.remove('current'));const a=document.createElement('article');a.className='card c12 release current';a.dataset.v108Release='1';a.innerHTML=`<div class="eyebrow">V0.10.8 · 5 SEP 2026 · CURRENT</div><h3>Reliability + mobile app polish</h3><ul class="list"><li><b>Installable web app foundation:</b> YTIntel now has a manifest, app icon and service worker so supported devices can add it to the Home Screen / desktop like an app.</li><li><b>Draft protection:</b> pasted video URLs, Pattern Mine links and discovery searches survive accidental refreshes or tab closes.</li><li><b>Offline-safe shell:</b> the interface and saved browser history can still open when the network drops; new live analyses clearly still require internet.</li><li><b>Network status:</b> a small online/offline indicator now makes connection problems obvious instead of looking like a broken analyser.</li><li><b>Update system cleanup:</b> v0.10.8 is the only current popup. v0.10.7 analyser fixes and v0.10.6 AI Intelligence remain preserved in the full log.</li></ul>`;g.prepend(a);const v107=g.querySelector('[data-v107-release]');const ai=g.querySelector('[data-release="ai-intelligence"]');if(v107)a.insertAdjacentElement('afterend',v107);if(ai&&v107)v107.insertAdjacentElement('afterend',ai)}
function popupHtml(){return `<div class="update-panel"><div class="update-top"><div class="grow"><span class="update-version">YTIntel v0.10.8 · RELIABILITY POLISH</span><h2>YTIntel is safer to use like a real app.</h2><p class="muted">This release focuses on not losing work, handling weak connections better, and making the public GitHub Pages build behave more like an installable app.</p></div><button class="update-close" data-v108-close aria-label="Close">×</button></div><div class="update-items"><div class="update-item"><div class="tick">✓</div><div><b>Installable app foundation</b><span class="muted">Manifest, icon and service worker are now included for supported Home Screen / desktop installs.</span></div></div><div class="update-item"><div class="tick">✓</div><div><b>Your pasted work is remembered</b><span class="muted">Analysis URLs, Similar searches, channel searches and Pattern Mine lists persist through refreshes.</span></div></div><div class="update-item"><div class="tick">✓</div><div><b>Better offline behaviour</b><span class="muted">The app shell and browser-saved research can still open if your connection disappears.</span></div></div><div class="update-item"><div class="tick">✓</div><div><b>Cleaner update ownership</b><span class="muted">Only the newest release owns What’s New. Older AI and analyser updates stay in the log without hijacking the popup.</span></div></div></div><div class="v10-note"><strong>Core analyser:</strong> v0.10.7’s takeaway, re-hook, niche and visual-source fixes remain active. The v0.10.6 GPT-5.6 Sol milestone remains in the update log.</div><div class="update-actions"><button class="primary" data-v108-close>Continue</button><button data-v108-log>Full update log</button></div></div>`}
function wirePopup(){const m=$('#updateModal');if(!m)return;m.innerHTML=popupHtml();const close=()=>{m.classList.remove('show');try{localStorage.setItem(RELEASE,'seen')}catch{}};m.querySelectorAll('[data-v108-close]').forEach(x=>x.addEventListener('click',close));m.querySelector('[data-v108-log]')?.addEventListener('click',()=>{close();if(typeof tab==='function')tab('updates');else $('[data-tab="updates"]')?.click()});let b=$('#whatsNewBtn');if(b){const n=b.cloneNode(true);b.replaceWith(n);n.addEventListener('click',()=>{m.innerHTML=popupHtml();wirePopup();m.classList.add('show')})}}
function init(){drafts();networkPill();registerSW();release();wirePopup();const s=$('#status');if(s&&!/key needed/i.test(s.textContent||''))s.textContent='v0.10.8 · ready';let seen=false;try{seen=localStorage.getItem(RELEASE)==='seen'}catch{}if(!seen)setTimeout(()=>{$('#updateModal')?.classList.add('show')},250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();setTimeout(()=>{release();wirePopup()},7000);
})();