(function(){
'use strict';
const VERSION='0.16.0',TITLE=`YTIntel v${VERSION} — Smart Start`,RELEASE='ytintel-whats-new-0.16.0-smart-start';
const HEALTH='https://dkmacktcfhubsumwrydw.supabase.co/functions/v1/ytintel-v082?action=health';
if(document.documentElement.dataset.yt160Shell==='1')return;document.documentElement.dataset.yt160Shell='1';
window.YTINTEL_VERSION=VERSION;window.YTINTEL_UPDATE_OWNER=RELEASE;document.body.classList.add('yt-ui-v13');
const OLD=['ytintel-whats-new-0.10.1','ytintel-whats-new-0.10.2','ytintel-whats-new-0.10.4','ytintel-whats-new-0.10.5','ytintel-whats-new-0.10.7-actual','ytintel-whats-new-0.10.8','ytintel-whats-new-0.10.9','ytintel-whats-new-0.10.9-ai-live','ytintel-whats-new-0.11.0-actionboard','ytintel-whats-new-0.11.1-decision-gate','ytintel-whats-new-0.11.2-replication','ytintel-whats-new-0.12.0-opportunity-radar','ytintel-whats-new-0.12.1-packaging-lab','ytintel-whats-new-0.13.0-interface-rebuild','ytintel-whats-new-0.13.1-ui-stability','ytintel-whats-new-0.14.0-research-os','ytintel-whats-new-0.15.0-creator-loop'];try{OLD.forEach(k=>localStorage.setItem(k,'seen'))}catch{}
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const I=name=>{const p={os:'<path d="M4 17V9M9 17V5M14 17v-4M19 17V3"/><path d="M3 20h18"/><path d="m4 8 5-4 5 8 5-10"/>',loop:'<path d="M8 7H5a3 3 0 0 0-3 3v4a3 3 0 0 0 3 3h3"/><path d="M16 7h3a3 3 0 0 1 3 3v4a3 3 0 0 1-3 3h-3"/><path d="m14 4-4 16M8 12h8"/>',analyse:'<circle cx="11" cy="11" r="6.5"/><path d="m16 16 4 4"/><path d="M8.5 11h5M11 8.5v5"/>',radar:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4"/><path d="M12 12 18 6"/>',packaging:'<path d="m12 3 8 4-8 4-8-4 8-4Z"/><path d="m4 12 8 4 8-4M4 17l8 4 8-4"/>',history:'<path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5M12 7v5l3 2"/>',similar:'<circle cx="7" cy="7" r="3"/><circle cx="17" cy="17" r="3"/><path d="M9.5 8.5 14.5 15.5M17 4v6M14 7h6"/>',batch:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',visuals:'<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8.5" cy="9" r="1.5"/><path d="m4 17 5-5 3 3 2-2 6 5"/>',updates:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m16.5 16.5 4 4"/>'};return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${p[name]||p.search}</svg>`};
let explicit=false,enforcing=false,aiLive=null;const modal=()=>document.querySelector('#updateModal'),status=()=>document.querySelector('#status');
function lockTitle(){if(document.title!==TITLE)document.title=TITLE}
function lockStatus(){const s=status();if(!s)return;const w=aiLive===true?`v${VERSION} · GPT-5.6 Sol intelligence LIVE`:aiLive===false?`v${VERSION} · intelligence ready`:`v${VERSION} · checking intelligence…`;if(s.textContent!==w){enforcing=true;s.textContent=w;enforcing=false}s.classList.toggle('is-live',aiLive===true)}
async function health(){try{const r=await fetch(`${HEALTH}&t=${Date.now()}`,{cache:'no-store'}),d=await r.json();aiLive=!!(r.ok&&d&&d.configured)}catch{aiLive=null}lockStatus()}
function loadSmartAssets(){if(!document.querySelector('link[data-v160-smart]')){const l=document.createElement('link');l.rel='stylesheet';l.href='v160-smartstart.css?v=0160';l.dataset.v160Smart='1';document.head.appendChild(l)}if(!document.querySelector('script[data-v160-smart]')){const s=document.createElement('script');s.src='v160-smartstart.js?v=0160';s.dataset.v160Smart='1';document.body.appendChild(s)}}
function buildWorkspace(){const brand=document.querySelector('.brand');if(brand)brand.innerHTML='<span class="logo" aria-hidden="true">YT</span><span class="brand-copy"><strong>YTIntel</strong><small>Creator Intelligence OS</small></span>';const top=document.querySelector('.top > .split');if(top){top.classList.add('top-actions');if(!document.querySelector('#ytCommandBtn')){const b=document.createElement('button');b.type='button';b.className='btn small yt-command-btn no-print';b.id='ytCommandBtn';b.innerHTML=`${I('search')}<span>Quick switch</span><kbd>⌘K</kbd>`;top.insertBefore(b,top.firstChild)}}const nav=document.querySelector('.tabs');if(!nav)return;const cfg={os:['Command Center','os'],loop:['Creator Loop','loop'],analyse:['Analyse','analyse'],radar:['Opportunity Radar','radar'],packaging:['Packaging Lab','packaging'],history:['History','history'],similar:['Similar Videos','similar'],batch:['Pattern Mine','batch'],visuals:['Visuals + Audio','visuals'],updates:['Updates','updates']};nav.setAttribute('aria-label','YTIntel workspace');nav.querySelectorAll('button[data-tab]').forEach(b=>{const c=cfg[b.dataset.tab];if(!c)return;const beta=b.querySelector('.beta')?.outerHTML||'';b.innerHTML=`<span class="nav-ico">${I(c[1])}</span><span class="nav-label">${E(c[0])}</span>${beta}`;b.setAttribute('aria-label',c[0])});const group=(key,label)=>{if(nav.querySelector(`[data-nav-group="${key}"]`))return;const before=nav.querySelector(`[data-tab="${key}"]`);if(!before)return;const s=document.createElement('span');s.className='nav-group';s.dataset.navGroup=key;s.textContent=label;nav.insertBefore(s,before)};group('os','Start + Mission control');group('loop','Execution');group('analyse','Research');group('history','Library');group('updates','System');if(!document.querySelector('#ytWorkflowRail')){const r=document.createElement('div');r.id='ytWorkflowRail';r.className='workflow-rail no-print';r.setAttribute('aria-label','Core research workflow');nav.insertAdjacentElement('afterend',r)}}
function goTab(key,focus){document.querySelector(`.tabs [data-tab="${key}"]`)?.click();setTimeout(()=>{syncNav();syncRail();if(focus)document.querySelector(focus)?.focus()},30)}
const FLOW=[['radar','01','Discover','Find opportunity'],['analyse','02','Investigate','Deep evidence'],['batch','03','Validate','Cross-video proof'],['packaging','04','Package','Build execution'],['loop','05','Learn','Measure outcomes']];function has(k){try{const x=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(x)&&x.length>0}catch{return false}}
function syncNav(){const a=document.querySelector('.view.active')?.id;document.querySelectorAll('.tabs [data-tab]').forEach(b=>{const on=b.dataset.tab===a;b.classList.toggle('on',on);if(on)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')})}
function syncRail(){const r=document.querySelector('#ytWorkflowRail');if(!r)return;const active=document.querySelector('.view.active')?.id||'os',core=FLOW.some(x=>x[0]===active);r.classList.toggle('show',core);if(!core)return;const done={radar:has('ytintel-v120-radar-history'),analyse:has('ytintel-v09-history'),batch:has('ytintel-v10-pattern-history'),packaging:has('ytintel-v121-package-history'),loop:has('ytintel-v150-experiments')};const html=FLOW.map(x=>`<button type="button" class="flow-step ${x[0]===active?'current':''} ${done[x[0]]?'done':''}" data-flow="${x[0]}"><span class="flow-no">${done[x[0]]?'✓':x[1]}</span><span><strong>${x[2]}</strong><small>${x[3]}</small></span></button>`).join('');if(r.innerHTML===html)return;r.innerHTML=html;r.querySelectorAll('[data-flow]').forEach(b=>b.addEventListener('click',()=>goTab(b.dataset.flow)))}
const COMMANDS=[['Smart Start','Paste anything and let YTIntel choose the right workflow','os','#smartStartInput','G','os'],['Open Command Center','See market memory, momentum and next actions','os','','C','os'],['Open Creator Loop','Track packages through publishing and learn from outcomes','loop','','L','loop'],['Run Opportunity Radar','Discover and rank what is worth analysing','radar','#radarQuery','R','radar'],['Analyse a video','Open Deep Analyse and paste a YouTube URL','analyse','#videoUrl','A','analyse'],['Open Pattern Mine','Validate patterns across competitors','batch','#batchUrls','M','batch'],['Open Packaging Lab','Turn verified research into titles, thumbnails and hooks','packaging','#packageAngle','P','packaging'],['Research history','Return to saved niche intelligence','history','','H','history'],['Find similar videos','Explore adjacent videos and channel outliers','similar','#similarQuery','S','similar'],['Visuals + Audio','Inspect media evidence and replay hotzones','visuals','','V','visuals'],['Updates','Open the product changelog','updates','','U','updates']];let ov,inp,list,filtered=COMMANDS.slice(),selected=0;
function draw(q=''){const z=String(q||'').toLowerCase().trim();filtered=COMMANDS.filter(c=>!z||`${c[0]} ${c[1]}`.toLowerCase().includes(z));selected=Math.min(selected,Math.max(0,filtered.length-1));list.innerHTML=filtered.length?filtered.map((c,i)=>`<button type="button" class="yt-command-item" data-ci="${i}" aria-selected="${i===selected}"><span class="ci">${I(c[5])}</span><span><b>${E(c[0])}</b><small>${E(c[1])}</small></span><kbd>${c[4]}</kbd></button>`).join(''):'<div class="yt-command-empty">No matching workspace action.</div>';list.querySelectorAll('[data-ci]').forEach(b=>b.addEventListener('click',()=>run(Number(b.dataset.ci))))}
function run(i){const c=filtered[i];if(!c)return;closeCmd();goTab(c[2],c[3])}function openCmd(){ov.classList.add('show');document.body.style.overflow='hidden';selected=0;draw();setTimeout(()=>inp.focus(),20)}function closeCmd(){if(!ov)return;ov.classList.remove('show');document.body.style.overflow='';inp.value=''}
function buildCommands(){ov=document.querySelector('#ytCommandOverlay');if(!ov){ov=document.createElement('div');ov.id='ytCommandOverlay';ov.className='yt-command-overlay no-print';ov.setAttribute('role','dialog');ov.setAttribute('aria-modal','true');ov.innerHTML=`<div class="yt-command-panel"><div class="yt-command-search">${I('search')}<input id="ytCommandInput" type="search" autocomplete="off" placeholder="Jump anywhere in YTIntel…" aria-label="Search YTIntel commands"></div><div class="yt-command-list" id="ytCommandList"></div></div>`;document.body.appendChild(ov)}inp=ov.querySelector('#ytCommandInput');list=ov.querySelector('#ytCommandList');ov.addEventListener('mousedown',e=>{if(e.target===ov)closeCmd()});inp.addEventListener('input',()=>{selected=0;draw(inp.value)});inp.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();selected=Math.min(selected+1,filtered.length-1);draw(inp.value)}else if(e.key==='ArrowUp'){e.preventDefault();selected=Math.max(0,selected-1);draw(inp.value)}else if(e.key==='Enter'){e.preventDefault();run(selected)}else if(e.key==='Escape')closeCmd()});document.querySelector('#ytCommandBtn')?.addEventListener('click',openCmd);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();ov.classList.contains('show')?closeCmd():openCmd()}else if(e.key==='Escape'&&ov.classList.contains('show'))closeCmd()})}
function modalHtml(){return `<div class="update-panel"><div class="update-top"><div class="grow"><span class="update-version">YTIntel v${VERSION} · SMART START</span><h2>You no longer need to learn YTIntel before using it.</h2><p class="muted">Paste a video, channel, competitor set or topic. Smart Start detects what you supplied, chooses the right research workflow and keeps the next useful action in front of you.</p></div><button class="update-close" data-v160-close aria-label="Close">×</button></div><div class="update-items"><div class="update-item"><div class="tick">✓</div><div><b>One universal research box</b><span class="muted">Video → Analyse, channel → Outlier scan, 5–10 links → Pattern Mine, topic → Radar.</span></div></div><div class="update-item"><div class="tick">✓</div><div><b>Next-action guidance</b><span class="muted">Single-video reports now push users toward cross-video validation instead of accidental overfitting.</span></div></div><div class="update-item"><div class="tick">✓</div><div><b>Recent research resume</b><span class="muted">Return to recent videos, topics and competitor sets from the front door.</span></div></div><div class="update-item"><div class="tick">✓</div><div><b>Power tools stay available</b><span class="muted">The full Research OS remains underneath Smart Start for advanced workflows.</span></div></div></div><div class="update-actions"><button class="primary" data-v160-close>Continue</button><button data-v160-log>Full update log</button></div></div>`}
function closeModal(){const m=modal();if(!m)return;explicit=false;m.classList.remove('show');try{localStorage.setItem(RELEASE,'seen')}catch{}}function openModal(){const m=modal();if(!m)return;explicit=true;enforcing=true;m.innerHTML=modalHtml();m.classList.add('show');enforcing=false;m.querySelectorAll('[data-v160-close]').forEach(x=>x.addEventListener('click',closeModal));m.querySelector('[data-v160-log]')?.addEventListener('click',()=>{closeModal();goTab('updates')})}
function protectModal(){const m=modal();if(!m||enforcing)return;const tag=m.querySelector('.update-version')?.textContent||'';if(m.classList.contains('show')&&!explicit){enforcing=true;m.classList.remove('show');enforcing=false}if(explicit&&!tag.includes(`v${VERSION}`))openModal()}
function bindWhatsNew(){const b=document.querySelector('#whatsNewBtn');if(!b||b.dataset.v160==='1')return;b.dataset.v160='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();openModal()},true)}
function ensureRelease(){const g=document.querySelector('#updates .grid');if(!g||enforcing)return;enforcing=true;let a=g.querySelector('[data-v160-release]');g.querySelectorAll('.release.current').forEach(x=>{if(x!==a)x.classList.remove('current')});if(!a){a=document.createElement('article');a.className='card c12 release current';a.dataset.v160Release='1';a.innerHTML=`<div class="eyebrow">V${VERSION} · 5 SEP 2026 · CURRENT</div><h3>Smart Start — useful before you understand the product</h3><ul class="list"><li><b>Universal input:</b> paste a video, channel, 5–10 links or type a niche and YTIntel routes it automatically.</li><li><b>Single-video guardrail:</b> every Deep Analyse result now makes the cross-video validation step obvious.</li><li><b>Fast continuation:</b> recent videos, topics and pattern sets are one click away on the Command Center.</li><li><b>Zero dead-end batches:</b> 2–4 links are preserved in Pattern Mine and YTIntel tells you exactly how many more are required.</li><li><b>Advanced workflow preserved:</b> Radar, Pattern Mine, Packaging Lab, Creator Loop and Research OS remain fully accessible.</li></ul>`;g.prepend(a)}else{if(!a.classList.contains('current'))a.classList.add('current');if(g.firstElementChild!==a)g.prepend(a)}enforcing=false}
async function sw(){if(!('serviceWorker'in navigator))return;try{const reg=await navigator.serviceWorker.register('./sw.js?v=0160',{updateViaCache:'none'});await reg.update();if('caches'in window){const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('ytintel-shell-')&&k!=='ytintel-shell-v0160').map(k=>caches.delete(k)))}}catch{}}
function chromeStabilize(){if(enforcing)return;lockTitle();lockStatus();bindWhatsNew();protectModal();ensureRelease()}
loadSmartAssets();buildWorkspace();buildCommands();lockTitle();lockStatus();bindWhatsNew();ensureRelease();syncNav();syncRail();const m=modal();if(m)m.classList.remove('show');
const title=document.querySelector('title');if(title)new MutationObserver(lockTitle).observe(title,{childList:true,subtree:true,characterData:true});const chrome=new MutationObserver(chromeStabilize);const top=document.querySelector('.top');if(top)chrome.observe(top,{subtree:true,childList:true,characterData:true});if(m)chrome.observe(m,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});const updates=document.querySelector('#updates .grid');if(updates)chrome.observe(updates,{childList:true,attributes:true,subtree:true,attributeFilter:['class']});const views=new MutationObserver(()=>{syncNav();syncRail()});document.querySelectorAll('.view').forEach(v=>views.observe(v,{attributes:true,attributeFilter:['class']}));document.querySelectorAll('.tabs [data-tab]').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{syncNav();syncRail()},20)));
health();setTimeout(health,2500);setInterval(health,60000);window.addEventListener('focus',health);document.addEventListener('visibilitychange',()=>{if(!document.hidden)health()});window.addEventListener('load',sw,{once:true});
})();