(function(){
'use strict';
const VERSION='0.17.0';
const RADAR='ytintel-v120-radar-history';
const PACKAGES='ytintel-v121-package-history';
const EXPERIMENTS='ytintel-v150-experiments';
const SPRINTS='ytintel-v170-sprints';
const ACTIVE='ytintel-v170-active-sprint';
const PACKAGE_API='https://dkmacktcfhubsumwrydw.supabase.co/functions/v1/ytintel-v082?action=package';
const $=s=>document.querySelector(s);
const arr=x=>Array.isArray(x)?x:[];
const num=x=>Number(x);
const finite=x=>Number.isFinite(num(x));
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function read(k,f=[]){try{const x=JSON.parse(localStorage.getItem(k)||'null');return x==null?f:x}catch{return f}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}}
function toast(s){if(typeof window.YTIntelToast==='function')window.YTIntelToast(s)}
function go(tab,focus){document.querySelector(`.tabs [data-tab="${tab}"]`)?.click();setTimeout(()=>focus&&$(focus)?.focus(),40)}
function history(){return arr(read(SPRINTS,[]))}
function activeSprint(){const id=localStorage.getItem(ACTIVE)||'';return history().find(x=>x.id===id)||null}
function saveSprint(x){if(!x)return;const xs=history().filter(y=>y.id!==x.id);xs.unshift({...x,updated:Date.now()});write(SPRINTS,xs.slice(0,12));try{localStorage.setItem(ACTIVE,x.id)}catch{}render()}
function setStage(patch){const x=activeSprint();if(!x)return null;const n={...x,...patch,updated:Date.now()};saveSprint(n);return n}
function waitUntil(fn,timeout=160000,interval=400){return new Promise(async(resolve,reject)=>{const end=Date.now()+timeout;while(Date.now()<end){try{const v=fn();if(v)return resolve(v)}catch{}await sleep(interval)}reject(new Error('This step took too long. Completed research is still saved, so you can retry without losing the earlier work.'))})}
function radarHistory(){return arr(read(RADAR,[]))}
function latestScan(topic){const q=norm(topic);return radarHistory().find(x=>norm(x?.query)===q)||null}
function videoId(v){const direct=String(v?.id||'').trim();if(direct)return direct;const u=String(v?.url||'');return (u.match(/[?&]v=([^&]+)/)||u.match(/youtu\.be\/([^?&/]+)/)||u.match(/shorts\/([^?&/]+)/)||[])[1]||''}
function thumb(v){return v?.thumbnail||((id=>id?`https://i.ytimg.com/vi/${id}/hqdefault.jpg`:'')(videoId(v)))}
function enrichScan(scan){if(!scan)return scan;let changed=false;for(const v of arr(scan.videos)){if(!v.thumbnail){const t=thumb(v);if(t){v.thumbnail=t;changed=true}}}if(changed){const xs=radarHistory();const i=xs.findIndex(x=>x===scan||((x?.created===scan.created)&&norm(x?.query)===norm(scan.query)));if(i>=0){xs[i]=scan;write(RADAR,xs)}}return scan}
function chooseSet(scan){const vs=arr(scan?.videos).filter(v=>v?.url).slice().sort((a,b)=>(num(b.score)||0)-(num(a.score)||0));const clusters=arr(scan?.clusters).filter(c=>arr(c?.videos).filter(v=>v?.url).length>=5).slice().sort((a,b)=>(num(b.winners)||0)-(num(a.winners)||0)||(num(b.channels)||0)-(num(a.channels)||0));if(clusters.length){const c=clusters[0],chosen=[],seen=new Set;for(const v of arr(c.videos).slice().sort((a,b)=>(num(b.score)||0)-(num(a.score)||0))){const k=norm(v.channel);if(!seen.has(k)){chosen.push(v);seen.add(k)}}for(const v of arr(c.videos)){if(chosen.length>=8)break;if(v?.url&&!chosen.includes(v))chosen.push(v)}if(chosen.length>=5)return{videos:chosen.slice(0,8),basis:`Repeated concept: ${c.label||'cross-channel cluster'}`}}
 const chosen=[],seen=new Set;for(const v of vs){const k=norm(v.channel);if(chosen.length<5&&!seen.has(k)){chosen.push(v);seen.add(k)}}for(const v of vs){if(chosen.length>=8)break;if(!chosen.includes(v))chosen.push(v)}return{videos:chosen.slice(0,8),basis:'Highest-ranked channel-diverse Radar set'}}
function stats(set){const vs=arr(set?.videos),verified=vs.filter(v=>finite(v.outlier)).length,winners=vs.filter(v=>finite(v.outlier)&&num(v.outlier)>=1.5).length,controls=vs.filter(v=>finite(v.outlier)&&num(v.outlier)<1.15).length,channels=new Set(vs.map(v=>norm(v.channel)).filter(Boolean)).size;return{verified,winners,controls,channels,total:vs.length}}
function sourceVideo(v){return{title:v?.title||'',channel:v?.channel||'',url:v?.url||'',thumbnail:thumb(v),score:num(v?.score)||0,outlier:finite(v?.outlier)?num(v.outlier):null,confidence:v?.confidence||'',verdict:v?.verdict||'',age:finite(v?.age)?num(v.age):null,vpd:finite(v?.vpd)?num(v.vpd):null,replay:!!v?.replay,cluster:v?.cluster?{status:v.cluster.status||'',channels:num(v.cluster.channels)||0,winners:num(v.cluster.winners)||0,controls:num(v.cluster.controls)||0}:null}}
function packageResearch(scan,set,pattern,topic){const all=arr(scan?.videos).map(sourceVideo),selected=arr(set?.videos).map(sourceVideo),winners=selected.filter(v=>v.outlier!=null&&v.outlier>=1.5).sort((a,b)=>b.score-a.score),controls=all.filter(v=>v.outlier!=null&&v.outlier<1.15).sort((a,b)=>b.score-a.score).slice(0,4);return{query:topic,creator_angle:`Create a fresh original angle for ${topic}. Preserve evidence-backed mechanisms, but do not copy competitor wording, composition, jokes or story details.`,generated_at:new Date().toISOString(),research_sprint:{basis:set.basis,selected_count:selected.length,independent_channels:new Set(selected.map(v=>norm(v.channel)).filter(Boolean)).size,pattern_mine:pattern||null},winners:winners.length?winners:selected.slice(0,5),controls,clusters:arr(scan?.clusters).slice(0,6).map(c=>({label:c.label,status:c.status,channels:c.channels,winners:c.winners,controls:c.controls,videos:arr(c.videos).slice(0,6).map(v=>({title:v.title,channel:v.channel,outlier:v.outlier,score:v.score}))})),guardrails:{minimum_verified_winners:2,minimum_independent_channels:2,rule:'A Research Sprint must stop rather than convert a thin or one-creator sample into a strong recommendation.'}}}
async function runPattern(set,topic){if(typeof window.api!=='function')throw Error('YTIntel analysis engine is not ready. Reload the app and try again.');const urls=arr(set?.videos).map(v=>v.url).filter(Boolean).slice(0,10);const d=await window.api('batch',{urls,name:`Research Sprint — ${topic}`});const p=d?.pattern_mine_v09||d?.pattern_mine||null;if(!p)throw Error('Pattern Mine did not return a structured comparison for this set.');return p}
async function runPackage(research){const images=[...arr(research.winners),...arr(research.controls)].map(v=>v.thumbnail).filter(Boolean).slice(0,9);const r=await fetch(PACKAGE_API,{method:'POST',headers:{'content-type':'application/json','x-ytintel-client':'web-v170-sprint'},body:JSON.stringify({research,images})});const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw Error(d.error||`Packaging intelligence HTTP ${r.status}`);const a=d.intelligence||d,packages=arr(a.packages).slice().sort((x,y)=>(num(x.rank)||99)-(num(y.rank)||99));if(!packages.length)throw Error('Packaging intelligence returned no usable packages.');const rec={id:Date.now(),saved:Date.now(),query:research.query,angle:research.creator_angle,thesis:a.research_thesis||null,packages,pattern_mine:research.research_sprint?.pattern_mine||null,source:'Research Sprint'};const xs=arr(read(PACKAGES,[])).filter(x=>x.id!==rec.id);xs.unshift(rec);write(PACKAGES,xs.slice(0,20));return rec}
function bestPackage(rec){return arr(rec?.packages).slice().sort((a,b)=>(num(b.package_score)||0)-(num(a.package_score)||0))[0]||null}
function confidence(x){const p=bestPackage(x?.package),s=stats(x?.researchSet),ef=num(p?.evidence_fit)||0,rp=num(p?.replication)||0;if(s.winners>=3&&s.channels>=2&&ef>=78&&rp>=65)return'STRONG';if(s.winners>=2&&s.channels>=2&&ef>=60)return'TEST';return'EARLY'}
function repeated(pattern){return arr(pattern?.most_repeated).map(x=>x?.statement).filter(Boolean).slice(0,4)}
function brief(x){const p=bestPackage(x?.package);if(!p)return'';const s=stats(x.researchSet),pat=x.pattern||{},rep=repeated(pat),w=pat.winner_vs_pack||{};return `# YTIntel Research Sprint — Ready-to-Make Brief\n\nTopic: ${x.topic}\nEvidence level: ${confidence(x)}\nResearch set: ${s.total} videos across ${s.channels} channels\nVerified winners: ${s.winners}\nControls: ${s.controls}\n\n## Recommended video\n${p.title}\n\nConcept: ${p.concept||''}\nViewer promise: ${p.viewer_promise||''}\n\n## Validated cross-video pattern\n${rep.map(v=>`- ${v}`).join('\n')||'- No repeated statement cleared the Pattern Mine threshold.'}\n${w.hook_type?`Winner hook: ${w.hook_type} — ${w.hook_exact||''}`:''}\n\n## Thumbnail\nVisual: ${p.thumbnail?.visual||''}\nFocal subject: ${p.thumbnail?.focal_subject||''}\nComposition: ${p.thumbnail?.composition||''}\nText: ${p.thumbnail?.text||'No text'}\nCuriosity gap: ${p.thumbnail?.curiosity_gap||''}\nAvoid: ${p.thumbnail?.avoid||''}\n\n## Opening hook\n${p.opening_hook||''}\n\n## Scores\nPackage: ${Math.round(num(p.package_score)||0)}/100\nEvidence fit: ${Math.round(num(p.evidence_fit)||0)}/100\nReplication: ${Math.round(num(p.replication)||0)}/100\nNovelty: ${Math.round(num(p.novelty)||0)}/100\nClarity: ${Math.round(num(p.clarity)||0)}/100\n\n## Originality / risk\n${p.originality_delta||''}\nRisk: ${p.risk||''}\nKill condition: ${p.falsifier||''}\nTest plan: ${p.test_plan||''}\n\nGuardrail: these are research and execution signals, not predictions of views, CTR or causation.\n`}
function addToLoop(x){const p=bestPackage(x?.package);if(!p)return toast('No finished package is available.');let xs=arr(read(EXPERIMENTS,[]));if(xs.some(e=>e.title===p.title&&e.stage!=='reviewed'))return toast('This package is already in Creator Loop.');xs.unshift({id:`exp-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,created:Date.now(),updated:Date.now(),query:x.topic,angle:x.package?.angle||'',title:p.title,concept:p.concept||'',hypothesis:p.viewer_promise||p.concept||'',source:'Research Sprint',source_package_rank:p.rank||null,package_score:finite(p.package_score)?num(p.package_score):null,evidence_fit:finite(p.evidence_fit)?num(p.evidence_fit):null,replication:finite(p.replication)?num(p.replication):null,title_mechanism:p.title_mechanism||'',viewer_promise:p.viewer_promise||'',opening_hook:p.opening_hook||'',test_plan:p.test_plan||'',stage:'planned',published_url:'',snapshots:[],postmortem:''});write(EXPERIMENTS,xs.slice(0,80));toast('Research Sprint brief added to Creator Loop.');go('loop')}
const ORDER=['discover','validate','package','ready'];
function stepClass(x,name){const cur=ORDER.indexOf(x?.stage),idx=ORDER.indexOf(name);return idx<cur?'done':idx===cur?'current':''}
function steps(x){return `<div class="sprint-steps"><div class="${stepClass(x,'discover')}"><span>01</span><b>Discover</b><small>Find candidates</small></div><div class="${stepClass(x,'validate')}"><span>02</span><b>Validate</b><small>Cross-video proof</small></div><div class="${stepClass(x,'package')}"><span>03</span><b>Package</b><small>Build execution</small></div><div class="${stepClass(x,'ready')}"><span>04</span><b>Ready</b><small>Production brief</small></div></div>`}
function startView(){return `<section class="sprint-start"><div class="eyebrow">ONE GUIDED WORKFLOW</div><h1>Go from a niche to a video you can actually make.</h1><p>Research Sprint discovers current opportunities, validates them across multiple videos, then passes that structured evidence into Packaging intelligence and returns one traceable production brief.</p><div class="sprint-start-box"><input id="sprintTopic" type="search" enterkeyhint="go" placeholder="e.g. AI agents for small business"><button class="btn primary" id="sprintGo">Run full Research Sprint →</button></div><div class="sprint-explain"><span><b>1.</b> Find current opportunities</span><span><b>2.</b> Mine 5–8 competitors</span><span><b>3.</b> Build original packaging</span><span><b>4.</b> Leave with one brief</span></div><div class="source-note">A full sprint makes multiple public-video research requests and one Packaging intelligence call. It stops when the evidence is too thin.</div></section>`}
function workingView(x){const s=stats(x.researchSet);return `<section class="sprint-working">${steps(x)}<div class="sprint-status"><div class="sprint-pulse"></div><div class="grow"><div class="eyebrow">${E(x.topic)}</div><h2>${E(x.message||'Research Sprint is working…')}</h2><p>${x.stage==='discover'?'Finding candidates and checking channel-relative performance.':x.stage==='validate'?`Mining ${s.total} videos across ${s.channels} channels for repeated evidence and winner differences.`:'Feeding the validated set into Packaging intelligence to build an original execution.'}</p></div><button class="btn small" id="sprintCancel">Stop</button></div>${x.researchSet?`<div class="sprint-mini-evidence"><span><b>${s.total}</b> research videos</span><span><b>${s.winners}</b> verified winners</span><span><b>${s.controls}</b> controls</span><span><b>${E(x.researchSet.basis)}</b></span></div>`:''}</section>`}
function blockedView(x){return `<section class="sprint-blocked">${steps(x)}<div class="eyebrow">SPRINT NEEDS MORE EVIDENCE</div><h1>YTIntel stopped instead of manufacturing confidence.</h1><p>${E(x.message||'The current sample did not justify a production recommendation.')}</p><div class="actions"><button class="btn primary" id="sprintOpenRadar">Open Opportunity Radar</button><button class="btn" id="sprintRestart">New sprint</button></div></section>`}
function readyView(x){const p=bestPackage(x.package),s=stats(x.researchSet),rep=repeated(x.pattern),w=x.pattern?.winner_vs_pack||{};return `<div>${steps(x)}<section class="sprint-ready"><div class="sprint-ready-head"><div><div class="eyebrow">READY-TO-MAKE · ${E(confidence(x))} EVIDENCE</div><h1>${E(p?.title||'Production brief')}</h1><p>${E(p?.concept||p?.viewer_promise||'')}</p></div><div class="sprint-score"><b>${Math.round(num(p?.package_score)||0)}</b><span>package</span></div></div><div class="sprint-score-row"><span>evidence <b>${Math.round(num(p?.evidence_fit)||0)}</b></span><span>replication <b>${Math.round(num(p?.replication)||0)}</b></span><span>novelty <b>${Math.round(num(p?.novelty)||0)}</b></span><span>clarity <b>${Math.round(num(p?.clarity)||0)}</b></span></div><div class="sprint-grid"><article><div class="eyebrow">VALIDATED PATTERN</div>${rep.length?`<ul class="list">${rep.map(v=>`<li>${E(v)}</li>`).join('')}</ul>`:'<p>No repeated statement cleared the Pattern Mine threshold.</p>'}${w.hook_type?`<p><b>Winner hook:</b> ${E(w.hook_type)} — ${E(w.hook_exact||'')}</p>`:''}<div class="pillrow"><span class="pill">${s.total} videos</span><span class="pill">${s.channels} channels</span><span class="pill">${s.winners} winners</span></div></article><article><div class="eyebrow">THUMBNAIL</div><h3>${E(p?.thumbnail?.visual||'Visual direction')}</h3><p><b>Composition:</b> ${E(p?.thumbnail?.composition||'')}</p><p><b>Text:</b> ${E(p?.thumbnail?.text||'No text')}</p><p><b>Curiosity gap:</b> ${E(p?.thumbnail?.curiosity_gap||'')}</p><small>Avoid: ${E(p?.thumbnail?.avoid||'')}</small></article><article><div class="eyebrow">OPENING HOOK</div><blockquote>${E(p?.opening_hook||'')}</blockquote><p><b>Promise:</b> ${E(p?.viewer_promise||'')}</p></article><article><div class="eyebrow">RISK / TEST</div><p>${E(p?.risk||'')}</p><p><b>Kill condition:</b> ${E(p?.falsifier||'')}</p><p><b>Test plan:</b> ${E(p?.test_plan||'')}</p></article></div><div class="actions sprint-ready-actions"><button class="btn primary" id="sprintTrack">Track in Creator Loop</button><button class="btn" id="sprintCopy">Copy production brief</button><button class="btn" id="sprintOpenPackaging">Open Packaging Lab</button><button class="btn" id="sprintRestart">New sprint</button></div><div class="os-guardrail">Research Sprint uses public evidence and model reasoning as decision support. It does not promise views, CTR, virality or causation.</div></section></div>`}
function renderRecent(){const root=$('#sprintRecent');if(!root)return;const xs=history();root.innerHTML=xs.length?`<div class="eyebrow">RECENT SPRINTS</div>${xs.slice(0,5).map(x=>`<button data-sprint-open="${E(x.id)}"><span>${E((x.stage||'').toUpperCase())}</span><b>${E(x.topic)}</b><small>${new Date(x.updated||x.created).toLocaleString()}</small></button>`).join('')}`:'';root.querySelectorAll('[data-sprint-open]').forEach(b=>b.addEventListener('click',()=>{try{localStorage.setItem(ACTIVE,b.dataset.sprintOpen)}catch{}render()}))}
function render(){const root=$('#sprintRoot');if(!root)return;const x=activeSprint();root.innerHTML=!x?startView():x.stage==='ready'?readyView(x):x.stage==='blocked'||x.stage==='cancelled'?blockedView(x):workingView(x);renderRecent();$('#sprintGo')?.addEventListener('click',()=>start($('#sprintTopic')?.value.trim()));$('#sprintTopic')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();start(e.currentTarget.value.trim())}});$('#sprintCancel')?.addEventListener('click',()=>{const a=activeSprint();if(a)saveSprint({...a,running:false,stage:'cancelled',message:'Sprint stopped. Completed evidence was kept.'})});$('#sprintRestart')?.addEventListener('click',()=>{try{localStorage.removeItem(ACTIVE)}catch{}render();setTimeout(()=>$('#sprintTopic')?.focus(),30)});$('#sprintOpenRadar')?.addEventListener('click',()=>go('radar','#radarQuery'));$('#sprintOpenPackaging')?.addEventListener('click',()=>go('packaging','#packageAngle'));$('#sprintTrack')?.addEventListener('click',()=>addToLoop(activeSprint()));$('#sprintCopy')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(brief(activeSprint()));toast('Production brief copied.')}catch{toast('Copy is unavailable in this browser.')}})}
async function start(topic){topic=String(topic||'').trim();if(!topic)return toast('Type the niche or topic you want to research.');if(!navigator.onLine)return toast('A Research Sprint needs internet access.');const id=`sprint-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,before=localStorage.getItem(RADAR)||'';saveSprint({id,created:Date.now(),updated:Date.now(),topic,stage:'discover',running:true,message:'Discovering and verifying current opportunities…'});go('sprint');try{const q=$('#radarQuery');if(q)q.value=topic;const rb=$('#radarBtn');if(!rb)throw Error('Opportunity Radar is not ready. Reload YTIntel and try again.');rb.click();let scan=await waitUntil(()=>{const raw=localStorage.getItem(RADAR)||'';if(raw===before)return null;return latestScan(topic)},150000);scan=enrichScan(scan);const set=chooseSet(scan),s=stats(set);if(s.total<5){saveSprint({...activeSprint(),scan,researchSet:set,running:false,stage:'blocked',message:`Radar found only ${s.total} usable videos. Pattern Mine needs at least 5, so the sprint stopped instead of padding the sample.`});return}if(s.winners<2||s.channels<2){saveSprint({...activeSprint(),scan,researchSet:set,running:false,stage:'blocked',message:`The selected set has ${s.winners} verified winner${s.winners===1?'':'s'} across ${s.channels} channel${s.channels===1?'':'s'}. YTIntel needs at least 2 verified winners across 2 independent channels before it will build a production recommendation.`});return}saveSprint({...activeSprint(),scan,researchSet:set,stage:'validate',message:`Pattern-mining ${s.total} competitors across ${s.channels} channels…`});const pattern=await runPattern(set,topic);saveSprint({...activeSprint(),pattern,stage:'package',message:'Turning the validated evidence into original packaging…'});const research=packageResearch(scan,set,pattern,topic),pack=await runPackage(research);saveSprint({...activeSprint(),research,package:pack,running:false,stage:'ready',message:'Your ready-to-make brief is complete.'});toast('Research Sprint complete. Your production brief is ready.')}catch(e){saveSprint({...activeSprint(),running:false,stage:'blocked',message:e?.message||String(e)})}}
function injectSmartStart(){const s=$('#smartStart');if(!s||$('#smartSprintBtn'))return;const controls=s.querySelector('.ss-controls > div');if(!controls)return;const b=document.createElement('button');b.id='smartSprintBtn';b.type='button';b.className='btn small';b.textContent='Full Research Sprint';b.addEventListener('click',()=>{const value=$('#smartStartInput')?.value.trim()||'';go('sprint','#sprintTopic');if(value&&!/https?:\/\//i.test(value))setTimeout(()=>{const i=$('#sprintTopic');if(i)i.value=value},70)});controls.insertBefore(b,controls.firstChild)}
function init(){document.querySelector('[data-tab="sprint"]')?.addEventListener('click',()=>setTimeout(render,20));render();injectSmartStart();setTimeout(injectSmartStart,600);setTimeout(injectSmartStart,2200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
