(function(){
'use strict';
if(document.documentElement.dataset.yt180Premium==='1')return;
document.documentElement.dataset.yt180Premium='1';
document.body.classList.add('yt-ui-v18');
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(k,f=[])=>{try{const x=JSON.parse(localStorage.getItem(k)||'null');return x==null?f:x}catch{return f}};
const count=k=>{const x=read(k,[]);return Array.isArray(x)?x.length:(x&&typeof x==='object'?Object.keys(x).length:0)};
function go(tab,focus){document.querySelector(`.tabs [data-tab="${tab}"]`)?.click();setTimeout(()=>focus&&$(focus)?.focus(),60)}
function navHierarchy(){const nav=$('.tabs');if(!nav||nav.dataset.v18==='1')return;nav.dataset.v18='1';nav.querySelectorAll('.nav-group').forEach(x=>x.remove());const take=keys=>keys.map(k=>nav.querySelector(`[data-tab="${k}"]`)).filter(Boolean);const section=(cls,label,nodes)=>{const d=document.createElement('div');d.className=`yt-nav-section ${cls}`;if(label){const k=document.createElement('div');k.className='yt-nav-kicker';k.textContent=label;d.appendChild(k)}nodes.forEach(n=>d.appendChild(n));return d};const core=section('yt-nav-core','Core',take(['os','sprint','analyse','loop']));const tools=section('yt-nav-tools','',[]);tools.dataset.open='false';const toggle=document.createElement('button');toggle.type='button';toggle.className='yt-toolkit-toggle';toggle.innerHTML='<span>Research toolkit</span><span class="chev">⌄</span>';const items=document.createElement('div');items.className='yt-toolkit-items';take(['radar','packaging','batch','similar','visuals','history']).forEach(n=>items.appendChild(n));tools.append(toggle,items);const system=section('yt-nav-system','System',take(['updates']));nav.replaceChildren(core,tools,system);const setOpen=v=>{tools.dataset.open=v?'true':'false';try{localStorage.setItem('ytintel-v18-toolkit',v?'1':'0')}catch{}};let pref=false;try{pref=localStorage.getItem('ytintel-v18-toolkit')==='1'}catch{}setOpen(pref);toggle.addEventListener('click',()=>setOpen(tools.dataset.open!=='true'));const sync=()=>{const active=$('.view.active')?.id;if(['radar','packaging','batch','similar','visuals','history'].includes(active))setOpen(true)};$$('.view').forEach(v=>new MutationObserver(sync).observe(v,{attributes:true,attributeFilter:['class']}));sync()}
function smartStart(){const start=$('#smartStart');if(!start||start.dataset.v18==='1')return;start.dataset.v18='1';const h=start.querySelector('.ss-copy h1'),p=start.querySelector('.ss-copy p'),eye=start.querySelector('.ss-copy .eyebrow');if(eye)eye.textContent='CREATOR INTELLIGENCE · START WITH ANY SIGNAL';if(h)h.textContent='Turn creator research into your next winning video.';if(p)p.textContent='Paste a topic, video, channel or competitor set. YTIntel discovers the opportunity, validates the pattern, and turns the evidence into a production-ready next move.';const main=document.createElement('div');main.className='yt-start-main';['.ss-copy','.ss-input-wrap','#smartStartRecent','.ss-proof'].forEach(sel=>{const n=start.querySelector(sel);if(n)main.appendChild(n)});const visual=document.createElement('aside');visual.className='yt-start-visual';visual.innerHTML='<div class="yt-visual-label"><span>Intelligence flow</span><span class="yt-live-dot">Live</span></div><div class="yt-flow"><div class="yt-flow-node"><span class="yt-flow-no">01</span><div><b>Input the market</b><small>Topic, video, channel or competitor set</small></div></div><div class="yt-flow-node"><span class="yt-flow-no">02</span><div><b>Find the breakout</b><small>Channel-relative opportunity and velocity</small></div></div><div class="yt-flow-node"><span class="yt-flow-no">03</span><div><b>Validate the mechanism</b><small>Cross-video evidence, controls and repetition</small></div></div><div class="yt-flow-node"><span class="yt-flow-no">04</span><div><b>Build an original package</b><small>Title, thumbnail, hook and execution logic</small></div></div><div class="yt-flow-node"><span class="yt-flow-no">05</span><div><b>Leave with a brief</b><small>Evidence, risk, kill condition and test plan</small></div></div></div>';const layout=document.createElement('div');layout.className='yt-start-layout';layout.append(main,visual);start.replaceChildren(layout)}
function pulse(){const start=$('#smartStart');if(!start)return;let root=$('#ytIntelPulse');if(!root){root=document.createElement('section');root.id='ytIntelPulse';root.className='yt-intel-pulse';start.after(root)}const stats=[[count('ytintel-v170-sprints'),'Research sprints'],[count('ytintel-v120-radar-history'),'Radar scans'],[count('ytintel-v121-package-history'),'Packages built'],[count('ytintel-v150-experiments'),'Creator Loop items']];root.innerHTML=`<div class="yt-pulse-head"><div><div class="eyebrow">INTELLIGENCE PULSE</div><h2>Your research gets more useful as it compounds.</h2></div></div><div class="yt-pulse-grid">${stats.map(([n,l])=>`<div class="yt-pulse-stat"><b>${n}</b><span>${E(l)}</span></div>`).join('')}</div>`}
function powerGrid(){if($('#ytPowerGrid')||!$('#ytIntelPulse'))return;const grid=document.createElement('section');grid.id='ytPowerGrid';grid.className='yt-power-grid';grid.innerHTML='<article class="yt-power-card"><div class="yt-power-icon">↗</div><h3>Find breakout opportunities</h3><p>Separate raw popularity from channel-relative performance, recency and repeatable market signals.</p></article><article class="yt-power-card"><div class="yt-power-icon">⌁</div><h3>Validate across competitors</h3><p>Compare winners with controls and independent creators before calling a pattern real.</p></article><article class="yt-power-card"><div class="yt-power-icon">◇</div><h3>Build original packaging</h3><p>Translate the proven mechanism into a fresh title, thumbnail, opening hook and execution plan.</p></article>';$('#ytIntelPulse').after(grid)}
function featuredBrief(){if($('#ytFeaturedBrief')||!$('#ytPowerGrid'))return;const el=document.createElement('section');el.id='ytFeaturedBrief';el.className='yt-featured-brief';el.innerHTML='<div class="yt-featured-copy"><div class="eyebrow">EXAMPLE OUTPUT · ILLUSTRATIVE</div><h2>Research should end with something you can actually make.</h2><p>The final brief compresses the market evidence into one production decision instead of leaving you with another dashboard to interpret.</p><div class="yt-featured-points"><div><b>Validated pattern</b><span>What repeated across independent winners.</span></div><div><b>Original package</b><span>What to preserve versus deliberately change.</span></div><div><b>Kill condition</b><span>What would prove the idea was wrong.</span></div></div><button type="button" class="btn primary" data-yt-go="sprint">Build my next-video brief →</button></div><div class="yt-featured-preview"><div class="yt-mini-brief"><div class="yt-mini-title">Ready-to-Make Brief</div><div class="yt-mini-row"><span>Hook</span><b>Show the result before explaining the setup.</b></div><div class="yt-mini-row"><span>Thumbnail</span><b>One clear contrast. Minimal text.</b></div><div class="yt-mini-row"><span>Pattern</span><b>Payoff-first opening + concrete transformation.</b></div><div class="yt-mini-row"><span>Risk</span><b>Do not treat one creator result as causal proof.</b></div></div></div>';$('#ytPowerGrid').after(el);const trust=document.createElement('div');trust.className='yt-trust-strip';trust.innerHTML='<span>Evidence-first</span><span>Cross-channel validation</span><span>No false confidence</span><span>Original execution</span>';el.after(trust)}
function topTrust(){const top=$('.top-actions');if(!top||$('#ytTrustChip'))return;const x=document.createElement('span');x.id='ytTrustChip';x.className='yt-trust-chip no-print';x.textContent='Evidence-first';const status=$('#status');top.insertBefore(x,status||null)}
function bind(){document.addEventListener('click',e=>{const x=e.target.closest('[data-yt-go]');if(x){e.preventDefault();go(x.dataset.ytGo)}});window.addEventListener('focus',pulse);window.addEventListener('storage',pulse)}
function refresh(){navHierarchy();smartStart();pulse();powerGrid();featuredBrief();topTrust()}
function init(){refresh();bind();setTimeout(refresh,250);setTimeout(refresh,900);setTimeout(refresh,2400)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
