(function(){
'use strict';
if(document.documentElement.dataset.yt220Pro==='1')return;
document.documentElement.dataset.yt220Pro='1';
document.body.classList.add('yt-ui-v22');
const CREATOR='ytintel-v220-creator',COMPETITORS='ytintel-v220-competitors',COMP_RESULTS='ytintel-v220-competitor-results',VAULT='ytintel-v220-vault';
const RADAR='ytintel-v120-radar-history',PACKAGES='ytintel-v121-package-history',SPRINTS='ytintel-v170-sprints',EXPERIMENTS='ytintel-v150-experiments';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(k,f='')=>{try{return localStorage.getItem(k)||f}catch{return f}};
const write=(k,v)=>{try{localStorage.setItem(k,v);return true}catch{return false}};
const readJson=(k,f=[])=>{try{const x=JSON.parse(localStorage.getItem(k)||'null');return x==null?f:x}catch{return f}};
const writeJson=(k,v)=>write(k,JSON.stringify(v));
const arr=x=>Array.isArray(x)?x:[];
const num=x=>Number(x);
const finite=x=>Number.isFinite(num(x));
const fmt=x=>finite(x)?new Intl.NumberFormat(undefined,{notation:'compact',maximumFractionDigits:1}).format(num(x)):'—';
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
function toast(s){if(typeof window.YTIntelToast==='function')window.YTIntelToast(s);else console.info('[YTIntel]',s)}
function go(tab,focus){document.querySelector(`.tabs [data-tab="${tab}"]`)?.click();setTimeout(()=>focus&&$(focus)?.focus(),80)}
function creator(){return readJson(CREATOR,{name:'',channel:'',niche:'',goal:'Grow with evidence-backed videos'})}
function competitors(){return arr(readJson(COMPETITORS,[]))}
function competitorResults(){return arr(readJson(COMP_RESULTS,[]))}
function vault(){return arr(readJson(VAULT,[]))}
function radar(){return arr(readJson(RADAR,[]))}
function packages(){return arr(readJson(PACKAGES,[]))}
function experiments(){return arr(readJson(EXPERIMENTS,[]))}
function latestRadar(){return radar()[0]||null}
function topOpportunity(){const s=latestRadar();return arr(s?.videos).slice().sort((a,b)=>(num(b.score)||0)-(num(a.score)||0))[0]||null}
function topPackage(){const p=packages()[0];if(!p)return null;return arr(p.packages).slice().sort((a,b)=>(num(b.package_score)||0)-(num(a.package_score)||0))[0]||null}
function counts(){const r=latestRadar(),vs=arr(r?.videos);return{candidates:vs.length,priority:vs.filter(x=>x.verdict==='PRIORITY').length,saved:vault().length,experiments:experiments().length,tracked:competitors().length}}
function urlId(u){const s=String(u||'');return (s.match(/[?&]v=([^&]+)/)||s.match(/youtu\.be\/([^?&/]+)/)||s.match(/shorts\/([^?&/]+)/)||[])[1]||''}
function thumb(v){return v?.thumbnail||((id)=>id?`https://i.ytimg.com/vi/${id}/hqdefault.jpg`:'')(v?.id||urlId(v?.url))}
function saveIdea(v,source='Research'){
  if(!v?.url)return toast('This item has no usable YouTube URL.');
  const xs=vault();if(xs.some(x=>x.url===v.url))return toast('Already saved in Idea Vault.');
  xs.unshift({id:`idea-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,saved:Date.now(),stage:'WATCH',source,title:v.title||'Saved video',channel:v.channel||'Unknown channel',url:v.url,thumbnail:thumb(v),score:finite(v.score)?num(v.score):null,outlier:finite(v.outlier)?num(v.outlier):finite(v.outlier_multiple)?num(v.outlier_multiple):null,confidence:v.confidence||'',verdict:v.verdict||'',note:''});
  writeJson(VAULT,xs.slice(0,80));toast('Saved to Idea Vault.');renderCommandCenter();decorateRadar()
}
function removeIdea(id){writeJson(VAULT,vault().filter(x=>x.id!==id));renderCommandCenter();decorateRadar()}
const STAGES=['WATCH','SHORTLIST','BUILD','PUBLISHED'];
function nextStage(id){const xs=vault(),x=xs.find(y=>y.id===id);if(!x)return;const i=STAGES.indexOf(x.stage);x.stage=STAGES[(i+1)%STAGES.length];x.updated=Date.now();writeJson(VAULT,xs);renderCommandCenter()}
function latestScanVideo(url){for(const scan of radar())for(const v of arr(scan?.videos))if(v?.url===url)return v;return null}
function metricTone(n,kind){if(kind==='outlier')return finite(n)&&num(n)>=1.5?'good':finite(n)&&num(n)<1.15?'hot':'';return finite(n)&&num(n)>=78?'good':finite(n)&&num(n)>=62?'warn':''}
function nextMove(){
  const op=topOpportunity(),pkg=topPackage(),ex=experiments();
  if(!latestRadar())return{eyebrow:'START HERE',title:'Find the market signal first.',text:'Run one Research Sprint or Opportunity Radar scan. YTIntel cannot recommend a serious production move before it has market evidence.',action:'Run Research Sprint',tab:'sprint'};
  if(op?.verdict==='PRIORITY'&&!pkg)return{eyebrow:'BEST NEXT MOVE',title:'Turn the strongest opportunity into packaging.',text:`${op.title} currently leads the latest Radar scan. Build an original title + thumbnail + hook against the verified evidence before production.`,action:'Open Packaging Lab',tab:'packaging'};
  if(pkg&&!ex.length)return{eyebrow:'BEST NEXT MOVE',title:'Move the best package into production.',text:`“${pkg.title}” is the strongest saved package right now. Put it into Creator Loop so the hypothesis, publish step and outcome are tracked.`,action:'Open Creator Loop',tab:'loop'};
  if(pkg&&ex.length)return{eyebrow:'BEST NEXT MOVE',title:'Keep the research → publish → learn loop moving.',text:'You have market research, packaging and Creator Loop history. Prioritise one test, publish it, then record the public outcome before repeating the mechanism.',action:'Open Creator Loop',tab:'loop'};
  return{eyebrow:'BEST NEXT MOVE',title:'Strengthen the evidence before production.',text:'The current Radar scan has not produced a fully verified priority yet. Broaden discovery or validate more same-niche videos.',action:'Open Radar',tab:'radar'}
}
function workspaceLabel(){const c=creator();return c.name||c.niche||'Your creator workspace'}
function creatorCard(){const c=creator();return `<section class="v22-workspace-card"><div><div class="eyebrow">CREATOR WORKSPACE</div><h2>${E(workspaceLabel())}</h2><p>${E(c.niche||'Add your niche so YTIntel can keep the workspace focused around what you actually create.')}</p></div><div class="v22-workspace-meta"><span><small>Goal</small><b>${E(c.goal||'Grow with evidence-backed videos')}</b></span>${c.channel?`<span><small>Channel</small><b>${E(c.channel)}</b></span>`:''}<button type="button" class="btn small" data-v22-setup>${c.name||c.channel||c.niche?'Edit workspace':'Set up workspace'}</button></div></section>`}
function signalCard(){const op=topOpportunity();if(!op)return `<article class="v22-signal-card empty"><div class="eyebrow">TOP OPPORTUNITY</div><h3>No market signal yet</h3><p>Run Radar or a Research Sprint and the strongest channel-relative opportunity will appear here.</p><button class="btn primary" data-v22-go="radar">Find opportunities</button></article>`;const o=finite(op.outlier)?`${num(op.outlier).toFixed(1)}× baseline`:'baseline unverified';return `<article class="v22-signal-card"><div class="v22-signal-top"><div><div class="eyebrow">TOP OPPORTUNITY · ${E(op.verdict||'VERIFY')}</div><h3>${E(op.title)}</h3><p>${E(op.channel||'Unknown channel')}</p></div><div class="v22-score-ring" style="--score:${Math.max(0,Math.min(100,num(op.score)||0))}"><strong>${Math.round(num(op.score)||0)}</strong><small>signal</small></div></div><div class="v22-chips"><span class="${metricTone(op.outlier,'outlier')}">${E(o)}</span><span>${E(op.confidence||'LOW')} confidence</span>${op.cluster?.status?`<span>${E(op.cluster.status)}</span>`:''}</div><div class="v22-card-actions"><button class="btn small primary" data-v22-analyse="${E(op.url)}">Deep analyse</button><button class="btn small" data-v22-save-url="${E(op.url)}">Save idea</button><button class="btn small" data-v22-go="packaging">Build packaging</button></div></article>`}
function packageCard(){const p=topPackage();if(!p)return `<article class="v22-package-card empty"><div class="eyebrow">BEST PACKAGE</div><h3>Packaging becomes useful after evidence.</h3><p>Once Radar verifies the market, the strongest title + thumbnail + hook combination will live here.</p><button class="btn" data-v22-go="packaging">Open Packaging Lab</button></article>`;return `<article class="v22-package-card"><div class="eyebrow">BEST PACKAGE · ${E((p.recommendation||'TEST').toUpperCase())}</div><h3>${E(p.title)}</h3><p>${E(p.concept||p.viewer_promise||'')}</p><div class="v22-mini-score"><span><small>Package</small><b>${Math.round(num(p.package_score)||0)}</b></span><span><small>Evidence</small><b>${Math.round(num(p.evidence_fit)||0)}</b></span><span><small>Replication</small><b>${Math.round(num(p.replication)||0)}</b></span></div><div class="v22-card-actions"><button class="btn small primary" data-v22-go="packaging">Open package</button><button class="btn small" data-v22-copy-title="${E(p.title)}">Copy title</button><button class="btn small" data-v22-go="loop">Move to Creator Loop</button></div></article>`}
function vaultCard(){const xs=vault().slice(0,6);return `<section class="v22-panel v22-vault"><div class="v22-panel-head"><div><div class="eyebrow">IDEA VAULT</div><h2>Research worth coming back to</h2><p>Save opportunities instead of losing them in tabs. Move each one from watch → shortlist → build → published.</p></div><span class="v22-count">${vault().length}</span></div>${xs.length?`<div class="v22-vault-list">${xs.map(x=>`<article class="v22-vault-row"><img src="${E(x.thumbnail||'')}" alt="" loading="lazy"><div class="grow"><b>${E(x.title)}</b><small>${E(x.channel)} · ${E(x.source)}</small><div class="v22-vault-metrics">${finite(x.score)?`<span>signal ${Math.round(num(x.score))}</span>`:''}${finite(x.outlier)?`<span>${num(x.outlier).toFixed(1)}× baseline</span>`:''}</div></div><button type="button" class="v22-stage" data-v22-stage="${E(x.id)}">${E(x.stage)}</button><button type="button" class="v22-icon-btn" data-v22-vault-analyse="${E(x.url)}" aria-label="Analyse">↗</button><button type="button" class="v22-icon-btn" data-v22-remove="${E(x.id)}" aria-label="Remove">×</button></article>`).join('')}</div><button type="button" class="btn small" data-v22-compare>Compare top saved ideas</button>`:'<div class="v22-empty-state"><b>Your shortlist is empty.</b><span>Save from Opportunity Radar or Competitor Watchtower and YTIntel will keep the decision trail here.</span><button class="btn small" data-v22-go="radar">Open Radar</button></div>'}</section>`}
function watchtowerCard(){const cs=competitors(),rs=competitorResults().slice(0,8);return `<section class="v22-panel v22-watchtower"><div class="v22-panel-head"><div><div class="eyebrow">COMPETITOR WATCHTOWER</div><h2>Track channels you actually care about</h2><p>Add competitor channels once. Scan them together and surface their strongest verified breakouts without retyping every channel.</p></div><span class="v22-count">${cs.length}</span></div><div class="v22-competitor-add"><input id="v22CompetitorInput" placeholder="Paste a channel URL or channel name"><button class="btn" data-v22-add-competitor>Add</button><button class="btn primary" data-v22-scan ${cs.length?'':'disabled'}>Scan tracked channels</button></div>${cs.length?`<div class="v22-competitor-chips">${cs.map((x,i)=>`<span>${E(x)} <button data-v22-drop-competitor="${i}" aria-label="Remove">×</button></span>`).join('')}</div>`:'<div class="v22-source-note">Tip: track 3–10 direct competitors, not every creator in the niche.</div>'}<div id="v22WatchtowerResults">${rs.length?`<div class="v22-watch-results">${rs.map(x=>`<article><img src="${E(x.thumbnail||'')}" alt="" loading="lazy"><div class="grow"><b>${E(x.title)}</b><small>${E(x.channel)}${finite(x.outlier)?` · ${num(x.outlier).toFixed(1)}× baseline`:''}${finite(x.views)?` · ${fmt(x.views)} views`:''}</small></div><button class="btn small" data-v22-watch-analyse="${E(x.url)}">Analyse</button><button class="btn small" data-v22-watch-save="${E(x.url)}">Save</button></article>`).join('')}</div>`:'<div class="v22-empty-state compact"><b>No Watchtower scan saved yet.</b><span>Add channels, then scan them together.</span></div>'}</div></section>`}
function briefText(){const c=creator(),op=topOpportunity(),p=topPackage(),cs=counts(),saved=vault().slice(0,5);return `# YTIntel Creator Intelligence Brief\n\nWorkspace: ${workspaceLabel()}\nNiche: ${c.niche||'Not set'}\nGoal: ${c.goal||'Grow with evidence-backed videos'}\n\n## Workspace snapshot\n- Latest Radar candidates: ${cs.candidates}\n- Verified Priority signals: ${cs.priority}\n- Saved ideas: ${cs.saved}\n- Creator Loop items: ${cs.experiments}\n- Tracked competitors: ${cs.tracked}\n\n## Best next move\n${nextMove().title}\n${nextMove().text}\n\n## Strongest current opportunity\n${op?`${op.title}\nChannel: ${op.channel||''}\nOpportunity score: ${Math.round(num(op.score)||0)}/100\n${finite(op.outlier)?`Channel-relative outlier: ${num(op.outlier).toFixed(1)}×\n`:''}Verdict: ${op.verdict||'VERIFY'} · Confidence: ${op.confidence||'LOW'}`:'No current Radar opportunity.'}\n\n## Best current package\n${p?`${p.title}\nPackage score: ${Math.round(num(p.package_score)||0)}/100\nEvidence fit: ${Math.round(num(p.evidence_fit)||0)}/100\nReplication: ${Math.round(num(p.replication)||0)}/100\nViewer promise: ${p.viewer_promise||''}`:'No current package.'}\n\n## Idea Vault\n${saved.length?saved.map((x,i)=>`${i+1}. [${x.stage}] ${x.title}${finite(x.score)?` — signal ${Math.round(num(x.score))}`:''}`).join('\n'):'No saved ideas.'}\n\nGuardrail: scores are research decision aids, not predictions of views or CTR. Public evidence does not prove causation.\n`}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('Copied to clipboard.')}catch{toast('Could not copy this time.')}}
function renderCommandCenter(){
  const launch=$('#v21PublicLaunch');if(!launch)return;
  let root=$('#v22CommandCenter');if(!root){root=document.createElement('section');root.id='v22CommandCenter';root.className='v22-command-center';launch.insertAdjacentElement('afterend',root)}
  const c=counts(),move=nextMove();root.innerHTML=`${creatorCard()}<section class="v22-command-shell"><div class="v22-command-heading"><div><div class="eyebrow">CREATOR COMMAND CENTER</div><h1>Research. Decide. Ship.</h1><p>One workspace for the market signal, your saved opportunities, competitor movement and the next production decision.</p></div><div class="v22-command-actions"><button class="btn" data-v22-copy-brief>Copy intelligence brief</button><button class="btn primary" data-v22-go="sprint">New Research Sprint</button></div></div><div class="v22-metrics"><span><small>Radar candidates</small><b>${c.candidates}</b></span><span><small>Priority signals</small><b>${c.priority}</b></span><span><small>Saved ideas</small><b>${c.saved}</b></span><span><small>Tracked competitors</small><b>${c.tracked}</b></span><span><small>Creator Loop</small><b>${c.experiments}</b></span></div><article class="v22-next"><div><div class="eyebrow">${E(move.eyebrow)}</div><h2>${E(move.title)}</h2><p>${E(move.text)}</p></div><button class="btn primary" data-v22-go="${E(move.tab)}">${E(move.action)} →</button></article><div class="v22-decision-grid">${signalCard()}${packageCard()}</div>${watchtowerCard()}${vaultCard()}</section>`;
  bindCenter(root)
}
function bindCenter(root){
  root.querySelector('[data-v22-setup]')?.addEventListener('click',openSetup);
  root.querySelectorAll('[data-v22-go]').forEach(b=>b.onclick=()=>go(b.dataset.v22Go));
  root.querySelector('[data-v22-copy-brief]')?.addEventListener('click',()=>copy(briefText()));
  root.querySelectorAll('[data-v22-analyse],[data-v22-vault-analyse],[data-v22-watch-analyse]').forEach(b=>b.onclick=()=>analyseUrl(b.dataset.v22Analyse||b.dataset.v22VaultAnalyse||b.dataset.v22WatchAnalyse));
  root.querySelectorAll('[data-v22-save-url]').forEach(b=>b.onclick=()=>{const v=latestScanVideo(b.dataset.v22SaveUrl);if(v)saveIdea(v,'Opportunity Radar')});
  root.querySelector('[data-v22-copy-title]')?.addEventListener('click',b=>copy(b.currentTarget.dataset.v22CopyTitle||''));
  root.querySelectorAll('[data-v22-stage]').forEach(b=>b.onclick=()=>nextStage(b.dataset.v22Stage));
  root.querySelectorAll('[data-v22-remove]').forEach(b=>b.onclick=()=>removeIdea(b.dataset.v22Remove));
  root.querySelector('[data-v22-compare]')?.addEventListener('click',openCompare);
  root.querySelector('[data-v22-add-competitor]')?.addEventListener('click',addCompetitor);
  root.querySelector('#v22CompetitorInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addCompetitor()}});
  root.querySelectorAll('[data-v22-drop-competitor]').forEach(b=>b.onclick=()=>dropCompetitor(Number(b.dataset.v22DropCompetitor)));
  root.querySelector('[data-v22-scan]')?.addEventListener('click',scanCompetitors);
  root.querySelectorAll('[data-v22-watch-save]').forEach(b=>b.onclick=()=>{const x=competitorResults().find(v=>v.url===b.dataset.v22WatchSave);if(x)saveIdea(x,'Competitor Watchtower')})
}
function analyseUrl(url){if(!url)return;go('analyse','#videoUrl');setTimeout(()=>{const i=$('#videoUrl');if(i){i.value=url;i.dispatchEvent(new Event('input',{bubbles:true}));$('#analyseForm')?.requestSubmit?.()}},130)}
function addCompetitor(){const i=$('#v22CompetitorInput'),q=i?.value.trim();if(!q)return i?.focus();const xs=competitors();if(xs.some(x=>norm(x)===norm(q)))return toast('That competitor is already tracked.');xs.push(q);writeJson(COMPETITORS,xs.slice(0,20));renderCommandCenter()}
function dropCompetitor(i){const xs=competitors();xs.splice(i,1);writeJson(COMPETITORS,xs);renderCommandCenter()}
function normalizeWatch(v,seed){return{url:v?.url||v?.webpage_url||'',id:v?.id||urlId(v?.url||v?.webpage_url),title:v?.title||'Untitled',channel:v?.channel||v?.uploader||seed,views:finite(v?.views??v?.view_count)?num(v.views??v.view_count):null,outlier:finite(v?.outlier_multiple)?num(v.outlier_multiple):finite(v?.outlier?.multiple)?num(v.outlier.multiple):null,thumbnail:v?.thumbnail||'',published:v?.published_text||v?.upload_date||v?.published_at||'',source_seed:seed}}
async function scanCompetitors(){
  const cs=competitors(),box=$('#v22WatchtowerResults'),btn=$('[data-v22-scan]');if(!cs.length||typeof window.api!=='function')return toast('YTIntel research engine is not ready yet. Reload and try again.');
  if(btn){btn.disabled=true;btn.textContent='Scanning…'}if(box)box.innerHTML='<div class="v22-watch-loading"><span></span><b>Scanning tracked competitors…</b><small>Checking current uploads and channel-relative breakouts.</small></div>';
  const out=[];for(let idx=0;idx<cs.length;idx++){const seed=cs[idx];if(box)box.querySelector('small').textContent=`${idx+1} of ${cs.length} · ${seed}`;try{const d=await window.api('discover',{mode:'channel',query:seed,limit:16}),disc=d?.discovery||d||{},vs=arr(disc.videos);for(const v of vs.slice(0,16)){const x=normalizeWatch(v,seed);if(x.url)out.push(x)}}catch(e){console.warn('[YTIntel Watchtower]',seed,e)}}
  const dedup=[];const seen=new Set;for(const x of out){const k=x.id||x.url;if(seen.has(k))continue;seen.add(k);dedup.push(x)}dedup.sort((a,b)=>{const ao=finite(a.outlier)?a.outlier:-1,bo=finite(b.outlier)?b.outlier:-1;if(bo!==ao)return bo-ao;return (b.views||0)-(a.views||0)});writeJson(COMP_RESULTS,dedup.slice(0,40));renderCommandCenter();toast(`Watchtower scanned ${cs.length} competitor${cs.length===1?'':'s'}.`)
}
function setupModal(){if($('#v22Setup'))return;const d=document.createElement('div');d.id='v22Setup';d.className='v22-modal';d.innerHTML='<div class="v22-modal-card"><button class="v22-modal-close" data-v22-close aria-label="Close">×</button><div class="eyebrow">CREATOR WORKSPACE</div><h2>Make YTIntel feel like your research desk.</h2><p class="muted">This stays in your browser. It changes workspace context, not evidence thresholds.</p><label>Workspace / channel name<input id="v22CreatorName" placeholder="e.g. Mitch Builds"></label><label>Channel URL or @handle<input id="v22CreatorChannel" placeholder="https://youtube.com/@..."></label><label>Niche / audience<input id="v22CreatorNiche" placeholder="e.g. AI tools for Australian trades businesses"></label><label>Primary goal<select id="v22CreatorGoal"><option>Grow with evidence-backed videos</option><option>Find repeatable video ideas</option><option>Track competitors and move faster</option><option>Improve titles, thumbnails and hooks</option><option>Build a repeatable content system for clients</option></select></label><button class="btn primary" data-v22-save-workspace>Save workspace</button></div>';document.body.appendChild(d);d.querySelector('[data-v22-close]').onclick=()=>d.classList.remove('show');d.addEventListener('click',e=>{if(e.target===d)d.classList.remove('show')});d.querySelector('[data-v22-save-workspace]').onclick=()=>{writeJson(CREATOR,{name:$('#v22CreatorName').value.trim(),channel:$('#v22CreatorChannel').value.trim(),niche:$('#v22CreatorNiche').value.trim(),goal:$('#v22CreatorGoal').value});d.classList.remove('show');renderCommandCenter();toast('Creator workspace saved.')}}
function openSetup(){const c=creator(),d=$('#v22Setup');if(!d)return;$('#v22CreatorName').value=c.name||'';$('#v22CreatorChannel').value=c.channel||'';$('#v22CreatorNiche').value=c.niche||'';$('#v22CreatorGoal').value=c.goal||'Grow with evidence-backed videos';d.classList.add('show')}
function compareModal(){if($('#v22Compare'))return;const d=document.createElement('div');d.id='v22Compare';d.className='v22-modal';d.innerHTML='<div class="v22-modal-card wide"><button class="v22-modal-close" data-v22-close aria-label="Close">×</button><div class="eyebrow">IDEA VAULT COMPARISON</div><h2>Which opportunity deserves production time?</h2><div id="v22CompareBody"></div></div>';document.body.appendChild(d);d.querySelector('[data-v22-close]').onclick=()=>d.classList.remove('show');d.addEventListener('click',e=>{if(e.target===d)d.classList.remove('show')})}
function openCompare(){const d=$('#v22Compare'),body=$('#v22CompareBody'),xs=vault().slice().sort((a,b)=>(num(b.score)||0)-(num(a.score)||0)).slice(0,3);if(!xs.length)return toast('Save a few ideas first.');body.innerHTML=`<div class="v22-compare-grid">${xs.map((x,i)=>`<article><div class="eyebrow">#${i+1} · ${E(x.stage)}</div><img src="${E(x.thumbnail||'')}" alt="" loading="lazy"><h3>${E(x.title)}</h3><p>${E(x.channel)}</p><div class="v22-compare-metrics"><span><small>Signal</small><b>${finite(x.score)?Math.round(num(x.score)):'—'}</b></span><span><small>Outlier</small><b>${finite(x.outlier)?`${num(x.outlier).toFixed(1)}×`:'—'}</b></span></div><div class="v22-source-note">${finite(x.outlier)?'Channel-relative performance is verified in the saved research.':'Channel baseline is not verified; treat this as a weaker signal.'}</div><button class="btn small primary" data-v22-compare-analyse="${E(x.url)}">Deep analyse</button></article>`).join('')}</div><div class="v22-compare-foot">Use the highest evidence quality, not just the biggest raw view count. YTIntel does not treat this ranking as a prediction of future views.</div>`;body.querySelectorAll('[data-v22-compare-analyse]').forEach(b=>b.onclick=()=>{d.classList.remove('show');analyseUrl(b.dataset.v22CompareAnalyse)});d.classList.add('show')}
function decorateRadar(){
  $$('.radar-video').forEach(card=>{if(card.querySelector('[data-v220-save]'))return;const a=card.querySelector('[data-radar-analyse]'),url=a?.dataset.radarAnalyse;if(!url)return;const btn=document.createElement('button');btn.type='button';btn.className='btn small v22-save-btn';btn.dataset.v220Save='1';const saved=vault().some(x=>x.url===url);btn.textContent=saved?'Saved ✓':'Save idea';btn.disabled=saved;btn.onclick=()=>{const v=latestScanVideo(url);if(v){saveIdea(v,'Opportunity Radar');btn.textContent='Saved ✓';btn.disabled=true}};(card.querySelector('.actions')||card).appendChild(btn)})
}
function decorateAnalyse(){const form=$('#analyseForm');if(!form||$('#v22SaveCurrent'))return;const b=document.createElement('button');b.type='button';b.id='v22SaveCurrent';b.className='btn';b.textContent='Save to Idea Vault';b.onclick=()=>{const url=$('#videoUrl')?.value.trim();if(!url)return toast('Analyse or paste a video first.');const v=latestScanVideo(url)||{url,title:$('#report h1,#report h2')?.textContent?.trim()||'Analysed YouTube video',channel:'',score:null,outlier:null};saveIdea(v,'Deep Analyse')};form.appendChild(b)}
function premiumTop(){const top=$('.top'),brand=$('.brand');if(top&&!$('#v22PlanBadge')){const b=document.createElement('span');b.id='v22PlanBadge';b.className='v22-plan-badge';b.innerHTML='<i></i> CREATOR INTELLIGENCE';brand?.appendChild(b)}const hero=$('#os .hero');if(hero){hero.querySelector('.eyebrow').textContent='CREATOR INTELLIGENCE OS';hero.querySelector('h1').textContent='Know what to make next — and why.';hero.querySelector('p').textContent='Track competitors, find channel-relative breakouts, validate patterns, save opportunities, build original packaging and learn what actually fits your channel.'}}
function release(){const g=$('#updates .grid');if(!g||g.querySelector('[data-v220-release]'))return;g.querySelectorAll('.release.current').forEach(x=>x.classList.remove('current'));const a=document.createElement('article');a.className='card c12 release current';a.dataset.v220Release='1';a.innerHTML='<div class="eyebrow">V0.22.0 · 6 SEP 2026 · CURRENT</div><h3>Creator Command Center — built to be worth paying for</h3><ul class="list"><li><b>Creator Command Center:</b> the strongest market signal, best current package, workspace metrics and the single next move now live in one premium dashboard.</li><li><b>Competitor Watchtower:</b> save the channels that matter, scan them together and surface their strongest current channel-relative breakouts.</li><li><b>Idea Vault:</b> save research from Radar, Analyse or Watchtower and move ideas through Watch → Shortlist → Build → Published.</li><li><b>Opportunity comparison:</b> compare saved ideas side by side using signal strength and channel-relative evidence instead of raw views alone.</li><li><b>Creator workspace:</b> save a channel, niche and goal locally so the product behaves like a persistent research desk rather than a disposable tool.</li><li><b>Premium visual system:</b> stronger hierarchy, signal-red accents, score rings, decision panels, responsive data cards and a more product-grade home experience.</li></ul>';g.prepend(a)}
let queued=false;function refresh(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;decorateRadar();decorateAnalyse();release()})}
function init(){premiumTop();setupModal();compareModal();renderCommandCenter();decorateRadar();decorateAnalyse();release();const o=new MutationObserver(refresh);o.observe(document.body,{childList:true,subtree:true});window.addEventListener('storage',()=>renderCommandCenter());setTimeout(()=>renderCommandCenter(),1400)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
