(function(){
'use strict';
if(document.documentElement.dataset.yt240Usefulness==='1')return;
document.documentElement.dataset.yt240Usefulness='1';
document.body.classList.add('yt-ui-v24');
window.YTINTEL_VERSION='0.24.0';
const CREATOR='ytintel-v220-creator',COMPETITORS='ytintel-v220-competitors',COMP_RESULTS='ytintel-v220-competitor-results',VAULT='ytintel-v220-vault',RADAR='ytintel-v120-radar-history',PACKAGES='ytintel-v121-package-history',EXPERIMENTS='ytintel-v150-experiments',WATCH_HISTORY='ytintel-v240-watch-history',LAST_REFRESH='ytintel-v240-last-refresh';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const arr=x=>Array.isArray(x)?x:[];
const num=x=>Number(x);
const finite=x=>Number.isFinite(num(x));
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function read(k,f=''){try{return localStorage.getItem(k)||f}catch{return f}}
function write(k,v){try{localStorage.setItem(k,v);return true}catch{return false}}
function readJson(k,f=[]){try{const x=JSON.parse(localStorage.getItem(k)||'null');return x==null?f:x}catch{return f}}
function writeJson(k,v){return write(k,JSON.stringify(v))}
function toast(s){if(typeof window.YTIntelToast==='function')window.YTIntelToast(s);else console.info('[YTIntel]',s)}
function go(tab,focus){document.querySelector(`.tabs [data-tab="${tab}"]`)?.click();setTimeout(()=>focus&&$(focus)?.focus(),80)}
function fmt(x){return finite(x)?new Intl.NumberFormat(undefined,{notation:'compact',maximumFractionDigits:1}).format(num(x)):'—'}
function ago(ts){if(!finite(ts))return'not refreshed yet';const d=(Date.now()-num(ts))/86400000;if(d<1/1440)return'just now';if(d<1/24)return`${Math.max(1,Math.round(d*1440))}m ago`;if(d<1)return`${Math.round(d*24)}h ago`;if(d<30)return`${Math.round(d)}d ago`;return new Date(ts).toLocaleDateString()}
function creator(){return readJson(CREATOR,{name:'',channel:'',niche:'',goal:'Grow with evidence-backed videos'})}
function competitors(){return arr(readJson(COMPETITORS,[]))}
function watchResults(){return arr(readJson(COMP_RESULTS,[]))}
function radar(){return arr(readJson(RADAR,[]))}
function packages(){return arr(readJson(PACKAGES,[]))}
function vault(){return arr(readJson(VAULT,[]))}
function experiments(){return arr(readJson(EXPERIMENTS,[]))}
function watchHistory(){return arr(readJson(WATCH_HISTORY,[]))}
function latestRadar(){return radar()[0]||null}
function topOpportunity(){return arr(latestRadar()?.videos).slice().sort((a,b)=>(num(b.score)||0)-(num(a.score)||0))[0]||null}
function topPackage(){const r=packages()[0];return arr(r?.packages).slice().sort((a,b)=>(num(b.package_score)||0)-(num(a.package_score)||0))[0]||null}
function latestSnap(x){return arr(x?.snapshots).at(-1)||null}
function idFor(v){const direct=String(v?.id||'').trim();if(direct)return direct;const u=String(v?.url||'');return (u.match(/[?&]v=([^&]+)/)||u.match(/youtu\.be\/([^?&/]+)/)||u.match(/shorts\/([^?&/]+)/)||[])[1]||u}
function thumb(v){const id=idFor(v);return v?.thumbnail||(id&&!/^https?:/i.test(id)?`https://i.ytimg.com/vi/${id}/hqdefault.jpg`:'')}
function setMeta(){document.title='YTIntel — Your YouTube Creator Intelligence Workspace';const d=$('meta[name="description"]');if(d)d.content='Track competitors, spot channel-relative breakouts, decide what to make next, build the package and learn from your own published outcomes.'}
function injectCss(){if($('link[data-v240]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='v240-usefulness.css?v=0240';l.dataset.v240='1';document.head.appendChild(l)}
function rewriteHero(){const hero=$('#os .hero');if(hero){const e=hero.querySelector('.eyebrow'),h=hero.querySelector('h1'),p=hero.querySelector('p');if(e)e.textContent='YOUR CREATOR INTELLIGENCE WORKSPACE';if(h)h.textContent='Know what changed. Know what to make. Know what to do next.';if(p)p.textContent='YTIntel keeps competitor movement, market opportunities, saved ideas, packaging and your own channel outcomes in one place — then turns that evidence into the next useful action.'}const launch=$('#v21PublicLaunch');if(launch){launch.querySelector('.eyebrow').textContent='START ANYWHERE';launch.querySelector('h2').textContent='Paste a video or type a topic.';const p=launch.querySelector('.v21-public-top p');if(p)p.textContent='YTIntel automatically routes a video into deep analysis or a topic into full market research. No need to learn the tools first.'}}
function watchSig(rs){return arr(rs).slice(0,40).map(x=>`${idFor(x)}:${finite(x.outlier)?num(x.outlier).toFixed(3):''}:${finite(x.views)?Math.round(num(x.views)):''}`).join('|')}
function captureWatchSnapshot(){const rs=watchResults();if(!rs.length)return;const hist=watchHistory(),sig=watchSig(rs);if(hist.at(-1)?.sig===sig)return;hist.push({captured:Date.now(),sig,results:rs.slice(0,40)});writeJson(WATCH_HISTORY,hist.slice(-12))}
function watchChanges(){const hist=watchHistory(),cur=hist.at(-1),prev=hist.at(-2);if(!cur)return{has:false,newItems:[],newBreakouts:[],top:null,biggest:null,vpd:null};const rs=arr(cur.results),top=rs.filter(x=>finite(x.outlier)).sort((a,b)=>num(b.outlier)-num(a.outlier))[0]||rs.slice().sort((a,b)=>(num(b.views)||0)-(num(a.views)||0))[0]||null;if(!prev)return{has:true,baseline:true,newItems:[],newBreakouts:[],top,biggest:null,vpd:null};const pm=new Map(arr(prev.results).map(x=>[idFor(x),x])),newItems=rs.filter(x=>!pm.has(idFor(x))),newBreakouts=rs.filter(x=>finite(x.outlier)&&num(x.outlier)>=1.5&&(!pm.has(idFor(x))||!finite(pm.get(idFor(x))?.outlier)||num(pm.get(idFor(x)).outlier)<1.5));let biggest=null,vpd=null;const days=Math.max(.02,(cur.captured-prev.captured)/86400000);for(const x of rs){const old=pm.get(idFor(x));if(!old)continue;if(finite(x.outlier)&&finite(old.outlier)){const d=num(x.outlier)-num(old.outlier);if(!biggest||d>biggest.delta)biggest={...x,delta:d}}if(finite(x.views)&&finite(old.views)){const rate=Math.max(0,(num(x.views)-num(old.views))/days);if(!vpd||rate>vpd.rate)vpd={...x,rate}}}return{has:true,baseline:false,newItems,newBreakouts,top,biggest,vpd}}
function personalFit(){const measured=experiments().filter(x=>finite(latestSnap(x)?.outlier)),n=measured.length,above=measured.filter(x=>num(latestSnap(x).outlier)>=1.5).length,avg=n?measured.reduce((s,x)=>s+num(latestSnap(x).outlier),0)/n:null,map=new Map;for(const x of measured){const k=x.title_mechanism||'Manual / uncategorised';if(!map.has(k))map.set(k,[]);map.get(k).push(num(latestSnap(x).outlier))}const mechanisms=[...map.entries()].map(([name,os])=>({name,n:os.length,avg:os.reduce((a,b)=>a+b,0)/os.length})).filter(x=>x.n>=2).sort((a,b)=>b.avg-a.avg),best=mechanisms[0]||null,last=measured.slice().sort((a,b)=>(latestSnap(b)?.captured||0)-(latestSnap(a)?.captured||0))[0]||null;return{n,above,avg,best,last}}
function dataFreshness(){const ts=num(read(LAST_REFRESH,'0'))||watchHistory().at(-1)?.captured||0;return{ts,stale:!ts||Date.now()-ts>86400000}}
function actionPlan(){const c=creator(),cs=competitors(),op=topOpportunity(),pkg=topPackage(),ex=experiments(),fresh=dataFreshness(),actions=[];if(!c.niche){actions.push({icon:'01',title:'Set your niche once',text:'YTIntel can then reuse it for refreshes and research instead of asking every session.',act:'setup'});return actions}if(!cs.length)actions.push({icon:'01',title:'Add 3–10 direct competitors',text:'Watchtower becomes much more useful when it knows which channels you actually care about.',act:'setup'});if((cs.length||c.niche)&&fresh.stale)actions.push({icon:'02',title:'Refresh my intelligence',text:'Scan tracked competitors and refresh your niche so the dashboard reflects current evidence.',act:'refresh'});if(!latestRadar())actions.push({icon:'03',title:'Run your first market scan',text:'Build the market baseline YTIntel needs before recommending production decisions.',act:'refresh'});else if(op?.verdict==='PRIORITY'&&!pkg)actions.push({icon:'03',title:'Package the strongest signal',text:'You have a verified priority opportunity. Turn it into an original title, thumbnail brief and hook.',act:'package'});if(pkg&&!ex.some(x=>['planned','producing'].includes(x.stage)))actions.push({icon:'04',title:'Move a package into production',text:'Keep the research attached to the video so YTIntel can learn from the result later.',act:'loop'});const staleOutcome=ex.find(x=>x.stage==='published'&&x.published_url&&(!latestSnap(x)||Date.now()-(latestSnap(x).captured||0)>86400000));if(staleOutcome)actions.push({icon:'05',title:'Update a published result',text:'Refresh the public outcome so your personal channel-fit evidence keeps compounding.',act:'loop'});if(actions.length<3)actions.push({icon:'06',title:'Review your Idea Vault',text:'Shortlist the research worth making instead of letting useful opportunities disappear after a scan.',act:'vault'});return actions.slice(0,3)}
function opportunitySignal(){const op=topOpportunity();if(!op)return`<article class="v24-signal"><div class="eyebrow">MARKET</div><h3>No market scan yet</h3><p>Refresh your niche or run Opportunity Radar to build the first evidence set.</p></article>`;return`<article class="v24-signal"><div class="eyebrow">MARKET · ${E(op.verdict||'VERIFY')}</div><h3>${E(op.title||'Top opportunity')}</h3><p>${E(op.channel||'Unknown channel')}</p><div class="v24-signal-score"><span class="${num(op.score)>=78?'good':''}">signal ${Math.round(num(op.score)||0)}</span>${finite(op.outlier)?`<span class="${num(op.outlier)>=1.5?'good':''}">${num(op.outlier).toFixed(1)}× baseline</span>`:'<span class="warn">baseline unverified</span>'}</div></article>`}
function competitorSignal(){const ch=watchChanges(),x=ch.newBreakouts[0]||ch.newItems[0]||ch.top;if(!ch.has)return`<article class="v24-signal"><div class="eyebrow">COMPETITORS</div><h3>No Watchtower snapshot yet</h3><p>Add competitors and hit Refresh my intelligence. Future scans will show what changed.</p></article>`;if(!x)return`<article class="v24-signal"><div class="eyebrow">COMPETITORS</div><h3>No major change detected</h3><p>Your latest tracked-channel snapshot is saved and ready to compare on the next refresh.</p></article>`;const label=ch.newBreakouts.includes(x)?'NEW BREAKOUT':ch.newItems.includes(x)?'NEW UPLOAD':'TOP TRACKED SIGNAL';return`<article class="v24-signal"><div class="eyebrow">COMPETITORS · ${label}</div><h3>${E(x.title||'Tracked video')}</h3><p>${E(x.channel||x.source_seed||'Tracked competitor')}</p><div class="v24-signal-score">${finite(x.outlier)?`<span class="${num(x.outlier)>=1.5?'good':''}">${num(x.outlier).toFixed(1)}× baseline</span>`:''}${finite(x.views)?`<span>${fmt(x.views)} views</span>`:''}</div></article>`}
function fitSignal(){const f=personalFit();if(f.n<3)return`<article class="v24-signal"><div class="eyebrow">YOUR CHANNEL</div><h3>Personal fit is still learning</h3><p>${f.n?`${f.n} measured outcome${f.n===1?'':'s'} saved.`:'Publish and measure research-backed videos in Creator Loop.'} YTIntel waits for multiple outcomes before treating personal patterns seriously.</p></article>`;return`<article class="v24-signal"><div class="eyebrow">YOUR CHANNEL · ${f.n} OUTCOMES</div><h3>${f.best?E(f.best.name):'Personal evidence is building'}</h3><p>${f.best?`${f.best.n} measured tests · ${f.best.avg.toFixed(1)}× average channel-relative outcome.`:`${f.above}/${f.n} measured uploads finished above 1.5× channel baseline.`}</p><div class="v24-signal-score"><span>${f.above}/${f.n} above baseline</span><span class="${f.avg>=1.5?'good':''}">${f.avg?.toFixed(1)||'—'}× avg</span></div></article>`}
function changesPanel(){const ch=watchChanges(),hist=watchHistory(),rs=arr(hist.at(-1)?.results);if(!ch.has)return`<section class="v24-panel"><div class="v24-panel-head"><div><div class="eyebrow">WHAT CHANGED</div><h2>Competitor movement</h2><p>Refresh tracked competitors once to create the baseline. The next refresh will show new uploads and movement.</p></div></div><div class="v24-empty">No Watchtower comparison exists yet.</div></section>`;const items=[...ch.newBreakouts,...ch.newItems.filter(x=>!ch.newBreakouts.some(y=>idFor(y)===idFor(x)))].slice(0,5);return`<section class="v24-panel"><div class="v24-panel-head"><div><div class="eyebrow">WHAT CHANGED</div><h2>Competitor movement</h2><p>${ch.baseline?'Baseline created. Refresh again later and YTIntel will compare the movement.':'Changes since the previous tracked-channel snapshot.'}</p></div><span class="v24-count">${rs.length} videos</span></div><div class="v24-change-summary"><span><small>New uploads</small><b>${ch.newItems.length}</b></span><span><small>New breakouts</small><b>${ch.newBreakouts.length}</b></span><span><small>Top outlier</small><b>${finite(ch.top?.outlier)?`${num(ch.top.outlier).toFixed(1)}×`:'—'}</b></span><span><small>Fastest observed</small><b>${ch.vpd?`${fmt(ch.vpd.rate)}/d`:'—'}</b></span></div>${items.length?`<div class="v24-list">${items.map(x=>`<article class="v24-row"><img src="${E(thumb(x))}" alt="" loading="lazy"><div><b>${E(x.title)}</b><small>${E(x.channel||x.source_seed||'Tracked competitor')}${finite(x.outlier)?` · ${num(x.outlier).toFixed(1)}× baseline`:''}</small></div><div class="v24-row-actions"><button class="btn small" data-v24-analyse="${E(x.url)}">Analyse</button><button class="btn small" data-v24-save="${E(x.url)}">Save</button></div></article>`).join('')}</div>`:`<div class="v24-empty">No new uploads or newly verified breakouts were detected in this comparison.</div>`}</section>`}
function fitPanel(){const f=personalFit();return`<section class="v24-panel"><div class="v24-panel-head"><div><div class="eyebrow">PERSONAL FIT</div><h2>What your channel is teaching YTIntel</h2><p>Only measured Creator Loop outcomes count here.</p></div><span class="v24-count">${f.n} measured</span></div><div class="v24-personal"><span><small>Above baseline</small><b>${f.above}</b></span><span><small>Average outlier</small><b>${f.avg!=null?`${f.avg.toFixed(1)}×`:'—'}</b></span><span><small>Best repeated mechanism</small><b>${f.best?`${f.best.avg.toFixed(1)}×`:'—'}</b></span></div><div class="v24-learning"><b>${f.best?E(f.best.name):f.n<3?'Need more measured uploads':'No mechanism has 2+ measured tests yet'}</b><span>${f.best?`${f.best.n} measured uploads use this mechanism. Treat it as personal evidence, not a guaranteed formula.`:'YTIntel intentionally waits for repeated outcomes before highlighting a personal pattern.'}</span></div><div class="v24-modal-actions"><button class="btn small" data-v24-act="loop">Open Creator Loop</button></div></section>`}
function queuePanel(){const xs=vault().slice().sort((a,b)=>{const rank={BUILD:0,SHORTLIST:1,WATCH:2,PUBLISHED:3};return(rank[a.stage]??9)-(rank[b.stage]??9)||(b.saved||0)-(a.saved||0)}).slice(0,6);return`<section class="v24-panel"><div class="v24-panel-head"><div><div class="eyebrow">PRODUCTION QUEUE</div><h2>Ideas worth doing something with</h2><p>Move saved research from Watch → Shortlist → Build → Published.</p></div><span class="v24-count">${vault().length} saved</span></div>${xs.length?`<div class="v24-queue">${xs.map(x=>`<article class="v24-queue-row"><div class="grow"><b>${E(x.title)}</b><small>${E(x.channel||x.source||'Saved research')}${finite(x.score)?` · signal ${Math.round(num(x.score))}`:''}</small></div><button class="v24-stage" data-v24-stage="${E(x.id)}">${E(x.stage||'WATCH')}</button><button class="btn small" data-v24-analyse="${E(x.url)}">Open</button></article>`).join('')}</div>`:`<div class="v24-empty">Save a strong Radar, Analyse or Watchtower result and it will appear here.</div>`}<div class="v24-modal-actions"><button class="btn small" data-v24-act="radar">Find ideas</button><button class="btn small" data-v24-act="packaging">Build packaging</button></div></section>`}
function setupCard(){const c=creator();if(c.niche)return'';return`<section class="v24-setup"><div class="eyebrow">60-SECOND SETUP</div><h2>Tell YTIntel what you create once.</h2><p>Add your niche and a few competitors. After that, the home screen can refresh the market for you instead of starting from zero every time.</p><button class="btn primary" data-v24-act="setup">Set up my workspace →</button></section>`}
function dashboard(){captureWatchSnapshot();let root=$('#v24Dashboard');const launch=$('#v21PublicLaunch');if(!launch)return;if(!root){root=document.createElement('div');root.id='v24Dashboard';root.className='v24-dashboard';launch.insertAdjacentElement('afterend',root)}const c=creator(),fresh=dataFreshness(),plan=actionPlan();root.innerHTML=`${setupCard()}<section class="v24-today"><div class="v24-today-head"><div><div class="eyebrow">TODAY · ${E(c.niche||'SET UP YOUR NICHE')}</div><h2>Your useful creator brief.</h2><p>Open YTIntel and see the strongest market signal, competitor movement, what your own channel is teaching you, and the next actions worth taking.</p></div><span class="v24-fresh ${fresh.stale?'stale':'fresh'}">${fresh.stale?'Needs refresh':'Current'} · ${ago(fresh.ts)}</span></div><div class="v24-refresh"><div class="v24-refresh-copy"><b>Refresh my intelligence</b><small>${competitors().length?`${competitors().length} tracked competitor${competitors().length===1?'':'s'} + `:''}${c.niche||'your niche'} · runs without leaving this dashboard</small></div><button class="btn primary" id="v24Refresh">Refresh now →</button><div class="v24-progress" id="v24Progress"><i></i></div></div><div class="v24-signals">${opportunitySignal()}${competitorSignal()}${fitSignal()}</div><div class="v24-actions">${plan.map(a=>`<button class="v24-action" data-v24-act="${E(a.act)}"><span>${E(a.icon)}</span><div><b>${E(a.title)}</b><small>${E(a.text)}</small></div></button>`).join('')}</div></section><div class="v24-grid">${changesPanel()}${fitPanel()}${queuePanel()}<section class="v24-panel"><div class="v24-panel-head"><div><div class="eyebrow">ONE INPUT</div><h2>Research anything without learning the app</h2><p>Paste a competitor video into the box above for Deep Analyse, or type any niche/topic for a full Research Sprint.</p></div></div><div class="v24-learning"><b>YTIntel should reduce decisions, not create more dashboards.</b><span>The deeper tools stay available in the tabs when you want control. The home screen is designed to tell you what matters now.</span></div></section></div><div class="v24-footer-tools"><div class="left"><button class="btn small" data-v24-act="setup">Workspace settings</button><button class="btn small" data-v24-act="marketing">Share / marketing kit</button></div><div class="right"><button class="btn small v24-advanced-toggle" data-v24-legacy>${document.body.classList.contains('v24-show-legacy')?'Hide legacy workspace':'Show advanced Research OS'}</button></div></div>`;bind(root)}
function bind(root){root.querySelector('#v24Refresh')?.addEventListener('click',refreshAll);root.querySelectorAll('[data-v24-act]').forEach(b=>b.onclick=()=>act(b.dataset.v24Act));root.querySelectorAll('[data-v24-analyse]').forEach(b=>b.onclick=()=>analyse(b.dataset.v24Analyse));root.querySelectorAll('[data-v24-save]').forEach(b=>b.onclick=()=>saveWatchIdea(b.dataset.v24Save));root.querySelectorAll('[data-v24-stage]').forEach(b=>b.onclick=()=>advanceStage(b.dataset.v24Stage));root.querySelector('[data-v24-legacy]')?.addEventListener('click',()=>{document.body.classList.toggle('v24-show-legacy');dashboard()})}
function act(a){if(a==='setup')return openSetup();if(a==='refresh')return refreshAll();if(a==='marketing')return openMarketing();if(a==='vault'){document.querySelector('.v24-panel:nth-of-type(3)')?.scrollIntoView({behavior:'smooth',block:'center'});return}if(['radar','packaging','loop','sprint','analyse'].includes(a))return go(a)}
function analyse(url){if(!url)return;go('analyse','#videoUrl');setTimeout(()=>{const i=$('#videoUrl');if(i){i.value=url;i.dispatchEvent(new Event('input',{bubbles:true}));$('#analyseForm')?.requestSubmit?.()}},120)}
function saveWatchIdea(url){const x=watchResults().find(v=>v.url===url)||watchHistory().at(-1)?.results?.find(v=>v.url===url);if(!x)return toast('That Watchtower item is no longer available.');const xs=vault();if(xs.some(v=>v.url===url))return toast('Already saved in Idea Vault.');xs.unshift({id:`idea-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,saved:Date.now(),stage:'WATCH',source:'Competitor Watchtower',title:x.title||'Saved video',channel:x.channel||x.source_seed||'',url:x.url,thumbnail:thumb(x),score:finite(x.score)?num(x.score):null,outlier:finite(x.outlier)?num(x.outlier):null,confidence:x.confidence||'',verdict:x.verdict||''});writeJson(VAULT,xs.slice(0,80));toast('Saved to Idea Vault.');dashboard();window.dispatchEvent(new Event('storage'))}
function advanceStage(id){const stages=['WATCH','SHORTLIST','BUILD','PUBLISHED'],xs=vault(),x=xs.find(v=>v.id===id);if(!x)return;const i=Math.max(0,stages.indexOf(x.stage));x.stage=stages[(i+1)%stages.length];x.updated=Date.now();writeJson(VAULT,xs);dashboard();window.dispatchEvent(new Event('storage'))}
function normalizeWatch(v,seed){return{url:v?.url||v?.webpage_url||'',id:v?.id||idFor(v),title:v?.title||'Untitled',channel:v?.channel||v?.uploader||seed,views:finite(v?.views??v?.view_count)?num(v.views??v.view_count):null,outlier:finite(v?.outlier_multiple)?num(v.outlier_multiple):finite(v?.outlier?.multiple)?num(v.outlier.multiple):null,thumbnail:v?.thumbnail||'',published:v?.published_text||v?.upload_date||v?.published_at||'',source_seed:seed}}
async function pool(items,limit,worker){const out=new Array(items.length),q=items.map((x,i)=>({x,i}));async function run(){while(q.length){const {x,i}=q.shift();try{out[i]=await worker(x,i)}catch(e){out[i]={error:e}}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},run));return out}
async function scanWatchtower(progress){const cs=competitors();if(!cs.length)return[];if(typeof window.api!=='function')throw Error('YTIntel research engine is still loading. Reload once and try again.');let done=0;const sets=await pool(cs,3,async seed=>{const d=await window.api('discover',{mode:'channel',query:seed,limit:16});done++;progress?.(done,cs.length,`Scanning competitor ${done} of ${cs.length}`);return arr((d?.discovery||d||{}).videos).map(v=>normalizeWatch(v,seed))});const flat=sets.flatMap(x=>Array.isArray(x)?x:[]),seen=new Set,dedup=[];for(const x of flat){if(!x.url)continue;const k=idFor(x);if(seen.has(k))continue;seen.add(k);dedup.push(x)}dedup.sort((a,b)=>{const ao=finite(a.outlier)?num(a.outlier):-1,bo=finite(b.outlier)?num(b.outlier):-1;if(bo!==ao)return bo-ao;return(num(b.views)||0)-(num(a.views)||0)});writeJson(COMP_RESULTS,dedup.slice(0,40));const hist=watchHistory(),sig=watchSig(dedup);if(hist.at(-1)?.sig!==sig){hist.push({captured:Date.now(),sig,results:dedup.slice(0,40)});writeJson(WATCH_HISTORY,hist.slice(-12))}return dedup}
function radarSignature(){const s=latestRadar();return JSON.stringify(s||{})}
async function refreshRadar(niche,progress){if(!niche||!$('#radarBtn')||!$('#radarQuery'))return false;const before=radarSignature(),input=$('#radarQuery');input.value=niche;input.dispatchEvent(new Event('input',{bubbles:true}));progress?.(0,1,'Refreshing your niche opportunity map');$('#radarBtn').click();const end=Date.now()+150000;while(Date.now()<end){await new Promise(r=>setTimeout(r,650));const now=latestRadar();if(now&&norm(now.query)===norm(niche)&&radarSignature()!==before)return true}return false}
let refreshing=false;async function refreshAll(){if(refreshing)return;const c=creator(),cs=competitors();if(!c.niche&&!cs.length)return openSetup();refreshing=true;const btn=$('#v24Refresh'),bar=$('#v24Progress'),fill=bar?.querySelector('i');if(btn){btn.disabled=true;btn.textContent='Refreshing…'}bar?.classList.add('show');const set=(pct,msg)=>{if(fill)fill.style.width=`${Math.max(3,Math.min(100,pct))}%`;const s=$('.v24-refresh-copy small');if(s)s.textContent=msg};try{let step=0,total=(cs.length?1:0)+(c.niche?1:0);if(cs.length){set(8,'Scanning tracked competitors…');await scanWatchtower((done,n,msg)=>set(8+Math.round((done/Math.max(1,n))*42),msg));step++;set(Math.round(step/total*80),'Competitor snapshot saved.')}if(c.niche){set(total>1?55:12,`Refreshing ${c.niche}…`);const ok=await refreshRadar(c.niche,(a,b,msg)=>set(total>1?62:35,msg));step++;if(!ok)toast('Competitor refresh finished, but the niche scan took too long. Your earlier Radar evidence is still saved.')}write(LAST_REFRESH,String(Date.now()));set(100,'Fresh intelligence ready.');captureWatchSnapshot();dashboard();window.dispatchEvent(new Event('storage'));toast('YTIntel workspace refreshed.')}catch(e){toast(e?.message||'Refresh could not finish. Your saved research was not lost.')}finally{refreshing=false;setTimeout(()=>{if(btn){btn.disabled=false;btn.textContent='Refresh now →'}bar?.classList.remove('show');if(fill)fill.style.width='0'},800)}}
function setupModal(){if($('#v24Setup'))return;const d=document.createElement('div');d.id='v24Setup';d.className='v24-setup-modal';d.innerHTML=`<div class="v24-modal-card"><div class="v24-modal-top"><div><div class="eyebrow">CREATOR WORKSPACE</div><h2>Set it once. Reuse it everywhere.</h2><p class="muted">YTIntel stores this in your browser and uses it to make the home screen useful immediately.</p></div><button class="v24-close" data-v24-close>×</button></div><div class="v24-setup-grid"><label>Workspace / channel name<input id="v24Name" placeholder="e.g. Mitch Builds"></label><label>Your channel or @handle<input id="v24Channel" placeholder="https://youtube.com/@..."></label><label class="wide">Niche / audience<input id="v24Niche" placeholder="e.g. AI tools for Australian small businesses"></label><label class="wide">Direct competitors<textarea id="v24Competitors" placeholder="One channel URL or name per line. Start with 3–10 direct competitors."></textarea></label></div><div class="v24-setup-actions"><button class="btn primary" data-v24-save-setup>Save workspace</button><span class="source-note">Competitors are for research only; they do not change evidence thresholds.</span></div></div>`;document.body.appendChild(d);d.querySelector('[data-v24-close]').onclick=()=>d.classList.remove('show');d.onclick=e=>{if(e.target===d)d.classList.remove('show')};d.querySelector('[data-v24-save-setup]').onclick=()=>{const old=creator(),cs=$('#v24Competitors').value.split(/\n+/).map(x=>x.trim()).filter(Boolean);writeJson(CREATOR,{...old,name:$('#v24Name').value.trim(),channel:$('#v24Channel').value.trim(),niche:$('#v24Niche').value.trim(),goal:old.goal||'Grow with evidence-backed videos'});writeJson(COMPETITORS,[...new Set(cs)].slice(0,20));d.classList.remove('show');dashboard();window.dispatchEvent(new Event('storage'));toast('Workspace saved. Refresh when you are ready.')}}
function openSetup(){const d=$('#v24Setup'),c=creator();if(!d)return;$('#v24Name').value=c.name||'';$('#v24Channel').value=c.channel||'';$('#v24Niche').value=c.niche||'';$('#v24Competitors').value=competitors().join('\n');d.classList.add('show')}
function marketingModal(){if($('#v24Marketing'))return;const d=document.createElement('div');d.id='v24Marketing';d.className='v24-marketing-modal';const pitch='YTIntel is a creator intelligence workspace that tracks competitor breakouts, finds evidence-backed video opportunities, turns them into titles, thumbnail briefs and hooks, and learns from what you actually publish.';d.innerHTML=`<div class="v24-modal-card"><div class="v24-modal-top"><div><div class="eyebrow">SHARE / MARKETING · SECONDARY</div><h2>Marketing stays separate from the product.</h2><p class="muted">The app is usefulness-first. This is just the copy you can use when you want to explain or share it.</p></div><button class="v24-close" data-v24-close>×</button></div><div class="v24-pitch">${E(pitch)}</div><div class="v24-modal-actions"><button class="btn primary" data-v24-copy-pitch>Copy one-line pitch</button><button class="btn" data-v24-share-app>Share YTIntel</button></div></div>`;document.body.appendChild(d);d.querySelector('[data-v24-close]').onclick=()=>d.classList.remove('show');d.onclick=e=>{if(e.target===d)d.classList.remove('show')};d.querySelector('[data-v24-copy-pitch]').onclick=async()=>{try{await navigator.clipboard.writeText(pitch);toast('Pitch copied.')}catch{}};d.querySelector('[data-v24-share-app]').onclick=shareApp}
function openMarketing(){$('#v24Marketing')?.classList.add('show')}
async function shareApp(){const url='https://mitchloxton.github.io/pinnacle-navigator/ytintel/latest/';if(navigator.share){try{await navigator.share({title:'YTIntel',text:'Know what to make next — and why.',url});return}catch(e){if(e?.name==='AbortError')return}}try{await navigator.clipboard.writeText(url);toast('YTIntel link copied.')}catch{}}
function handleLinks(){const p=new URLSearchParams(location.search);if(p.get('pitch')==='1'||p.get('marketing')==='1')setTimeout(openMarketing,350)}
function release(){const g=$('#updates .grid');if(!g||g.querySelector('[data-v240-release]'))return;g.querySelectorAll('.release.current').forEach(x=>x.classList.remove('current'));const a=document.createElement('article');a.className='card c12 release current';a.dataset.v240Release='1';a.innerHTML='<div class="eyebrow">V0.24.0 · 6 SEP 2026 · CURRENT</div><h3>Usefulness First — open YTIntel and know what matters now</h3><ul class="list"><li><b>Today brief:</b> one home screen now combines the strongest market opportunity, competitor movement, personal channel-fit evidence and the next actions worth taking.</li><li><b>Refresh My Intelligence:</b> one click refreshes tracked competitors and the creator niche without forcing the user through separate tools.</li><li><b>What Changed:</b> Watchtower snapshots now build a comparison history so repeat visits can show new uploads, newly verified breakouts and observed movement.</li><li><b>Personal Fit:</b> measured Creator Loop outcomes are summarised on the home screen, with repeated title mechanisms only surfaced after multiple tests.</li><li><b>Production Queue:</b> saved ideas are visible as an actionable Watch → Shortlist → Build → Published pipeline.</li><li><b>60-second setup:</b> save niche, channel and direct competitors once and reuse them every session.</li><li><b>Marketing separated:</b> sales copy is now a secondary share kit instead of taking over the core product experience.</li></ul>';g.prepend(a)}
let timer=null;function schedule(){clearTimeout(timer);timer=setTimeout(()=>{captureWatchSnapshot();dashboard();release()},220)}
function init(){injectCss();setMeta();rewriteHero();setupModal();marketingModal();dashboard();release();handleLinks();const o=new MutationObserver(schedule);['#radarRoot','#packageRoot','#loopRoot','#sprintRoot'].map($).filter(Boolean).forEach(r=>o.observe(r,{childList:true,subtree:true,characterData:true}));window.addEventListener('storage',schedule);window.addEventListener('focus',()=>{captureWatchSnapshot();dashboard()});setTimeout(()=>{captureWatchSnapshot();dashboard()},1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
