(function(){
'use strict';
if(document.documentElement.dataset.yt260Cloud==='1')return;
document.documentElement.dataset.yt260Cloud='1';
document.body.classList.add('yt-ui-v26');
window.YTINTEL_VERSION='0.26.0';

const SUPA='https://dkmacktcfhubsumwrydw.supabase.co';
const PUB='sb_publishable_VATM2AkVyl-yvxv28S2FXw_CqMpBr6q';
const WORKER=`${SUPA}/functions/v1/ytintel-intel`;
const LIB='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.min.js';
const LS={
  creator:'ytintel-v220-creator',competitors:'ytintel-v220-competitors',vault:'ytintel-v220-vault',
  radar:'ytintel-v120-radar-history',packages:'ytintel-v121-package-history',experiments:'ytintel-v150-experiments',
  watch:'ytintel-v240-watch-history',watchResults:'ytintel-v220-competitor-results',timeline:'ytintel-v250-video-timeline',
  cloudPulse:'ytintel-v260-cloud-pulse',lastSync:'ytintel-v260-last-sync'
};
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s)),A=x=>Array.isArray(x)?x:[];
const N=x=>Number(x),F=x=>x!==null&&x!==undefined&&x!==''&&Number.isFinite(Number(x));
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
function read(k,f=null){try{const v=localStorage.getItem(k);return v==null?f:JSON.parse(v)}catch{return f}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}}
function text(k,f=''){try{return localStorage.getItem(k)??f}catch{return f}}
function toast(s){if(typeof window.YTIntelToast==='function')window.YTIntelToast(s);else console.info('[YTIntel]',s)}
function ago(ts){if(!ts)return'never';const t=typeof ts==='number'?ts:Date.parse(ts);if(!Number.isFinite(t))return'unknown';const d=(Date.now()-t)/1000;if(d<60)return'just now';if(d<3600)return`${Math.max(1,Math.round(d/60))}m ago`;if(d<86400)return`${Math.round(d/3600)}h ago`;return`${Math.round(d/86400)}d ago`}
function fmt(x){return F(x)?new Intl.NumberFormat(undefined,{notation:'compact',maximumFractionDigits:1}).format(N(x)):'—'}
function vid(v){const d=String(v?.video_id||v?.id||'').trim();if(d)return d;const u=String(v?.url||'');return(u.match(/[?&]v=([^&]+)/)||u.match(/youtu\.be\/([^?&/]+)/)||u.match(/shorts\/([^?&/]+)/)||[])[1]||u}
function localCreator(){return read(LS.creator,{name:'',channel:'',niche:'',goal:'Grow with evidence-backed videos'})||{}}
function localCompetitors(){return A(read(LS.competitors,[])).map(x=>String(x).trim()).filter(Boolean)}
function setStatus(){const s=$('#status');if(s){s.textContent='v0.26.0 · cloud intelligence live';s.title='YTIntel v0.26: local creator intelligence plus optional account-backed cloud sync and scheduled monitoring.'}}
function go(tab){document.querySelector(`.tabs [data-tab="${tab}"]`)?.click()}
function analyse(url){if(!url)return;go('analyse');setTimeout(()=>{const i=$('#videoUrl');if(i){i.value=url;$('#analyseForm')?.requestSubmit?.()}},120)}

let client=null,session=null,summary=null,booted=false,applying=false,syncTimer=null,summaryTimer=null,monitoring=false;
function loadLibrary(){return new Promise((resolve,reject)=>{if(window.supabase?.createClient)return resolve(window.supabase);const old=$('script[data-yt260-supabase]');if(old){old.addEventListener('load',()=>resolve(window.supabase),{once:true});old.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src=LIB;s.async=true;s.dataset.yt260Supabase='1';s.onload=()=>resolve(window.supabase);s.onerror=()=>reject(Error('Cloud library could not load. Local YTIntel still works.'));document.head.appendChild(s)})}
async function initClient(){const lib=await loadLibrary();client=lib.createClient(SUPA,PUB,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const g=await client.auth.getSession();session=g.data?.session||null;client.auth.onAuthStateChange((_event,s)=>{session=s||null;setTimeout(()=>onAuthChange(),0)});return client}
function authHeader(){return session?.access_token?{authorization:`Bearer ${session.access_token}`}:{}}
async function worker(action,body={}){if(!session)throw Error('Sign in to use cloud intelligence.');const r=await fetch(`${WORKER}?action=${encodeURIComponent(action)}`,{method:'POST',headers:{'content-type':'application/json',...authHeader()},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok||d?.ok===false)throw Error(d?.error||`Cloud intelligence ${r.status}`);return d}

function meaningfulPayload(p){return !!(p?.creator?.niche||p?.creator?.channel||A(p?.competitors).length||A(p?.vault).length||A(p?.radar).length||A(p?.experiments).length)}
function payload(){return{
  version:1,creator:localCreator(),competitors:localCompetitors(),vault:A(read(LS.vault,[])),radar:A(read(LS.radar,[])).slice(0,12),
  packages:A(read(LS.packages,[])).slice(0,12),experiments:A(read(LS.experiments,[])).slice(0,80),watch:A(read(LS.watch,[])).slice(-12),
  timeline:read(LS.timeline,{})||{},client_updated_at:new Date().toISOString()
}}
function uniqueBy(xs,keyFn,timeFn){const m=new Map;for(const x of A(xs)){const k=keyFn(x);if(!k)continue;const old=m.get(k);if(!old||Number(timeFn(x)||0)>=Number(timeFn(old)||0))m.set(k,x)}return[...m.values()]}
function mergeTimeline(a,b){const out={...(a||{})};for(const [k,v] of Object.entries(b||{})){const old=out[k]||{},ps=uniqueBy([...A(old.points),...A(v?.points)],x=>String(x.t||''),x=>Number(x.t||0)).sort((x,y)=>Number(x.t)-Number(y.t)).slice(-40);out[k]={...old,...v,points:ps,updated:Math.max(Number(old.updated||0),Number(v?.updated||0))}}return out}
function mergePayload(local,cloud){
  const lc=local?.creator||{},cc=cloud?.creator||{};
  return{version:1,creator:{...cc,...Object.fromEntries(Object.entries(lc).filter(([,v])=>String(v??'').trim()!==''))},
    competitors:[...new Set([...A(cloud?.competitors),...A(local?.competitors)].map(x=>String(x).trim()).filter(Boolean))].slice(0,20),
    vault:uniqueBy([...A(cloud?.vault),...A(local?.vault)],x=>x?.id||x?.url,x=>x?.updated||x?.saved||0).sort((a,b)=>(b.updated||b.saved||0)-(a.updated||a.saved||0)).slice(0,80),
    radar:uniqueBy([...A(cloud?.radar),...A(local?.radar)],x=>norm(x?.query),x=>x?.created||0).sort((a,b)=>(b.created||0)-(a.created||0)).slice(0,12),
    packages:uniqueBy([...A(cloud?.packages),...A(local?.packages)],x=>`${norm(x?.query)}:${x?.created||x?.saved||''}`,x=>x?.created||x?.saved||0).sort((a,b)=>(b.created||b.saved||0)-(a.created||a.saved||0)).slice(0,12),
    experiments:uniqueBy([...A(cloud?.experiments),...A(local?.experiments)],x=>x?.id||x?.published_url||x?.title,x=>x?.updated||x?.created||0).slice(0,80),
    watch:uniqueBy([...A(cloud?.watch),...A(local?.watch)],x=>String(x?.captured||x?.sig||''),x=>x?.captured||0).sort((a,b)=>(a.captured||0)-(b.captured||0)).slice(-12),
    timeline:mergeTimeline(cloud?.timeline,local?.timeline),client_updated_at:new Date().toISOString()}
}
function applyPayload(p){if(!p)return;applying=true;try{if(p.creator)write(LS.creator,p.creator);if(p.competitors)write(LS.competitors,p.competitors);if(p.vault)write(LS.vault,p.vault);if(p.radar)write(LS.radar,p.radar);if(p.packages)write(LS.packages,p.packages);if(p.experiments)write(LS.experiments,p.experiments);if(p.watch)write(LS.watch,p.watch);if(p.timeline)write(LS.timeline,p.timeline);window.dispatchEvent(new Event('storage'))}finally{setTimeout(()=>{applying=false},0)}}
async function reconcileWorkspace(){if(!session||!client)return;const uid=session.user.id,local=payload();const q=await client.from('ytintel_workspace_state').select('payload,updated_at').eq('user_id',uid).maybeSingle();if(q.error)throw q.error;const cloud=q.data?.payload||null;let merged=local;if(cloud){merged=!meaningfulPayload(local)&&meaningfulPayload(cloud)?cloud:mergePayload(local,cloud);applyPayload(merged)}await client.from('ytintel_workspace_state').upsert({user_id:uid,payload:merged,client_updated_at:new Date().toISOString()});localStorage.setItem(LS.lastSync,String(Date.now()))}
async function syncProfile(){if(!session||!client)return;const c=localCreator(),uid=session.user.id;const profile={user_id:uid,channel_name:String(c.name||''),channel_url:String(c.channel||''),niche:String(c.niche||''),goal:String(c.goal||'Grow with evidence-backed videos')};const p=await client.from('ytintel_profiles').upsert(profile);if(p.error)throw p.error;const current=await client.from('ytintel_competitors').select('id,seed').eq('user_id',uid);if(current.error)throw current.error;const want=new Set(localCompetitors()),have=A(current.data);const remove=have.filter(x=>!want.has(x.seed)).map(x=>x.id);if(remove.length){const d=await client.from('ytintel_competitors').delete().in('id',remove);if(d.error)throw d.error}const haveSeeds=new Set(have.map(x=>x.seed));const add=[...want].filter(x=>!haveSeeds.has(x)).map(seed=>({user_id:uid,seed,label:''}));if(add.length){const i=await client.from('ytintel_competitors').insert(add);if(i.error)throw i.error}}
function scheduleSync(){if(applying||!session)return;clearTimeout(syncTimer);syncTimer=setTimeout(async()=>{try{await reconcileWorkspace();await syncProfile();renderAccount()}catch(e){console.warn('[YTIntel cloud sync]',e)}},1600)}

function cloudToLocal(d){if(!d)return;const shots=A(d.recent_snapshots),tl=read(LS.timeline,{})||{},latestCompetitor=new Map;for(const s of shots){const id=String(s.video_id||'');if(!id)continue;const t=Date.parse(s.captured_at)||0,x=tl[id]||{id,url:s.url||'',title:s.title||'',channel:s.channel||'',thumbnail:s.payload?.thumbnail||'',points:[]};x.url=s.url||x.url;x.title=s.title||x.title;x.channel=s.channel||x.channel;x.thumbnail=s.payload?.thumbnail||x.thumbnail;const p={t,views:F(s.views)?N(s.views):null,outlier:F(s.outlier_multiple)?N(s.outlier_multiple):null},exists=A(x.points).some(y=>Number(y.t)===t);if(t&&!exists)x.points.push(p);x.points=A(x.points).sort((a,b)=>Number(a.t)-Number(b.t)).slice(-40);x.updated=Math.max(Number(x.updated||0),t);tl[id]=x;if(s.source_type==='competitor'&&!latestCompetitor.has(id))latestCompetitor.set(id,{id,url:s.url,title:s.title,channel:s.channel,views:s.views,outlier:s.outlier_multiple,thumbnail:s.payload?.thumbnail||'',published:s.published_text,source_seed:s.source_seed})}
  write(LS.timeline,tl);if(latestCompetitor.size){const existing=A(read(LS.watchResults,[])),merged=uniqueBy([...latestCompetitor.values(),...existing],x=>vid(x),x=>0).slice(0,80);write(LS.watchResults,merged)}window.dispatchEvent(new Event('storage'))}
async function refreshSummary(opts={}){if(!session)return;clearTimeout(summaryTimer);try{const d=await worker('summary');summary=d;cloudToLocal(d);renderCloud();patchPersonalFit();renderAccount();if(opts.seed&&d?.profile&&!d.profile.last_background_scan_at&&meaningfulPayload(payload()))setTimeout(()=>monitorNow(true),700)}catch(e){console.warn('[YTIntel cloud summary]',e);renderCloud(String(e?.message||e))}}
async function monitorNow(silent=false){if(!session||monitoring)return;monitoring=true;renderCloud();try{await syncProfile();await reconcileWorkspace();const d=await worker('monitor-user');summary=d.summary||summary;cloudToLocal(summary);if(!silent)toast(`Cloud scan complete · ${d.snapshots||0} observations saved.`)}catch(e){if(!silent)toast(e?.message||'Cloud scan could not finish.');console.warn(e)}finally{monitoring=false;renderCloud();patchPersonalFit();renderAccount()}}

function fitFor(title,model){if(!model||Number(model.sample_size||0)<5||Number(model.winner_count||0)<2)return{label:'LEARNING',tone:'learn',detail:`${model?.sample_size||0} own-channel videos observed. YTIntel waits for more evidence before claiming personal fit.`,matched:[]};const tt=new Set(norm(title).split(' ').filter(x=>x.length>2)),matched=A(model.winning_terms).filter(x=>tt.has(norm(x.term))).slice(0,5),support=matched.reduce((n,x)=>n+Number(x.support||0),0);if(matched.length>=2||support>=4)return{label:'STRONG OVERLAP',tone:'strong',detail:`Shares ${matched.map(x=>x.term).join(', ')} with repeated terms from your stronger channel-relative uploads.`,matched};if(matched.length===1)return{label:'SOME OVERLAP',tone:'some',detail:`Shares “${matched[0].term}” with your stronger channel-relative uploads.`,matched};return{label:'NO REPEATED OVERLAP YET',tone:'low',detail:'No repeated winning title terms overlap yet. Treat market evidence separately from personal fit.',matched:[]}}
function patchPersonalFit(){const card=$('.v25-make');if(!card)return;card.querySelector('.v26-fit-strip')?.remove();const title=card.querySelector('.v25-make-top h2')?.textContent||'',model=summary?.own_channel_model;if(!title||!model)return;const f=fitFor(title,model),d=document.createElement('div');d.className=`v26-fit-strip ${f.tone}`;d.innerHTML=`<div><small>YOUR CHANNEL FIT EVIDENCE</small><b>${E(f.label)}</b></div><p>${E(f.detail)}</p><span>${Number(model.sample_size||0)} own-channel videos · ${Number(model.winner_count||0)} ≥1.5× winners</span>`;const proof=card.querySelector('.v25-proof');proof?.insertAdjacentElement('afterend',d)}

function bestCloudSignal(){const shots=A(summary?.recent_snapshots),latest=new Map;for(const s of shots){if(s.source_type==='own_channel'||!F(s.outlier_multiple))continue;const old=latest.get(s.video_id);if(!old||Date.parse(s.captured_at)>Date.parse(old.captured_at))latest.set(s.video_id,s)}return[...latest.values()].filter(x=>N(x.outlier_multiple)>=1.5).sort((a,b)=>{const ao=N(a.outlier_multiple),bo=N(b.outlier_multiple);return bo-ao||Date.parse(b.captured_at)-Date.parse(a.captured_at)})[0]||null}
function cloudPanel(){if(!session)return`<section class="v26-cloud-card signed-out"><div><div class="eyebrow">CLOUD INTELLIGENCE · OPTIONAL</div><h2>Make YTIntel useful even when this browser is closed.</h2><p>Sign in to sync your workspace across devices, preserve longitudinal history and let the scheduled monitor watch your saved competitors and own channel between visits.</p></div><button class="btn primary" data-v26-auth>Sign in / create account →</button></section>`;
  const p=summary?.profile,alerts=A(summary?.unread_alerts),model=summary?.own_channel_model||{},best=bestCloudSignal(),fit=best?fitFor(best.title,model):null,last=p?.last_background_scan_at;
  return`<section class="v26-cloud-card"><div class="v26-cloud-head"><div><div class="eyebrow">CLOUD INTELLIGENCE · ${E(session.user.email||'SIGNED IN')}</div><h2>${best?'YTIntel kept watching while you were away.':'Your workspace now follows you.'}</h2><p>${last?`Latest scheduled intelligence: ${ago(last)}.`:'Cloud workspace connected. The first server scan will seed your background history.'} ${alerts.length?`${alerts.length} unread opportunity alert${alerts.length===1?'':'s'}.`:''}</p></div><div class="v26-cloud-actions"><button class="btn primary" data-v26-monitor ${monitoring?'disabled':''}>${monitoring?'Scanning…':'Scan now'}</button><button class="btn" data-v26-account>Account</button></div></div>
  <div class="v26-cloud-metrics"><span><small>Background</small><b>${p?.background_enabled===false?'Paused':'ON'}</b></span><span><small>Interval</small><b>${p?.scan_interval_hours||6}h</b></span><span><small>Cloud alerts</small><b>${alerts.length}</b></span><span><small>Own-channel learning</small><b>${model.sample_size||0} videos</b></span></div>
  ${best?`<div class="v26-background-signal"><div><span class="v26-live-dot"></span><small>STRONGEST BACKGROUND SIGNAL</small><h3>${E(best.title)}</h3><p>${E(best.channel||best.source_seed)} · ${N(best.outlier_multiple).toFixed(1)}× channel baseline · observed ${ago(best.captured_at)}</p></div><div class="v26-background-fit"><small>PERSONAL EVIDENCE</small><b class="${E(fit?.tone||'learn')}">${E(fit?.label||'LEARNING')}</b><span>${E(fit?.detail||'')}</span></div><button class="btn small" data-v26-analyse="${E(best.url)}">Analyse</button></div>`:''}
  ${alerts.length?`<div class="v26-alerts"><div class="v26-alerts-head"><b>Opportunity alerts</b><button class="btn small" data-v26-read>Mark all read</button></div>${alerts.slice(0,5).map(a=>`<article class="${E(a.severity||'info')}"><div><small>${E(String(a.kind||'signal').replace(/_/g,' ').toUpperCase())}</small><b>${E(a.title)}</b><p>${E(a.message)}</p></div>${a.url?`<button class="btn small" data-v26-analyse="${E(a.url)}">Open</button>`:''}</article>`).join('')}</div>`:''}
  <div class="v26-cloud-foot"><span>Scheduled monitoring is server-side. It can keep collecting snapshots after you close YTIntel; alerts persist here for your next visit.</span><div><button class="v26-link" data-v26-feedback="1">Useful</button><button class="v26-link" data-v26-feedback="0">Needs work</button></div></div></section>`}
function renderCloud(err=''){let host=$('#v26CloudHost');const target=$('#v25Intelligence')||$('#v24Dashboard')||$('#v21PublicLaunch');if(!target)return;if(!host){host=document.createElement('div');host.id='v26CloudHost';target.insertAdjacentElement('beforebegin',host)}host.innerHTML=err?`<section class="v26-cloud-card error-state"><div><div class="eyebrow">CLOUD INTELLIGENCE</div><h2>Local YTIntel is still available.</h2><p>${E(err)}</p></div><button class="btn" data-v26-account>Account</button></section>`:cloudPanel();bindCloud(host)}
function bindCloud(host){host.querySelectorAll('[data-v26-auth],[data-v26-account]').forEach(b=>b.onclick=openAuth);host.querySelector('[data-v26-monitor]')?.addEventListener('click',()=>monitorNow(false));host.querySelectorAll('[data-v26-analyse]').forEach(b=>b.onclick=()=>analyse(b.dataset.v26Analyse));host.querySelector('[data-v26-read]')?.addEventListener('click',markAllRead);host.querySelectorAll('[data-v26-feedback]').forEach(b=>b.onclick=()=>sendFeedback(b.dataset.v26Feedback==='1'))}
async function markAllRead(){if(!session||!client)return;const r=await client.from('ytintel_alerts').update({read_at:new Date().toISOString()}).eq('user_id',session.user.id).is('read_at',null);if(r.error)return toast(r.error.message);await refreshSummary();toast('Alerts marked as read.')}
async function sendFeedback(useful){if(!session||!client)return toast('Sign in to save product feedback.');const best=bestCloudSignal();const r=await client.from('ytintel_feedback').insert({user_id:session.user.id,context:'v0.26 creator workspace',useful,note:'',metadata:{best_video_id:best?.video_id||null,best_outlier:best?.outlier_multiple||null}});if(r.error)return toast('Feedback could not be saved.');toast(useful?'Thanks — marked useful.':'Thanks — marked as needs work.')}

function ensureTopButton(){const top=$('.top .split');if(!top||$('#v26AccountBtn'))return;const b=document.createElement('button');b.id='v26AccountBtn';b.className='btn small v26-account-btn';b.onclick=openAuth;top.insertBefore(b,top.firstChild);renderAccount()}
function renderAccount(){const b=$('#v26AccountBtn');if(!b)return;b.innerHTML=session?`<span class="v26-cloud-dot"></span> Synced`:'Sign in / Sync';b.title=session?`Cloud sync active for ${session.user.email||'this account'}`:'Optional account for cloud sync and background intelligence'}
function authModal(){let m=$('#v26Auth');if(m)return m;m=document.createElement('div');m.id='v26Auth';m.className='v26-modal';m.innerHTML=`<div class="v26-modal-card"><div class="v26-modal-top"><div><div class="eyebrow">YTINTEL ACCOUNT</div><h2>Keep your intelligence, not just your browser.</h2><p>Accounts unlock cross-device workspace sync, persistent alerts and scheduled competitor/own-channel monitoring.</p></div><button class="v26-close">×</button></div><div id="v26AuthBody"></div></div>`;document.body.appendChild(m);m.querySelector('.v26-close').onclick=()=>m.classList.remove('show');m.onclick=e=>{if(e.target===m)m.classList.remove('show')};return m}
function openAuth(){const m=authModal(),body=$('#v26AuthBody');if(session){const p=summary?.profile||{};body.innerHTML=`<div class="v26-account-summary"><b>${E(session.user.email||'Signed in')}</b><span>Last cloud sync ${ago(Number(text(LS.lastSync,'0'))||0)}</span></div><div class="v26-settings"><label>Background scan interval<select id="v26Interval"><option value="3">Every 3 hours</option><option value="6">Every 6 hours</option><option value="12">Every 12 hours</option><option value="24">Every 24 hours</option></select></label><label class="v26-switch"><input type="checkbox" id="v26Background" ${p.background_enabled===false?'':'checked'}><span>Keep scheduled monitoring active</span></label></div><div class="v26-modal-actions"><button class="btn primary" data-v26-sync-now>Sync now</button><button class="btn" data-v26-save-settings>Save monitoring</button><button class="btn" data-v26-signout>Sign out</button></div><div class="v26-account-note">Your data is protected by per-user database policies. Public YouTube evidence remains observational; cloud sync does not change YTIntel’s evidence thresholds.</div>`;const sel=$('#v26Interval');if(sel)sel.value=String(p.scan_interval_hours||6);body.querySelector('[data-v26-sync-now]').onclick=async()=>{try{await reconcileWorkspace();await syncProfile();await refreshSummary();toast('Workspace synced.')}catch(e){toast(e?.message||'Sync failed.')}};body.querySelector('[data-v26-save-settings]').onclick=saveMonitoring;body.querySelector('[data-v26-signout]').onclick=async()=>{await client.auth.signOut();m.classList.remove('show')}}else{body.innerHTML=`<div class="v26-auth-grid"><label>Email<input id="v26Email" type="email" autocomplete="email" placeholder="you@example.com"></label><label>Password<input id="v26Password" type="password" autocomplete="current-password" placeholder="At least 8 characters"></label></div><div class="v26-auth-error" id="v26AuthError"></div><div class="v26-modal-actions"><button class="btn primary" data-v26-signin>Sign in</button><button class="btn" data-v26-signup>Create account</button></div><p class="v26-account-note">You can keep using YTIntel locally without an account. Sign in only adds persistent cloud intelligence and multi-device sync.</p>`;body.querySelector('[data-v26-signin]').onclick=()=>doAuth('signin');body.querySelector('[data-v26-signup]').onclick=()=>doAuth('signup')}m.classList.add('show')}
async function doAuth(mode){const email=$('#v26Email')?.value.trim(),password=$('#v26Password')?.value||'',err=$('#v26AuthError');if(err)err.textContent='';if(!email||password.length<8){if(err)err.textContent='Enter a valid email and a password of at least 8 characters.';return}try{const r=mode==='signup'?await client.auth.signUp({email,password}):await client.auth.signInWithPassword({email,password});if(r.error)throw r.error;if(mode==='signup'&&!r.data?.session){if(err)err.textContent='Account created. Check your email to confirm it, then sign in.';return}$('#v26Auth')?.classList.remove('show')}catch(e){if(err)err.textContent=e?.message||'Could not sign in.'}}
async function saveMonitoring(){if(!session||!client)return;const interval=Math.max(3,Math.min(24,Number($('#v26Interval')?.value)||6)),enabled=!!$('#v26Background')?.checked;const r=await client.from('ytintel_profiles').update({scan_interval_hours:interval,background_enabled:enabled}).eq('user_id',session.user.id);if(r.error)return toast(r.error.message);await refreshSummary();toast(enabled?`Background monitoring set to every ${interval}h.`:'Background monitoring paused.');$('#v26Auth')?.classList.remove('show')}

async function onAuthChange(){ensureTopButton();renderAccount();renderCloud();if(!session){summary=null;patchPersonalFit();return}try{await reconcileWorkspace();await syncProfile();await refreshSummary({seed:true})}catch(e){console.warn('[YTIntel auth sync]',e);renderCloud(e?.message||'Cloud sync is temporarily unavailable.')}}
function observeProduct(){window.addEventListener('storage',scheduleSync);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'&&session)scheduleSync()});let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(()=>{renderCloud();patchPersonalFit()},250)}).observe(document.body,{childList:true,subtree:true});window.addEventListener('focus',()=>{if(session&&Date.now()-Number(text(LS.cloudPulse,'0')||0)>120000){localStorage.setItem(LS.cloudPulse,String(Date.now()));refreshSummary()}})}
async function boot(){if(booted)return;booted=true;setStatus();ensureTopButton();renderCloud();observeProduct();try{await initClient();await onAuthChange()}catch(e){console.warn('[YTIntel cloud bootstrap]',e);renderCloud('Cloud features could not load. The full local YTIntel research workflow still works normally.')}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,350),{once:true});else setTimeout(boot,350);
})();