(function(){
'use strict';
if(document.documentElement.dataset.yt281Ideas==='1')return;
document.documentElement.dataset.yt281Ideas='1';
const BANKS='ytintel-v270-style-banks',ACTIVE='ytintel-v270-active-bank',API='https://dkmacktcfhubsumwrydw.supabase.co/functions/v1/ytintel-v082?action=package';
const $=s=>document.querySelector(s),A=x=>Array.isArray(x)?x:[],N=x=>Number(x),F=x=>x!==null&&x!==undefined&&x!==''&&Number.isFinite(Number(x));
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function read(k,f=null){try{const v=localStorage.getItem(k);return v==null?f:JSON.parse(v)}catch{return f}}
function text(k,f=''){try{return localStorage.getItem(k)??f}catch{return f}}
function bank(){const id=text(ACTIVE,'');return A(read(BANKS,[])).find(x=>x.id===id)||null}
function toast(s){if(typeof window.YTIntelToast==='function')window.YTIntelToast(s);else console.info('[YTIntel]',s)}
function research(b,direction=''){const all=A(b?.videos),verified=all.filter(x=>F(x.outlier)&&N(x.outlier)>=1.5).sort((a,c)=>N(c.outlier)-N(a.outlier)),winners=(verified.length?verified:all.slice(0,6)).slice(0,8),winIds=new Set(winners.map(x=>x.id)),controls=all.filter(x=>!winIds.has(x.id)).slice(0,6),clusters=A(b?.pattern?.repeated).slice(0,10).map(x=>({label:String(x.statement||''),pattern:String(x.statement||''),controls:0,videos:A(x.sources).slice(0,5).map(s=>({title:s.video_title||'',channel:'',outlier:null}))}));const row=x=>({title:x.title||'',channel:x.channel||'',url:x.url||'',outlier:F(x.outlier)?N(x.outlier):null,views:F(x.views)?N(x.views):null});return{query:b?.niche||b?.name||'YouTube niche',creator_angle:String(direction||'').trim(),winners:winners.map(row),controls:controls.map(row),clusters}}
async function generate(b,direction,btn,status,root){btn.disabled=true;btn.textContent='Building ideas...';status.textContent='Using the saved winner/control evidence, attached Pattern Mine and YTIntel packaging engine. The result is original packaging, not copied competitor creative.';try{const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json','x-ytintel-client':'web-v028'},body:JSON.stringify({research:research(b,direction)})}),d=await r.json().catch(()=>({}));if(!r.ok||d?.ok===false)throw Error(d?.error||`Idea engine ${r.status}`);const intel=d?.intelligence||d?.data||{},packs=A(intel.packages);if(!packs.length)throw Error('No idea packages came back. Add more comparable winner evidence and try again.');status.innerHTML=`${d?.fallback?'<b>Always-On engine</b>':'<b>Cloud-enhanced engine</b>'} · ${packs.length} original packages from the current evidence set.`;root.innerHTML=`<div class="v281-list">${packs.map((p,i)=>`<article class="v281-idea"><div class="v281-rank">#${p.rank||i+1}</div><div class="v281-main"><div class="v281-top"><div><small>${E(p.recommendation||'TEST')} · package ${F(p.package_score)?Math.round(N(p.package_score)):'-'}</small><h3>${E(p.title||'Untitled idea')}</h3></div><button class="btn primary small" data-v281-use="${i}">Build script</button></div><p>${E(p.concept||'')}</p><div class="v281-cols"><div><small>OPENING HOOK</small><blockquote>"${E(p.opening_hook||'')}"</blockquote></div><div><small>THUMBNAIL DIRECTION</small><p><b>${E(p.thumbnail?.visual||'')}</b>${p.thumbnail?.text?` · ${E(p.thumbnail.text)}`:''}</p></div></div><details><summary>Why this package</summary><div class="v281-evidence">${A(p.source_evidence).slice(0,5).map(x=>`<div><b>${E(x.source_title||'Source')}</b><span>${E(x.observed_signal||'')}</span></div>`).join('')||'<div>No individual source rows returned.</div>'}</div><p class="v281-risk"><b>Risk:</b> ${E(p.risk||'Keep this as a test, not a prediction.')}</p></details></div></article>`).join('')}</div>`;root.querySelectorAll('[data-v281-use]').forEach(x=>x.onclick=()=>{const p=packs[N(x.dataset.v281Use)],input=$('#v28Idea');if(input){input.value=p.title||p.concept||b.niche;input.dispatchEvent(new Event('input',{bubbles:true}))}const holder=$('#v281Selected');if(holder)holder.innerHTML=`<div class="v281-selected"><small>SELECTED PACKAGE</small><b>${E(p.title||'')}</b><p>Hook: "${E(p.opening_hook||'')}"</p><p>Thumbnail: ${E(p.thumbnail?.visual||'')}</p></div>`;document.querySelector('[data-v28-build]')?.click();setTimeout(()=>$('#v28Plan')?.scrollIntoView({behavior:'smooth',block:'start'}),80);toast('Package sent into the script blueprint.')})}catch(e){status.textContent=e?.message||String(e);toast(e?.message||'Idea generation failed.')}finally{btn.disabled=false;btn.textContent='Generate ideas from this bank'}}
function inject(){const studio=$('#v28ProductionStudio'),b=bank();if(!studio||!b)return;if($('#v281IdeaLab')?.dataset.bank===b.id)return;$('#v281IdeaLab')?.remove();const s=document.createElement('section');s.id='v281IdeaLab';s.dataset.bank=b.id;s.className='v281-lab';s.innerHTML=`<div class="v281-head"><div><div class="eyebrow">IDEA LAB · BUILT FROM THE WINNERS</div><h2>Generate the next concepts from what is already working.</h2><p>YTIntel uses this Style Bank's channel-relative winners, controls and repeated Pattern Mine evidence to create original titles, hooks and thumbnail directions.</p></div></div><div class="v281-form"><input id="v281Direction" type="text" placeholder="Optional twist / constraint — e.g. beginner version, 30-day test, no-budget"><button class="btn primary" data-v281-generate>Generate ideas from this bank</button></div><div id="v281IdeaStatus" class="v28-status">${A(b.videos).length} saved video${A(b.videos).length===1?'':'s'} · ${A(b.videos).filter(x=>F(x.outlier)&&N(x.outlier)>=1.5).length} verified >=1.5x breakouts.</div><div id="v281Selected"></div><div id="v281Ideas"></div>`;const grid=studio.querySelector('.v28-grid');(grid||studio).insertAdjacentElement('afterend',s);const btn=s.querySelector('[data-v281-generate]');btn.onclick=()=>generate(b,s.querySelector('#v281Direction')?.value.trim()||'',btn,s.querySelector('#v281IdeaStatus'),s.querySelector('#v281Ideas'))}
let t;function refresh(){clearTimeout(t);t=setTimeout(inject,150)}
function init(){inject();new MutationObserver(refresh).observe(document.body,{childList:true,subtree:true});window.addEventListener('storage',refresh)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
