(function(){
'use strict';
if(document.documentElement.dataset.yt284Luxe==='1')return;
document.documentElement.dataset.yt284Luxe='1';
document.body.classList.add('yt-ui-v284');
window.YTINTEL_VERSION='0.28.4';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
function addHeroNote(view){const hero=$(`#${view}>.hero`);if(!hero||hero.querySelector('.v284-hero-note'))return;const n=document.createElement('div');n.className='v284-hero-note';n.setAttribute('aria-hidden','true');hero.appendChild(n)}
function proof(icon,title,sub,good=false){return `<span class="v284-proof${good?' good':''}"><i>${icon}</i><span><b>${title}</b><small>${sub}</small></span></span>`}
function analyseHero(){const hero=$('#analyse>.hero');if(!hero)return;addHeroNote('analyse');const form=$('#analyseForm');if(form&&!hero.querySelector('.v284-proofbar')){const rail=document.createElement('div');rail.className='v284-proofbar';rail.innerHTML=proof('T','Transcript','Full source evidence')+proof('R','Replay','Public hotzones')+proof('V','Visuals','Frames + style')+proof('O','Outlier','Channel-relative')+proof('AI','Intelligence','Deep reasoning',true);form.insertAdjacentElement('afterend',rail)}const btn=form?.querySelector('.primary');if(btn&&!btn.dataset.v284Label){btn.dataset.v284Label='1';btn.textContent='Analyse deeply →'}}
function packagingHero(){const hero=$('#packaging>.hero');if(!hero)return;addHeroNote('packaging');if(!hero.querySelector('.v284-pack-title')){const badge=document.createElement('div');badge.className='v284-pack-title';badge.textContent='Deep source-specific packaging';hero.querySelector('.eyebrow')?.insertAdjacentElement('afterend',badge)}const form=hero.querySelector('.formrow');if(form&&!hero.querySelector('.v284-pack-source')){const rail=document.createElement('div');rail.className='v284-pack-source';rail.innerHTML='<span>Actual transcript</span><span>Exact examples</span><span>Replay moments</span><span>Visual evidence</span><span>Max reasoning</span>';form.insertAdjacentElement('afterend',rail)}const btn=$('#packageBtn');if(btn&&!btn.dataset.v284Label){btn.dataset.v284Label='1';btn.textContent='Build deep packages →'}}
function visualHero(){const hero=$('#visuals>.hero');if(!hero)return;if(!hero.querySelector('.v284-proofbar')){const rail=document.createElement('div');rail.className='v284-proofbar';rail.innerHTML=proof('F','Frames','Storyboard evidence')+proof('A','Audio','Attributed tracks')+proof('H','Hotzones','Replay targets')+proof('S','Style','Visual patterns')+proof('P','Production','Reusable cues',true);hero.appendChild(rail)}}
function packageCards(){const root=$('#packageRoot');if(!root)return;const cards=$$('.yt282-package-option');if(!cards.length)return;cards.forEach((c,i)=>{c.classList.toggle('v284-featured',i===0);if(!c.dataset.v284Ready){c.dataset.v284Ready='1';const score=c.querySelector('.yt282-score b');if(score){const n=Number(score.textContent);if(Number.isFinite(n)){const holder=score.closest('.yt282-score');holder.title=`YTIntel package score ${Math.round(n)}/100 — a decision aid, not a performance prediction.`}}}})}
function polishLibrary(){const r=$('#packageRecent');if(!r)return;r.querySelectorAll('.yt282-folder').forEach(d=>{if(d.dataset.v284Ready)return;d.dataset.v284Ready='1';d.querySelector('summary')?.setAttribute('title','Open this saved packaging session')})}
function topPolish(){const s=$('#status');if(s&&/0\.28\.[0-3]/.test(s.textContent||''))s.textContent=(s.textContent||'').replace(/0\.28\.[0-3]/,'0.28.4');const brand=$('.brand');if(brand&&!brand.querySelector('.v284-brand-dot')){const dot=document.createElement('span');dot.className='v284-brand-dot';dot.style.cssText='width:6px;height:6px;border-radius:50%;background:#61e2a1;box-shadow:0 0 14px rgba(97,226,161,.65);margin-left:2px;flex:0 0 auto';dot.title='YTIntel intelligence live';brand.appendChild(dot)}}
function refresh(){analyseHero();packagingHero();visualHero();packageCards();polishLibrary();topPolish()}
let queued=false;function queue(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;refresh()})}
function init(){refresh();const o=new MutationObserver(queue);o.observe(document.body,{childList:true,subtree:true});window.addEventListener('storage',queue);window.addEventListener('focus',queue);setTimeout(refresh,500);setTimeout(refresh,1600)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
