(function(){
'use strict';
if(window.YTIntelBrief)return;
let M;const ready=import('./v330-evidence.mjs?v=0330').then(x=>M=x);
const $=s=>document.querySelector(s),A=x=>Array.isArray(x)?x:[],E=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=x=>M.finite(x)?Number(x):null,fmt=x=>M.timestamp(x),pretty=x=>n(x)===null?'Unavailable':new Intl.NumberFormat(undefined,{maximumFractionDigits:1,notation:'compact'}).format(Number(x));
const tag=(a,b)=>`<div class="yt300-stat"><span>${E(a)}</span><b>${E(b??'Unavailable')}</b></div>`;
const box=(n,k,title,body)=>`<section class="yt300-section" data-brief-section="${n}"><div class="yt300-section-head"><div><div class="yt300-kicker">${E(k)}</div><h2>${E(title)}</h2></div><span class="yt300-stepno">${n}</span></div>${body}</section>`;
const notice=s=>`<p class="yt330-notice">${E(s)}</p>`;
function age(x){const d=M.dateMs(x);if(d===null)return 'Unknown';const h=Math.max(0,(Date.now()-d)/36e5);return h<48?`${Math.round(h)}h old - still growing`:`${Math.floor(h/24)}d old - cumulative views`;}
function strip(r,iv,profile,intel){
 const v=r.video||{},o=v.outlier||{},p=M.pace(r),d=M.dateMs(v.upload_date),fields=[['Title',v.title],['Channel',v.channel],['Subs',pretty(v.channel_follower_count)],['Views',pretty(v.view_count)],['Likes',pretty(v.like_count)],['Comments',pretty(v.comment_count)],['Upload',d===null?'Unknown':new Date(d).toLocaleDateString()],['Age',age(v.upload_date)],['Length',fmt(v.duration)],['Outlier',n(o.multiple)===null?'Unavailable':Number(o.multiple).toFixed(2)+'x'],['Median',pretty(o.channel_median_views)],['Niche',r.content_niche||intel?.niche?.label||'Unclassified'],['Subniche',r.source_subniche||'Not classified'],['Pulled',new Date(r.pulled_at||r.retrieved_at).toLocaleString()],['WPM',p.wpm??'Withheld']];
 return box(1,'THE STRIP','Source snapshot',`<div class="yt300-strip" tabindex="0" aria-label="Source metrics; scroll horizontally for all fields">${fields.map(([a,b])=>`<div title="${E(b)}"><span>${E(a)}</span><b>${E(b??'Unavailable')}</b></div>`).join('')}</div>${notice('Source niche is separate from your creator profile. '+(r.brief_baseline?.median_views!==null&&r.brief_baseline?`${r.brief_baseline.sample_count} baseline uploads; current views are not age-matched.`:'Missing source metrics remain unavailable.'))}`);
}
function audio(r,visual){const p=M.pace(r),gap=M.captionGap(r),events=A(visual?.audio);return box(11,'AUDIO','Speaking pace and the limits of caption evidence',`<div class="yt300-statcards">${tag('Overall caption WPM',p.wpm??'Withheld')}${tag('De-duplicated words',p.word_count)}${tag('Longest caption gap',gap?`${gap.seconds.toFixed(1)}s at ${fmt(gap.start)}`:'Unavailable')}${tag('Acoustic silence','Not measured')}</div><h3>WPM by minute</h3><div class="yt300-minute-wpm">${p.by_minute.map(x=>`<div title="${x.words} caption words across ${x.seconds}s"><span>Min ${x.minute}</span><b>${x.wpm<=330?x.wpm:'Withheld'}</b></div>`).join('')}</div>${notice(p.precision)}<h3>Music and sound cues</h3>${events.length?events.map(x=>`<p>${fmt(x.start)} - ${E(x.label)} <small>(caption-coded cue)</small></p>`).join(''):notice('No caption-coded music or sound-effect cues were supplied. This does not establish that the video has no music or sound design.')}<p>Music start/shift times, sound-effect timing and audio underneath each replay peak need an accessible audio track. They have not been acoustically verified on this pass.</p>`);}
function frameAt(visual,t){const frames=A(visual?.frames);return [...frames].sort((a,b)=>Math.abs(a.seconds-t)-Math.abs(b.seconds-t))[0]||null;}
function frameImage(f){if(!f)return '';if(f.preview)return `<img class="yt330-frame" src="${E(f.preview)}" alt="Source frame near ${fmt(f.seconds)}">`;if(f.style)return `<div class="yt330-frame" role="img" aria-label="Storyboard sample at ${fmt(f.seconds)}" style="${E(f.style)}"></div>`;return '';}
function replay(r,visual){
 const h=M.replay(r),media=r.brief_media_analysis,describe=t=>A(media?.frames).find(f=>Math.abs((n(f.seconds)??-999)-t)<6)?.description;
 if(!h.available){const m=r.brief_mechanics,hyp=[...A(m?.rehooks).map(x=>({e:x.evidence,reason:x.why})),...A(m?.payoffs).map(x=>({e:x.evidence,reason:x.why}))].slice(0,6);return box(7,'MOST REPLAYED','No usable public curve on this pull',notice(h.reason)+`<p>No curve, peak score or retention percentage has been invented.</p>${hyp.length?'<h3>Transcript attention hypotheses - not measured replay</h3>'+hyp.map(x=>{const s=M.segments(r).find(z=>z.id===x.e?.segment_id);return `<details><summary>Hypothesis near ${fmt(s?.start)}</summary><p>${E(x.reason)}</p><blockquote>${E(x.e?.quote)}</blockquote></details>`;}).join(''):notice('Transcript hypotheses require a completed structure specialist. No speculative peak locations are shown while that model stage is blocked.')}`);}
 const min=Math.min(...h.points.map(x=>x.value)),max=Math.max(...h.points.map(x=>x.value)),dur=Number(r.video.duration)||1,path=h.points.map((p,i)=>`${i?'L':'M'}${(p.time/dur*800).toFixed(1)},${(110-90*(p.value-min)/Math.max(.001,max-min)).toFixed(1)}`).join(' ');
 const cards=(xs,type)=>xs.map(p=>{const cap=M.captionAt(r,p.time),f=frameAt(visual,p.time);return `<article class="yt300-callout"><h3>${type} ${fmt(p.time)} - relative replay ${p.value.toFixed(2)}</h3>${frameImage(f)}${notice(f?`Storyboard sample at ${fmt(f.seconds)}; ${Math.abs(f.seconds-p.time).toFixed(1)}s from curve point.`:'No frame was retrieved for this curve point.')}<blockquote>${E(cap?.text||'No caption available')}</blockquote><p>${E(cap?.match||'')} ${cap?`(${fmt(cap.start)}-${fmt(cap.end??cap.start)})`:''}</p><p>${E(describe(p.time)||'On-screen meaning not yet verified by the media specialist.')}</p><p>Audio at this moment: not acoustically inspected.</p></article>`;}).join('');
 return box(7,'MOST REPLAYED','Curve, peaks, troughs and their source context',`<svg viewBox="0 0 800 125" role="img" aria-label="Relative public replay curve"><path d="${path}" fill="none" stroke="currentColor" stroke-width="3"/></svg>${notice('Relative public replay/seek interest, not retention. Caption text and storyboard times have separate precision; they are not exact frame/word matches.')}<h3>Peaks</h3><div class="yt330-cards">${cards(h.peaks,'Peak')}</div><h3>Troughs</h3><div class="yt330-cards">${cards(h.troughs,'Trough')}</div>`);
}
function visuals(r,visual){const ma=r.brief_media_analysis,frames=A(visual?.frames),pick=frames.filter((_,i)=>i%Math.max(1,Math.ceil(frames.length/24))===0),find=f=>A(ma?.frames).find(x=>x.image_id===f.media_id||Math.abs(x.seconds-f.seconds)<2);return box(9,'VISUALS','Keyframes across the runtime',`<div class="yt300-statcards">${tag('Production mode',ma?.production_mode||'Not semantically verified')}${tag('Sampled frames',frames.length)}${tag('Visual changes/min proxy',n(visual?.cuts_per_minute))}${tag('Every original frame?','No - sampled evidence')}</div>${notice('Storyboard changes are not an exact editing cut count. Small text, brief inserts and events between samples may be missed.')}<div class="yt330-cards">${pick.map(f=>`<article>${frameImage(f)}<b>${fmt(f.seconds)}</b><p>${E(find(f)?.description||'Source frame; semantic interpretation unavailable.')}</p></article>`).join('')||notice(visual?.error||'Public keyframes were not retrieved. No visual claims have been invented.')}</div>`);}
function motion(r,visual){const ma=r.brief_media_analysis,xs=A(ma?.events),peaks=M.replay(r).peaks;return box(10,'MOTION GRAPHICS','Observed overlays and sampled change candidates',`${xs.length?xs.map(x=>`<article class="yt300-callout"><h3>${fmt(x.seconds)} - ${E(x.kind)}</h3><p>${E(x.description)}</p><p>Source image: ${E(x.image_id)}. ${peaks.some(p=>Math.abs(p.time-x.seconds)<6)?'Near a measured replay peak.':'No measured peak alignment established.'}</p></article>`).join(''):notice('No model-reviewed overlay, transition, zoom or B-roll inventory is available. Unclassified pixel changes below are candidates, not identified motion graphics.')}<details><summary>Inspect ${A(visual?.motion).length} pixel-change candidates</summary>${A(visual?.motion).map(x=>`<p>${fmt(x.time)} - ${E(x.type)} (candidate)</p>`).join('')}</details>${notice('Still images can show an overlay or composition. They cannot prove the movement of a zoom or transition. Exhaustive motion timing requires the source video.')}`);}
function packaging(r,visual,channel){const v=r.video||{},obs=M.titleObservations(r,channel),ma=r.brief_media_analysis,thumb=ma?.thumbnail,px=visual?.thumbPixels||{},m=r.brief_mechanics;return box(12,'PACKAGING','Title, thumbnail and the promise delivered',`<div class="yt300-package"><div>${visual?.thumbUrl?`<img class="yt300-thumb" src="${E(visual.thumbUrl)}" alt="Source thumbnail">`:notice('Thumbnail unavailable.')}<div class="yt300-statcards">${tag('Brightness',px.brightness)}${tag('Contrast',px.contrast)}${tag('Saturation',px.saturation)}</div></div><div><h3>${E(v.title)}</h3>${obs.observations.map(x=>`<p><b>${E(x.source)}:</b> ${E(x.title)}</p>`).join('')}${notice(`${obs.variant_count} observed title variant(s). ${obs.explanation}`)}<h3>Thumbnail composition</h3>${thumb?`<p>${E(thumb.composition)}</p><p>Subjects: ${E(thumb.subjects)}</p><p>Visible text: ${E(thumb.text)}</p><p>Visual promise: ${E(thumb.promise)}</p>`:notice('Image pixels are available where listed, but a composition/meaning analysis requires a successful image-model call. Pixel brightness is not thumbnail intelligence.')}<h3>Promise versus delivery</h3><p>${E(m?.title_promise_verdict||'Not judged: the structure specialist has not completed. Keyword overlap is not proof that the promise was delivered.')}</p></div></div>`);}
function coverage(r,visual,intel,save){const reviewed=r.deep_research?.status==='model_reviewed',textOk=intel?.quality_pass,hm=M.replay(r),states=['Source data',textOk?'Reviewed synthesis':'Blocked',textOk?'Reviewed synthesis':'Blocked',textOk?'Transcript analysis':'Blocked',textOk?'Transcript analysis':'Blocked',textOk?'Transcript analysis':'Blocked',hm.available?'Public curve':'Unavailable / hypotheses',textOk?'Source-backed analysis':'Blocked',r.brief_media_analysis?'Sampled-image analysis':'Limited / unavailable',r.brief_media_analysis?'Sampled observations':'Candidates only','Caption estimates only',r.brief_media_analysis?'Image + text analysis':'Partial evidence',r.brief_baseline?.median_views?'Sampled baseline':'Baseline unavailable',reviewed?'Reviewed directions':'Blocked',save?.ok?'Saved':'Not saved',reviewed?'Text review passed':'Review incomplete','Source transcript'];return M.SECTIONS.map((name,i)=>({section:i+1,name,status:states[i]}));}
function decorate(r,intel,visual,save){
 const root=$('#yt300Report');if(!root)return;r.brief_mechanics=intel?.benchmark_mechanics||null;const exportSection=root.children[15];
 const old=$('#yt330Coverage');old?.remove();const d=document.createElement('details');d.id='yt330Coverage';d.open=true;d.innerHTML='<summary>17-section delivery and evidence coverage</summary><table><thead><tr><th>Section</th><th>Evidence status</th></tr></thead><tbody>'+coverage(r,visual,intel,save).map(x=>`<tr><td>${x.section}. ${E(x.name)}</td><td>${E(x.status)}</td></tr>`).join('')+'</tbody></table>'+notice('A completed text review is not proof of full video/audio inspection. Export preserves these limitations.');exportSection?.prepend(d);
 root.querySelectorAll(':scope>.yt300-section').forEach((s,i)=>{s.dataset.briefSection=String(i+1);s.id='yt330Section'+(i+1);});
 const summ=root.children[1];if(summ){const p=M.pace(r),note=document.createElement('p');note.className='yt330-notice';note.textContent=`${p.word_count} caption words; ${p.wpm??'unavailable'} WPM overall. Minute estimates and audio limits are in section 11.`;summ.appendChild(note);}
}
async function image(url){return new Promise((resolve,reject)=>{const im=new Image(),timer=setTimeout(()=>reject(Error('Image timed out')),7000);im.crossOrigin='anonymous';im.onload=()=>{clearTimeout(timer);resolve(im)};im.onerror=()=>{clearTimeout(timer);reject(Error('Image access unavailable'))};im.src=url;});}
async function collectMedia(r,iv){
 const images=[],cache=new Map(),sb=A(iv?.data?.storyboards).filter(x=>x.templateUrl&&Number(x.interval)>0).sort((a,b)=>Number(b.width)-Number(a.width))[0],duration=Number(r.video?.duration)||0;
 async function read(url){if(!cache.has(url))cache.set(url,image(url));return cache.get(url);}
 const push=(im,x,y,w,h,id,kind,seconds)=>{const c=document.createElement('canvas');c.width=kind==='thumbnail'?640:320;c.height=Math.round(c.width*h/w);const q=c.getContext('2d');q.drawImage(im,x,y,w,h,0,0,c.width,c.height);images.push({id,kind,seconds,image_url:c.toDataURL('image/jpeg',.7)});};
 const work=[];
 work.push((async()=>{try{const url=`https://i.ytimg.com/vi/${encodeURIComponent(r.video.id)}/hqdefault.jpg`,im=await read(url);push(im,0,0,im.width,im.height,'thumbnail','thumbnail',null)}catch{}})());
 if(sb){const times=[...Array.from({length:10},(_,i)=>duration*(i+.5)/10),...M.replay(r).peaks.slice(0,5).map(p=>p.time)],seen=new Set();for(const t of times){const idx=Math.min(Number(sb.count)-1,Math.floor(t*1000/Number(sb.interval))),cols=Number(sb.storyboardWidth)||1,rows=Number(sb.storyboardHeight)||1;if(idx<0||seen.has(idx))continue;seen.add(idx);work.push((async()=>{try{let url=sb.templateUrl.replace(/\$M/g,String(Math.floor(idx/(cols*rows))));if(!/^https:\/\//.test(url))url=(iv.base||'')+url;const im=await read(url),w=im.width/cols,h=im.height/rows,cell=idx%(cols*rows);push(im,(cell%cols)*w,Math.floor(cell/cols)*h,w,h,'frame-'+idx,'storyboard',idx*Number(sb.interval)/1000)}catch{}})());}}
 await Promise.allSettled(work);r.media_evidence={images:M.mediaManifest(images,duration),coverage:'Sampled storyboard stills and source thumbnail, not exhaustive video or audio.'};return r.media_evidence;
}
function progress(taskStates,modelTasks){const root=$('#yt300Progress');if(!root)return;let map=$('#yt330Roadmap');if(!map){map=document.createElement('details');map.id='yt330Roadmap';root.appendChild(map);}const stage=['evidence','summary','takeaways','mechanics','mechanics','mechanics','replay','mechanics','media','media','visual','media','evidence','remake','vault','final_review','evidence'];map.innerHTML='<summary>Follow the 17-section roadmap</summary><div class="yt330-roadmap">'+M.SECTIONS.map((name,i)=>{const k=stage[i],s=modelTasks[k]?.status||taskStates[k]||'wait';return `<span data-state="${E(s)}">${i+1}. ${E(name)} <small>${E(s==='warn'?'limited / blocked':s)}</small></span>`;}).join('')+'</div>';}
function css(){const s=document.createElement('style');s.textContent='.yt330-notice{font-size:12px;color:#a8b6c9;line-height:1.65;padding:10px;border-left:2px solid #879ec5}.yt330-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,240px),1fr));gap:12px}.yt330-frame{display:block;width:100%;aspect-ratio:16/9;object-fit:contain;background-color:#05080d}.yt330-roadmap{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:8px;margin-top:12px}.yt330-roadmap span{border:1px solid #343d4e;border-radius:8px;padding:8px;font-size:12px}.yt330-roadmap small{display:block;color:#a7b6cb}.yt330-roadmap [data-state=done]{border-color:#3e8d68}.yt330-roadmap [data-state=run]{border-color:#a2b8ff}#yt330Coverage table{width:100%;border-collapse:collapse}#yt330Coverage td,#yt330Coverage th{text-align:left;padding:8px;border-bottom:1px solid #303744}.yt300-strip{display:flex;overflow-x:auto;gap:8px}.yt300-strip>div{flex:0 0 auto;max-width:260px}.yt300-strip b{display:block;max-width:260px} @media print{.yt300-section{break-inside:auto!important}.yt300-section h2{break-after:avoid}.yt330-cards article,.yt300-callout{break-inside:avoid}.yt300-strip{display:grid!important;grid-template-columns:repeat(3,1fr)!important;overflow:visible!important}.yt300-strip>div{max-width:none!important}.yt300-section .yt330-frame{max-height:180px}.yt300-transcript{max-height:none!important;overflow:visible!important}nav,header,.top,.tabs,.mobile-dock,#yt300Progress,.no-print{display:none!important}}';document.head.appendChild(s);}
let printed=[];window.addEventListener('beforeprint',()=>{printed=[...document.querySelectorAll('#yt300Report details')].filter(x=>!x.open);printed.forEach(x=>x.open=true)});window.addEventListener('afterprint',()=>{printed.forEach(x=>x.open=false);printed=[];});
window.YTIntelBrief={ready,strip,audio,replay,visuals,motion,packaging,decorate,progress,collectMedia,enrich:(...x)=>M.enrich(...x),pace:r=>M.pace(r),mediaManifest:(...x)=>M.mediaManifest(...x)};css();
})();

(function(){const s=document.createElement('style');s.id='yt330-print-contrast';s.textContent=`
@media print {
 html,body{background:#fff!important;color:#111!important;font-family:Arial,sans-serif!important;}
 #yt300Report,#yt300Report *{background:transparent!important;background-image:none!important;color:#111!important;text-shadow:none!important;box-shadow:none!important;max-height:none!important;font-family:Arial,sans-serif!important;}
 #yt300Report{font-size:10pt!important;line-height:1.4!important;}
 #yt300Report .yt300-section{border:1px solid #bbb!important;break-inside:auto!important;margin:0 0 12pt!important;padding:12pt!important;}
 #yt300Report h2{font-size:15pt!important;break-after:avoid!important;}
 #yt300Report h3{font-size:12pt!important;break-after:avoid!important;}
 #yt300Report p,#yt300Report td,#yt300Report li{font-size:10pt!important;}
 #yt300Report a{color:#174a9b!important;text-decoration:underline!important;}
 #yt300Report .yt300-strip{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;overflow:visible!important;}
 #yt300Report .yt300-strip>div{border:1px solid #ddd!important;min-width:0!important;break-inside:avoid!important;}
 #yt300Report .yt300-strip b{white-space:normal!important;overflow:visible!important;}
 #yt300Report .yt300-callout,#yt300Report article{break-inside:avoid!important;}
 #yt300Report pre{white-space:pre-wrap!important;overflow:visible!important;font-size:9pt!important;}
 #yt300Report img{max-width:100%!important;}
 #yt300Report button{display:none!important;}
}`;document.head.appendChild(s);})();
