const URL='https://dkmacktcfhubsumwrydw.supabase.co';
const KEY='sb_publishable_VATM2AkVyl-yvxv28S2FXw_CqMpBr6q';
let sb=null,session=null,user=null,ready=false,listeners=[];
const clean=s=>String(s??'').replace(/\s+/g,' ').trim();
function emit(){const d=getCloudState();for(const fn of listeners)try{fn(d)}catch{}window.dispatchEvent(new CustomEvent('ytintel:v360-cloud',{detail:d}))}
export function onCloudChange(fn){listeners.push(fn);return()=>listeners=listeners.filter(x=>x!==fn)}
export function getCloudState(){return{ready,signed_in:!!user,user_id:user?.id||null,email:user?.email||null,label:!ready?'Cloud sync starting…':user?'Account sync on':'Local-only until sign-in'}}
export async function initCloud(){try{const mod=await import('https://esm.sh/@supabase/supabase-js@2.57.4');sb=mod.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce'}});const x=await sb.auth.getSession();session=x.data?.session||null;user=session?.user||null;ready=true;sb.auth.onAuthStateChange((_event,next)=>{session=next||null;user=session?.user||null;emit()});emit();return getCloudState()}catch(e){ready=true;emit();return{...getCloudState(),error:clean(e?.message||e)}}}
export async function requestMagicLink(email){if(!sb)throw Error('Account service is not ready');email=clean(email).toLowerCase();if(!email||!email.includes('@'))throw Error('Enter a valid email');const redirect=location.origin+location.pathname;const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:redirect,shouldCreateUser:true}});if(error)throw error;return true}
export async function signOut(){if(sb)await sb.auth.signOut();session=null;user=null;emit()}
export async function loadProfile(){if(!sb||!user)return null;const {data,error}=await sb.from('ytintel_profiles').select('*').eq('user_id',user.id).maybeSingle();if(error)throw error;return data}
export async function saveProfile(p){if(!sb||!user)return null;const row={user_id:user.id,channel_name:clean(p.channel_name||p.channel||''),channel_url:clean(p.channel_url||p.channel||''),niche:clean(p.niche),subniche:clean(p.subniche),target_audience:clean(p.target_audience||p.audience),brand_rules:clean(p.brand_rules||p.brand),competitors:clean(p.competitors),goal:clean(p.goal)||'Grow with evidence-backed videos',updated_at:new Date().toISOString()};const {data,error}=await sb.from('ytintel_profiles').upsert(row,{onConflict:'user_id'}).select().single();if(error)throw error;return data}
function hookRow(report,profile){const h=report?.hook_framework||{},hs=report?.hook_story?.hook||{},line=clean(h.exact_line||h.opening_15s||hs.excerpt||'').slice(0,1800);return{user_id:user.id,video_id:report.video.id,video_url:report.video.webpage_url||'',video_title:report.video.title||'',channel:report.video.channel||'',niche:profile?.niche||'',subniche:profile?.subniche||'',hook_type:h.primary_type||hs.type||'',exact_line:line,timestamp_seconds:Number(hs.time)||0,why_it_works:clean(h.why||hs.mechanism||''),mechanism:clean(h.why||hs.mechanism||''),outlier_multiple:report.video?.outlier?.multiple??null}}
function packageRow(report,profile,extras){const pk=report?.research_intelligence?.packaging||{},thumb=extras?.thumbnail_analysis||{};return{user_id:user.id,video_id:report.video.id,video_url:report.video.webpage_url||'',video_title:report.video.title||'',channel:report.video.channel||'',niche:profile?.niche||'',subniche:profile?.subniche||'',source_title:report.video.title||'',title_variants:extras?.model?.remake?.directions?.flatMap(x=>x.titles||[])||[],hook_keywords:(report?.hook_framework?.exact_line||'').toLowerCase().match(/[a-z0-9']+/g)?.filter(x=>x.length>3).slice(0,16)||[],title_keywords:(report.video.title||'').toLowerCase().match(/[a-z0-9']+/g)?.filter(x=>x.length>3).slice(0,16)||[],thumbnail:{url:extras?.media?.thumbnail||'',analysis:thumb},promise_vs_delivery:clean(pk.promise_vs_delivery||extras?.model?.review?.verdict||''),outlier_multiple:report.video?.outlier?.multiple??null}}
export async function syncAnalysis(report,profile={},extras={}){if(!sb||!user||!report?.video?.id)return{synced:false};const vid=report.video.id,now=new Date().toISOString(),vault={user_id:user.id,video_id:vid,video_url:report.video.webpage_url||report.video.original_url||'',title:report.video.title||'',channel:report.video.channel||'',niche:profile.niche||'',subniche:profile.subniche||'',pulled_at:now,report,synthesis:extras.model||{},visual_analysis:{media:extras.media||{},visual:extras.visual||{},audio:extras.audio||{},thumbnail:extras.thumbnail_analysis||{}},remake:extras.model?.remake||{},vault_entry:extras.bank||{},tags:[profile.niche,profile.subniche,report?.hook_framework?.primary_type].filter(Boolean),updated_at:now};const old=await sb.from('ytintel_analysis_vault').select('id').eq('user_id',user.id).eq('video_id',vid).order('updated_at',{ascending:false}).limit(1);let vr;if(old.data?.[0]?.id)vr=await sb.from('ytintel_analysis_vault').update(vault).eq('id',old.data[0].id);else vr=await sb.from('ytintel_analysis_vault').insert(vault);if(vr.error)throw vr.error;const hook=hookRow(report,profile);if(hook.exact_line){const q=await sb.from('ytintel_hook_bank').upsert(hook,{onConflict:'user_id,video_id,exact_line'});if(q.error)throw q.error}const pack=packageRow(report,profile,extras);const pq=await sb.from('ytintel_package_bank').upsert(pack,{onConflict:'user_id,video_id'});if(pq.error)throw pq.error;const style={user_id:user.id,name:`auto:${vid}`,niche:profile.niche||'',payload:{video_id:vid,title:report.video.title,script_style:extras.bank?.script_style||'',edit_style:extras.bank?.edit_style||'',production_modes:extras.bank?.production_modes||[],motion_graphics:extras.bank?.motion_graphics||[],wpm:report?.pacing?.video_words_per_minute??null,updated_at:now},updated_at:now};const existing=await sb.from('ytintel_style_banks').select('id').eq('user_id',user.id).eq('name',style.name).limit(1);if(existing.data?.[0]?.id)await sb.from('ytintel_style_banks').update(style).eq('id',existing.data[0].id);else await sb.from('ytintel_style_banks').insert(style);return{synced:true}}
export async function loadCloudBanks(){if(!sb||!user)return null;const [vault,hooks,packs,styles,competitors,snaps]=await Promise.all([sb.from('ytintel_analysis_vault').select('*').eq('user_id',user.id).order('updated_at',{ascending:false}).limit(100),sb.from('ytintel_hook_bank').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(250),sb.from('ytintel_package_bank').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(250),sb.from('ytintel_style_banks').select('*').eq('user_id',user.id).order('updated_at',{ascending:false}).limit(250),sb.from('ytintel_competitors').select('*').eq('user_id',user.id).eq('active',true).order('updated_at',{ascending:false}),sb.from('ytintel_snapshots').select('*').eq('user_id',user.id).order('captured_at',{ascending:false}).limit(500)]);for(const x of [vault,hooks,packs,styles,competitors,snaps])if(x.error)throw x.error;return{vault:vault.data||[],hooks:hooks.data||[],packages:packs.data||[],styles:styles.data||[],competitors:competitors.data||[],snapshots:snaps.data||[]}}
export async function syncCompetitor(seed,label=''){if(!sb||!user)return null;const {data,error}=await sb.from('ytintel_competitors').upsert({user_id:user.id,seed:clean(seed),label:clean(label),active:true,updated_at:new Date().toISOString()},{onConflict:'user_id,seed'}).select().single();if(error)throw error;return data}
export async function removeCompetitor(seed){if(!sb||!user)return;const {error}=await sb.from('ytintel_competitors').update({active:false,updated_at:new Date().toISOString()}).eq('user_id',user.id).eq('seed',clean(seed));if(error)throw error}
export async function saveSnapshots(seed,discovery,channelStats=null){if(!sb||!user||!discovery)return[];const now=new Date().toISOString(),rows=(discovery.videos||[]).slice(0,30).map(v=>({user_id:user.id,source_type:'competitor',source_seed:clean(seed),video_id:v.video_id||'',url:v.url||'',title:v.title||'',channel:v.channel||clean(seed),views:Number.isFinite(Number(v.views))?Number(v.views):null,outlier_multiple:Number.isFinite(Number(v.outlier_multiple))?Number(v.outlier_multiple):null,published_text:v.published_text||'',captured_at:now,payload:{video:v,channel_statistics:channelStats?.statistics||null,channel_id:channelStats?.channel_id||discovery.channel_id||null}})).filter(x=>x.video_id);if(!rows.length)return[];const {error}=await sb.from('ytintel_snapshots').insert(rows);if(error)throw error;return rows}
export function velocityFromSnapshots(seed,current,history=[]){const prior=history.filter(x=>x.source_seed===seed).sort((a,b)=>new Date(b.captured_at)-new Date(a.captured_at)),latestBy=new Map();for(const x of prior)if(!latestBy.has(x.video_id))latestBy.set(x.video_id,x);return(current?.videos||[]).map(v=>{const p=latestBy.get(v.video_id),hours=p?Math.max(.01,(Date.now()-new Date(p.captured_at).getTime())/36e5):null,delta=p&&Number.isFinite(Number(v.views))&&Number.isFinite(Number(p.views))?Number(v.views)-Number(p.views):null;return{...v,prior:p||null,view_delta:delta,hours,views_per_hour:delta!=null?Math.round(delta/hours):null}})}
