const SCRIPT=String.raw`(function(){
'use strict';
if(window.__PN_V5337_LEARNING_LOOP__)return;window.__PN_V5337_LEARNING_LOOP__=true;
var FAB={T01:1,T02:1,T03:1,T04:1,T05:1,T06:1,T07:1,T08:1,T09:1,T10:1,T11:1,T12:1,T13:1,T14:1,T15:1,T16:1,T17:1,T18:1,T19:1,T20:1,T21:1,T22:1,T23:1,T24:1,T25:1,T26:1,T27:1};
function who(){try{if(typeof state!=='undefined'&&state&&state.currentUser)return String(state.currentUser);}catch(e){}try{return localStorage.getItem('pn_live_person')||'';}catch(e){return '';}}
function liveTask(){try{if(typeof currentPersonTask==='function'){var t=currentPersonTask();if(t)return t;}}catch(e){}try{var p=who(),id=String(state&&state.startedByPerson&&state.startedByPerson[p]||'');if(id&&Array.isArray(TASKS))return TASKS.find(function(x){return x&&x.id===id;})||null;}catch(e){}return null;}
function startedId(){try{var p=who();return String(state&&state.startedByPerson&&state.startedByPerson[p]||'');}catch(e){return '';}}
function passed(id){try{return !!(window.__pnPreflightPassed&&window.__pnPreflightPassed(id));}catch(e){return false;}}
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c];});}
function style(){if(document.getElementById('pn5337Style'))return;var s=document.createElement('style');s.id='pn5337Style';s.textContent='#pn5337Learning{margin:0 0 10px;border:3px solid #b06b00;border-radius:14px;background:#fff3d6;color:#111;font-family:Arial;padding:11px;box-shadow:0 4px 12px rgba(0,0,0,.08)}.pn5337K{font-size:9px;font-weight:900;letter-spacing:.09em;color:#7a4800}.pn5337T{font-size:17px;font-weight:900;line-height:1.15;margin-top:3px}.pn5337S{font-size:11px;font-weight:800;line-height:1.4;margin-top:5px;color:#4f4433}.pn5337B{width:100%;min-height:44px;margin-top:8px;border:0;border-radius:9px;background:#111;color:#fff;font:900 10px Arial}@media(max-width:700px){.pn5337T{font-size:15px}}';document.head.appendChild(s);}
function remove(){var x=document.getElementById('pn5337Learning');if(x)x.remove();}
function render(){style();var p=who(),t=liveTask(),sid=startedId();if((p!=='me'&&p!=='ronan')||!t||!FAB[t.id]||sid!==t.id||passed(t.id)){remove();return;}var host=document.getElementById('taskCard'),anchor=document.getElementById('pn5323OneStep');if(!host||!anchor||anchor.parentNode!==host)return;var x=document.getElementById('pn5337Learning');if(!x){x=document.createElement('section');x.id='pn5337Learning';host.insertBefore(x,anchor);}x.innerHTML='<div class="pn5337K">AUTOMATIC SAFETY LEARNING · '+esc(t.id)+'</div><div class="pn5337T">NEW DAY · RECHECK SETUP BEFORE CONTINUING</div><div class="pn5337S">This task is already carried as started, but today’s current-source STEP ZERO is not passed yet. Recheck support, datum, fit-up and the next step before continuing physical work.</div><button type="button" class="pn5337B" id="pn5337Check">CHECK SETUP NOW</button>';var b=document.getElementById('pn5337Check');if(b)b.onclick=function(){var q=document.getElementById('pn5322Open');if(q){q.click();return;}try{window.scrollTo({top:0,behavior:'smooth'});}catch(e){}};}
function tick(){if(!document.hidden)render();}
function boot(){style();render();setTimeout(render,350);setTimeout(render,900);setInterval(tick,1200);window.addEventListener('pn-preflight-changed',function(){setTimeout(render,50);});window.addEventListener('pageshow',render);document.addEventListener('visibilitychange',function(){if(!document.hidden)render();});try{if(window.__pnDiagLog)window.__pnDiagLog('boot_ok_v5337_learning_loop','Continuous improvement runtime guard loaded',{phase:'new_day_recheck'});}catch(e){}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();`;
Deno.serve((req:Request)=>{if(req.method!=='GET'&&req.method!=='HEAD')return new Response('Method not allowed',{status:405,headers:{'Access-Control-Allow-Origin':'*'}});return new Response(req.method==='HEAD'?'':SCRIPT,{status:200,headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'no-store, max-age=0','Access-Control-Allow-Origin':'*','X-Navigator-Client':'v53.37-learning-loop'}})});