import {VERSION,A,clean,fail,validateInput,scriptSource,sourceFromReport,chunks,schemas,SYSTEM,prompts,validateOutput,atomsFor,ledgerFrom,writeBatches,resultFrom} from '../latest/v320-script-contract.mjs';
const BASE=Deno.env.get('SUPABASE_URL')||'',SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',MODEL=Deno.env.get('YTINTEL_RESEARCH_MODEL')||'gpt-5.6-sol';
const CORS={'access-control-allow-origin':'*','access-control-allow-headers':'authorization,apikey,content-type','access-control-allow-methods':'GET,POST,OPTIONS','cache-control':'no-store','content-type':'application/json'};
const json=(x,status=200)=>new Response(JSON.stringify(x),{status,headers:CORS});
async function db(path,method='GET',body){const r=await fetch(`${BASE}/rest/v1/${path}`,{method,headers:{apikey:SERVICE,authorization:'Bearer '+SERVICE,'content-type':'application/json',prefer:'return=representation'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(15000)});const d=await r.json().catch(()=>null);if(!r.ok)throw fail('STORAGE_UNAVAILABLE','Private project storage is unavailable.',503);return d}
async function apiKey(){const k=Deno.env.get('OPENAI_API_KEY')||Deno.env.get('OPENAI_KEY');if(k)return k;try{const d=await db('rpc/ytintel_get_openai_key','POST',{});return typeof d==='string'?d:''}catch{return ''}}
async function identity(req){const auth=req.headers.get('authorization');if(!/^Bearer\s+\S+$/i.test(auth||''))throw fail('SIGN_IN_REQUIRED','Sign in to keep your script and saved versions private.',401);const r=await fetch(BASE+'/auth/v1/user',{headers:{apikey:SERVICE,authorization:auth},signal:AbortSignal.timeout(10000)}),d=await r.json().catch(()=>({}));if(!r.ok||!d.id)throw fail('SESSION_EXPIRED','Sign in again to resume your saved script project.',401);return d.id}
const rp=id=>'ytintel_script_runs?id=eq.'+id;
const sp=(id,key)=>'ytintel_script_steps?run_id=eq.'+id+'&step_key=eq.'+encodeURIComponent(key);
async function load(id,uid){if(!/^[a-f0-9-]{36}$/i.test(id||''))throw fail('RUN_NOT_FOUND','Script project not found.',404);const rows=await db(rp(id)+'&user_id=eq.'+uid+'&limit=1');if(!rows?.[0])throw fail('RUN_NOT_FOUND','Script project not found.',404);const steps=await db('ytintel_script_steps?run_id=eq.'+id+'&order=step_key');return {run:rows[0],steps}}
const task=(key,kind,label,input)=>({key,kind,label,input});
export function graph(config,rows){
 const done=Object.fromEntries(rows.filter(x=>x.status==='done').map(x=>[x.step_key,x.result]));
 const base=config.urls.map((url,i)=>task('source_'+i,'source','Read video '+(i+1)+' captions',{url,index:i}));
 const plan=task('plan','plan','Lead editor: preserve voice and tier rules',{script:config.script,brief:config.brief,tiers:config.tiers,target:config.target});
 const jobs=[...base,plan];
 if(!done.plan||base.some(j=>!done[j.key]))return {jobs,done,sources:base.map(j=>done[j.key]).filter(Boolean)};
 const sources=[scriptSource(config.script),...base.map(j=>done[j.key])];
 if(A(done.plan.questions).length)return {jobs,done,sources,questions:done.plan.questions};
 const cs=sources.flatMap(x=>chunks(x));if(cs.length>40)throw fail('RESEARCH_SIZE_LIMIT','More than 40 source chunks: use fewer or shorter videos. No source was silently truncated.');
 for(const c of cs){jobs.push(task('extract_'+c.id,'extract','Extract '+c.id,{chunk:c,brief:config.brief,first_pass:null}));if(done['extract_'+c.id])jobs.push(task('audit_'+c.id,'audit','Coverage audit '+c.id,{chunk:c,brief:config.brief,first_pass:done['extract_'+c.id]}));}
 if(cs.some(c=>!done['extract_'+c.id]||!done['audit_'+c.id]))return {jobs,done,sources,chunks:cs};
 const atoms=atomsFor(cs.map(chunk=>({chunk,extract:done['extract_'+chunk.id],audit:done['audit_'+chunk.id]})));
 if(!atoms.length)throw fail('NO_DETAILS_FOUND','No source-backed details were extracted. Review the sources instead of inventing a list.');
 if(JSON.stringify(atoms).length>600000)throw fail('LEDGER_SIZE_LIMIT','The atomic ledger is too large for a single comparison. Split this research project; nothing was truncated.');
 jobs.push(task('merge','merge','Deduplicate, preserve nuance and flag conflicts',{atoms,tiers:config.tiers,tier_rules:done.plan.tier_rules,brief:config.brief}));
 if(!done.merge)return {jobs,done,sources,chunks:cs,atoms};
 const ledger=ledgerFrom(done.merge,atoms,config),batches=writeBatches(ledger,config.tiers);
 if(!ledger.selected.length)return {jobs,done,sources,chunks:cs,atoms,ledger,questions:['No eligible source-stated details remain. Review the withheld ledger or explicitly enable attributed rumors/inferences.']};
 for(const b of batches)jobs.push(task(b.key,'write','Write '+b.tier+' ('+b.details.length+' details)',{details:b.details,tier:b.tier,voice_notes:done.plan.voice_notes,script:config.script,brief:config.brief,actual_count:ledger.selected.length}));
 jobs.push(task('wrapper','wrapper','Polish opening and closing',{script:config.script,brief:config.brief,actual_count:ledger.selected.length,tiers:config.tiers,voice_notes:done.plan.voice_notes}));
 if(batches.some(b=>!done[b.key])||!done.wrapper)return {jobs,done,sources,chunks:cs,atoms,ledger};
 const draft=resultFrom(config,sources,ledger,done);
 jobs.push(task('review','review','Independent editor: audit the complete draft',{original_script:config.script,brief:config.brief,draft:{title:draft.title,opening:draft.opening,closing:draft.closing,tiers:draft.tiers},ledger:ledger.selected,actual_count:ledger.selected.length}));
 return {jobs,done,sources,chunks:cs,atoms,ledger,result:done.review?resultFrom(config,sources,ledger,done):null};
}
async function provider(path,method='GET',body){const key=await apiKey();if(!key)throw fail('API_KEY_MISSING','The AI provider is not configured.',503);let r,d;try{r=await fetch('https://api.openai.com/v1/'+path,{method,headers:{authorization:'Bearer '+key,'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(30000)});d=await r.json().catch(()=>({}));}catch{throw fail('PROVIDER_NETWORK_ERROR','The AI provider could not be reached. Saved work is preserved.',504)}if(!r.ok){const code=String(d.error?.code||d.error?.type||'PROVIDER_ERROR').replace(/[^a-z0-9_]/gi,'').toUpperCase();throw fail(code,code.includes('CREDIT')||code==='INSUFFICIENT_QUOTA'?'AI drafting is blocked by the API credit balance. Your script and source pack are saved.':'The AI provider rejected this stage: '+code,r.status===429?429:502)}return d}
async function launch(job){return provider('responses','POST',{model:MODEL,background:true,store:true,reasoning:{effort:'max'},max_output_tokens:job.kind==='merge'?30000:['extract','audit'].includes(job.kind)?20000:job.kind==='plan'?6000:16000,text:{format:{type:'json_schema',name:'script_'+job.kind,schema:schemas[job.kind],strict:true}},input:[{role:'system',content:[{type:'input_text',text:SYSTEM+'\n'+prompts[job.kind]}]},{role:'user',content:[{type:'input_text',text:JSON.stringify(job.input)}]}]})}
async function readSource(input){let d,r;try{r=await fetch(BASE+'/functions/v1/ytintel-v093?action=analyze',{method:'POST',headers:{'content-type':'application/json','x-ytintel-client':'web-v093'},body:JSON.stringify({url:input.url}),signal:AbortSignal.timeout(115000)});d=await r.json();}catch{throw fail('SOURCE_UNAVAILABLE','Video '+(input.index+1)+' could not be read. Retry or replace this source; it has not been skipped.',502)}if(!r.ok||d.ok===false||!d.report)throw fail('SOURCE_UNAVAILABLE','Video '+(input.index+1)+' did not return usable source evidence.',502);return sourceFromReport(d.report,input.url,input.index)}
async function finishModel(run,job,response){if(['queued','in_progress'].includes(response.status))return {pending:true};if(response.status!=='completed')throw fail(response.error?.code?.toUpperCase()||'MODEL_OUTPUT_INCOMPLETE','The model did not finish this stage; no partial result was accepted.',502);let text='';for(const o of response.output||[])for(const c of o.content||[])if(c.type==='output_text')text+=c.text||'';let data;try{data=JSON.parse(text||response.output_text||'')}catch{throw fail('MODEL_OUTPUT_INVALID','The model returned an invalid structured result.',502)}const checks=validateOutput(job.kind,data,job.input);if(checks.length)throw fail('SOURCE_QUALITY_CHECK_FAILED',checks.join(', '),422);await db(sp(run.id,job.key),'PATCH',{status:'done',result:data,finished_at:new Date().toISOString(),error_code:null,error_detail:null});if(response.id)await provider('responses/'+encodeURIComponent(response.id),'DELETE').catch(()=>{});return {done:true}}
async function work(run,rows,job){
 const old=rows.find(s=>s.step_key===job.key);if(old?.status==='done')return {done:true,cached:true};if(old?.status==='failed')throw fail(old.error_code||'STAGE_FAILED',old.error_detail||'Stage blocked. Retry after resolving the cause.',422);
 if(old?.response_id){if(Date.now()-Date.parse(old.started_at)>12*60*1000){await provider('responses/'+encodeURIComponent(old.response_id)+'/cancel','POST',{}).catch(()=>{});await db(sp(run.id,job.key),'PATCH',{status:'failed',error_code:'MODEL_TIMEOUT',error_detail:'This stage exceeded its 12-minute safety budget.'});throw fail('MODEL_TIMEOUT','The stage exceeded its safety budget. Saved work is preserved.',504)}return finishModel(run,job,await provider('responses/'+encodeURIComponent(old.response_id)))}
 if(old){if(Date.now()-Date.parse(old.started_at)>150000){await db(sp(run.id,job.key),'PATCH',{status:'failed',error_code:'INTERRUPTED_STAGE',error_detail:'Stage was interrupted before a response ID was saved.'});throw fail('INTERRUPTED_STAGE','This stage was interrupted. Retry explicitly to continue.',503)}return {pending:true}}
 if(!await db('rpc/ytintel_script_claim','POST',{p_run:run.id,p_key:job.key,p_kind:job.kind}))return {pending:true};
 try{if(job.kind==='source'){const data=await readSource(job.input);await db(sp(run.id,job.key),'PATCH',{status:'done',result:data,finished_at:new Date().toISOString()});return {done:true}}
 const response=await launch(job);await db(sp(run.id,job.key),'PATCH',{response_id:response.id||null});return await finishModel(run,job,response);
 }catch(e){await db(sp(run.id,job.key),'PATCH',{status:'failed',error_code:e.code||'STAGE_FAILED',error_detail:clean(e.message).slice(0,800),finished_at:new Date().toISOString()}).catch(()=>{});throw e}
}
async function state(run,steps){const g=graph(run.config,steps),status=g.result?.status||(g.questions?.length?'clarification':steps.some(x=>x.status==='failed')?'blocked':'researching');if(run.status!=='cancelled'&&status!==run.status)await db(rp(run.id),'PATCH',{status,result:g.result||null,updated_at:new Date().toISOString()});const summary=g.jobs.map(j=>({key:j.key,kind:j.kind,label:j.label,status:steps.find(x=>x.step_key===j.key)?.status||'queued',error_code:steps.find(x=>x.step_key===j.key)?.error_code||null,error_detail:steps.find(x=>x.step_key===j.key)?.error_detail||null}));return {ok:true,run_id:run.id,status:run.status==='cancelled'?'cancelled':status,config:run.config,jobs:summary,questions:g.questions||[],sources:g.sources||[],coverage:{chunks_total:g.chunks?.length||0,chunks_extracted:summary.filter(x=>x.kind==='extract'&&x.status==='done').length,chunks_audited:summary.filter(x=>x.kind==='audit'&&x.status==='done').length},ledger:g.ledger||null,result:g.result||run.result||null,limits:['Sources only; no external fact checking.','Visual-only details need a separate review.']}}
export async function handleScript(req){
 if(req.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});
 try{const action=new URL(req.url).searchParams.get('action')||'health';if(action==='health')return json({ok:true,version:VERSION,feature:'Script Studio',configured:!!await apiKey(),model:MODEL,private_projects:true,source_mode:'complete caption chunks + preserved original script',visual_only_details:'not_exhaustively_inspected'});if(req.method!=='POST')throw fail('POST_REQUIRED','POST required.',405);const uid=await identity(req);const raw=await req.text();if(raw.length>100000)throw fail('REQUEST_TOO_LARGE','Request exceeds 100,000 characters.',413);let b;try{b=JSON.parse(raw)}catch{throw fail('INVALID_JSON','Invalid JSON.',400)}
 if(action==='list'){const list=await db('ytintel_script_runs?user_id=eq.'+uid+'&select=id,status,created_at,updated_at,config&order=created_at.desc&limit=20');return json({ok:true,runs:list.map(x=>({id:x.id,status:x.status,created_at:x.created_at,target:x.config.target,brief:clean(x.config.brief).slice(0,130)}))})}
 if(action==='start'){const config=validateInput(b);const quota=await db('rpc/ytintel_ai_take_quota','POST',{p_bucket:'script32:'+uid,p_per_ip:5,p_global:25});if(!quota?.ok)throw fail('RESEARCH_SAFETY_LIMIT','The research safety budget has been reached. Saved drafts remain available.',429);const rows=await db('ytintel_script_runs','POST',{user_id:uid,config});return json(await state(rows[0],[]))}
 const {run,steps}=await load(b.run_id,uid);
 if(action==='state')return json(await state(run,steps));
 if(action==='delete'){for(const s of steps.filter(x=>x.response_id&&x.status==='running'))await provider('responses/'+encodeURIComponent(s.response_id)+'/cancel','POST',{}).catch(()=>{});await db(rp(run.id),'DELETE');return json({ok:true,deleted:true})}
 if(action==='retry'){const allowed=['CREDIT_BALANCE_EXHAUSTED','INSUFFICIENT_QUOTA','PROVIDER_NETWORK_ERROR','MODEL_TIMEOUT','INTERRUPTED_STAGE','SOURCE_UNAVAILABLE'];for(const s of steps.filter(x=>x.status==='failed'&&allowed.includes(x.error_code)&&x.attempts<3)){await db(sp(run.id,s.step_key),'DELETE')}await db(rp(run.id),'PATCH',{status:'researching'});return json({ok:true})}
 if(action!=='work')throw fail('UNKNOWN_ACTION','Unknown Script Studio action.',404);
 const g=graph(run.config,steps);if(g.questions?.length||g.result)return json(await state(run,steps));const job=g.jobs.find(x=>x.key===b.step_key);if(!job)throw fail('DEPENDENCY_NOT_READY','That task is not ready or does not belong to this run.',409);try{const progress=await work(run,steps,job);return json({ok:true,...progress})}catch(e){await db(rp(run.id),'PATCH',{status:'blocked',updated_at:new Date().toISOString()}).catch(()=>{});throw e}
 }catch(e){return json({ok:false,code:e.code||'SCRIPT_STUDIO_UNAVAILABLE',error:clean(e.message||'Script Studio is temporarily unavailable.'),fallback:false},e.status||500)}
}
