const VERSION='0.10.7';
const CLIENT='web-v093';
const CORS={'access-control-allow-origin':'*','access-control-allow-headers':'content-type,x-ytintel-client','access-control-allow-methods':'GET,POST,OPTIONS','cache-control':'no-store'};
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...CORS,'content-type':'application/json'}});
const clean=s=>String(s??'').replace(/\s+/g,' ').trim();
const fmt=x=>{x=Math.max(0,Math.round(Number(x)||0));return `${Math.floor(x/60)}:${String(x%60).padStart(2,'0')}`};
const NUM={one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10,first:1,second:2,third:3,fourth:4,fifth:5,sixth:6,seventh:7,eighth:8,ninth:9,tenth:10};
async function upstream(action,body={}){const base=Deno.env.get('SUPABASE_URL');const r=await fetch(`${base}/functions/v1/ytintel-v092?action=${encodeURIComponent(action)}`,{method:'POST',headers:{'content-type':'application/json','x-ytintel-client':'web-v092'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw Error(d.error||`upstream ${r.status}`);return d}
function units(r){const out=[];for(const s of r?.transcript?.segments||[]){const text=clean(s.text);if(!text)continue;const ps=text.split(/(?<=[.!?])\s+|\s+>>\s+/).map(clean).filter(Boolean),st=Number(s.start)||0,en=Number(s.end)||st+30,d=Math.max(.5,en-st),cs=ps.map(x=>Math.max(1,x.split(/\s+/).length)),tot=cs.reduce((a,b)=>a+b,0)||1;let p=0;for(let i=0;i<ps.length;i++){const a=st+d*p/tot,b=st+d*(p+cs[i])/tot;p+=cs[i];out.push({text:ps[i],start:a,end:b,timestamp:`≈${fmt(a)}`})}}return out}
function declared(r){const s=`${r?.video?.title||''} ${units(r).filter(x=>x.start<90).map(x=>x.text).join(' ')}`,m=s.match(/\b(\d{1,2}|one|two|three|four|five|six|seven|eight|nine|ten)\s+(ways?|methods?|steps?|tips?|strategies?|ideas?|reasons?|tools?|mistakes?)\b/i);return m?{count:/^\d+$/.test(m[1])?Number(m[1]):NUM[m[1].toLowerCase()],kind:m[2]}:null}
function mark(t,last){let m=t.match(/\b(?:way|method|step|tip|strategy|idea|reason|tool|mistake)\s*(?:number\s*)?(\d{1,2}|one|two|three|four|five|six|seven|eight|nine|ten)\b/i);if(m)return /^\d+$/.test(m[1])?Number(m[1]):NUM[m[1].toLowerCase()];m=t.match(/\b(first|second|third|fourth|fifth|sixth|seventh|eighth|ninth|tenth)\s+(?:way|method|step|tip|strategy|idea|reason|tool|mistake)\b/i);if(m)return NUM[m[1].toLowerCase()];if(/\b(?:next|another)\s+(?:way|method|step|tip|strategy|idea|reason|tool)\b/i.test(t))return last+1;return null}
function score(t,offset){const s=clean(t).toLowerCase();let n=Math.max(0,8-offset);if(/\b(start|create|build|offer|sell|use|launch|make|provide|become|freelance|automate|open|join|find|learn|run|set up|sign up|post|upload|generate|write|design|charge|market|monetize|monetise)\b/.test(s))n+=8;if(/\b(you can|you should|you need to|all you have to|the idea is|the method is|the way is|one way is|step .* is|method .* is|way .* is)\b/.test(s))n+=6;if(/\b(service|agency|channel|product|tool|freelanc|business|client|template|prompt|content|automation|youtube|website|store)\b/.test(s))n+=4;if(s.split(/\s+/).length>=5&&s.split(/\s+/).length<=28)n+=3;if(/\b(most people|everyone|today|before we|stuck|subscribe|sponsor|giveaway|comment below|like this video)\b/.test(s))n-=10;if(/^step\s+(?:one|two|three|four|five|\d+)\.?$/i.test(s))n-=20;return n}
function methodLabel(t){let x=clean(t);const patterns=[/\b(?:way|method|step|tip|strategy|idea|reason|tool|mistake)\s*(?:number\s*)?(?:\d{1,2}|one|two|three|four|five|six|seven|eight|nine|ten)\b[^.!?]{0,35}?\b(?:is|would be|is to|:)\s*([^.!?]{4,120})/i,/\b(?:first|second|third|fourth|fifth|sixth|seventh|eighth|ninth|tenth)\s+(?:way|method|step|tip|strategy|idea|reason|tool|mistake)\b[^.!?]{0,25}?\b(?:is|would be|is to|:)\s*([^.!?]{4,120})/i,/^(?:you can|you could|you should|you need to|start by|the idea is to|all you have to do is)\s+([^.!?]{4,120})/i];for(const p of patterns){const m=x.match(p);if(m){x=m[1];break}}x=x.replace(/^(basically|simply|just|actually)\s+/i,'').split(/[.!?]/)[0].trim();if(x.length>100)x=x.slice(0,100).replace(/\s+\S*$/,'');return x}
function takeaways(r){const u=units(r),d=declared(r);if(!d?.count||d.count<2||d.count>20)return null;const as=[];let last=0;for(let i=0;i<u.length;i++){const n=mark(u[i].text,last);if(n&&n<=d.count&&!as.some(a=>a.n===n)){as.push({n,i,start:u[i].start,timestamp:u[i].timestamp});last=n}}as.sort((a,b)=>a.n-b.n);if(as.length<2)return null;const items=as.map((a,k)=>{const end=as[k+1]?.i??Math.min(u.length,a.i+18),raw=u.slice(a.i,Math.min(end,a.i+18)).filter(x=>x.text.length>7&&!/subscribe|sponsor|giveaway|comment below/i.test(x.text)),ranked=raw.map((x,i)=>({x,s:score(x.text,i)})).sort((a,b)=>b.s-a.s),chosen=ranked[0]?.x||raw[0]||u[a.i],idx=Math.max(0,raw.indexOf(chosen)),name=methodLabel(chosen.text)||methodLabel(raw[0]?.text||'')||`Method ${a.n}`,how=raw.slice(idx,Math.min(raw.length,idx+4)).map(x=>x.text).filter((v,i)=>i===0||v!==chosen.text).join(' ');return{index:a.n,label:name,statement:name,explanation:how||chosen.text,how_to_do:how||chosen.text,timestamp:chosen.timestamp||a.timestamp,start:chosen.start??a.start,exact_line:chosen.text,source:'declared-list-structure'}});return{kind:'structured-list',target_count:d.count,detected_count:items.length,items,guardrail:`Reconstructed the video's declared ${d.count} ${d.kind}. Each item is selected as the most method-like/actionable line inside its section, then paired with nearby how-to context.`}}
function rehooks(r){const rx=/\b(?:but first|but here(?:'s| is)|here(?:'s| is) the catch|next(?: up)?|another (?:way|thing|method|step)|the next (?:way|thing|method|step)|now let(?:'s| us)|before we|what happens next|the crazy part|the important part|the biggest|the best part|here(?:'s| is) where|that brings us to|moving on to|finally|the last (?:way|thing|method|step))\b/i;return units(r).filter(x=>x.start>=20&&rx.test(x.text)&&x.text.length>15).filter((x,i,a)=>!i||x.start-a[i-1].start>10).slice(0,8).map(x=>({timestamp:x.timestamp,start:x.start,excerpt:x.text,reason:'Real section transition / attention reset from the transcript.'}))}
function niche(r){const s=`${r?.video?.title||''} ${r?.video?.description||''} ${units(r).slice(0,100).map(x=>x.text).join(' ')}`.toLowerCase(),xs=[[/\b(gta|grand theft auto|rockstar games?)\b/,'GTA'],[/\b(roblox|blox fruits|brookhaven)\b/,'ROBLOX'],[/\b(youtube automation|faceless youtube|faceless channel|cash cow channel)\b/,'YouTube Automation'],[/\b(chatgpt|openai|claude|anthropic|gemini|artificial intelligence|\bai\b|llm|ai agent|prompt engineering)\b/,'AI'],[/\b(tutorial|how to|explained|guide|learn|education|course|lesson)\b/,'Info / Education'],[/\b(minecraft|fortnite|gaming|gameplay)\b/,'Gaming'],[/\b(futures|trading|forex|crypto|stocks?)\b/,'Trading / Finance'],[/\b(fitness|gym|workout|bodybuilding)\b/,'Fitness'],[/\b(dropshipping|shopify|ecommerce|e-commerce)\b/,'E-commerce']];for(const [rx,n] of xs)if(rx.test(s))return n;return'Other'}
function enrich(r){const k=takeaways(r);if(k)r.content_extraction=k;const rs=rehooks(r);r.rehook_examples=rs;r.content_niche=niche(r);r.hook_story=r.hook_story||{};if(rs[0])r.hook_story.rehook=rs[0];r.schema_version=VERSION;return r}
export async function handleLegacy(req){if(req.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});const u=new URL(req.url),action=u.searchParams.get('action')||'health';if(action==='health')return json({ok:true,version:VERSION,structured_takeaways:'action-ranked declared sections',content_niches:true,real_rehooks:true});if(req.headers.get('x-ytintel-client')!==CLIENT)return json({ok:false,error:'Unauthorized client'},401);const b=req.method==='POST'?await req.json().catch(()=>({})):{};try{const d=await upstream(action,b);if(action==='analyze'&&d.report)d.report=enrich(d.report);return json({...d,version:VERSION})}catch(e){return json({ok:false,error:String(e?.message||e)},502)}}
